load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adif_io",
    srcs = glob(["**/*.rs"]),
    crate = "adif_io",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
