#!/usr/bin/env bash

VERSION=$(cargo get package.version)
mkdir -p dist

echo "Compiling native executable..."
cargo build --release --package adif_io --example json2adi --features="serde_impl"
cargo build --release --package adif_io --example adi2json --features="serde_impl"
cargo build --release --package adif_io --example monitor
echo
echo "Packaging native executable..."
pushd target/release/examples > /dev/null || exit
tar -czf ../../../dist/adif_io_"${VERSION}"_Linux_amd64.tgz adi2json json2adi monitor
popd > /dev/null || exit

echo
echo "Crosscompiling for Windows..."
cargo build --release --target x86_64-pc-windows-gnu --package adif_io --example json2adi --features="serde_impl"
cargo build --release --target x86_64-pc-windows-gnu --package adif_io --example adi2json --features="serde_impl"
cargo build --release --target x86_64-pc-windows-gnu --package adif_io --example monitor
echo
echo "Packaging Windows executable..."
zip -j dist/adif_io_"${VERSION}"_Windows_amd64.zip target/x86_64-pc-windows-gnu/release/examples/adi2json.exe target/x86_64-pc-windows-gnu/release/examples/json2adi.exe target/x86_64-pc-windows-gnu/release/examples/monitor.exe

echo
echo "..done!"