load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_bdd_grid_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_bdd_grid_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-bdd-scenario-core/0.1.0:adze_bdd_scenario_core",
    ],
)
