load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abar",
    srcs = glob(["**/*.rs"]),
    crate = "abar",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/spmc/0.3.0:spmc",
    ],
)
