load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abci",
    srcs = glob(["**/*.rs"]),
    crate = "abci",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/env_logger/0.6.2:env_logger",
        "//third-party/rust/crates/integer-encoding/1.1.7:integer_encoding",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mockstream/0.0.3:mockstream",
        "//third-party/rust/crates/protobuf/2.28.0:protobuf",
    ],
)
