//! Macro for creating new actor implementations using an sync actor under the hood

/// Generate an [`SyncActor`](crate::util::SyncActor) type-saftey wrapper.
///
/// This macro takes the following arguments:
///   * The desired name for the resulting [`Actor`](crate::traits::Actor) wrapper
///   * The type of the input [`Event`](crate::traits::Event) (Inbox)
///   * The type of the output [`Event`](crate::traits::Event) (Outbox)
///   * The type of the persistent `context`
///   * The method to be used for event processing
///
/// This builds an actor from a closure of type `Fn(&mut Context, InboxEvent) ->
/// Option<OutboxEvent>`. This closure is passed in a mutable reference to the persistent context
/// value, which it is expected to modify directly.
///
/// The provided closure can also, optionally, return an an event to be broadcast to this
/// [`Actor`](crate::traits::Actor)'s outbox.
///
/// The code generated by this macro takes care of completion tokens automatically, stripping them
/// from the inbound event before being passed into the closure, and reattaching them to the
/// outbound event if there was both a token and an outbound event
#[macro_export]
macro_rules! sync_actor {
    ($type_name:ident, $input_type:ty, $output_type:ty, $context_type:ty, $event_method:ident) => {
        pub struct $type_name<X: Executor>(SyncActor<$input_type, $output_type, X>);
        impl<X: Executor> $type_name<X> {
            pub fn new(initial_context: $context_type, bound: Option<usize>) -> Self {
                let actor = SyncActor::spawn(
                    |value: &mut $context_type, mut event: $input_type| {
                        let token = event.token();
                        let mut result = $event_method(value, event);
                        if let Some(token) = token {
                            if let Some(event) = result.as_mut() {
                                event.set_completion_token(token);
                            }
                        }
                        result
                    },
                    initial_context,
                    bound,
                );
                Self(actor)
            }
        }
        impl<X: Executor> Clone for $type_name<X> {
            fn clone(&self) -> Self {
                Self(self.0.clone())
            }
        }
        #[async_trait]
        impl<X: Executor> EventConsumer<$input_type> for $type_name<X> {
            type Error = SyncActorError;
            async fn accept(&self, event: $input_type) -> Result<(), Self::Error> {
                self.0.accept(event).await
            }
            fn accept_sync(&self, event: $input_type) -> Result<(), Self::Error> {
                self.0.accept_sync(event)
            }
        }
        #[async_trait]
        impl<X: Executor> EventProducer<$output_type> for $type_name<X> {
            type Error = SyncActorError;
            async fn register_consumer<C>(&self, consumer: C) -> Result<(), Self::Error>
            where
                C: EventConsumer<$output_type> + Send + Sync + 'static,
            {
                self.0.register_consumer(consumer).await
            }

            async fn register_callback<F>(
                &self,
                callback: F,
                token: CompletionToken,
            ) -> Result<(), Self::Error>
            where
                F: FnOnce($output_type) + Send + Sync + 'static,
            {
                self.0.register_callback(callback, token).await
            }

            fn register_consumer_sync<C>(&self, consumer: C) -> Result<(), Self::Error>
            where
                C: EventConsumer<$output_type> + Send + Sync + 'static,
            {
                self.0.register_consumer_sync(consumer)
            }

            fn register_callback_sync<F>(
                &self,
                callback: F,
                token: CompletionToken,
            ) -> Result<(), Self::Error>
            where
                F: FnOnce($output_type) + Send + Sync + 'static,
            {
                self.0.register_callback_sync(callback, token)
            }
        }
        impl<X: Executor> Actor<$input_type, $output_type, X> for $type_name<X> {
            type Inbox = Self;
            type Outbox = Self;

            fn inbox(&self) -> &Self::Inbox {
                self
            }

            fn outbox(&self) -> &Self::Outbox {
                self
            }

            fn shutdown(&self) -> Waiter {
                self.0.shutdown()
            }

            fn catchup(&self) -> Waiter {
                self.0.catchup()
            }
        }
    };
}
