load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_path",
    srcs = glob(["**/*.rs"]),
    crate = "access_path",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/access_path_derive/0.1.0:access_path_derive",
    ],
)
