load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdc_parser",
    srcs = glob(["**/*.rs"]),
    crate = "acdc_parser",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/encoding_rs/0.8.35:encoding_rs",
        "//third-party/rust/crates/evalexpr/13.1.0:evalexpr",
        "//third-party/rust/crates/peg/0.8.6:peg",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
