pub const RESERVED: &[&str] = &[
    "ls",
    "projects",
    "status",
    "daemon",
    "ps",
    "image",
    "images",
    "volume",
    "volumes",
    "network",
    "networks",
    "system",
    "registry",
    "df",
    "prune",
    "config",
    "schema",
    "guide",
    "completions",
    "version",
    "project",
    "rmi",
    "help",
    "run",
    "build",
    "create",
    "start",
    "stop",
    "restart",
    "rm",
    "delete",
    "exec",
    "sh",
    "shell",
    "logs",
    "inspect",
    "kill",
    "cp",
    "copy",
    "export",
    "stats",
    "top",
    "port",
    "pull",
    "push",
    "tag",
    "save",
    "load",
    "login",
    "logout",
    "builder",
    "machine",
    "machines",
    "__supervise",
];

pub const PROJECT_ACTIONS: &[&str] = &[
    "start", "up", "stop", "down", "restart", "ls", "ps", "status", "logs", "run", "create", "top",
    "wait", "push", "export", "exec", "sh", "shell", "stats", "inspect", "kill", "rm", "cp",
    "pull", "port", "ip", "env", "build", "rollout", "login", "config", "services", "builds",
    "profiles", "images", "volumes", "scripts", "help",
];
