load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_concurrency_caps_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_concurrency_caps_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-concurrency-caps-contract-core/0.1.0:adze_concurrency_caps_contract_core",
        "//third-party/rust/crates/adze-concurrency-env-core/0.1.0:adze_concurrency_env_core",
        "//third-party/rust/crates/adze-concurrency-init-core/0.1.0:adze_concurrency_init_core",
        "//third-party/rust/crates/adze-concurrency-map-core/0.1.0:adze_concurrency_map_core",
    ],
)
