load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "AronIS_GPS_Crate",
    srcs = glob(["**/*.rs"]),
    crate = "AronIS_GPS_Crate",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rpi_embedded/0.0.5:rpi_embedded",
    ],
)
