load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_derive",
    srcs = glob(["**/*.rs"]),
    crate = "actix_derive",
    crate_root = "src/lib.rs",
    edition = "2015",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/0.4.30:proc_macro2",
        "//third-party/rust/crates/quote/0.6.13:quote",
        "//third-party/rust/crates/syn/0.15.44:syn",
    ],
)
