load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa_core",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abscissa_derive/0.7.0:abscissa_derive",
        "//third-party/rust/crates/backtrace/0.3.76:backtrace",
        "//third-party/rust/crates/canonical-path/2.0.2:canonical_path",
        "//third-party/rust/crates/fs-err/2.11.0:fs_err",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
    ],
)
