load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_validation_propagation",
    srcs = glob(["**/*.rs"]),
    crate = "acme_validation_propagation",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hickory-resolver/0.24.4:hickory_resolver",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
