load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abu_base",
    srcs = glob(["**/*.rs"]),
    crate = "abu_base",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_builder/0.20.2:derive_builder",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.25.0:strum",
    ],
)
