load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsb_deku",
    srcs = glob(["**/*.rs"]),
    crate = "adsb_deku",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/deku/0.12.6:deku",
    ],
)
