load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adf435x",
    srcs = glob(["**/*.rs"]),
    crate = "adf435x",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/device-driver/1.0.9:device_driver",
    ],
)
