load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abgleich",
    srcs = glob(["**/*.rs"]),
    crate = "abgleich",
    crate_root = "src/main.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
)
