load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_redis_client",
    srcs = glob(["**/*.rs"]),
    crate = "actix_redis_client",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/redis/0.8.0:redis",
    ],
)
