load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actson",
    srcs = glob(["**/*.rs"]),
    crate = "actson",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ringbuffer/0.14.2:ringbuffer",
    ],
)
