load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adrift_macros",
    srcs = glob(["**/*.rs"]),
    crate = "adrift_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adrift_core/0.0.6:adrift_core",
        "//third-party/rust/crates/convert_case/0.6.0:convert_case",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
