load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_compose_macros",
    srcs = glob(["**/*.rs"]),
    crate = "ac_compose_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ac-primitives/1.21.0:ac_primitives",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/maybe-async/0.2.11:maybe_async",
    ],
)
