load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "act_build",
    srcs = glob(["**/*.rs"]),
    crate = "act_build",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-types/0.5.0:act_types",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/ciborium/0.2.2:ciborium",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/globset/0.4.20:globset",
        "//third-party/rust/crates/json-patch/4.2.0:json_patch",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/wasm-encoder/0.247.0:wasm_encoder",
        "//third-party/rust/crates/wasmparser/0.247.0:wasmparser",
    ],
)
