load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accumulate_client",
    srcs = glob(["**/*.rs"]),
    crate = "accumulate_client",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dotenvy/0.15.7:dotenvy",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/k256/0.13.4:k256",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/sha3/0.10.9:sha3",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
