load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acgmath",
    srcs = glob(["**/*.rs"]),
    crate = "acgmath",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/approx/0.1.1:approx",
        "//third-party/rust/crates/num-traits/0.1.43:num_traits",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
