load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads1x15",
    srcs = glob(["**/*.rs"]),
    crate = "ads1x15",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/i2cdev/0.4.4:i2cdev",
    ],
)
