load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actui",
    srcs = glob(["**/*.rs"]),
    crate = "actui",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ansi-to-tui/7.0.0:ansi_to_tui",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/dark-light/1.1.1:dark_light",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/notify-rust/4.18.0:notify_rust",
        "//third-party/rust/crates/open/5.4.1:open",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
