load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_ios",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_ios",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.24.1:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.36.0:accesskit_consumer",
        "//third-party/rust/crates/hashbrown/0.16.1:hashbrown",
        "//third-party/rust/crates/objc2-foundation/0.2.2:objc2_foundation",
        "//third-party/rust/crates/objc2-ui-kit/0.2.2:objc2_ui_kit",
        "//third-party/rust/crates/objc2/0.5.2:objc2",
    ],
)
