load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_sqlx_tx",
    srcs = glob(["**/*.rs"]),
    crate = "actix_sqlx_tx",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/sqlx/0.6.3:sqlx",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
