load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abelian",
    srcs = glob(["**/*.rs"]),
    crate = "abelian",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
)
