load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptance_contract",
    srcs = glob(["**/*.rs"]),
    crate = "acceptance_contract",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
