load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adc_lang",
    srcs = glob(["**/*.rs"]),
    crate = "adc_lang",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit-vec/0.8.0:bit_vec",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/malachite/0.4.22:malachite",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/unchecked-index/0.2.2:unchecked_index",
    ],
)
