load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acall_cli",
    srcs = glob(["**/*.rs"]),
    crate = "acall_cli",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
    ],
)
