load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_header",
    srcs = glob(["**/*.rs"]),
    crate = "add_header",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/color-eyre/0.6.5:color_eyre",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
