load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_storage_sqlite_buffer",
    srcs = glob(["**/*.rs"]),
    crate = "aa_storage_sqlite_buffer",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/metrics/0.24.6:metrics",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
