load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_codec",
    srcs = glob(["**/*.rs"]),
    crate = "actix_codec",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-sink/0.3.34:futures_sink",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/tokio-util/0.3.1:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
