load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads129xx",
    srcs = glob(["**/*.rs"]),
    crate = "ads129xx",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitfield/0.13.2:bitfield",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/nb/0.1.3:nb",
        "//third-party/rust/crates/void/1.0.2:void",
    ],
)
