load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_store",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_store",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/memmap2/0.9.11:memmap2",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rmp-serde/1.3.1:rmp_serde",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
