load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp_agent",
    srcs = glob(["**/*.rs"]),
    crate = "acp_agent",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/agent-client-protocol-http/2.0.0:agent_client_protocol_http",
        "//third-party/rust/crates/agent-client-protocol/2.0.0:agent_client_protocol",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/bzip2/0.6.1:bzip2",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/zip/8.6.0:zip",
    ],
)
