load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_glr_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_glr_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-ir/0.8.0:adze_ir",
        "//third-party/rust/crates/fixedbitset/0.5.7:fixedbitset",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/typed-arena/2.0.2:typed_arena",
    ],
)
