load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abc_parser",
    srcs = glob(["**/*.rs"]),
    crate = "abc_parser",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fraction/0.15.4:fraction",
        "//third-party/rust/crates/peg/0.8.6:peg",
    ],
)
