load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_daemon_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_daemon_utils",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix/0.9.0:actix",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
