load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advtools",
    srcs = glob(["**/*.rs"]),
    crate = "advtools",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.5.2:arrayvec",
        "//third-party/rust/crates/hashbrown/0.6.3:hashbrown",
        "//third-party/rust/crates/itertools/0.8.2:itertools",
        "//third-party/rust/crates/num/0.2.1:num",
        "//third-party/rust/crates/odds/0.3.1:odds",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
