load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_feature_policy_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_feature_policy_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-parser-backend-core/0.1.0:adze_parser_backend_core",
        "//third-party/rust/crates/adze-parser-feature-profile-core/0.1.0:adze_parser_feature_profile_core",
    ],
)
