load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_sdk_macros",
    srcs = glob(["**/*.rs"]),
    crate = "act_sdk_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-types/0.5.0:act_types",
        "//third-party/rust/crates/ciborium/0.2.2:ciborium",
        "//third-party/rust/crates/darling/0.23.0:darling",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/tar/0.4.46:tar",
    ],
)
