load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp_llm_adapter",
    srcs = glob(["**/*.rs"]),
    crate = "acp_llm_adapter",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/agent-client-protocol/1.3.0:agent_client_protocol",
        "//third-party/rust/crates/blocking/1.6.2:blocking",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/globset/0.4.20:globset",
        "//third-party/rust/crates/grep/0.4.1:grep",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/rmcp/2.2.0:rmcp",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sse-reqwest-client/0.3.0:sse_reqwest_client",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
