load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_validation_propagation",
    srcs = glob(["**/*.rs"]),
    crate = "acme_validation_propagation",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hickory-resolver/0.26.1:hickory_resolver",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
