load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams_traits",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams_traits",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/typetag/0.1.8:typetag",
    ],
)
