load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable_derive",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable_derive_lib/0.5.0:abi_stable_derive_lib",
    ],
)
