load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze",
    srcs = glob(["**/*.rs"]),
    crate = "adze",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-concurrency-caps-core/0.1.0:adze_concurrency_caps_core",
        "//third-party/rust/crates/adze-glr-core/0.8.0:adze_glr_core",
        "//third-party/rust/crates/adze-ir/0.8.0:adze_ir",
        "//third-party/rust/crates/adze-linecol-core/0.1.0:adze_linecol_core",
        "//third-party/rust/crates/adze-macro/0.8.0:adze_macro",
        "//third-party/rust/crates/adze-runtime-governance-api/0.1.0:adze_runtime_governance_api",
        "//third-party/rust/crates/adze-stack-pool-core/0.1.0:adze_stack_pool_core",
        "//third-party/rust/crates/adze-tablegen/0.8.0:adze_tablegen",
        "//third-party/rust/crates/adze-ts-format-core/0.1.0:adze_ts_format_core",
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
