load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advantage",
    srcs = glob(["**/*.rs"]),
    crate = "advantage",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/nalgebra/0.19.0:nalgebra",
        "//third-party/rust/crates/num/0.2.1:num",
        "//third-party/rust/crates/paste/0.1.18:paste",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/static_assertions/1.1.0:static_assertions",
    ],
)
