#! /bin/bash -e

echo '# This file is used to benchmark acon' > 'lorem ipsum'
echo '[' >> 'lorem ipsum'
command -v lorem >/dev/null 2>&1 || {
	echo "Command lorem not found. Aborting"
	exit 1
}
echo "$(lorem -p 10000)" | sed 's/^/\t/g' >> 'lorem ipsum'
echo '$' >> 'lorem ipsum'
