load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acid_state",
    srcs = glob(["**/*.rs"]),
    crate = "acid_state",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/0.5.9:bincode",
        "//third-party/rust/crates/lazy_static/0.2.11:lazy_static",
        "//third-party/rust/crates/rustc-serialize/0.3.25:rustc_serialize",
    ],
)
