load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaparser",
    srcs = glob(["**/*.rs"]),
    crate = "adaparser",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aleph-syntax-tree/0.1.5:aleph_syntax_tree",
        "//third-party/rust/crates/lalrpop-util/0.22.2:lalrpop_util",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
