load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acteur",
    srcs = glob(["**/*.rs"]),
    crate = "acteur",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dashmap/3.11.10:dashmap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rand/0.7.3:rand",
    ],
)
