load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_threadpool",
    srcs = glob(["**/*.rs"]),
    crate = "actix_threadpool",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/parking_lot/0.7.1:parking_lot",
        "//third-party/rust/crates/threadpool/1.8.1:threadpool",
    ],
)
