load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admixture_docker",
    srcs = glob(["**/*.rs"]),
    crate = "admixture_docker",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/admixture-docker-macros/0.1.0:admixture_docker_macros",
        "//third-party/rust/crates/admixture/0.1.0:admixture",
        "//third-party/rust/crates/testcontainers/0.26.3:testcontainers",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
