load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_remote",
    srcs = glob(["**/*.rs"]),
    crate = "actix_remote",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/canary/0.3.3:canary",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
