load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_bluefruit_protocol",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_bluefruit_protocol",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/heapless/0.7.17:heapless",
    ],
)
