load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_http_test",
    srcs = glob(["**/*.rs"]),
    crate = "actix_http_test",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-rt/0.2.6:actix_rt",
        "//third-party/rust/crates/actix-server/0.4.3:actix_server",
        "//third-party/rust/crates/actix-service/0.3.6:actix_service",
        "//third-party/rust/crates/actix-utils/0.3.5:actix_utils",
        "//third-party/rust/crates/base64/0.10.1:base64",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/env_logger/0.6.2:env_logger",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/http/0.1.21:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.5.5:serde_urlencoded",
        "//third-party/rust/crates/sha1/0.6.1:sha1",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/time/0.1.45:time",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
