load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads_client",
    srcs = glob(["**/*.rs"]),
    crate = "ads_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
