load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admissibility_kernel",
    srcs = glob(["**/*.rs"]),
    crate = "admissibility_kernel",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/lru/0.12.5:lru",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/regex-lite/0.1.9:regex_lite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/xxhash-rust/0.8.18:xxhash_rust",
    ],
)
