load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abs_data",
    srcs = glob(["**/*.rs"]),
    crate = "abs_data",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.25.0:strum",
        "//third-party/rust/crates/strum_macros/0.25.3:strum_macros",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
