load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/canonical-path/0.1.1:canonical_path",
        "//third-party/rust/crates/clear_on_drop/0.2.5:clear_on_drop",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/failure_derive/0.1.8:failure_derive",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
    ],
)
