load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_client",
    srcs = glob(["**/*.rs"]),
    crate = "acme_client",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/error-chain/0.9.0:error_chain",
        "//third-party/rust/crates/hyper/0.10.16:hyper",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/openssl/0.9.24:openssl",
        "//third-party/rust/crates/reqwest/0.4.0:reqwest",
        "//third-party/rust/crates/rustc-serialize/0.3.25:rustc_serialize",
    ],
)
