load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "account_compression",
    srcs = glob(["**/*.rs"]),
    crate = "account_compression",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aligned-sized/1.1.0:aligned_sized",
        "//third-party/rust/crates/anchor-lang/0.31.1:anchor_lang",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/light-account-checks/0.3.0:light_account_checks",
        "//third-party/rust/crates/light-batched-merkle-tree/0.3.0:light_batched_merkle_tree",
        "//third-party/rust/crates/light-bounded-vec/2.0.1:light_bounded_vec",
        "//third-party/rust/crates/light-compressed-account/0.3.0:light_compressed_account",
        "//third-party/rust/crates/light-concurrent-merkle-tree/2.1.0:light_concurrent_merkle_tree",
        "//third-party/rust/crates/light-hash-set/2.1.0:light_hash_set",
        "//third-party/rust/crates/light-hasher/3.1.0:light_hasher",
        "//third-party/rust/crates/light-indexed-merkle-tree/2.1.0:light_indexed_merkle_tree",
        "//third-party/rust/crates/light-merkle-tree-metadata/0.3.0:light_merkle_tree_metadata",
        "//third-party/rust/crates/light-zero-copy/0.2.0:light_zero_copy",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/solana-security-txt/1.1.3:solana_security_txt",
        "//third-party/rust/crates/zerocopy/0.8.56:zerocopy",
    ],
)
