load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abyss_protocol",
    srcs = glob(["**/*.rs"]),
    crate = "abyss_protocol",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/notify/7.0.0:notify",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tachyonfx/0.9.3:tachyonfx",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
