load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_runtime_governance_api",
    srcs = glob(["**/*.rs"]),
    crate = "adze_runtime_governance_api",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-runtime-governance/0.1.0:adze_runtime_governance",
    ],
)
