load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actfv",
    srcs = glob(["**/*.rs"]),
    crate = "actfv",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/notify-debouncer-full/0.1.0:notify_debouncer_full",
        "//third-party/rust/crates/notify/6.1.1:notify",
    ],
)
