load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accroitre",
    srcs = glob(["**/*.rs"]),
    crate = "accroitre",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/russh/0.61.2:russh",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/xxhash-rust/0.8.18:xxhash_rust",
    ],
)
