load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adorn",
    srcs = glob(["**/*.rs"]),
    crate = "adorn",
    crate_root = "src/lib.rs",
    edition = "2015",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/0.2.3:proc_macro2",
        "//third-party/rust/crates/quote/0.4.2:quote",
        "//third-party/rust/crates/syn/0.12.15:syn",
    ],
)
