load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adler32",
    srcs = glob(["**/*.rs"]),
    crate = "adler32",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
