load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adc_mcp3008",
    srcs = glob(["**/*.rs"]),
    crate = "adc_mcp3008",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/0.1.3:embedded_hal",
    ],
)
