load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_std_fs",
    srcs = glob(["**/*.rs"]),
    crate = "adana_std_fs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adana-script-core/0.15.1:adana_script_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
    ],
)
