load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aaai",
    srcs = glob(["**/*.rs"]),
    crate = "aaai",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aaai-core/0.2.0:aaai_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
