image: rust:latest

stages:
  - check
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/

fmt:
  stage: check
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy:
  stage: check
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

test:
  stage: test
  script:
    - cargo test
