load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_mcp",
    srcs = glob(["**/*.rs"]),
    crate = "add_mcp",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
