load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity",
    srcs = glob(["**/*.rs"]),
    crate = "activity",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
