load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ABC_ECS",
    srcs = glob(["**/*.rs"]),
    crate = "ABC_ECS",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/slotmap/1.1.1:slotmap",
    ],
)
