load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrpc_transport",
    srcs = glob(["**/*.rs"]),
    crate = "actrpc_transport",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrpc-core/0.1.0:actrpc_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/interprocess/2.4.3:interprocess",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-tungstenite/0.29.0:tokio_tungstenite",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
