load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa_core",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa_core",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abscissa_derive/0.3.0:abscissa_derive",
        "//third-party/rust/crates/canonical-path/2.0.2:canonical_path",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
    ],
)
