load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_can",
    srcs = glob(["**/*.rs"]),
    crate = "ace_can",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-core/0.3.1:ace_core",
        "//third-party/rust/crates/ace-proto/0.3.1:ace_proto",
        "//third-party/rust/crates/heapless/0.9.3:heapless",
    ],
)
