load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abbreviator",
    srcs = glob(["**/*.rs"]),
    crate = "abbreviator",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/unicode-segmentation/1.13.3:unicode_segmentation",
    ],
)
