load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessors",
    srcs = glob(["**/*.rs"]),
    crate = "accessors",
    crate_root = "src/lib.rs",
    edition = "2015",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/quote/0.3.15:quote",
        "//third-party/rust/crates/syn/0.9.2:syn",
    ],
)
