load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_ffmpeg_build",
    srcs = glob(["**/*.rs"]),
    crate = "ac_ffmpeg_build",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
        "//third-party/rust/crates/pkg-config/0.3.33:pkg_config",
        "//third-party/rust/crates/vcpkg/0.2.15:vcpkg",
    ],
)
