load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abs_sync",
    srcs = glob(["**/*.rs"]),
    crate = "abs_sync",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/atomex/0.1.1:atomex",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
        "//third-party/rust/crates/pin-utils/0.1.0:pin_utils",
    ],
)
