load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adamastor",
    srcs = glob(["**/*.rs"]),
    crate = "adamastor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adamastor-macros/0.3.0:adamastor_macros",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
