load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpi",
    srcs = glob(["**/*.rs"]),
    crate = "acpi",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.10.3:bit_field",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/spinning_top/0.3.0:spinning_top",
    ],
)
