load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme",
    srcs = glob(["**/*.rs"]),
    crate = "acme",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/der/0.7.10:der",
        "//third-party/rust/crates/ecdsa/0.16.9:ecdsa",
        "//third-party/rust/crates/eyre/0.6.14:eyre",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/p256/0.13.2:p256",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/pem-rfc7468/0.7.0:pem_rfc7468",
        "//third-party/rust/crates/pkcs8/0.10.2:pkcs8",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/x509-cert/0.2.5:x509_cert",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
