load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_spsc",
    srcs = glob(["**/*.rs"]),
    crate = "ach_spsc",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
)
