load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acuity_index_api_rs",
    srcs = glob(["**/*.rs"]),
    crate = "acuity_index_api_rs",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-tungstenite/0.29.0:tokio_tungstenite",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
