load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_node_api",
    srcs = glob(["**/*.rs"]),
    crate = "ac_node_api",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ac-primitives/0.6.0:ac_primitives",
        "//third-party/rust/crates/bitvec/1.1.1:bitvec",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/frame-metadata/15.2.0:frame_metadata",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parity-scale-codec/3.7.5:parity_scale_codec",
        "//third-party/rust/crates/scale-info/2.11.6:scale_info",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sp-application-crypto/21.0.0:sp_application_crypto",
        "//third-party/rust/crates/sp-core/19.0.0:sp_core",
        "//third-party/rust/crates/sp-runtime-interface/16.0.0:sp_runtime_interface",
        "//third-party/rust/crates/sp-runtime/22.0.0:sp_runtime",
    ],
)
