load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adbear",
    srcs = glob(["**/*.rs"]),
    crate = "adbear",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/fast_qr/0.12.7:fast_qr",
        "//third-party/rust/crates/mdns-sd/0.11.5:mdns_sd",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
