load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actaeon",
    srcs = glob(["**/*.rs"]),
    crate = "actaeon",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sodiumoxide/0.2.7:sodiumoxide",
        "//third-party/rust/crates/toml/0.5.11:toml",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
    ],
)
