load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accrua_rs",
    srcs = glob(["**/*.rs"]),
    crate = "accrua_rs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
    ],
)
