load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acid_io",
    srcs = glob(["**/*.rs"]),
    crate = "acid_io",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/memchr/2.8.3:memchr",
    ],
)
