load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_bits",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_bits",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-bits-derive/0.1.0:abstract_bits_derive",
        "//third-party/rust/crates/arbitrary-int/1.3.0:arbitrary_int",
        "//third-party/rust/crates/bitvec/1.1.1:bitvec",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
