load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acadrust",
    srcs = glob(["**/*.rs"]),
    crate = "acadrust",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/encoding_rs/0.8.35:encoding_rs",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/itoa/1.0.18:itoa",
        "//third-party/rust/crates/nalgebra/0.32.6:nalgebra",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/ryu/1.0.23:ryu",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
