load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acktor_ipc_proto",
    srcs = glob(["**/*.rs"]),
    crate = "acktor_ipc_proto",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/prost/0.14.4:prost",
    ],
)
