[book]
authors = ["Muhammad Fiaz <contact@example.com>"]
language = "en"
multilingual = false
src = "src"
title = "Adapters"
description = "High-performance, schema-driven data validation, serialization, deserialization, and structural transformation library for Rust."

[output.html]
git-repository-url = "https://github.com/muhammad-fiaz/adapters"
edit-url-template = "https://github.com/muhammad-fiaz/adapters/edit/main/docs/{path}"
preferred-dark-theme = "navy"
