load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr_of_enum_macro",
    srcs = glob(["**/*.rs"]),
    crate = "addr_of_enum_macro",
    crate_root = "lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive-syn-parse/0.1.5:derive_syn_parse",
        "//third-party/rust/crates/proc-macro-error/1.0.4:proc_macro_error",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/template-quote/0.3.1:template_quote",
    ],
)
