load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accurate",
    srcs = glob(["**/*.rs"]),
    crate = "accurate",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cfg-if/0.1.10:cfg_if",
        "//third-party/rust/crates/ieee754/0.2.6:ieee754",
        "//third-party/rust/crates/num/0.1.43:num",
    ],
)
