load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adequate",
    srcs = glob(["**/*.rs"]),
    crate = "adequate",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/strfmt/0.1.6:strfmt",
    ],
)
