load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_dit",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_dit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cpufeatures/0.2.17:cpufeatures",
    ],
)
