load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu_vulkan",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu_vulkan",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi_gpu_base/0.9.0:adi_gpu_base",
        "//third-party/rust/crates/asi_vulkan/0.8.0:asi_vulkan",
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
