load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actl",
    srcs = glob(["**/*.rs"]),
    crate = "actl",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.3.23:rand",
        "//third-party/rust/crates/serde/1.0.37:serde",
        "//third-party/rust/crates/serde_derive/1.0.37:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.13:serde_json",
        "//third-party/rust/crates/sta/0.1.10:sta",
    ],
)
