load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "advisorygraphen",
    srcs = glob(["**/*.rs"]),
    crate = "advisorygraphen",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advisorygraphen-core/0.3.0:advisorygraphen_core",
        "//third-party/rust/crates/advisorygraphen-projection/0.3.0:advisorygraphen_projection",
        "//third-party/rust/crates/advisorygraphen-runtime/0.3.0:advisorygraphen_runtime",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
