load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abus",
    srcs = glob(["**/*.rs"]),
    crate = "abus",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anchovy/0.2.0:anchovy",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/getrandom/0.4.3:getrandom",
        "//third-party/rust/crates/itoa/1.0.18:itoa",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/rustix/1.1.4:rustix",
        "//third-party/rust/crates/serde_core/1.0.229:serde_core",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
