load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_runtime",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_runtime",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/fs2/0.4.3:fs2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
