load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/md-5/0.9.1:md_5",
    ],
)
