load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aati",
    srcs = glob(["**/*.rs"]),
    crate = "aati",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ascii/1.1.0:ascii",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/humansize/2.1.3:humansize",
        "//third-party/rust/crates/lz4/1.28.1:lz4",
        "//third-party/rust/crates/ring/0.16.20:ring",
        "//third-party/rust/crates/rustc_version/0.4.1:rustc_version",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/tiny_http/0.12.0:tiny_http",
        "//third-party/rust/crates/toml/0.7.8:toml",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
