load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart_rfc7578",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart_rfc7578",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/1.0.1:actix_http",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
