load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_storage_memory",
    srcs = glob(["**/*.rs"]),
    crate = "aa_storage_memory",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
    ],
)
