load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_webpack_proxy",
    srcs = glob(["**/*.rs"]),
    crate = "actix_webpack_proxy",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-web-actors/1.0.4:actix_web_actors",
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/awc/0.2.8:awc",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
