load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_trait",
    srcs = glob(["**/*.rs"]),
    crate = "ad_trait",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/approx/0.5.1:approx",
        "//third-party/rust/crates/bevy_reflect/0.17.3:bevy_reflect",
        "//third-party/rust/crates/nalgebra/0.33.3:nalgebra",
        "//third-party/rust/crates/ndarray/0.17.2:ndarray",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_with/3.22.0:serde_with",
        "//third-party/rust/crates/simba/0.9.1:simba",
        "//third-party/rust/crates/tinyvec/1.12.0:tinyvec",
    ],
)
