load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_channels",
    srcs = glob(["**/*.rs"]),
    crate = "actix_channels",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-web-actors/3.0.0:actix_web_actors",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/actix/0.10.0:actix",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
