load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbutils",
    srcs = glob(["**/*.rs"]),
    crate = "adbutils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/curl/0.4.50:curl",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/path-absolutize/3.1.1:path_absolutize",
    ],
)
