load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abootimg_oxide",
    srcs = glob(["**/*.rs"]),
    crate = "abootimg_oxide",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/binrw/0.14.2:binrw",
    ],
)
