//! Pure-Rust parser and AST types used by the runtime.
//!
//! This module provides a self-contained LR parser that mirrors the
//! Tree-sitter ABI. It is used as the default parsing backend when the
//! `pure-rust` feature is enabled, and can handle any grammar that does not
//! require GLR (ambiguity) support.
//!
//! # Key types
//!
//! - [`Parser`](crate::pure_parser::Parser) — the main entry point; call
//!   [`parse_string`](crate::pure_parser::Parser::parse_string) to parse
//!   source code.
//! - [`ParseResult`](crate::pure_parser::ParseResult) — returned by parse
//!   methods, containing either a
//!   [`ParsedNode`](crate::pure_parser::ParsedNode) tree or a list of
//!   [`ParseError`](crate::pure_parser::ParseError)s.
//! - [`ParsedNode`](crate::pure_parser::ParsedNode) — a node in the concrete
//!   syntax tree with child accessors, byte ranges, and node-kind queries.
#![cfg_attr(feature = "strict_docs", allow(missing_docs))]

// Pure-Rust Tree-sitter compatible parser runtime
// This implements the core parsing algorithm with GLR support

use std::ffi::c_void;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Instant;

// Import ABI types from tablegen
pub type TSSymbol = u16;
pub type TSStateId = u16;
#[allow(dead_code)]
pub type TSFieldId = u16;

/// Lex state for external scanners
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct TSLexState {
    pub lex_state: u16,
    pub external_lex_state: u16,
}

// Language version constants
pub const TREE_SITTER_LANGUAGE_VERSION: u32 = 15;
pub const TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION: u32 = 13;

/// Wrapper for raw pointers to make them Sync
#[repr(transparent)]
pub struct SyncPtr(*const u8);

unsafe impl Sync for SyncPtr {}

impl SyncPtr {
    pub const fn new(ptr: *const u8) -> Self {
        Self(ptr)
    }

    pub const fn as_ptr(&self) -> *const u8 {
        self.0
    }
}

/// A position in a text document expressed as zero-based row and column.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Point {
    /// Zero-based line number.
    pub row: u32,
    /// Zero-based column offset (in bytes, not characters).
    pub column: u32,
}

/// An LR parser for Tree-sitter grammars.
///
/// Create a parser with [`Parser::new`], assign a language via
/// [`Parser::set_language`], then parse source text with
/// [`Parser::parse_string`].
///
/// # Examples
///
/// ```ignore
/// use adze::pure_parser::{Parser, TSLanguage};
///
/// let mut parser = Parser::new();
/// // `language` is typically generated by the adze build tool
/// parser.set_language(language()).expect("compatible ABI version");
/// let result = parser.parse_string("1 + 2");
/// assert!(result.errors.is_empty());
/// ```
#[derive(Debug)]
// Define full TSLanguage for pure-Rust implementation - matches Tree-sitter ABI 15
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TSLanguage {
    pub version: u32,
    pub symbol_count: u32,
    pub alias_count: u32,
    pub token_count: u32,
    pub external_token_count: u32,
    pub state_count: u32,
    pub large_state_count: u32,
    pub production_id_count: u32,
    pub field_count: u32,
    pub max_alias_sequence_length: u16,
    pub production_id_map: *const u16,
    pub parse_table: *const u16,
    pub small_parse_table: *const u16,
    pub small_parse_table_map: *const u32,
    pub parse_actions: *const TSParseAction,
    pub symbol_names: *const *const u8,
    pub field_names: *const *const u8,
    pub field_map_slices: *const u16,
    pub field_map_entries: *const u16,
    pub symbol_metadata: *const u8,
    pub public_symbol_map: *const TSSymbol,
    pub alias_map: *const u16,
    pub alias_sequences: *const TSSymbol,
    pub lex_modes: *const TSLexState,
    pub lex_fn: Option<unsafe extern "C" fn(*mut c_void, TSLexState) -> bool>,
    pub keyword_lex_fn: Option<unsafe extern "C" fn(*mut c_void, TSStateId) -> TSSymbol>,
    pub keyword_capture_token: TSSymbol,
    pub external_scanner: ExternalScanner,
    pub primary_state_ids: *const TSStateId,
    pub production_lhs_index: *const u16, // LHS symbols in table index space
    pub production_count: u16,            // Number of productions
    pub eof_symbol: u16,                  // Column index of EOF (usually 0)
    pub rules: *const TSRule,             // Rule metadata array
    pub rule_count: u16,                  // Number of rules
}

/// Rule metadata for Tree-sitter grammars
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct TSRule {
    pub lhs: u16,    // SymbolId of LHS
    pub rhs_len: u8, // number of symbols on RHS
    pub _pad: u8,    // keep alignment
}

// SAFETY: TSLanguage is a read-only structure that doesn't contain any mutable state.
// All pointers point to static data that is never modified after initialization.
unsafe impl Sync for TSLanguage {}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct TSParseAction {
    pub action_type: u8,
    pub extra: u8,
    pub child_count: u8,
    pub dynamic_precedence: i8,
    pub symbol: TSSymbol,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ExternalScanner {
    pub states: *const u8,
    pub symbol_map: *const TSSymbol,
    pub create: Option<unsafe extern "C" fn() -> *mut c_void>,
    pub destroy: Option<unsafe extern "C" fn(*mut c_void)>,
    pub scan: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, *const bool) -> bool>,
    pub serialize: Option<unsafe extern "C" fn(*mut c_void, *mut u8) -> u32>,
    pub deserialize: Option<unsafe extern "C" fn(*mut c_void, *const u8, u32)>,
}

impl ExternalScanner {
    pub const fn default() -> Self {
        Self {
            states: std::ptr::null(),
            symbol_map: std::ptr::null(),
            create: None,
            destroy: None,
            scan: None,
            serialize: None,
            deserialize: None,
        }
    }
}

impl Default for ExternalScanner {
    fn default() -> Self {
        Self::default()
    }
}

pub struct Parser {
    language: Option<&'static TSLanguage>,
    stack: Vec<StackEntry>,
    timeout_micros: u64,
    cancellation_flag: Option<*const AtomicBool>,
    lexer: Option<Lexer>,
}

/// Stack entry for LR parsing
#[derive(Debug, Clone)]
struct StackEntry {
    state: TSStateId,
    subtree: Option<Subtree>,
    #[allow(dead_code)]
    position: usize,
}

/// Lexer state
#[derive(Debug)]
struct Lexer {
    input: Vec<u8>,
    #[allow(dead_code)]
    position: usize,
    #[allow(dead_code)]
    external_scanner: Option<*mut c_void>,
}

/// Internal node representation during parsing
#[derive(Debug, Clone)]
struct Subtree {
    symbol: TSSymbol,
    children: Vec<Subtree>,
    start_byte: usize,
    end_byte: usize,
    start_point: Point,
    end_point: Point,
    is_extra: bool,
    is_error: bool,
    is_missing: bool,
    #[allow(dead_code)]
    production_id: u16,
    /// Optional field identifier for this node within its parent
    field_id: Option<u16>,
}

/// The result of a parse operation.
///
/// On success, `root` contains the root [`ParsedNode`] of the concrete syntax
/// tree and `errors` is empty. On failure, `root` may be `None` and `errors`
/// will contain one or more [`ParseError`]s.
pub struct ParseResult {
    /// Root node of the parse tree, or `None` if parsing failed completely.
    pub root: Option<ParsedNode>,
    /// Errors encountered during parsing.
    pub errors: Vec<ParseError>,
}

/// A node in the concrete syntax tree produced by the parser.
///
/// Each node records its symbol, byte range, child nodes, and various
/// classification flags. Use the accessor methods (e.g., [`kind`](Self::kind),
/// [`children`](Self::children), [`utf8_text`](Self::utf8_text)) rather than
/// accessing fields directly.
#[derive(Debug, Clone)]
pub struct ParsedNode {
    /// Numeric symbol identifier from the grammar.
    pub symbol: TSSymbol,
    /// Ordered child nodes.
    pub children: Vec<ParsedNode>,
    /// Inclusive start byte offset in the source.
    pub start_byte: usize,
    /// Exclusive end byte offset in the source.
    pub end_byte: usize,
    /// Start position as row/column.
    pub start_point: Point,
    /// End position as row/column.
    pub end_point: Point,
    /// Whether this node represents an "extra" token (e.g., whitespace or comment).
    pub is_extra: bool,
    /// Whether this node represents a parse error.
    pub is_error: bool,
    /// Whether the parser inserted this node to represent a missing token.
    pub is_missing: bool,
    /// Whether this is a named (as opposed to anonymous) grammar symbol.
    pub is_named: bool,
    /// Optional field identifier for this node within its parent.
    pub field_id: Option<u16>,
    pub(crate) language: Option<*const TSLanguage>,
}

/// A parse error at a specific position in the source.
#[derive(Debug, Clone)]
pub struct ParseError {
    /// Byte offset where the error occurred.
    pub position: usize,
    /// Row/column position of the error.
    pub point: Point,
    /// Symbol IDs that the parser expected at this position.
    pub expected: Vec<TSSymbol>,
    /// Symbol ID that the parser actually found.
    pub found: TSSymbol,
}

impl Parser {
    /// Creates a new parser with no language assigned.
    ///
    /// Call [`set_language`](Self::set_language) before parsing.
    pub fn new() -> Self {
        Parser {
            language: None,
            stack: Vec::new(),
            timeout_micros: 0,
            cancellation_flag: None,
            lexer: None,
        }
    }

    /// Sets the language (grammar) that this parser will use.
    ///
    /// # Errors
    ///
    /// Returns `Err` with a description if the language's ABI version is
    /// incompatible or if required table pointers are null.
    pub fn set_language(&mut self, language: &'static TSLanguage) -> Result<(), String> {
        // Validate language version
        if language.version < TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION
            || language.version > TREE_SITTER_LANGUAGE_VERSION
        {
            return Err(format!(
                "Incompatible language version: {}",
                language.version
            ));
        }

        // Validate required pointers based on table type
        if language.large_state_count > 0 {
            // Large-table path requires parse_table + parse_actions
            if language.parse_table.is_null() || language.parse_actions.is_null() {
                return Err(
                    "Invalid language: large_state_count > 0 but parse_table/parse_actions is null"
                        .to_string(),
                );
            }
        } else {
            // Small-table path requires both small arrays
            if language.small_parse_table.is_null() || language.small_parse_table_map.is_null() {
                return Err("Invalid language: small table path missing small_parse_table/small_parse_table_map".to_string());
            }
        }

        // Symbol metadata & names must be present
        if language.symbol_names.is_null() || language.symbol_metadata.is_null() {
            return Err("Invalid language: missing symbol_names or symbol_metadata".to_string());
        }

        // Field names can be null if field_count == 0
        if language.field_count > 0 && language.field_names.is_null() {
            return Err("Invalid language: field_count > 0 but field_names is null".to_string());
        }

        self.language = Some(language);
        self.reset();
        Ok(())
    }

    /// Returns the currently assigned language, if any.
    pub fn language(&self) -> Option<&'static TSLanguage> {
        self.language
    }

    /// Sets the maximum time (in microseconds) the parser may run.
    ///
    /// A value of `0` (the default) means no timeout.
    pub fn set_timeout_micros(&mut self, timeout: u64) {
        self.timeout_micros = timeout;
    }

    /// Sets an atomic flag that, when set to `true`, cancels the current parse.
    ///
    /// # Safety
    ///
    /// The caller must ensure the pointed-to [`AtomicBool`] outlives the parse
    /// operation.
    pub fn set_cancellation_flag(&mut self, flag: Option<*const AtomicBool>) {
        self.cancellation_flag = flag;
    }

    /// Resets the parser state, discarding any partial parse progress.
    pub fn reset(&mut self) {
        self.stack.clear();
    }

    /// Parses a UTF-8 string and returns a [`ParseResult`].
    ///
    /// This is the primary entry point for parsing. A language must be set via
    /// [`set_language`](Self::set_language) before calling this method.
    pub fn parse_string(&mut self, source: &str) -> ParseResult {
        self.parse_string_with_tree(source, None)
    }

    /// Parses a UTF-8 string, optionally reusing nodes from a previous tree for
    /// incremental parsing.
    pub fn parse_string_with_tree(
        &mut self,
        source: &str,
        old_tree: Option<&crate::pure_incremental::Tree>,
    ) -> ParseResult {
        let bytes = source.as_bytes();
        self.parse_bytes_with_tree(bytes, old_tree)
    }

    /// Parses raw bytes of source code and returns a [`ParseResult`].
    pub fn parse_bytes(&mut self, source: &[u8]) -> ParseResult {
        self.parse_bytes_with_tree(source, None)
    }

    /// Parses raw bytes, optionally reusing nodes from a previous tree.
    pub fn parse_bytes_with_tree(
        &mut self,
        source: &[u8],
        old_tree: Option<&crate::pure_incremental::Tree>,
    ) -> ParseResult {
        let language = match self.language {
            Some(lang) => lang,
            None => {
                return ParseResult {
                    root: None,
                    errors: vec![ParseError {
                        position: 0,
                        point: Point { row: 0, column: 0 },
                        expected: vec![],
                        found: 0,
                    }],
                };
            }
        };

        // Initialize parser state
        self.stack.clear();

        // The initial state is always state 0 in a properly generated parser
        let initial_state = 0;

        self.stack.push(StackEntry {
            state: initial_state,
            subtree: None,
            position: 0,
        });

        // Initialize lexer with sentinel byte to prevent OOB reads
        let mut input_with_sentinel = source.to_vec();
        // Add a null byte sentinel if not already present
        if input_with_sentinel.last().copied() != Some(0) {
            input_with_sentinel.push(0);
        }
        self.lexer = Some(Lexer {
            input: input_with_sentinel,
            position: 0,
            external_scanner: None,
        });

        // Get reusable nodes from old tree if available
        let _reusable_nodes = old_tree.map(|tree| tree.get_reusable_nodes());

        let mut errors = Vec::new();
        let mut position = 0;
        let mut point = Point { row: 0, column: 0 };
        let start_time = Instant::now();
        // Collect extra tokens so they can be attached to the final tree after parsing
        let mut extra_nodes: Vec<Subtree> = Vec::new();

        // Main parsing loop
        let mut iteration_count = 0;
        loop {
            iteration_count += 1;
            if iteration_count > 10000 {
                //eprintln!("WARNING: Parser exceeded 10000 iterations, likely infinite loop");
                errors.push(ParseError {
                    position,
                    point,
                    expected: vec![],
                    found: 0,
                });
                break;
            }

            // Check timeout
            if self.timeout_micros > 0 {
                let elapsed = start_time.elapsed().as_micros() as u64;
                if elapsed > self.timeout_micros {
                    errors.push(ParseError {
                        position,
                        point,
                        expected: vec![],
                        found: 0,
                    });
                    break;
                }
            }

            // Check cancellation
            if let Some(flag) = self.cancellation_flag {
                unsafe {
                    if (*flag).load(Ordering::Relaxed) {
                        errors.push(ParseError {
                            position,
                            point,
                            expected: vec![],
                            found: 0,
                        });
                        break;
                    }
                }
            }

            // Get current state
            let current_state = match self.stack.last() {
                Some(entry) => entry.state,
                None => break,
            };

            // Lex next token
            let token = self.lex_token(language, current_state, position, &mut point);

            // Handle extra tokens (like whitespace)
            if token.is_extra {
                // Safety check: ensure token length doesn't exceed remaining input
                if position + token.length > source.len() {
                    errors.push(ParseError {
                        position,
                        point,
                        expected: vec![], // Empty since this is a bounds error, not a parsing error
                        found: token.symbol,
                    });
                    break;
                }

                // Create a subtree for the extra token
                let token_end = position + token.length;
                let end_point = advance_point(point, &source[position..token_end]);
                let extra = Subtree {
                    symbol: token.symbol,
                    children: Vec::new(),
                    start_byte: position,
                    end_byte: token_end,
                    start_point: point,
                    end_point,
                    is_extra: true,
                    is_error: false,
                    is_missing: false,
                    production_id: 0,
                    field_id: None,
                };

                // Attach to current stack node if possible, otherwise stash for later
                if let Some(top) = self.stack.last_mut() {
                    if let Some(ref mut node) = top.subtree {
                        node.end_byte = extra.end_byte;
                        node.end_point = extra.end_point;
                        node.children.push(extra);
                    } else {
                        extra_nodes.push(extra);
                    }
                } else {
                    extra_nodes.push(extra);
                }

                // Advance position and point
                position = token_end;
                point = end_point;
                continue;
            }

            // Track parsing progress

            // Get action for current state and token
            let action = self.get_action(language, current_state, token.symbol);
            // Debug logging for arithmetic parsing
            if source.len() < 20 {
                //if current_state == 0 && position == 0 {
                self.dump_row(language, 0);
                //}
                let _byte_repr = if position < source.len() {
                    format!(
                        "'{}' (0x{:02x})",
                        source[position] as char, source[position]
                    )
                } else {
                    "EOF".to_string()
                };
                // eprintln!(
                // "DEBUG: Position={}, State={}, token symbol={}, action={:?}, current_byte={}, stack_len={}",
                // position,
                // current_state,
                // token.symbol,
                // action,
                // _byte_repr,
                // self.stack.len()
                // );
                // eprintln!(
                // "DEBUG: Stack size: {}, token.length={}",
                // self.stack.len(),
                // token.length
                // );
            }
            match action {
                Action::Shift(next_state) => {
                    // Safety check: ensure token length doesn't exceed remaining input
                    if position + token.length > source.len() {
                        errors.push(ParseError {
                            position,
                            point,
                            expected: vec![], // Empty since this is a bounds error, not a parsing error
                            found: token.symbol,
                        });
                        break;
                    }

                    // Create leaf node
                    let token_end = position + token.length;
                    let end_point = advance_point(point, &source[position..token_end]);
                    let subtree = Subtree {
                        symbol: token.symbol,
                        children: Vec::new(),
                        start_byte: position,
                        end_byte: token_end,
                        start_point: point,
                        end_point,
                        is_extra: token.is_extra,
                        is_error: false,
                        is_missing: false,
                        production_id: 0,
                        field_id: None,
                    };

                    // Push onto stack
                    self.stack.push(StackEntry {
                        state: next_state,
                        subtree: Some(subtree),
                        position: token_end,
                    });

                    // Advance position (using safe calculation)
                    position = token_end;
                    point = end_point;

                    if position < 10 {
                        ////eprintln!($
                        //    "DEBUG: Advanced position to {} (after {} bytes), continuing to next token",
                        //    position, token.length
                        //);
                    }
                    // Don't break here! We need to continue the loop
                    // break;
                }

                Action::Reduce(rule_id) => {
                    if !self.reduce(language, rule_id, source) {
                        // Reduction failed - record error and try to recover
                        errors.push(ParseError {
                            position,
                            point,
                            expected: self.get_expected_symbols(language, current_state),
                            found: token.symbol,
                        });

                        // Simple recovery: skip token and continue
                        position += token.length;
                        point = advance_point(point, &source[position - token.length..position]);
                    }
                    // Important: Don't advance position after reduce!
                    // The same token needs to be processed again with the new state
                    continue;
                }

                Action::Accept => {
                    ////eprintln!("DEBUG: Got ACCEPT action!");
                    // Parse successful
                    if let Some(entry) = self.stack.pop()
                        && let Some(subtree) = entry.subtree
                    {
                        let mut root = subtree;
                        if !extra_nodes.is_empty() {
                            // Track the maximum end position of all extra tokens
                            let mut max_end_byte = root.end_byte;
                            let mut max_end_point = root.end_point;

                            for extra in extra_nodes.drain(..) {
                                if extra.end_byte > max_end_byte {
                                    max_end_byte = extra.end_byte;
                                    max_end_point = extra.end_point;
                                }
                                root.children.push(extra);
                            }

                            // Update root to span all tokens including extras
                            root.end_byte = max_end_byte;
                            root.end_point = max_end_point;
                        }
                        return ParseResult {
                            root: Some(subtree_to_node(root, Some(language as *const _))),
                            errors,
                        };
                    }
                    break;
                }

                Action::Error => {
                    // Record error and try to recover
                    let expected_symbols = self.get_expected_symbols(language, current_state);
                    // eprintln!(
                    // "ERROR: position={}, current_state={}, expected_symbols={:?}, token.symbol={}",
                    // position, current_state, expected_symbols, token.symbol
                    // );
                    errors.push(ParseError {
                        position,
                        point,
                        expected: expected_symbols,
                        found: token.symbol,
                    });

                    // Simple error recovery: skip token
                    if position < source.len() {
                        position += 1;
                        point = advance_point(point, &source[position - 1..position]);
                    } else {
                        break;
                    }
                }
            }
        }

        ParseResult { root: None, errors }
    }

    /// Lex a token at the current position
    fn lex_token(
        &mut self,
        language: &TSLanguage,
        state: TSStateId,
        position: usize,
        point: &mut Point,
    ) -> Token {
        let lexer = match self.lexer.as_mut() {
            Some(l) => l,
            None => {
                debug_assert!(
                    language.eof_symbol < language.token_count as u16,
                    "EOF symbol {} must be within token range [0, {})",
                    language.eof_symbol,
                    language.token_count
                );
                return Token {
                    symbol: language.eof_symbol,
                    length: 0,
                    is_extra: false,
                };
            }
        };

        // Check for EOF (accounting for sentinel byte)
        if position >= lexer.input.len() - 1 {
            debug_assert!(
                language.eof_symbol < language.token_count as u16,
                "EOF symbol {} must be within token range [0, {})",
                language.eof_symbol,
                language.token_count
            );
            return Token {
                symbol: language.eof_symbol,
                length: 0,
                is_extra: false,
            }; // EOF
        }

        // Get lex state for current parser state with null pointer check
        let lex_mode = unsafe {
            if !language.lex_modes.is_null() && state < language.state_count as u16 {
                *language.lex_modes.add(state as usize)
            } else {
                TSLexState {
                    lex_state: 0,
                    external_lex_state: 0,
                }
            }
        };

        // Try external scanner first if available
        if lex_mode.external_lex_state != 0
            && let Some(scan_fn) = language.external_scanner.scan
        {
            unsafe {
                // Build valid symbols array from external_lex_state bitset.
                // Tree-sitter's external scanners expect a 1-based array of flags
                // with index 0 unused, so allocate an extra slot and shift bits.
                // `Vec<bool>` is bitpacked and unsuitable for FFI; use `u8`.
                let external_count = language.external_token_count as usize;
                let mut valid_symbols = vec![0u8; external_count + 1];
                for i in 0..external_count {
                    if (lex_mode.external_lex_state >> i) & 1 != 0 {
                        valid_symbols[i + 1] = 1;
                    }
                }

                // Create scanner instance if provided
                let scanner_instance = if let Some(create_fn) = language.external_scanner.create {
                    create_fn()
                } else {
                    std::ptr::null_mut()
                };

                // Prepare lexer adapter
                let mut ext_lexer = ExternalLexer::new(
                    &lexer.input[position..],
                    point.row as usize,
                    point.column as usize,
                );
                let mut ts_lexer = create_ts_lexer(&mut ext_lexer);

                let success = scan_fn(
                    scanner_instance,
                    &mut ts_lexer as *mut _ as *mut c_void,
                    valid_symbols.as_ptr().cast::<bool>(),
                );
                ext_lexer.result_symbol = ts_lexer.result_symbol;

                if !scanner_instance.is_null()
                    && let Some(destroy_fn) = language.external_scanner.destroy
                {
                    destroy_fn(scanner_instance);
                }

                if success
                    && ext_lexer.result_symbol > 0
                    && (ext_lexer.result_symbol as usize) <= external_count
                {
                    let symbol = if !language.external_scanner.symbol_map.is_null() {
                        *language
                            .external_scanner
                            .symbol_map
                            .add(ext_lexer.result_symbol as usize)
                    } else {
                        ext_lexer.result_symbol
                    };

                    return Token {
                        symbol,
                        length: ext_lexer.token_end,
                        is_extra: false,
                    };
                }
            }
        }

        // Use built-in lexer
        if let Some(lex_fn) = language.lex_fn {
            // Adapt Tree-sitter's C-style lexer callback to our input. We create a
            // minimal `TsLexer` backed by the remaining input starting at
            // `position` and invoke the language's lexer function.
            unsafe {
                use crate::lex::TsLexer;

                #[repr(C)]
                struct Backing<'a> {
                    input: &'a [u8],
                    pos: usize,
                    mark: usize,
                    tok_len: usize,
                }

                unsafe extern "C" fn lookahead(lex: *mut TsLexer) -> u32 {
                    unsafe {
                        // Null pointer check
                        if lex.is_null() || (*lex).data.is_null() {
                            return 0;
                        }
                        let st = &*((*lex).data as *const Backing);
                        if st.pos < st.input.len() {
                            st.input[st.pos] as u32
                        } else {
                            0
                        }
                    }
                }

                unsafe extern "C" fn advance(lex: *mut TsLexer, _skip: bool) {
                    unsafe {
                        // Null pointer check
                        if lex.is_null() || (*lex).data.is_null() {
                            return;
                        }
                        let st = &mut *((*lex).data as *mut Backing);
                        if st.pos < st.input.len() {
                            st.pos += 1;
                        }
                    }
                }

                unsafe extern "C" fn mark_end(lex: *mut TsLexer) {
                    unsafe {
                        // Null pointer check
                        if lex.is_null() || (*lex).data.is_null() {
                            return;
                        }
                        let st = &mut *((*lex).data as *mut Backing);
                        st.mark = st.pos;
                    }
                }

                // Safety check: ensure position doesn't exceed input bounds
                if position >= lexer.input.len() {
                    return Token {
                        symbol: language.eof_symbol,
                        length: 0,
                        is_extra: false,
                    };
                }

                let mut backing = Backing {
                    input: &lexer.input,
                    pos: position,
                    mark: position,
                    tok_len: 0,
                };

                let mut ts = TsLexer {
                    lookahead,
                    advance,
                    mark_end,
                    result_symbol: u16::MAX,
                    data: &mut backing as *mut _ as *mut c_void,
                };

                if lex_fn(&mut ts as *mut _ as *mut c_void, lex_mode)
                    && ts.result_symbol != u16::MAX
                {
                    let end = if backing.mark > position {
                        backing.mark
                    } else {
                        backing.pos
                    };
                    let symbol = ts.result_symbol;
                    return Token {
                        symbol,
                        length: end - position,
                        is_extra: self.is_extra_symbol(language, symbol),
                    };
                } else {
                    let at_eof = position >= lexer.input.len() - 1;
                    let symbol = if at_eof { language.eof_symbol } else { 0 };
                    return Token {
                        symbol,
                        length: 0,
                        is_extra: false,
                    };
                }
            }
        }

        // Fallback: simple character-by-character lexing
        // Safe access with bounds check (accounting for sentinel)
        if position >= lexer.input.len() - 1 {
            // At EOF - return EOF symbol from language
            debug_assert!(
                language.eof_symbol < language.token_count as u16,
                "EOF symbol {} must be within token range [0, {})",
                language.eof_symbol,
                language.token_count
            );
            return Token {
                symbol: language.eof_symbol, // EOF column index from language
                length: 0,
                is_extra: false,
            };
        }

        let ch = lexer.input[position];
        //eprintln!("DEBUG lex_token: Fallback lexing at position={}, ch={:?} ({})", position, ch as char, ch);

        // Skip whitespace as extras
        if ch.is_ascii_whitespace() {
            let mut len = 1;
            while position + len < lexer.input.len() - 1  // Account for sentinel
                && lexer.input[position + len].is_ascii_whitespace()
            {
                len += 1;
            }
            return Token {
                symbol: 1,
                length: len,
                is_extra: true,
            };
        }

        // Single character tokens
        Token {
            symbol: ch as u16,
            length: 1,
            is_extra: false,
        }
    }

    /// Check if a symbol is marked as hidden (starts with _)
    fn is_hidden_symbol(&self, language: &TSLanguage, symbol: TSSymbol) -> bool {
        // SAFETY: `symbol_metadata` points to a static array of `symbol_count`
        // entries. `symbol` is bounds-checked before dereferencing.
        unsafe {
            if symbol < language.symbol_count as u16 {
                let metadata_ptr = language.symbol_metadata;
                if metadata_ptr.is_null() {
                    return false;
                }

                let metadata = *metadata_ptr.add(symbol as usize);
                // Check if HIDDEN flag is set (0x04)
                let is_hidden = (metadata & 0x04) != 0;
                // Also check if NOT VISIBLE (0x01 is visible flag)
                let not_visible = (metadata & 0x01) == 0;
                is_hidden || not_visible
            } else {
                false
            }
        }
    }

    /// Check if a symbol is marked as extra (e.g., whitespace)
    fn is_extra_symbol(&self, language: &TSLanguage, symbol: TSSymbol) -> bool {
        // SAFETY: Same invariants as `is_hidden_symbol` — static metadata array
        // with bounds check on `symbol`.
        unsafe {
            if symbol < language.symbol_count as u16 {
                let metadata_ptr = language.symbol_metadata;
                if metadata_ptr.is_null() {
                    //eprintln!("ERROR: metadata_ptr is NULL!");
                    return false;
                }

                // Debug: print first few metadata bytes
                if symbol == 3 || symbol == 4 {
                    ////eprintln!("DEBUG metadata array dump for symbol {}:", symbol);
                    for i in 0..std::cmp::min(9, language.symbol_count) {
                        let _byte = *metadata_ptr.add(i as usize);
                        //eprintln!("  metadata[{}] = {:#x}", i, byte);
                    }
                }

                let metadata = *metadata_ptr.add(symbol as usize);
                // Check if HIDDEN flag is set (0x04)

                ////eprintln!($
                //"DEBUG is_extra_symbol: symbol={}, metadata_ptr={:p}, offset={}, metadata={:#x}, is_hidden={}",
                //symbol, metadata_ptr, symbol as usize, metadata, is_hidden
                //);
                (metadata & 0x04) != 0
            } else {
                false
            }
        }
    }

    /// Debug helper: dump a parse table row
    #[allow(dead_code)]
    fn dump_row(&self, language: &TSLanguage, state: u16) {
        // SAFETY: Reads from static parse table arrays. All accesses are bounded
        // by `large_state_count`, `symbol_count`, and `state_count`.
        unsafe {
            let large_state_count = language.large_state_count as usize;
            let token_count = language.token_count as u16;

            // eprintln!("=== Dumping state {} ===", state);
            // eprintln!(
            // "token_count: {}, symbol_count: {}",
            // language.token_count, language.symbol_count
            // );

            if (state as usize) >= large_state_count {
                let map_index = (state as usize) - large_state_count;
                let start_offset = (*language.small_parse_table_map.add(map_index)) as usize;
                let end_offset = (*language.small_parse_table_map.add(map_index + 1)) as usize;

                // eprintln!(
                // "Small state: map_index={}, start={}, end={}",
                // map_index, start_offset, end_offset
                // );

                let mut offset = start_offset;
                while offset + 1 < end_offset {
                    let s = *language.small_parse_table.add(offset);
                    let _v = *language.small_parse_table.add(offset + 1);
                    offset += 2;

                    let _kind = if s < token_count { "TOK " } else { "GOTO" };
                    // eprintln!("  {:>4} {:>5} -> action {}", kind, s, v);
                }
            } else {
                // eprintln!("Large state - dense row in parse_table");
            }
        }
    }

    /// Get goto state for a non-terminal after reduction
    /// Note: symbol parameter is a table column index, not a symbol ID
    fn get_goto(
        &self,
        language: &TSLanguage,
        state: TSStateId,
        symbol: TSSymbol, // Actually a column index in table space
    ) -> Option<TSStateId> {
        // eprintln!(
        // "DEBUG get_goto: state={}, col_idx={}, token_count={}, symbol_count={}",
        // state, symbol, language.token_count, language.symbol_count
        // );
        // SAFETY: All pointer reads into `parse_table`, `small_parse_table`, and
        // `small_parse_table_map` are guarded by bounds checks against
        // `state_count`, `symbol_count`, and `large_state_count`.
        unsafe {
            // Check bounds
            if state >= language.state_count as u16 || symbol >= language.symbol_count as u16 {
                // eprintln!(
                // "  Bounds check failed: state >= {} or symbol >= {}",
                // language.state_count, language.symbol_count
                // );
                return None;
            }

            let large_state_count = language.large_state_count as usize;
            let symbol_count = language.symbol_count as usize;
            let token_count = language.token_count as u16;

            // Only non-terminals have goto entries
            if symbol < token_count {
                // eprintln!(
                // "  Symbol {} is a token (< {}), no goto",
                // symbol, token_count
                // );
                return None;
            }
            // eprintln!(
            // "  Column {} is a non-terminal (>= {}), checking goto",
            // symbol, token_count
            // );
            // eprintln!(
            // "  large_state_count={}, state={}, is_large={}",
            // large_state_count,
            // state,
            // (state as usize) < large_state_count
            // );

            if (state as usize) < large_state_count {
                // LARGE STATE: Dense row in parse_table
                let base = (state as usize) * symbol_count;
                let index = base + (symbol as usize);
                let goto_state = *language.parse_table.add(index);

                // eprintln!(
                // "  Large state: base={}, index={}, goto_state={}",
                // base, index, goto_state
                // );

                if goto_state != 0 {
                    return Some(goto_state);
                }
            } else {
                // SMALL STATE: Look for goto entry
                let map_index = (state as usize) - large_state_count;
                let start_offset = (*language.small_parse_table_map.add(map_index)) as usize;
                let end_offset = (*language.small_parse_table_map.add(map_index + 1)) as usize;

                // eprintln!(
                // "  Small state: map_index={}, start_offset={}, end_offset={}",
                // map_index, start_offset, end_offset
                // );

                let mut offset = start_offset;
                while offset + 1 < end_offset {
                    let entry_col = *language.small_parse_table.add(offset) as usize;
                    let entry_val = *language.small_parse_table.add(offset + 1);
                    // eprintln!(
                    // "    Entry at offset {}: col={}, val={}",
                    // offset, entry_col, entry_val
                    // );
                    offset += 2;

                    // Check if this is the column we're looking for
                    if entry_col == symbol as usize {
                        // This entry is for a non-terminal (symbol >= token_count was checked above)
                        // The value is the goto state

                        // Debug guard: verify this is a nonterminal column
                        debug_assert!(
                            symbol >= token_count,
                            "get_goto should only find NT columns: {} >= {}",
                            symbol,
                            token_count
                        );

                        // eprintln!(
                        // "    Found match for column {}! goto_state={}",
                        // symbol, entry_val
                        // );
                        if entry_val != 0 {
                            return Some(entry_val);
                        }
                        return None;
                    }
                }
                // eprintln!("    No match found for column {}", symbol);
            }
            None
        }
    }

    /// Get parse action for state and symbol
    fn get_action(&self, language: &TSLanguage, state: TSStateId, symbol: TSSymbol) -> Action {
        // Debug dump state 0 once
        use std::sync::Once;
        static DUMP_ONCE: Once = Once::new();
        if state == 0 {
            DUMP_ONCE.call_once(|| self.dump_row(language, 0));
        }

        // Look up action in parse table
        // SAFETY: All pointer reads into `parse_table`, `small_parse_table`, and
        // `small_parse_table_map` are guarded by bounds checks on `state` and
        // `symbol` against `state_count` and `symbol_count`.
        unsafe {
            // Check bounds
            if state >= language.state_count as u16 || symbol >= language.symbol_count as u16 {
                return Action::Error;
            }

            let large_state_count = language.large_state_count as usize;
            let symbol_count = language.symbol_count as usize;
            let token_count = language.token_count as u16;

            // Only tokens (not non-terminals) are valid lookaheads
            if symbol >= token_count {
                return Action::Error;
            }

            // Sanity checks
            debug_assert!((language.token_count as usize) <= language.symbol_count as usize);
            debug_assert!((state as usize) < language.state_count as usize);

            if (state as usize) < large_state_count {
                // LARGE STATE: Dense row in parse_table
                // Layout: parse_table[(state * symbol_count) + lookahead]
                let base = (state as usize) * symbol_count;
                let index = base + (symbol as usize);

                // Large states use the main parse_table
                let action_value = *language.parse_table.add(index);

                if action_value != 0 {
                    return self.decode_action(language, action_value as usize);
                }
            } else {
                // SMALL STATE: Compressed row in small_parse_table
                // Format is direct (symbol, action) pairs
                let map_index = (state as usize) - large_state_count;

                // Read u32 offsets properly!
                let start_offset = (*language.small_parse_table_map.add(map_index)) as usize;
                let end_offset = (*language.small_parse_table_map.add(map_index + 1)) as usize;

                // Parse direct (column, value) pairs
                let mut offset = start_offset;

                while offset + 1 < end_offset {
                    let entry_col = *language.small_parse_table.add(offset);
                    let entry_val = *language.small_parse_table.add(offset + 1);
                    offset += 2;

                    // Check if this is the column we're looking for
                    // For tokens, symbol ID equals column index (by design)
                    if entry_col == symbol {
                        // Verify this is a token column (should always be true when called from get_action)
                        debug_assert!(
                            entry_col < token_count,
                            "get_action should only look at token columns"
                        );
                        if entry_val != 0 {
                            return self.decode_action(language, entry_val as usize);
                        }
                        return Action::Error;
                    }
                }
            }
        }

        Action::Error
    }

    /// Decode action from parse table
    fn decode_action(&self, _language: &TSLanguage, action_index: usize) -> Action {
        // Decode action from index
        //
        // Action Encoding Contract (must match tablegen/src/compress.rs):
        // ┌──────────┬──────────────┬──────────────────┐
        // │ Encoding │ Meaning      │ Bits             │
        // ├──────────┼──────────────┼──────────────────┤
        // │ 0x0000   │ Error        │ 0000000000000000 │
        // │ 0x0001   │ Shift(1)     │ 0nnnnnnnnnnnnnnn │
        // │ 0x7FFF   │ Shift(32767) │ 0111111111111111 │
        // │ 0x8000   │ Reduce(0)    │ 1nnnnnnnnnnnnnnn │
        // │ 0xFFFE   │ Reduce(32766)│ 1111111111111110 │
        // │ 0xFFFF   │ Accept       │ 1111111111111111 │
        // └──────────┴──────────────┴──────────────────┘
        //
        // IMPORTANT: Order matters!
        // 1. Check Accept (0xFFFF) FIRST - it has high bit set and would match Reduce
        // 2. Check Error (0x0000) SECOND - it would otherwise match Shift(0)
        // 3. Check Reduce (high bit set)
        // 4. Everything else is Shift

        if action_index == 0xFFFF {
            // Accept action (encoded as 0xFFFF in compression)
            Action::Accept
        } else if action_index == 0 {
            // Error action (encoded as 0 or missing from table)
            // tablegen/compress.rs skips Action::Error entries to save space
            Action::Error
        } else if action_index & 0x8000 != 0 {
            // Reduce action (high bit set)
            let production_id = (action_index & 0x7FFF) as u16;
            Action::Reduce(production_id)
        } else {
            // Shift action (low values, no high bit)
            let next_state = action_index as u16;
            Action::Shift(next_state)
        }
    }

    /// Get the LHS symbol index for a production from the production_lhs_index array
    #[inline]
    fn lhs_index_of(&self, language: &TSLanguage, production_index: u16) -> u16 {
        // SAFETY: Caller ensures `production_index < production_id_count`.
        // `production_lhs_index` is a static array of at least that many entries.
        unsafe { *language.production_lhs_index.add(production_index as usize) }
    }

    /// Perform a reduction
    fn reduce(&mut self, language: &TSLanguage, production_id: u16, source: &[u8]) -> bool {
        if source.len() < 20 {
            // eprintln!(
            // "DEBUG reduce: Reducing with production_id={} (from parse table)",
            // production_id
            // );
            // eprintln!(
            // "DEBUG reduce: Stack before reduction has {} entries",
            // self.stack.len()
            // );
            for entry in self.stack.iter() {
                if let Some(ref _subtree) = entry.subtree {
                    // eprintln!(
                    // "  Stack[{}]: state={}, symbol={}",
                    // i, entry.state, subtree.symbol
                    // );
                } else {
                    // eprintln!("  Stack[{}]: state={}, no subtree", i, entry.state);
                }
            }
        }

        // SAFETY: `production_id_map`, `parse_actions`, and `production_lhs_index`
        // are static arrays from TSLanguage. All accesses are guarded by
        // `production_id_count` bounds checks.
        unsafe {
            // Tree-sitter uses 1-based production IDs in the parse table
            // We need to subtract 1 and then use production_id_map
            if production_id == 0 {
                ////eprintln!("DEBUG reduce: Invalid production_id=0 (production IDs are 1-based)");
                return false;
            }

            let zero_based_id = production_id - 1;

            // Use the production_id_map to get the actual production index
            let production_index = if zero_based_id < language.production_id_count as u16 {
                *language.production_id_map.add(zero_based_id as usize)
            } else {
                ////eprintln!("DEBUG reduce: Invalid production_id {} (zero_based={}, >= {})",
                //         production_id, zero_based_id, language.production_id_count);
                return false;
            };

            // Look up the parse action for this production
            if production_index >= language.production_id_count as u16 {
                ////eprintln!($
                //    "DEBUG reduce: Invalid production_index {} (>= {})",
                //    production_index, language.production_id_count
                //);
                return false;
            }

            let action = &*language.parse_actions.add(production_index as usize);
            let child_count = action.child_count as usize;

            // Get the LHS symbol from the production_lhs_index array instead of parse_actions
            // This ensures the symbol is in table index space
            let symbol = self.lhs_index_of(language, production_index);

            // Also check what parse_actions says for comparison
            let _parse_action_symbol = action.symbol;
            // eprintln!(
            // "DEBUG: production_index={}, lhs_index={}, parse_action_symbol={}",
            // production_index, symbol, parse_action_symbol
            // );

            if source.len() < 20 {
                // eprintln!(
                // "DEBUG reduce: Production {} (index {}) reduces to symbol {} with {} children (token_count={})",
                // production_id, production_index, symbol, child_count, language.token_count
                // );
                debug_assert!(
                    symbol >= language.token_count as u16,
                    "LHS symbol {} should be a non-terminal (>= token_count {})",
                    symbol,
                    language.token_count
                );
            }

            // If child_count is 3 but we only have 2 items on stack, something is wrong
            if child_count > self.stack.len() {
                ////eprintln!($
                //    "DEBUG reduce: ERROR! Need {} children but stack only has {} items",
                //    child_count,
                //    self.stack.len()
                //);
                return false;
            }

            // Check if we have enough stack entries
            if self.stack.len() < child_count {
                return false;
            }

            // Pop child_count entries from the stack
            let mut children = Vec::new();
            let mut start_byte = usize::MAX;
            let mut end_byte = 0;
            let mut start_point = Point {
                row: u32::MAX,
                column: u32::MAX,
            };
            let mut end_point = Point { row: 0, column: 0 };

            // Pop children in reverse order
            for _ in 0..child_count {
                if let Some(entry) = self.stack.pop()
                    && let Some(subtree) = entry.subtree
                {
                    // Update bounds
                    if subtree.start_byte < start_byte {
                        start_byte = subtree.start_byte;
                        start_point = subtree.start_point;
                    }
                    if subtree.end_byte > end_byte {
                        end_byte = subtree.end_byte;
                        end_point = subtree.end_point;
                    }
                    children.push(subtree);
                }
            }

            // Reverse children to correct order
            children.reverse();

            // Handle empty reduction
            if children.is_empty() && child_count == 0 {
                // For empty reductions, use position from top of stack
                if let Some(top) = self.stack.last() {
                    start_byte = top.position;
                    end_byte = top.position;
                    start_point = Point {
                        row: 0,
                        column: top.position as u32,
                    };
                    end_point = start_point;
                }
            }

            // Check if this symbol is hidden (e.g., _Expression)
            let is_hidden = self.is_hidden_symbol(language, symbol);

            // Create parent node or unwrap if hidden
            let parent = if is_hidden && children.len() == 1 {
                // Return the child directly, skipping the hidden wrapper
                if let Some(node) = children.pop() {
                    node
                } else {
                    Subtree {
                        symbol,
                        children,
                        start_byte,
                        end_byte,
                        start_point,
                        end_point,
                        is_extra: false,
                        is_error: false,
                        is_missing: false,
                        production_id,
                        field_id: None,
                    }
                }
            } else {
                // Create the parent node normally
                Subtree {
                    symbol,
                    children,
                    start_byte,
                    end_byte,
                    start_point,
                    end_point,
                    is_extra: false,
                    is_error: false,
                    is_missing: false,
                    production_id,
                    field_id: None,
                }
            };

            // Check if this is the start symbol (source_file)
            // The start symbol is typically the one that appears on the left side of the start rule
            // In Tree-sitter, the start symbol is typically called "source_file" or similar
            // We need to determine this dynamically from the language structure

            ////eprintln!($
            //    "DEBUG reduce: After reduction, stack size would be: {}",
            //    self.stack.len()
            //);

            // Get the goto state for the reduced symbol
            let prev_state = if let Some(entry) = self.stack.last() {
                entry.state
            } else {
                0
            };

            // eprintln!(
            // "DEBUG reduce: Looking up goto for symbol {} from state {}",
            // symbol, prev_state
            // );

            // Debug: Show all gotos available from this state
            if source.len() < 20 && prev_state == 0 {
                // eprintln!("DEBUG reduce: Available gotos from state 0:");
                for sym_idx in 0..12 {
                    if let Some(_goto_state) = self.get_goto(language, 0, sym_idx) {
                        // eprintln!("  Symbol {} -> state {}", sym_idx, goto_state);
                    }
                }
            }

            // Look up goto state for the non-terminal we just reduced to
            // eprintln!(
            // "DEBUG reduce: About to call get_goto with prev_state={}, symbol={}, token_count={}",
            // prev_state, symbol, language.token_count
            // );
            if let Some(goto_state) = self.get_goto(language, prev_state, symbol) {
                // eprintln!("DEBUG reduce: Found goto_state={}", goto_state);
                // Push the reduced node with the goto state
                self.stack.push(StackEntry {
                    state: goto_state,
                    subtree: Some(parent),
                    position: end_byte,
                });
                true
            } else {
                // No goto found - this shouldn't happen in a valid parse table
                // eprintln!(
                // "DEBUG reduce: No goto for symbol {} from state {} (symbol >= token_count: {})",
                // symbol,
                // prev_state,
                // symbol >= language.token_count as u16
                // );
                false
            }
        }
    }

    /// Get production ID for field mappings
    #[allow(dead_code)]
    fn get_production_id(&self, language: &TSLanguage, action_index: u16) -> u16 {
        // SAFETY: `production_id_map` is a static array of `production_id_count`
        // entries. `action_index` is bounds-checked before access.
        unsafe {
            if action_index < language.production_id_count as u16 {
                *language.production_id_map.add(action_index as usize)
            } else {
                0
            }
        }
    }

    /// Look up the goto state for a non-terminal using the parse table.
    /// Returns `0` when no transition exists, mirroring Tree-sitter's ABI.
    #[allow(dead_code)]
    fn get_goto_state(
        &self,
        language: &TSLanguage,
        state: TSStateId,
        symbol: TSSymbol,
    ) -> TSStateId {
        self.get_goto(language, state, symbol).unwrap_or(0)
    }

    /// Get expected symbols for error reporting
    fn get_expected_symbols(&self, language: &TSLanguage, state: TSStateId) -> Vec<TSSymbol> {
        let mut expected = Vec::new();

        // Check all possible symbols in the parse table
        // The parse table uses the symbol_to_index mapping, so we need to check
        // all symbols from 0 to symbol_count
        let symbol_count = language.symbol_count as u16;

        // For now, check all symbols to see what's valid
        // We can optimize this later to only check terminals
        for symbol in 0..symbol_count {
            let action = self.get_action(language, state, symbol);
            if !matches!(action, Action::Error) {
                expected.push(symbol);
                // Debug: print symbol names for expected symbols
                if state == 0 {
                    // SAFETY: `symbol_names` is a static array of `symbol_count`
                    // C-string entries. `symbol` is bounds-checked before indexing.
                    unsafe {
                        let symbol_names = std::slice::from_raw_parts(
                            language.symbol_names,
                            language.symbol_count as usize,
                        );
                        if symbol < language.symbol_count as u16 {
                            let name_ptr = symbol_names[symbol as usize];
                            if !name_ptr.is_null() {
                                let c_str = std::ffi::CStr::from_ptr(name_ptr as *const i8);
                                let _name = c_str.to_string_lossy();
                            }
                        }
                    }
                }
            }
        }

        expected
    }

    /// Re-parses the source after an edit, falling back to a full reparse.
    ///
    /// This is a temporary implementation that ignores `_old_tree` and `_edit`
    /// and performs a complete fresh parse. True incremental parsing will be
    /// enabled in a future release.
    pub fn reparse(
        &mut self,
        source: &str,
        _old_tree: &crate::pure_incremental::Tree,
        _edit: &crate::pure_incremental::Edit,
    ) -> ParseResult {
        self.parse_string(source)
    }
}

/// Token returned by lexer
#[derive(Debug, Clone, Copy)]
struct Token {
    symbol: TSSymbol,
    length: usize,
    is_extra: bool,
}

/// Parse action
#[derive(Debug, Clone, Copy)]
enum Action {
    Shift(TSStateId),
    Reduce(u16),
    Accept,
    Error,
}

/// Advance point by text
fn advance_point(mut point: Point, text: &[u8]) -> Point {
    for &byte in text {
        if byte == b'\n' {
            point.row += 1;
            point.column = 0;
        } else {
            point.column += 1;
        }
    }
    point
}

/// Convert internal subtree to public node
fn subtree_to_node(subtree: Subtree, language: Option<*const TSLanguage>) -> ParsedNode {
    ////eprintln!($
    //    "DEBUG subtree_to_node: Converting subtree with symbol {}, children: {}, extra: {}",
    //    subtree.symbol,
    //    subtree.children.len(),
    //    subtree.is_extra
    //);

    // Determine if the node is named based on symbol metadata
    let is_named = if let Some(lang_ptr) = language {
        // SAFETY: `lang_ptr` comes from a valid `TSLanguage` that outlives the
        // parse result. `symbol_metadata` is bounds-checked via `symbol_count`.
        unsafe {
            let lang = &*lang_ptr;
            if subtree.symbol < lang.symbol_count as u16 {
                let metadata = *lang.symbol_metadata.add(subtree.symbol as usize);
                // In Tree-sitter, metadata & 1 == 0 means named
                // metadata values: 0 = unnamed extra, 1 = unnamed, 3 = named
                metadata >= 2
            } else {
                false
            }
        }
    } else {
        true // Default to named if no language info
    };

    //eprintln!("  Symbol {} is_named: {}", subtree.symbol, is_named);

    ParsedNode {
        symbol: subtree.symbol,
        children: subtree
            .children
            .into_iter()
            .map(|s| subtree_to_node(s, language))
            .collect(),
        start_byte: subtree.start_byte,
        end_byte: subtree.end_byte,
        start_point: subtree.start_point,
        end_point: subtree.end_point,
        is_extra: subtree.is_extra,
        is_error: subtree.is_error,
        is_missing: subtree.is_missing,
        is_named,
        field_id: subtree.field_id,
        language,
    }
}

impl ParsedNode {
    /// Returns this node's symbol identifier in the grammar.
    pub fn symbol(&self) -> TSSymbol {
        self.symbol
    }

    /// Returns the inclusive start byte offset in the source.
    pub fn start_byte(&self) -> usize {
        self.start_byte
    }

    /// Returns the exclusive end byte offset in the source.
    pub fn end_byte(&self) -> usize {
        self.end_byte
    }

    /// Returns the start position as a row/column [`Point`].
    pub fn start_point(&self) -> Point {
        self.start_point
    }

    /// Returns the end position as a row/column [`Point`].
    pub fn end_point(&self) -> Point {
        self.end_point
    }

    /// Returns the number of direct children of this node.
    pub fn child_count(&self) -> usize {
        self.children.len()
    }

    /// Returns the child at the given index, or `None` if out of bounds.
    pub fn child(&self, index: usize) -> Option<&ParsedNode> {
        self.children.get(index)
    }

    /// Returns a slice of all direct children.
    pub fn children(&self) -> &[ParsedNode] {
        &self.children
    }

    /// Returns `true` if this node is an "extra" token (e.g., whitespace).
    pub fn is_extra(&self) -> bool {
        self.is_extra
    }

    /// Returns `true` if this node represents a parse error.
    pub fn is_error(&self) -> bool {
        self.is_error
    }

    /// Returns `true` if this node was inserted by error recovery to represent
    /// a missing token.
    pub fn is_missing(&self) -> bool {
        self.is_missing
    }

    /// Returns `true` if this node or any descendant is an error node.
    pub fn has_error(&self) -> bool {
        self.is_error || self.children.iter().any(|c| c.has_error())
    }

    /// Returns `true` if this is a named (non-anonymous) grammar symbol.
    pub fn is_named(&self) -> bool {
        self.is_named
    }

    /// Returns the UTF-8 text that this node spans in the given source.
    ///
    /// # Errors
    ///
    /// Returns [`Utf8Error`](std::str::Utf8Error) if the byte range is not
    /// valid UTF-8, or if the byte range is out of bounds.
    #[allow(invalid_from_utf8)]
    pub fn utf8_text<'a>(&self, source: &'a [u8]) -> Result<&'a str, std::str::Utf8Error> {
        let text = source.get(self.start_byte..self.end_byte).ok_or_else(|| {
            // Create a valid Utf8Error by attempting to parse invalid UTF-8
            let invalid = [0x80, 0x80]; // Invalid UTF-8 sequence
            std::str::from_utf8(&invalid).unwrap_err()
        })?;
        std::str::from_utf8(text)
    }

    /// Creates a [`ChildWalker`] for cursor-style traversal of this node's
    /// children.
    pub fn walk(&self) -> ChildWalker<'_> {
        ChildWalker {
            children: &self.children,
            index: 0,
        }
    }

    /// Returns the grammar rule name (kind) of this node.
    ///
    /// When a [`TSLanguage`] is available the name is looked up from the
    /// language's symbol table; otherwise a hardcoded fallback is used.
    pub fn kind(&self) -> &str {
        if let Some(language) = self.language {
            // SAFETY: `language` is a valid pointer to a TSLanguage that outlives
            // this node. `symbol_names` is a static array of `symbol_count` C
            // strings. `self.symbol` is bounds-checked before indexing.
            unsafe {
                let language = &*language;
                if self.symbol < language.symbol_count as u16 {
                    let symbol_names = std::slice::from_raw_parts(
                        language.symbol_names,
                        language.symbol_count as usize,
                    );
                    let name_ptr = symbol_names[self.symbol as usize];
                    let c_str = std::ffi::CStr::from_ptr(name_ptr as *const i8);
                    c_str.to_str().unwrap_or("unknown")
                } else {
                    "unknown"
                }
            }
        } else {
            // Fallback for when language is not available
            match self.symbol {
                0 => "end",
                1 => "*",
                2 => "_2",
                3 => "_6",
                4 => "-",
                5 => "Expression",
                6 => "Whitespace__whitespace",
                7 => "Whitespace",
                8 => "Expression_Sub_1",
                9 => "Expression_Sub",
                10 => "rule_10",
                _ => "unknown",
            }
        }
    }
}

/// Cursor for iterating over a node's children.
///
/// Obtained via [`ParsedNode::walk`]. Navigate with
/// [`goto_first_child`](Self::goto_first_child) and
/// [`goto_next_sibling`](Self::goto_next_sibling), and read the current child
/// with [`node`](Self::node).
pub struct ChildWalker<'a> {
    children: &'a [ParsedNode],
    index: usize,
}

impl<'a> ChildWalker<'a> {
    /// Moves the cursor to the first child. Returns `false` if there are no
    /// children.
    pub fn goto_first_child(&mut self) -> bool {
        self.index = 0;
        !self.children.is_empty()
    }

    /// Advances the cursor to the next sibling. Returns `false` if the cursor
    /// is already at the last child.
    pub fn goto_next_sibling(&mut self) -> bool {
        if self.index + 1 < self.children.len() {
            self.index += 1;
            true
        } else {
            false
        }
    }

    /// Returns the child node at the current cursor position.
    ///
    /// # Panics
    ///
    /// Panics if the cursor index is out of bounds (should not happen with
    /// normal usage of `goto_first_child` / `goto_next_sibling`).
    pub fn node(&self) -> &ParsedNode {
        &self.children[self.index]
    }
}

impl Default for Parser {
    fn default() -> Self {
        Self::new()
    }
}

/// Minimal lexer implementation passed to external scanners
struct ExternalLexer<'a> {
    input: &'a [u8],
    position: usize,
    token_end: usize,
    row: usize,
    column: usize,
    result_symbol: TSSymbol,
}

impl<'a> ExternalLexer<'a> {
    fn new(input: &'a [u8], row: usize, column: usize) -> Self {
        Self {
            input,
            position: 0,
            token_end: 0,
            row,
            column,
            result_symbol: 0,
        }
    }

    // The following `unsafe extern "C"` functions implement the Tree-sitter
    // lexer callback ABI. Each receives a `TsLexer*` whose `data` field points
    // to a valid `ExternalLexer` allocated by the caller. All pointer
    // dereferences are guarded by null checks.

    unsafe extern "C" fn lookahead(lexer: *mut crate::lex::TsLexer) -> u32 {
        if lexer.is_null() {
            return 0;
        }

        // SAFETY: `lexer` is non-null (checked above).
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return 0;
        }

        // SAFETY: `data` was set to point to a valid `ExternalLexer` by the caller.
        let ext_lexer = unsafe { &*(data as *const ExternalLexer) };
        ext_lexer
            .input
            .get(ext_lexer.position)
            .copied()
            .map(u32::from)
            .unwrap_or(0)
    }

    unsafe extern "C" fn advance(lexer: *mut crate::lex::TsLexer, skip: bool) {
        if lexer.is_null() {
            return;
        }

        // SAFETY: `lexer` is non-null (checked above).
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return;
        }

        // SAFETY: `data` points to a valid `ExternalLexer`. Mutable reference
        // is safe because no other references exist during this callback.
        let ext_lexer = unsafe { &mut *(data as *mut ExternalLexer) };
        if ext_lexer.position < ext_lexer.input.len() {
            let byte = ext_lexer.input[ext_lexer.position];
            ext_lexer.position += 1;

            // Update row/column information
            if byte == b'\n' {
                ext_lexer.row += 1;
                ext_lexer.column = 0;
            } else if byte == b'\r' {
                // Handle CRLF by consuming the following LF if present
                if ext_lexer.position < ext_lexer.input.len()
                    && ext_lexer.input[ext_lexer.position] == b'\n'
                {
                    ext_lexer.position += 1;
                }
                ext_lexer.row += 1;
                ext_lexer.column = 0;
            } else {
                ext_lexer.column += 1;
            }

            if !skip {
                ext_lexer.token_end = ext_lexer.position;
            }
        }
    }

    unsafe extern "C" fn mark_end(lexer: *mut crate::lex::TsLexer) {
        if lexer.is_null() {
            return;
        }

        // SAFETY: `lexer` is non-null (checked above).
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return;
        }

        // SAFETY: `data` points to a valid `ExternalLexer`.
        let ext_lexer = unsafe { &mut *(data as *mut ExternalLexer) };
        ext_lexer.token_end = ext_lexer.position;
    }

    // Additional methods for external scanner compatibility (required for C ABI)
    #[allow(dead_code)]
    unsafe extern "C" fn get_column(lexer: *mut crate::lex::TsLexer) -> u32 {
        if lexer.is_null() {
            return 0;
        }
        // SAFETY: `lexer` is non-null. `data` points to a valid `ExternalLexer`.
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return 0;
        }
        let ext_lexer = unsafe { &*(data as *const ExternalLexer) };
        ext_lexer.column as u32
    }

    #[allow(dead_code)]
    unsafe extern "C" fn is_at_included_range_start(lexer: *mut crate::lex::TsLexer) -> bool {
        if lexer.is_null() {
            return false;
        }
        // SAFETY: `lexer` is non-null. `data` points to a valid `ExternalLexer`.
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return false;
        }
        let ext_lexer = unsafe { &*(data as *const ExternalLexer) };
        ext_lexer.position == 0
    }

    #[allow(dead_code)]
    unsafe extern "C" fn eof(lexer: *mut crate::lex::TsLexer) -> bool {
        if lexer.is_null() {
            return true;
        }
        // SAFETY: `lexer` is non-null. `data` points to a valid `ExternalLexer`.
        let data = unsafe { (*lexer).data };
        if data.is_null() {
            return true;
        }
        let ext_lexer = unsafe { &*(data as *const ExternalLexer) };
        ext_lexer.position >= ext_lexer.input.len()
    }
}

/// Create a TSLexer adapter for external scanners
fn create_ts_lexer(ext_lexer: &mut ExternalLexer) -> crate::lex::TsLexer {
    crate::lex::TsLexer {
        lookahead: ExternalLexer::lookahead,
        advance: ExternalLexer::advance,
        mark_end: ExternalLexer::mark_end,
        result_symbol: 0,
        data: ext_lexer as *mut _ as *mut c_void,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parser_creation() {
        let parser = Parser::new();
        assert!(parser.language().is_none());
        assert_eq!(parser.timeout_micros, 0);
    }

    #[test]
    fn test_point_advance() {
        let point = Point { row: 0, column: 0 };
        let point = advance_point(point, b"hello");
        assert_eq!(point.row, 0);
        assert_eq!(point.column, 5);

        let point = advance_point(point, b"\nworld");
        assert_eq!(point.row, 1);
        assert_eq!(point.column, 5);
    }

    #[test]
    fn test_empty_parse() {
        let mut parser = Parser::new();
        let result = parser.parse_string("");
        assert!(result.root.is_none());
        assert!(!result.errors.is_empty());
    }

    #[test]
    fn test_get_goto_handles_missing_entries() {
        // Minimal language with a single token and no goto entries.
        static PARSE_TABLE: [u16; 1] = [0];
        static SMALL_PARSE_TABLE: [u16; 1] = [0];
        static SMALL_PARSE_TABLE_MAP: [u32; 1] = [0];
        static LANGUAGE: TSLanguage = TSLanguage {
            version: TREE_SITTER_LANGUAGE_VERSION,
            symbol_count: 1,
            alias_count: 0,
            token_count: 1,
            external_token_count: 0,
            state_count: 1,
            large_state_count: 1,
            production_id_count: 0,
            field_count: 0,
            max_alias_sequence_length: 0,
            production_id_map: std::ptr::null(),
            parse_table: PARSE_TABLE.as_ptr(),
            small_parse_table: SMALL_PARSE_TABLE.as_ptr(),
            small_parse_table_map: SMALL_PARSE_TABLE_MAP.as_ptr(),
            parse_actions: std::ptr::null(),
            symbol_names: std::ptr::null(),
            field_names: std::ptr::null(),
            field_map_slices: std::ptr::null(),
            field_map_entries: std::ptr::null(),
            symbol_metadata: std::ptr::null(),
            public_symbol_map: std::ptr::null(),
            alias_map: std::ptr::null(),
            alias_sequences: std::ptr::null(),
            lex_modes: std::ptr::null(),
            lex_fn: None,
            keyword_lex_fn: None,
            keyword_capture_token: 0,
            external_scanner: ExternalScanner::default(),
            primary_state_ids: std::ptr::null(),
            production_lhs_index: std::ptr::null(),
            production_count: 0,
            eof_symbol: 0,
            rules: std::ptr::null(),
            rule_count: 0,
        };

        let parser = Parser {
            language: None,
            stack: Vec::new(),
            timeout_micros: 0,
            cancellation_flag: None,
            lexer: None,
        };

        // Symbol 0 is a token; there is no goto entry. The helper should
        // return None instead of panicking.
        assert!(parser.get_goto(&LANGUAGE, 0, 0).is_none());
    }

    #[test]
    fn test_get_goto_state_returns_zero_when_missing() {
        // Language with one token and one non-terminal but no goto entries.
        static PARSE_TABLE: [u16; 2] = [0, 0];
        static SMALL_PARSE_TABLE: [u16; 1] = [0];
        static SMALL_PARSE_TABLE_MAP: [u32; 1] = [0];
        static LEX_MODES: [TSLexState; 1] = [TSLexState {
            lex_state: 0,
            external_lex_state: 0,
        }];
        static LANGUAGE: TSLanguage = TSLanguage {
            version: TREE_SITTER_LANGUAGE_VERSION,
            symbol_count: 2,
            alias_count: 0,
            token_count: 1,
            external_token_count: 0,
            state_count: 1,
            large_state_count: 1,
            production_id_count: 0,
            field_count: 0,
            max_alias_sequence_length: 0,
            production_id_map: std::ptr::null(),
            parse_table: PARSE_TABLE.as_ptr(),
            small_parse_table: SMALL_PARSE_TABLE.as_ptr(),
            small_parse_table_map: SMALL_PARSE_TABLE_MAP.as_ptr(),
            parse_actions: std::ptr::null(),
            symbol_names: std::ptr::null(),
            field_names: std::ptr::null(),
            field_map_slices: std::ptr::null(),
            field_map_entries: std::ptr::null(),
            symbol_metadata: std::ptr::null(),
            public_symbol_map: std::ptr::null(),
            alias_map: std::ptr::null(),
            alias_sequences: std::ptr::null(),
            lex_modes: LEX_MODES.as_ptr(),
            lex_fn: None,
            keyword_lex_fn: None,
            keyword_capture_token: 0,
            external_scanner: ExternalScanner::default(),
            primary_state_ids: std::ptr::null(),
            production_lhs_index: std::ptr::null(),
            production_count: 0,
            eof_symbol: 0,
            rules: std::ptr::null(),
            rule_count: 0,
        };

        let parser = Parser::new();
        // Symbol 1 is the lone non-terminal; with no table entry this should return 0.
        assert_eq!(parser.get_goto_state(&LANGUAGE, 0, 1), 0);
    }

    #[test]
    fn test_external_lexer_column_tracking() {
        let input = b"hello\nworld";
        let mut ext = ExternalLexer::new(input, 0, 0);
        let mut ts = create_ts_lexer(&mut ext);

        // Initial column at start
        assert_eq!(unsafe { ExternalLexer::get_column(&mut ts) }, 0);

        // Advance over "hello"
        for _ in 0..5 {
            unsafe { ExternalLexer::advance(&mut ts, false) };
        }
        assert_eq!(unsafe { ExternalLexer::get_column(&mut ts) }, 5);

        // Advance over newline
        unsafe { ExternalLexer::advance(&mut ts, false) };
        assert_eq!(unsafe { ExternalLexer::get_column(&mut ts) }, 0);
    }

    #[test]
    fn test_external_lexer_included_range_start() {
        let input = b"abc";
        let mut ext = ExternalLexer::new(input, 0, 0);
        let mut ts = create_ts_lexer(&mut ext);

        assert!(unsafe { ExternalLexer::is_at_included_range_start(&mut ts) });
        unsafe { ExternalLexer::advance(&mut ts, true) };
        assert!(!unsafe { ExternalLexer::is_at_included_range_start(&mut ts) });
    }

    #[test]
    fn test_external_lexer_eof() {
        let input = b"a";
        let mut ext = ExternalLexer::new(input, 0, 0);
        let mut ts = create_ts_lexer(&mut ext);

        assert!(!unsafe { ExternalLexer::eof(&mut ts) });
        unsafe { ExternalLexer::advance(&mut ts, true) };
        assert!(unsafe { ExternalLexer::eof(&mut ts) });
    }
}
