load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "additional_accounts_request",
    srcs = glob(["**/*.rs"]),
    crate = "additional_accounts_request",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anchor-lang/0.29.0:anchor_lang",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
    ],
)
