load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advise",
    srcs = glob(["**/*.rs"]),
    crate = "advise",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anstream/0.6.21:anstream",
        "//third-party/rust/crates/anstyle/1.0.14:anstyle",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
