load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ada_url",
    srcs = glob(["**/*.rs"]),
    crate = "ada_url",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/1.0.0:derive_more",
    ],
)
