load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actman",
    srcs = glob(["**/*.rs"]),
    crate = "actman",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
