load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_office_formula_parser",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_office_formula_parser",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
