load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_core",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrow-array/53.4.1:arrow_array",
        "//third-party/rust/crates/arrow-schema/53.4.1:arrow_schema",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
    ],
)
