load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_screen",
    srcs = glob(["**/*.rs"]),
    crate = "adi_screen",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi_clock/0.2.0:adi_clock",
        "//third-party/rust/crates/ami/0.2.1:ami",
    ],
)
