load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adfs_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adfs_rs",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aws-config/1.10.1:aws_config",
        "//third-party/rust/crates/aws-credential-types/1.3.0:aws_credential_types",
        "//third-party/rust/crates/aws-sdk-sts/1.110.0:aws_sdk_sts",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde-xml-rs/0.8.2:serde_xml_rs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.9.8:toml",
    ],
)
