load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto",
    srcs = glob(["**/*.rs"]),
    crate = "adapto",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapto_store/0.2.5:adapto_store",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
