load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actually_beep",
    srcs = glob(["**/*.rs"]),
    crate = "actually_beep",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cpal/0.15.3:cpal",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
