load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_validator",
    srcs = glob(["**/*.rs"]),
    crate = "action_validator",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/serde-wasm-bindgen/0.4.5:serde_wasm_bindgen",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/valico/4.0.0:valico",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
