load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_computer_use",
    srcs = glob(["**/*.rs"]),
    crate = "adk_computer_use",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-auth/2.0.0:adk_auth",
        "//third-party/rust/crates/adk-core/2.0.0:adk_core",
        "//third-party/rust/crates/adk-eval/2.0.0:adk_eval",
        "//third-party/rust/crates/adk-graph/2.0.0:adk_graph",
        "//third-party/rust/crates/adk-tool/2.0.0:adk_tool",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/rmcp/3.1.2:rmcp",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
