load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac4490",
    srcs = glob(["**/*.rs"]),
    crate = "ac4490",
    crate_root = "src/lib/mod.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/defmt/0.3.100:defmt",
        "//third-party/rust/crates/num_enum/0.7.6:num_enum",
        "//third-party/rust/crates/thiserror-no-std/2.0.2:thiserror_no_std",
    ],
)
