load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abir_guard",
    srcs = glob(["**/*.rs"]),
    crate = "abir_guard",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes-gcm/0.10.3:aes_gcm",
        "//third-party/rust/crates/argon2/0.5.3:argon2",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/digest/0.10.7:digest",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/fips204/0.4.6:fips204",
        "//third-party/rust/crates/getrandom/0.4.3:getrandom",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hkdf/0.12.4:hkdf",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/ml-kem/0.3.2:ml_kem",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/ring/0.17.14:ring",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/sha3/0.10.9:sha3",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
