load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_std",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_std",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bech32/0.11.1:bech32",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-address-like/2.0.0:cw_address_like",
        "//third-party/rust/crates/cw-asset/4.0.0:cw_asset",
        "//third-party/rust/crates/cw-blob/0.2.0:cw_blob",
        "//third-party/rust/crates/cw-clearable/0.2.0:cw_clearable",
        "//third-party/rust/crates/cw-controllers/2.0.0:cw_controllers",
        "//third-party/rust/crates/cw-orch/0.27.0:cw_orch",
        "//third-party/rust/crates/cw-ownable/2.1.0:cw_ownable",
        "//third-party/rust/crates/cw-storage-plus/2.0.0:cw_storage_plus",
        "//third-party/rust/crates/cw-utils/2.0.0:cw_utils",
        "//third-party/rust/crates/cw2/2.0.0:cw2",
        "//third-party/rust/crates/cw20/2.0.0:cw20",
        "//third-party/rust/crates/function_name/0.3.0:function_name",
        "//third-party/rust/crates/ripemd/0.1.3:ripemd",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
