load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acridotheres_3ds",
    srcs = glob(["**/*.rs"]),
    crate = "acridotheres_3ds",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dh/0.8.1:dh",
    ],
)
