load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adts_reader",
    srcs = glob(["**/*.rs"]),
    crate = "adts_reader",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/mpeg4-audio-const/0.3.0:mpeg4_audio_const",
    ],
)
