load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_metrics_mw",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_metrics_mw",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/cadence/0.18.0:cadence",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/json/0.12.4:json",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/metrics-core/0.5.2:metrics_core",
        "//third-party/rust/crates/metrics-runtime/0.12.1:metrics_runtime",
        "//third-party/rust/crates/metrics/0.12.1:metrics",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
