load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_webfinger",
    srcs = glob(["**/*.rs"]),
    crate = "actix_webfinger",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/0.2.11:actix_http",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
    ],
)
