load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_adapter_utils",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_adapter_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-cw20/1.3.0:abstract_cw20",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/3.1.1:cw_asset",
    ],
)
