load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accurate",
    srcs = glob(["**/*.rs"]),
    crate = "accurate",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
        "//third-party/rust/crates/embed-doc-image/0.1.4:embed_doc_image",
        "//third-party/rust/crates/ieee754/0.2.6:ieee754",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
