load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acc",
    srcs = glob(["**/*.rs"]),
    crate = "acc",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
