load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_mqtt",
    srcs = glob(["**/*.rs"]),
    crate = "actix_mqtt",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-ioframe/0.1.1:actix_ioframe",
        "//third-party/rust/crates/actix-router/0.1.5:actix_router",
        "//third-party/rust/crates/actix-server-config/0.1.2:actix_server_config",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-utils/0.4.7:actix_utils",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/derive_more/0.15.0:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mqtt-codec/0.2.0:mqtt_codec",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/string/0.2.1:string",
        "//third-party/rust/crates/tokio-current-thread/0.1.7:tokio_current_thread",
        "//third-party/rust/crates/uuid/0.7.4:uuid",
    ],
)
