load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm",
    srcs = glob(["**/*.rs"]),
    crate = "acvm",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir/0.46.0:acir",
        "//third-party/rust/crates/acvm_blackbox_solver/0.46.0:acvm_blackbox_solver",
        "//third-party/rust/crates/brillig_vm/0.46.0:brillig_vm",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
