load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_easy_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_easy_multipart",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-easy-multipart-derive/3.0.0:actix_easy_multipart_derive",
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-multipart/0.4.0:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_plain/1.0.2:serde_plain",
    ],
)
