load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acheron",
    srcs = glob(["**/*.rs"]),
    crate = "acheron",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/im/12.3.4:im",
    ],
)
