load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_bdd_governance_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_bdd_governance_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-bdd-governance-reporting-core/0.1.0:adze_bdd_governance_reporting_core",
        "//third-party/rust/crates/adze-bdd-grid-core/0.1.0:adze_bdd_grid_core",
        "//third-party/rust/crates/adze-feature-policy-core/0.1.0:adze_feature_policy_core",
    ],
)
