load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx_seaorm",
    srcs = glob(["**/*.rs"]),
    crate = "adminx_seaorm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adminx-core/3.1.0:adminx_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/sea-orm/1.1.20:sea_orm",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
