load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code_data",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code_data",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono-tz/0.10.4:chrono_tz",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/directories/5.0.1:directories",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/simple_crypt/0.2.3:simple_crypt",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
