load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add6",
    srcs = glob(["**/*.rs"]),
    crate = "add6",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add3/1.0.0:add3",
    ],
)
