load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adam",
    srcs = glob(["**/*.rs"]),
    crate = "adam",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aho-corasick/0.7.20:aho_corasick",
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/color-eyre/0.6.5:color_eyre",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/directories/4.0.1:directories",
        "//third-party/rust/crates/dunce/1.0.5:dunce",
        "//third-party/rust/crates/filetime/0.2.29:filetime",
        "//third-party/rust/crates/heck/0.4.1:heck",
        "//third-party/rust/crates/indicatif/0.16.2:indicatif",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustc-hash/1.1.0:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.5.11:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
