load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptevm",
    srcs = glob(["**/*.rs"]),
    crate = "acceptevm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/alloy/2.3.0:alloy",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/k256/0.13.4:k256",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
