load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adabraka_perf",
    srcs = glob(["**/*.rs"]),
    crate = "adabraka_perf",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adabraka_collections/0.4.0:adabraka_collections",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
