load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix",
    srcs = glob(["**/*.rs"]),
    crate = "actix",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbeam/0.3.2:crossbeam",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/tokio-core/0.1.18:tokio_core",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/uuid/0.5.1:uuid",
    ],
)
