load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark_core",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/capnp/0.25.6:capnp",
        "//third-party/rust/crates/hdrhistogram/7.6.0:hdrhistogram",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/v8/149.2.0:v8",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/zip/6.0.0:zip",
    ],
)
