load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr2line",
    srcs = glob(["**/*.rs"]),
    crate = "addr2line",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/error-chain/0.7.2:error_chain",
        "//third-party/rust/crates/fallible-iterator/0.1.6:fallible_iterator",
        "//third-party/rust/crates/gimli/0.14.0:gimli",
        "//third-party/rust/crates/memmap/0.5.2:memmap",
        "//third-party/rust/crates/object/0.4.1:object",
        "//third-party/rust/crates/owning_ref/0.2.4:owning_ref",
    ],
)
