load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_codeact_monty",
    srcs = glob(["**/*.rs"]),
    crate = "adk_codeact_monty",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-agent/2.0.0:adk_agent",
        "//third-party/rust/crates/adk-code/2.0.0:adk_code",
        "//third-party/rust/crates/adk-core/2.0.0:adk_core",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
