load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abnf",
    srcs = glob(["**/*.rs"]),
    crate = "abnf",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nom/4.2.3:nom",
    ],
)
