load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapton",
    srcs = glob(["**/*.rs"]),
    crate = "adapton",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/quickcheck/0.2.27:quickcheck",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
