load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abol_util",
    srcs = glob(["**/*.rs"]),
    crate = "abol_util",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abol-rt/0.1.0:abol_rt",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
    ],
)
