load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acct",
    srcs = glob(["**/*.rs"]),
    crate = "acct",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
    ],
)
