image:
  name: rust:1.58.0-buster

stages:
  - test
  - publish

variables:
  CARGO_TEST_FEATURES: "--all-features"
  CARGO_PUBLISH_FEATURES: "--all-features"
  CARGO_PUBLISH_CRATES_IO: "true"

include:
  - project: build/pipelines/rust
    ref: master
    file: test.yml
  - project: build/pipelines/rust
    ref: master
    file: publish.yml