load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abpoa_sys",
    srcs = glob(["**/*.rs"]),
    crate = "abpoa_sys",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libz-sys/1.1.29:libz_sys",
    ],
)
