load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acick_util",
    srcs = glob(["**/*.rs"]),
    crate = "acick_util",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytefmt/0.1.7:bytefmt",
        "//third-party/rust/crates/console/0.10.3:console",
        "//third-party/rust/crates/cookie/0.12.0:cookie",
        "//third-party/rust/crates/cookie_store/0.11.0:cookie_store",
        "//third-party/rust/crates/dirs/2.0.2:dirs",
        "//third-party/rust/crates/fs2/0.4.3:fs2",
        "//third-party/rust/crates/getset/0.1.7:getset",
        "//third-party/rust/crates/humantime-serde/1.1.1:humantime_serde",
        "//third-party/rust/crates/indicatif/0.14.0:indicatif",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.10.10:reqwest",
        "//third-party/rust/crates/retry/1.3.1:retry",
        "//third-party/rust/crates/scraper/0.11.0:scraper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/shellexpand/2.1.2:shellexpand",
        "//third-party/rust/crates/strum/0.18.0:strum",
        "//third-party/rust/crates/webbrowser/0.5.5:webbrowser",
    ],
)
