load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_libkrun_sys",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_libkrun_sys",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
