load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absperf_minilzo",
    srcs = glob(["**/*.rs"]),
    crate = "absperf_minilzo",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/absperf-minilzo-sys/2.10.0:absperf_minilzo_sys",
    ],
)
