load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_reporting",
    srcs = glob(["**/*.rs"]),
    crate = "active_reporting",
    crate_root = "mod.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/issuing/0.3.0:issuing",
        "//third-party/rust/crates/systemstd/1.1.0:systemstd",
    ],
)
