load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_nextjs_spa",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_nextjs_spa",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-files/0.6.10:actix_files",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/path-tree/0.7.7:path_tree",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
