load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_loginmanager",
    srcs = glob(["**/*.rs"]),
    crate = "actix_loginmanager",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/2.2.2:actix_http",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/loginmanager-codegen/0.0.1:loginmanager_codegen",
        "//third-party/rust/crates/rust-crypto/0.2.36:rust_crypto",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.2.27:time",
    ],
)
