load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsb",
    srcs = glob(["**/*.rs"]),
    crate = "adsb",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/nom/4.2.3:nom",
    ],
)
