load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abhyas",
    srcs = glob(["**/*.rs"]),
    crate = "abhyas",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/inquire/0.6.2:inquire",
        "//third-party/rust/crates/rusqlite/0.30.0:rusqlite",
        "//third-party/rust/crates/tabled/0.14.0:tabled",
        "//third-party/rust/crates/termcolor/1.4.1:termcolor",
    ],
)
