load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acrylic",
    srcs = glob(["**/*.rs"]),
    crate = "acrylic",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/no-std-compat/0.4.1:no_std_compat",
    ],
)
