load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_xplat",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_xplat",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.23.0:accesskit",
        "//third-party/rust/crates/raw-window-handle/0.6.2:raw_window_handle",
    ],
)
