load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart_rfc7578",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart_rfc7578",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/common-multipart-rfc7578/0.4.2:common_multipart_rfc7578",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
