load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_lcd_backpack",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_lcd_backpack",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/mcp230xx/1.0.2:mcp230xx",
    ],
)
