load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actplane",
    srcs = glob(["**/*.rs"]),
    crate = "actplane",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actplane-bpf/0.1.0:actplane_bpf",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
