load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acacia",
    srcs = glob(["**/*.rs"]),
    crate = "acacia",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/itertools/0.15.0:itertools",
        "//third-party/rust/crates/nalgebra/0.35.0:nalgebra",
        "//third-party/rust/crates/rand/0.10.2:rand",
    ],
)
