load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ackerman",
    srcs = glob(["**/*.rs"]),
    crate = "ackerman",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
