load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_slog",
    srcs = glob(["**/*.rs"]),
    crate = "actix_slog",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/slog/2.8.2:slog",
    ],
)
