load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_middleware_slogger",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_middleware_slogger",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
