load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_proxy",
    srcs = glob(["**/*.rs"]),
    crate = "aa_proxy",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/hyper-util/0.1.20:hyper_util",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/lru/0.18.2:lru",
        "//third-party/rust/crates/rcgen/0.14.9:rcgen",
        "//third-party/rust/crates/rustls-native-certs/0.8.4:rustls_native_certs",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio-rustls/0.26.4:tokio_rustls",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
