load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_telemetry",
    srcs = glob(["**/*.rs"]),
    crate = "adk_telemetry",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
