// This file is @generated by prost-build.
/// A message which represents a `Result<T, E>` in Rust.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Result {
    #[prost(oneof = "result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<result::Result>,
}
/// Nested message and enum types in `Result`.
pub mod result {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// The ok message.
        #[prost(bytes, tag = "1")]
        Ok(::prost::bytes::Bytes),
        /// The err message.
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
/// A message which represents an `Option<T>` in Rust.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Option {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub option: ::core::option::Option<::prost::bytes::Bytes>,
}
/// A message which represents a `Vec<bool>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VecBool {
    #[prost(bool, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<bool>,
}
/// A message which represents a `Vec<i32>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VecInt32 {
    #[prost(sint32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i32>,
}
/// A message which represents a `Vec<i64>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VecInt64 {
    #[prost(sint64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i64>,
}
/// A message which represents a `Vec<u32>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VecUint32 {
    #[prost(uint32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u32>,
}
/// A message which represents a `Vec<u64>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VecUint64 {
    #[prost(uint64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u64>,
}
/// A message which represents a `Vec<f32>`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VecFloat {
    #[prost(float, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
/// A message which represents a `Vec<f64>`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VecDouble {
    #[prost(double, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<f64>,
}
/// A message which represents a `(t0, t1, ...)` up to 10 elements.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Tuple {
    #[prost(bytes = "bytes", optional, tag = "1")]
    pub t0: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "2")]
    pub t1: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub t2: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "4")]
    pub t3: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "5")]
    pub t4: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "6")]
    pub t5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "7")]
    pub t6: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "8")]
    pub t7: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "9")]
    pub t8: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes = "bytes", optional, tag = "10")]
    pub t9: ::core::option::Option<::prost::bytes::Bytes>,
}
/// A message which represents an `ActorRef`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActorRef {
    #[prost(oneof = "actor_ref::Ref", tags = "1, 2")]
    pub r#ref: ::core::option::Option<actor_ref::Ref>,
}
/// Nested message and enum types in `ActorRef`.
pub mod actor_ref {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Ref {
        /// The index of the actor.
        #[prost(uint64, tag = "1")]
        Index(u64),
        /// The label of the actor.
        #[prost(string, tag = "2")]
        Label(::prost::alloc::string::String),
    }
}
/// A message which represents a `Result<Address, E>`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResultAddress {
    #[prost(oneof = "result_address::Result", tags = "1, 2")]
    pub result: ::core::option::Option<result_address::Result>,
}
/// Nested message and enum types in `ResultAddress`.
pub mod result_address {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// The actor id of the actor in the remote node.
        #[prost(uint64, tag = "1")]
        Ok(u64),
        /// The error message.
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
