load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_analytics",
    srcs = glob(["**/*.rs"]),
    crate = "actix_analytics",
    crate_root = "src/analytics.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
