load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abyo_crdt",
    srcs = glob(["**/*.rs"]),
    crate = "abyo_crdt",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/getrandom/0.3.4:getrandom",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unicode-segmentation/1.13.3:unicode_segmentation",
    ],
)
