load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_middleware_slack",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_middleware_slack",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
