load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abhedya_ffi",
    srcs = glob(["**/*.rs"]),
    crate = "abhedya_ffi",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abhedya-core/1.0.24:abhedya_core",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/rand/0.9.5:rand",
    ],
)
