load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_pipeline_domain",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_pipeline_domain",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/ulid/1.2.1:ulid",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
