load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/adabraka-ui/adabraka-ui-0.2.2.crate",
    ],
    sha256 = "bb1b4f7681cfe662359f45fdfa5ac175958fa4123641da68beee12eb14d2da6f",
    type = "tar.gz",
    strip_prefix = "adabraka-ui-0.2.2",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "adabraka_ui",
    srcs = [":vendor"],
    crate = "adabraka_ui",
    crate_root = "vendor/src/lib.rs",
    edition = "2021",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
