load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_unix",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_unix",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.13.0:accesskit",
        "//third-party/rust/crates/accesskit_atspi_common/0.3.0:accesskit_atspi_common",
        "//third-party/rust/crates/atspi/0.19.0:atspi",
        "//third-party/rust/crates/futures-lite/1.13.0:futures_lite",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/zbus/3.15.2:zbus",
    ],
)
