load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_option",
    srcs = glob(["**/*.rs"]),
    crate = "ach_option",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ach-util/0.1.17:ach_util",
        "//third-party/rust/crates/interrupt/0.1.4:interrupt",
        "//third-party/rust/crates/spin_loop/0.1.1:spin_loop",
    ],
)
