load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "additive_fft_reed_solomon_gf2p8",
    srcs = glob(["**/*.rs"]),
    crate = "additive_fft_reed_solomon_gf2p8",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
)
