load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_cors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_cors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
