# A3sfile.hcl — generated by `a3s init`
# Run `a3s up` to start all services, `a3s validate` to check config.

dev {
  proxy_port = 7080
  log_level  = "info"
}

# brew {
#   packages = [
#     "redis",
#     "postgresql@16",
#   ]
# }

# service "api" {
#   cmd        = "cargo run -p my-api"
#   dir        = "./services/api"
#   port       = 3000
#   subdomain  = "api"
#   depends_on = ["db"]
#
#   env = {
#     DATABASE_URL = "postgres://localhost:5432/dev"
#   }
#
#   watch {
#     paths   = ["./services/api/src"]
#     ignore  = ["target"]
#     restart = true
#   }
#
#   health {
#     type     = "http"
#     path     = "/health"
#     interval = "2s"
#     timeout  = "1s"
#     retries  = 5
#   }
# }
#
# service "db" {
#   cmd  = "postgres -D /usr/local/var/postgresql@16"
#   port = 5432
#
#   health {
#     type    = "tcp"
#     timeout = "1s"
#     retries = 10
#   }
# }
