load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_power",
    srcs = glob(["**/*.rs"]),
    crate = "ac_power",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/idsp/0.15.1:idsp",
    ],
)
