load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ada_judge_app",
    srcs = glob(["**/*.rs"]),
    crate = "ada_judge_app",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ada-judge-public-models/0.8.4:ada_judge_public_models",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/keyring/4.1.6:keyring",
        "//third-party/rust/crates/open/5.4.1:open",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/rfd/0.17.2:rfd",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/slint/1.17.1:slint",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
