load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab_riscv_macros",
    srcs = glob(["**/*.rs"]),
    crate = "ab_riscv_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
)
