load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad9959",
    srcs = glob(["**/*.rs"]),
    crate = "ad9959",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.10.3:bit_field",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
    ],
)
