load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_governor",
    srcs = glob(["**/*.rs"]),
    crate = "actix_governor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/governor/0.4.2:governor",
    ],
)
