load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_client",
    srcs = glob(["**/*.rs"]),
    crate = "adb_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/mio/1.2.2:mio",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/termios/0.3.3:termios",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
