load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_network",
    srcs = glob(["**/*.rs"]),
    crate = "acme_network",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bson/2.15.0:bson",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/config/0.13.4:config",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/libp2p/0.45.1:libp2p",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/pretty_env_logger/0.4.0:pretty_env_logger",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
