load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_runtime_governance_matrix",
    srcs = glob(["**/*.rs"]),
    crate = "adze_runtime_governance_matrix",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-governance-runtime-core/0.1.0:adze_governance_runtime_core",
    ],
)
