load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_protobuf",
    srcs = glob(["**/*.rs"]),
    crate = "actix_protobuf",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/prost/0.6.1:prost",
    ],
)
