load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_core_rs",
    srcs = glob(["**/*.rs"]),
    crate = "ad_core_rs",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/asyn-rs/0.24.3:asyn_rs",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
