load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abjad",
    srcs = glob(["**/*.rs"]),
    crate = "abjad",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
