load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_datafusion",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_datafusion",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adbc_core/0.23.0:adbc_core",
        "//third-party/rust/crates/arrow-array/58.4.0:arrow_array",
        "//third-party/rust/crates/arrow-buffer/58.4.0:arrow_buffer",
        "//third-party/rust/crates/arrow-schema/58.4.0:arrow_schema",
        "//third-party/rust/crates/datafusion-substrait/53.1.0:datafusion_substrait",
        "//third-party/rust/crates/datafusion/53.1.0:datafusion",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
