load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbackup",
    srcs = glob(["**/*.rs"]),
    crate = "adbackup",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/failure_derive/0.1.8:failure_derive",
        "//third-party/rust/crates/fern/0.4.4:fern",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/rusqlite/0.13.0:rusqlite",
        "//third-party/rust/crates/spectral/0.6.0:spectral",
    ],
)
