load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aaplus",
    srcs = glob(["**/*.rs"]),
    crate = "aaplus",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
