load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_easy_multipart_derive",
    srcs = glob(["**/*.rs"]),
    crate = "actix_easy_multipart_derive",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/darling/0.14.4:darling",
        "//third-party/rust/crates/parse-size/1.1.0:parse_size",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
