load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activityrust",
    srcs = glob(["**/*.rs"]),
    crate = "activityrust",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ambassador/0.2.1:ambassador",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
