load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi_gpu_base/0.5.0:adi_gpu_base",
        "//third-party/rust/crates/ami/0.7.0:ami",
    ],
)
