load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activityforge",
    srcs = glob(["**/*.rs"]),
    crate = "activityforge",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activitystreams-vocabulary/0.5.2:activitystreams_vocabulary",
        "//third-party/rust/crates/argon2/0.5.3:argon2",
        "//third-party/rust/crates/base64ct/1.8.3:base64ct",
        "//third-party/rust/crates/chacha20poly1305/0.10.1:chacha20poly1305",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha3/0.10.9:sha3",
        "//third-party/rust/crates/sqlx/0.8.6:sqlx",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
