load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_common",
    srcs = glob(["**/*.rs"]),
    crate = "adze_common",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-common-syntax-core/0.8.0:adze_common_syntax_core",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
