load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_windows",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_windows",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.11.2:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.15.2:accesskit_consumer",
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/windows/0.48.0:windows",
    ],
)
