load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actpub_federation",
    srcs = glob(["**/*.rs"]),
    crate = "actpub_federation",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actpub-activitystreams/0.2.3:actpub_activitystreams",
        "//third-party/rust/crates/actpub-core/0.2.3:actpub_core",
        "//third-party/rust/crates/actpub-httpsig/0.2.3:actpub_httpsig",
        "//third-party/rust/crates/actpub-webfinger/0.2.3:actpub_webfinger",
        "//third-party/rust/crates/bon/3.9.3:bon",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/httpdate/1.0.3:httpdate",
        "//third-party/rust/crates/moka/0.12.16:moka",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
