load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acta_build",
    srcs = glob(["**/*.rs"]),
    crate = "acta_build",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
