load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ack_udp",
    srcs = glob(["**/*.rs"]),
    crate = "ack_udp",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
