load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acmer_server",
    srcs = glob(["**/*.rs"]),
    crate = "acmer_server",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acmer/0.0.18:acmer",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
