load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adam",
    srcs = glob(["**/*.rs"]),
    crate = "adam",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aho-corasick/0.7.20:aho_corasick",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/console/0.12.0:console",
        "//third-party/rust/crates/directories/3.0.2:directories",
        "//third-party/rust/crates/filetime/0.2.29:filetime",
        "//third-party/rust/crates/heck/0.3.3:heck",
        "//third-party/rust/crates/indicatif/0.15.0:indicatif",
        "//third-party/rust/crates/maplit/1.0.2:maplit",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.5.11:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/yy-typings/0.3.12:yy_typings",
    ],
)
