load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "stun",
    srcs = glob(["**/*.rs"]),
    crate = "stun",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/stun/0.8.0:stun",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/webrtc/0.14.0:webrtc",
    ],
)
