load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "academic_journals",
    srcs = glob(["**/*.rs"]),
    crate = "academic_journals",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
