load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_qu_ai_nt_cli_clap",
    srcs = glob(["**/*.rs"]),
    crate = "ac_qu_ai_nt_cli_clap",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
