load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adblock",
    srcs = glob(["**/*.rs"]),
    crate = "adblock",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/flatbuffers/25.12.19:flatbuffers",
        "//third-party/rust/crates/idna/1.1.0:idna",
        "//third-party/rust/crates/itertools/0.14.0:itertools",
        "//third-party/rust/crates/memchr/2.8.3:memchr",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/precomputed-hash/0.1.1:precomputed_hash",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/seahash/4.1.0:seahash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
