load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/aead/aead-0.6.0-rc.4.crate",
    ],
    sha256 = "d4432ec21d472b82641b64c82ad1daca981dbf58d0345d36616cf0ac7099db96",
    type = "tar.gz",
    strip_prefix = "aead-0.6.0-rc.4",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "aead",
    srcs = [":vendor"],
    crate = "aead",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",
    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
