load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actor_interfaces",
    srcs = glob(["**/*.rs"]),
    crate = "actor_interfaces",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_bytes/0.11.19:serde_bytes",
        "//third-party/rust/crates/wasmbus-rpc/0.13.0:wasmbus_rpc",
    ],
)
