load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpi_tables",
    srcs = glob(["**/*.rs"]),
    crate = "acpi_tables",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/zerocopy/0.8.56:zerocopy",
    ],
)
