load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_db",
    srcs = glob(["**/*.rs"]),
    crate = "adana_db",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
