load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_tls",
    srcs = glob(["**/*.rs"]),
    crate = "actix_tls",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.2.0:actix_codec",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-utils/1.0.6:actix_utils",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
