load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_jc",
    srcs = glob(["**/*.rs"]),
    crate = "actix_jc",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/jsonwebtoken/9.3.1:jsonwebtoken",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
