load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_one_06122023",
    srcs = glob(["**/*.rs"]),
    crate = "add_one_06122023",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
