load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adl_lsp",
    srcs = glob(["**/*.rs"]),
    crate = "adl_lsp",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-lsp/0.2.4:async_lsp",
        "//third-party/rust/crates/lsp-types/0.95.1:lsp_types",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/tree-sitter-adl/0.1.0:tree_sitter_adl",
        "//third-party/rust/crates/tree-sitter/0.25.10:tree_sitter",
    ],
)
