load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_request_reply_cache",
    srcs = glob(["**/*.rs"]),
    crate = "actix_request_reply_cache",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis/0.30.0:redis",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
