load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abaco",
    srcs = glob(["**/*.rs"]),
    crate = "abaco",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
