load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
