load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbutils",
    srcs = glob(["**/*.rs"]),
    crate = "adbutils",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
