load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_error_proc",
    srcs = glob(["**/*.rs"]),
    crate = "actix_error_proc",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/actix_error_proc_macros/0.1.2:actix_error_proc_macros",
    ],
)
