load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_telegram",
    srcs = glob(["**/*.rs"]),
    crate = "actix_telegram",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-telegram-derive/0.1.1:actix_telegram_derive",
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/env_logger/0.5.13:env_logger",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/multipart-rfc7578/0.6.0:multipart_rfc7578",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/0.1.22:tokio",
    ],
)
