load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acolor",
    srcs = glob(["**/*.rs"]),
    crate = "acolor",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/devela/0.8.0:devela",
        "//third-party/rust/crates/iunorm/0.2.2:iunorm",
    ],
)
