load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activitystreams-traits/0.2.0:activitystreams_traits",
        "//third-party/rust/crates/activitystreams-types/0.3.0:activitystreams_types",
    ],
)
