load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abi_cafe",
    srcs = glob(["**/*.rs"]),
    crate = "abi_cafe",
    crate_root = "src/main.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/camino/1.2.5:camino",
        "//third-party/rust/crates/cc/1.4.2:cc",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/include_dir/0.7.4:include_dir",
        "//third-party/rust/crates/kdl-script/0.4.1:kdl_script",
        "//third-party/rust/crates/kdl/4.7.1:kdl",
        "//third-party/rust/crates/libloading/0.7.4:libloading",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/miette/5.10.0:miette",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/rand_pcg/0.3.1:rand_pcg",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
