load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abac_rs",
    srcs = glob(["**/*.rs"]),
    crate = "abac_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acls-rs/0.2.1:acls_rs",
        "//third-party/rust/crates/ipnetwork/0.20.0:ipnetwork",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
