load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "frame",
    srcs = glob(["**/*.rs"]),
    crate = "frame",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/frame-conv/0.1.0:frame_conv",
        "//third-party/rust/crates/frame-core/0.1.0:frame_core",
        "//third-party/rust/crates/frame-mcp/0.1.0:frame_mcp",
        "//third-party/rust/crates/frame-state/0.1.0:frame_state",
        "//third-party/rust/crates/frame-view/0.1.0:frame_view",
    ],
)
