load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adnix",
    srcs = glob(["**/*.rs"]),
    crate = "adnix",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/color-eyre/0.6.5:color_eyre",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
