load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acc",
    srcs = glob(["**/*.rs"]),
    crate = "acc",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/colored/1.9.4:colored",
        "//third-party/rust/crates/num/0.1.43:num",
    ],
)
