load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abc",
    srcs = glob(["**/*.rs"]),
    crate = "abc",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbeam/0.2.12:crossbeam",
        "//third-party/rust/crates/itertools/0.4.19:itertools",
        "//third-party/rust/crates/num_cpus/0.2.13:num_cpus",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
