load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity_manager",
    srcs = glob(["**/*.rs"]),
    crate = "activity_manager",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
