load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adss",
    srcs = glob(["**/*.rs"]),
    crate = "adss",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/star-sharks/0.6.1:star_sharks",
        "//third-party/rust/crates/strobe-rs/0.8.1:strobe_rs",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
