load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_boot",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_boot",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
