load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aci_ppm",
    srcs = glob(["**/*.rs"]),
    crate = "aci_ppm",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/afi/0.7.0:afi",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
    ],
)
