load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_request_identifier",
    srcs = glob(["**/*.rs"]),
    crate = "actix_request_identifier",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
