load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adot",
    srcs = glob(["**/*.rs"]),
    crate = "adot",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/yaml-rust2/0.11.0:yaml_rust2",
    ],
)
