load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_add_on",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_add_on",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/2.4.0:cw_asset",
        "//third-party/rust/crates/cw-controllers/0.16.0:cw_controllers",
        "//third-party/rust/crates/cw-storage-plus/0.16.0:cw_storage_plus",
        "//third-party/rust/crates/cw2/0.16.0:cw2",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
