load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abao",
    srcs = glob(["**/*.rs"]),
    crate = "abao",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayref/0.3.9:arrayref",
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
    ],
)
