load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_casbin",
    srcs = glob(["**/*.rs"]),
    crate = "actix_casbin",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-casbin-auth/1.1.0:actix_casbin_auth",
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/casbin/2.20.0:casbin",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
