load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aae",
    srcs = glob(["**/*.rs"]),
    crate = "aae",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_jcs/0.1.0:serde_jcs",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/ulid/1.2.1:ulid",
    ],
)
