load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams_vocabulary",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams_vocabulary",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ammonia/4.1.4:ammonia",
        "//third-party/rust/crates/base58ck/0.4.0:base58ck",
        "//third-party/rust/crates/base64ct/1.8.3:base64ct",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/heck/0.5.0:heck",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/langtag/1.1.0:langtag",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/pem-rfc7468/1.0.0:pem_rfc7468",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/xsd-types/0.9.6:xsd_types",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
