load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acid64",
    srcs = glob(["**/*.rs"]),
    crate = "acid64",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
