load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp_server",
    srcs = glob(["**/*.rs"]),
    crate = "acdp_server",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp-crypto/0.6.1:acdp_crypto",
        "//third-party/rust/crates/acdp-did/0.6.1:acdp_did",
        "//third-party/rust/crates/acdp-primitives/0.6.1:acdp_primitives",
        "//third-party/rust/crates/acdp-producer/0.6.1:acdp_producer",
        "//third-party/rust/crates/acdp-safe-http/0.6.1:acdp_safe_http",
        "//third-party/rust/crates/acdp-types/0.6.1:acdp_types",
        "//third-party/rust/crates/acdp-validation/0.6.1:acdp_validation",
        "//third-party/rust/crates/acdp-verify/0.6.1:acdp_verify",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
