load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_pmsa_rt",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_pmsa_rt",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aarch64-cpu/11.2.0:aarch64_cpu",
    ],
)
