load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advapi32",
    srcs = glob(["**/*.rs"]),
    crate = "advapi32",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/winapi/0.3.9:winapi",
    ],
)
