load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_broker",
    srcs = glob(["**/*.rs"]),
    crate = "actix_broker",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
