load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acu",
    srcs = glob(["**/*.rs"]),
    crate = "acu",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
