load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acnh",
    srcs = glob(["**/*.rs"]),
    crate = "acnh",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.10.10:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
