load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_ed",
    srcs = glob(["**/*.rs"]),
    crate = "add_ed",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/as-any/0.3.2:as_any",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
