load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_http_test",
    srcs = glob(["**/*.rs"]),
    crate = "actix_http_test",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.11.0:base64",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/env_logger/0.6.2:env_logger",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/sha1/0.6.1:sha1",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/time/0.1.45:time",
    ],
)
