load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_actors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_actors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
    ],
)
