load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adv_linalg_lib",
    srcs = glob(["**/*.rs"]),
    crate = "adv_linalg_lib",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adv_linalg_proc_macro/0.1.0:adv_linalg_proc_macro",
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
    ],
)
