load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adabraka_collections",
    srcs = glob(["**/*.rs"]),
    crate = "adabraka_collections",
    crate_root = "src/collections.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
    ],
)
