load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_cloud_extra_macros",
    srcs = glob(["**/*.rs"]),
    crate = "actix_cloud_extra_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/3.0.3:syn",
    ],
)
