load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abnf_core",
    srcs = glob(["**/*.rs"]),
    crate = "abnf_core",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nom/6.2.2:nom",
    ],
)
