load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adibat",
    srcs = glob(["**/*.rs"]),
    crate = "adibat",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
