load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark_dns",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark_dns",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-broadcast/0.4.1:async_broadcast",
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/resolv-conf/0.7.6:resolv_conf",
        "//third-party/rust/crates/signal-hook/0.3.18:signal_hook",
        "//third-party/rust/crates/syslog/6.1.1:syslog",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/trust-dns-client/0.20.4:trust_dns_client",
        "//third-party/rust/crates/trust-dns-proto/0.20.4:trust_dns_proto",
        "//third-party/rust/crates/trust-dns-server/0.21.2:trust_dns_server",
    ],
)
