load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adder_codec_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adder_codec_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/duplicate/0.4.1:duplicate",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_bytes/0.11.19:serde_bytes",
    ],
)
