load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_tensor",
    srcs = glob(["**/*.rs"]),
    crate = "acme_tensor",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/rawpointer/0.2.1:rawpointer",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
