load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx_search",
    srcs = glob(["**/*.rs"]),
    crate = "adminx_search",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adminx-core/3.1.0:adminx_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/searchez/1.0.0:searchez",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
