load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab_riscv_primitives",
    srcs = glob(["**/*.rs"]),
    crate = "ab_riscv_primitives",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ab-riscv-macros/0.0.2:ab_riscv_macros",
    ],
)
