load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_one_konwrz20",
    srcs = glob(["**/*.rs"]),
    crate = "add_one_konwrz20",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
