load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advanced_collections",
    srcs = glob(["**/*.rs"]),
    crate = "advanced_collections",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fnv/1.0.7:fnv",
    ],
)
