load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adtensor",
    srcs = glob(["**/*.rs"]),
    crate = "adtensor",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/generic-array/0.12.4:generic_array",
        "//third-party/rust/crates/typename/0.1.2:typename",
        "//third-party/rust/crates/typenum/1.20.1:typenum",
    ],
)
