load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_one_ali",
    srcs = glob(["**/*.rs"]),
    crate = "add_one_ali",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
)
