load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapt",
    srcs = glob(["**/*.rs"]),
    crate = "adapt",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/essence/0.3.5:essence",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
