load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_kerberos",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_kerberos",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-core/0.0.1:adhammer_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/picky-asn1-der/0.5.6:picky_asn1_der",
        "//third-party/rust/crates/picky-asn1-x509/0.14.6:picky_asn1_x509",
        "//third-party/rust/crates/picky-asn1/0.10.1:picky_asn1",
        "//third-party/rust/crates/picky-krb/0.9.6:picky_krb",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
