load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a800xl_utils",
    srcs = glob(["**/*.rs"]),
    crate = "a800xl_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ufmt-stdio/0.3.0:ufmt_stdio",
        "//third-party/rust/crates/ufmt-write/0.1.0:ufmt_write",
    ],
)
