load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad57xx",
    srcs = glob(["**/*.rs"]),
    crate = "ad57xx",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitfield-struct/0.5.6:bitfield_struct",
        "//third-party/rust/crates/embedded-hal-async/1.0.0:embedded_hal_async",
        "//third-party/rust/crates/embedded-hal-bus/0.1.0:embedded_hal_bus",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
