load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhaan",
    srcs = glob(["**/*.rs"]),
    crate = "adhaan",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/jiff/0.2.35:jiff",
    ],
)
