load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_extract_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_extract_multipart",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-multipart/0.4.0:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
