load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_middleware_cognito",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_middleware_cognito",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/jsonwebtokens/1.2.0:jsonwebtokens",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
