load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "anew",
    srcs = glob(["**/*.rs"]),
    crate = "anew",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
    ],
)
