load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code_ocr",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code_ocr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/phf/0.11.3:phf",
    ],
)
