load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbyss_psl",
    srcs = glob(["**/*.rs"]),
    crate = "adbyss_psl",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/idna/1.1.0:idna",
    ],
)
