load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adblock",
    srcs = glob(["**/*.rs"]),
    crate = "adblock",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/addr/0.2.1:addr",
        "//third-party/rust/crates/base64/0.10.1:base64",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/hashbrown/0.3.1:hashbrown",
        "//third-party/rust/crates/idna/0.1.5:idna",
        "//third-party/rust/crates/itertools/0.8.2:itertools",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/matches/0.1.10:matches",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/seahash/3.0.7:seahash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/twoway/0.2.2:twoway",
        "//third-party/rust/crates/url/1.7.2:url",
    ],
)
