load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adguardian",
    srcs = glob(["**/*.rs"]),
    crate = "adguardian",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/crossterm/0.22.1:crossterm",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/ratatui/0.20.1:ratatui",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
