load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_esr_decoder",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_esr_decoder",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.10.3:bit_field",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
