load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_v2",
    srcs = glob(["**/*.rs"]),
    crate = "acme_v2",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
