load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adept",
    srcs = glob(["**/*.rs"]),
    crate = "adept",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adept-agent/0.1.1:adept_agent",
        "//third-party/rust/crates/adept-core/0.1.1:adept_core",
        "//third-party/rust/crates/adept-fmt/0.1.1:adept_fmt",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/owo-colors/4.3.0:owo_colors",
        "//third-party/rust/crates/rustyline/14.0.0:rustyline",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
