load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_rusqlite",
    srcs = glob(["**/*.rs"]),
    crate = "active_rusqlite",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/active_base/0.1.0:active_base",
        "//third-party/rust/crates/rusqlite/0.34.0:rusqlite",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
