load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actix_web_upload_example",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_upload_example",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/concat-string/1.0.1:concat_string",
        "//third-party/rust/crates/envy/0.4.2:envy",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
