load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable_derive/0.10.3:abi_stable_derive",
        "//third-party/rust/crates/abi_stable_shared/0.10.3:abi_stable_shared",
        "//third-party/rust/crates/core_extensions/1.5.4:core_extensions",
        "//third-party/rust/crates/generational-arena/0.2.9:generational_arena",
        "//third-party/rust/crates/libloading/0.7.4:libloading",
        "//third-party/rust/crates/lock_api/0.4.14:lock_api",
        "//third-party/rust/crates/parking_lot/0.11.2:parking_lot",
        "//third-party/rust/crates/repr_offset/0.2.2:repr_offset",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
    ],
)
