load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel_mma84",
    srcs = glob(["**/*.rs"]),
    crate = "accel_mma84",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tessel/0.3.1:tessel",
    ],
)
