load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori_rt",
    srcs = glob(["**/*.rs"]),
    crate = "actori_rt",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-macros/0.1.1:actori_macros",
        "//third-party/rust/crates/actori-threadpool/0.3.1:actori_threadpool",
        "//third-party/rust/crates/copyless/0.1.5:copyless",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
