load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "cargo_add_license",
    srcs = glob(["**/*.rs"]),
    crate = "cargo_add_license",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
