load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acid2",
    srcs = glob(["**/*.rs"]),
    crate = "acid2",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libm/0.2.16:libm",
    ],
)
