load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_requestid",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_requestid",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
