load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_winit",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_winit",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.15.0:accesskit",
        "//third-party/rust/crates/winit/0.30.13:winit",
    ],
)
