load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_toolbox",
    srcs = glob(["**/*.rs"]),
    crate = "actix_toolbox",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/byte-unit/4.0.19:byte_unit",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/log4rs/1.4.0:log4rs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
