load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_core",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrow-array/55.2.0:arrow_array",
        "//third-party/rust/crates/arrow-schema/55.2.0:arrow_schema",
    ],
)
