load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accrete",
    srcs = glob(["**/*.rs"]),
    crate = "accrete",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
