load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adrs",
    srcs = glob(["**/*.rs"]),
    crate = "adrs",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/edit/0.1.5:edit",
        "//third-party/rust/crates/fuzzy-matcher/0.3.7:fuzzy_matcher",
        "//third-party/rust/crates/pulldown-cmark-to-cmark/11.2.0:pulldown_cmark_to_cmark",
        "//third-party/rust/crates/pulldown-cmark/0.9.6:pulldown_cmark",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tinytemplate/1.2.1:tinytemplate",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/whoami/1.6.1:whoami",
    ],
)
