load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_nats",
    srcs = glob(["**/*.rs"]),
    crate = "actix_nats",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/backoff/0.1.6:backoff",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nitox/0.1.9:nitox",
    ],
)
