load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_cron",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_cron",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/opentelemetry/0.21.0:opentelemetry",
        "//third-party/rust/crates/opentelemetry_sdk/0.21.2:opentelemetry_sdk",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
