load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_proxy",
    srcs = glob(["**/*.rs"]),
    crate = "actix_proxy",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/awc/3.8.2:awc",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
    ],
)
