load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/actual/actual-0.0.2.crate",
    ],
    sha256 = "4ed4a6179c9c8f59c62a543c41bb6b582feb8a314b36b1b08f37ae0fefbfde51",
    type = "tar.gz",
    strip_prefix = "actual-0.0.2",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "actual",
    srcs = [":vendor"],
    crate = "actual",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
