load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_ica",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_ica",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-sdk/0.26.1:abstract_sdk",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-orch/0.27.0:cw_orch",
        "//third-party/rust/crates/cw-ownable/2.1.0:cw_ownable",
        "//third-party/rust/crates/map-macro/0.3.0:map_macro",
        "//third-party/rust/crates/polytone-evm/0.1.0:polytone_evm",
    ],
)
