load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adc_lang",
    srcs = glob(["**/*.rs"]),
    crate = "adc_lang",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitvec/1.0.1:bitvec",
        "//third-party/rust/crates/const_format/0.2.36:const_format",
        "//third-party/rust/crates/getrandom/0.4.2:getrandom",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/linefeed/0.6.0:linefeed",
        "//third-party/rust/crates/malachite/0.9.1:malachite",
        "//third-party/rust/crates/phf/0.13.1:phf",
        "//third-party/rust/crates/regex/1.12.3:regex",
    ],
)
