load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_determinism",
    srcs = glob(["**/*.rs"]),
    crate = "add_determinism",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/indoc/2.0.7:indoc",
        "//third-party/rust/crates/itertools/0.13.0:itertools",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nix/0.28.0:nix",
        "//third-party/rust/crates/num-bigint-dig/0.8.6:num_bigint_dig",
        "//third-party/rust/crates/num-integer/0.1.47:num_integer",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rlimit/0.10.2:rlimit",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/zip/0.6.6:zip",
    ],
)
