load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpx",
    srcs = glob(["**/*.rs"]),
    crate = "acpx",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/agent-client-protocol/0.10.4:agent_client_protocol",
        "//third-party/rust/crates/async-process/2.5.0:async_process",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
