load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a5",
    srcs = glob(["**/*.rs"]),
    crate = "a5",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
    ],
)
