load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acmap",
    srcs = glob(["**/*.rs"]),
    crate = "acmap",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
