load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actflow_agent_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "actflow_agent_sdk",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic-prost/0.14.6:tonic_prost",
        "//third-party/rust/crates/tonic/0.14.6:tonic",
    ],
)
