load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_unit",
    srcs = glob(["**/*.rs"]),
    crate = "access_unit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
    ],
)
