load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_ern",
    srcs = glob(["**/*.rs"]),
    crate = "acton_ern",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive-new/0.7.0:derive_new",
        "//third-party/rust/crates/derive_more/1.0.0:derive_more",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
