load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a10",
    srcs = glob(["**/*.rs"]),
    crate = "a10",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
