load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_error",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_error",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-error-derive/0.2.0:actix_web_error_derive",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
