load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrpc_orchestrator",
    srcs = glob(["**/*.rs"]),
    crate = "actrpc_orchestrator",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrpc-core/0.1.0:actrpc_core",
        "//third-party/rust/crates/actrpc-transport/0.1.0:actrpc_transport",
        "//third-party/rust/crates/jsonschema/0.46.10:jsonschema",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
