load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_macos",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_macos",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.13.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.18.0:accesskit_consumer",
        "//third-party/rust/crates/icrate/0.1.2:icrate",
        "//third-party/rust/crates/objc2/0.5.2:objc2",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
    ],
)
