load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_connect",
    srcs = glob(["**/*.rs"]),
    crate = "actix_connect",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
