load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_protocol",
    srcs = glob(["**/*.rs"]),
    crate = "actr_protocol",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
