load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a9",
    srcs = glob(["**/*.rs"]),
    crate = "a9",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
