load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_transport",
    srcs = glob(["**/*.rs"]),
    crate = "adb_transport",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bstr/1.13.1:bstr",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/diatomic-waker/0.2.3:diatomic_waker",
        "//third-party/rust/crates/enum_dispatch/0.3.13:enum_dispatch",
        "//third-party/rust/crates/flume/0.11.1:flume",
        "//third-party/rust/crates/num-bigint-dig/0.8.6:num_bigint_dig",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/nusb/0.1.14:nusb",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
