load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "Assignment_Tracker_GUI",
    srcs = glob(["**/*.rs"]),
    crate = "Assignment_Tracker_GUI",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/eframe/0.27.2:eframe",
        "//third-party/rust/crates/egui/0.27.2:egui",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
