load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abtc_infrastructure",
    srcs = glob(["**/*.rs"]),
    crate = "abtc_infrastructure",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abtc-adapters/0.1.0:abtc_adapters",
        "//third-party/rust/crates/abtc-application/0.1.0:abtc_application",
        "//third-party/rust/crates/abtc-domain/0.1.0:abtc_domain",
        "//third-party/rust/crates/abtc-ports/0.1.0:abtc_ports",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
