load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_module_factory",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_module_factory",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-macros/0.26.1:abstract_macros",
        "//third-party/rust/crates/abstract-sdk/0.26.1:abstract_sdk",
        "//third-party/rust/crates/abstract-std/0.26.1:abstract_std",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-ownable/2.1.0:cw_ownable",
        "//third-party/rust/crates/cw2/2.0.0:cw2",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde-cw-value/0.7.0:serde_cw_value",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
