load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_error_proc_macros",
    srcs = glob(["**/*.rs"]),
    crate = "actix_error_proc_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
