load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aderyn_core",
    srcs = glob(["**/*.rs"]),
    crate = "aderyn_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/crossbeam/0.8.4:crossbeam",
        "//third-party/rust/crates/eyre/0.6.14:eyre",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
