# SPDX-FileCopyrightText: 2023 Gustavo Coutinho de Souza <dev@onemoresuza.mailer.me>
#
# SPDX-License-Identifier: ISC

image: nixos/unstable

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  PROJECT_NAME: "aba"
  GIT_PUSH_URL: "git@git.sr.ht:~onemoresuza/aba"
  NIX_ARTIFACTs_PACKAGE: "hutArtifacts"
  CACHIX_BIN_CACHE: "rust-deps"

secrets:
  - b9d05891-f72c-4697-a908-d0f9c5334d60 # ssh key
  - f1895886-cbc7-46a8-b70f-797e1b707946 # cachix token for rust-deps
  - dcf7c4b1-8471-4d3d-97b6-370095811a3e # crates.io update crate token

oauth: "git.sr.ht/OBJECTS:RW git.sr.ht/REPOSITORIES:RO git.sr.ht/PROFILE:RO"

tasks:
  - setup-cachix: |
      cd "${PROJECT_NAME}"
      nix develop .#ci --command cachix use nix-community
      nix develop .#ci --command cachix use "${CACHIX_BIN_CACHE}"
  - reuse-lint: |
      cd "${PROJECT_NAME}"
      nix develop .#ci --command reuse lint
  - run-nix-flake-check: |
      cd "${PROJECT_NAME}"
      nix flake check
  - test-basic-functionality: |
      cd "${PROJECT_NAME}"
      nix build .
      nix run . -- --help
      nix run . -- --version
  - push-to-cachix: |
      cd "${PROJECT_NAME}"
      nix run .#pushToCachix -- .#artifacts .#default
  - generate-git-tag: |
      cd "${PROJECT_NAME}"
      VERSION="$(nix develop .#ci --command get-version)" \
        nix run .#genGitTagAndChangelog
  - upload-artifacts: |
      if [[ -n "${GIT_TAG_GENERATED}" ]]; then
        cd "${PROJECT_NAME}"
        nix develop .#ci --command cargo publish
        nix run .#uploadArtifacts
        nix run .#pushToCachix -- .#abaMusl
      fi

triggers:
  - action: email
    condition: failure
    to: srht1@onemoresuza.mailer.me
