load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_audit_core",
    srcs = glob(["**/*.rs"]),
    crate = "abi_audit_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/cargo_metadata/0.21.0:cargo_metadata",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
