load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr2line",
    srcs = glob(["**/*.rs"]),
    crate = "addr2line",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fallible-iterator/0.1.6:fallible_iterator",
        "//third-party/rust/crates/getopts/0.2.24:getopts",
        "//third-party/rust/crates/gimli/0.9.0:gimli",
        "//third-party/rust/crates/memmap/0.5.2:memmap",
        "//third-party/rust/crates/object/0.1.0:object",
    ],
)
