load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx_actix",
    srcs = glob(["**/*.rs"]),
    crate = "adminx_actix",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/adminx-core/3.1.0:adminx_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
