load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_osc_8_hyperlink",
    srcs = glob(["**/*.rs"]),
    crate = "add_osc_8_hyperlink",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hostname/0.3.1:hostname",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
