load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actify",
    srcs = glob(["**/*.rs"]),
    crate = "actify",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actify-macros/0.5.0:actify_macros",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
