load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin_app",
    srcs = glob(["**/*.rs"]),
    crate = "admin_app",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/apdu-app/0.2.0:apdu_app",
        "//third-party/rust/crates/cbor-smol/0.5.1:cbor_smol",
        "//third-party/rust/crates/ctaphid-app/0.2.0:ctaphid_app",
        "//third-party/rust/crates/delog/0.1.8:delog",
        "//third-party/rust/crates/heapless-bytes/0.5.0:heapless_bytes",
        "//third-party/rust/crates/heapless/0.9.3:heapless",
        "//third-party/rust/crates/hex-literal/0.4.1:hex_literal",
        "//third-party/rust/crates/iso7816/0.2.0:iso7816",
        "//third-party/rust/crates/littlefs2-core/0.1.3:littlefs2_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum_macros/0.25.3:strum_macros",
        "//third-party/rust/crates/trussed-core/0.2.2:trussed_core",
        "//third-party/rust/crates/trussed-manage/0.3.0:trussed_manage",
        "//third-party/rust/crates/trussed/0.2.0:trussed",
    ],
)
