load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adp5360",
    srcs = glob(["**/*.rs"]),
    crate = "adp5360",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/embedded-hal-async/1.0.0:embedded_hal_async",
        "//third-party/rust/crates/embedded-hal-mock/0.11.1:embedded_hal_mock",
    ],
)
