syntax = "proto3";
package aaru;

// The routing service
service Router {
  // Returns the appropriate route between the starting and ending locations.
  rpc Route (RouteRequest) returns (RouteResponse);
  rpc ClosestPoint (Coordinate) returns (Coordinate);
}

// The geocoding service
service Geocoder {
  // Determines an appropriate `Coordinate` for the provided `Geocode`
  rpc Forward(GeoLike) returns (Geocode);
  // Returns an appropriate `Geocode` for the provided geography
  rpc Reverse(Geocode) returns (Coordinate);
}

message GeoLike {
  oneof feature {
    Coordinate coordinate = 1;
    Polygon linestring = 3;
    Polygon polygon = 2;
  }
}

message Geocode {
  string title = 1;
  optional Coordinate position = 2;
}

message Polygon {
  optional string label = 1;
  repeated Coordinate coordinates = 2;
}

message Coordinate {
  double latitude = 1;
  double longitude = 2;
}

enum Costing {
  Car = 0;
}

// The request message containing the user's name.
message RouteRequest {
  Coordinate start = 1;
  Coordinate end = 2;
  Costing costing_method = 3;
}

/// The response message including pathing, and weighted heuristics
message RouteResponse {
  repeated Coordinate shape = 1;
  uint32 cost = 2;
}