load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accept_encoding_fork",
    srcs = glob(["**/*.rs"]),
    crate = "accept_encoding_fork",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/http/0.2.12:http",
    ],
)
