load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acsim",
    srcs = glob(["**/*.rs"]),
    crate = "acsim",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-files/0.6.10:actix_files",
        "//third-party/rust/crates/actix-governor/0.5.0:actix_governor",
        "//third-party/rust/crates/actix-multipart/0.6.2:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dotenv/0.15.0:dotenv",
        "//third-party/rust/crates/fern/0.6.2:fern",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/handlebars/4.5.0:handlebars",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/magic/0.16.7:magic",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/sqlx/0.7.4:sqlx",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
