load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbridge",
    srcs = glob(["**/*.rs"]),
    crate = "adbridge",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adb_client/3.2.3:adb_client",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/leptess/0.14.0:leptess",
        "//third-party/rust/crates/rmcp/1.8.0:rmcp",
        "//third-party/rust/crates/roxmltree/0.20.0:roxmltree",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
