load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsbx_screenshot",
    srcs = glob(["**/*.rs"]),
    crate = "adsbx_screenshot",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/headless_chrome/1.0.22:headless_chrome",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
