load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admob_android",
    srcs = glob(["**/*.rs"]),
    crate = "admob_android",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbow-android/0.1.18:crossbow_android",
    ],
)
