load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_admin",
    srcs = glob(["**/*.rs"]),
    crate = "actix_admin",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-admin-macros/0.1.0:actix_admin_macros",
        "//third-party/rust/crates/actix-multipart/0.4.0:actix_multipart",
        "//third-party/rust/crates/actix-session/0.7.2:actix_session",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/sea-orm/0.9.3:sea_orm",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/tera/1.20.1:tera",
    ],
)
