load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "address_formatter",
    srcs = glob(["**/*.rs"]),
    crate = "address_formatter",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/enum-map/0.5.0:enum_map",
        "//third-party/rust/crates/env_logger/0.6.2:env_logger",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/include_dir/0.2.1:include_dir",
        "//third-party/rust/crates/itertools/0.8.2:itertools",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/strum/0.15.0:strum",
        "//third-party/rust/crates/strum_macros/0.15.0:strum_macros",
        "//third-party/rust/crates/yaml-rust/0.4.5:yaml_rust",
    ],
)
