load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad7147",
    srcs = glob(["**/*.rs"]),
    crate = "ad7147",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byte-slice-cast/1.2.3:byte_slice_cast",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/heapless/0.7.17:heapless",
    ],
)
