load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abxml",
    srcs = glob(["**/*.rs"]),
    crate = "abxml",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ansi_term/0.12.1:ansi_term",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/encoding/0.2.33:encoding",
        "//third-party/rust/crates/env_logger/0.7.1:env_logger",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/xml-rs/0.8.29:xml_rs",
    ],
)
