load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpica_bindings",
    srcs = glob(["**/*.rs"]),
    crate = "acpica_bindings",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitfield-struct/0.5.6:bitfield_struct",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/spin/0.9.9:spin",
    ],
)
