load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acacia_net",
    srcs = glob(["**/*.rs"]),
    crate = "acacia_net",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/failure_derive/0.1.8:failure_derive",
        "//third-party/rust/crates/hematite-nbt/0.4.1:hematite_nbt",
    ],
)
