load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads7924",
    srcs = glob(["**/*.rs"]),
    crate = "ads7924",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.10.3:bit_field",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
