load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admiral_derive",
    srcs = glob(["**/*.rs"]),
    crate = "admiral_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/admiral-types/0.1.0:admiral_types",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/rustc-test/0.3.1:rustc_test",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
