load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_script_wasm",
    srcs = glob(["**/*.rs"]),
    crate = "adana_script_wasm",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adana-script-core/0.17.11:adana_script_core",
        "//third-party/rust/crates/adana-script/0.17.11:adana_script",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/serde-wasm-bindgen/0.6.5:serde_wasm_bindgen",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
