load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_colour",
    srcs = glob(["**/*.rs"]),
    crate = "aa_colour",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/displaydoc/0.1.7:displaydoc",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
