load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aaai",
    srcs = glob(["**/*.rs"]),
    crate = "aaai",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aaai-core/0.32.0:aaai_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/indicatif/0.18.6:indicatif",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/notify/8.2.0:notify",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/similar/3.1.2:similar",
    ],
)
