load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "rigid_body",
    srcs = glob(["**/*.rs"]),
    crate = "rigid_body",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/vecmath/1.0.0:vecmath",
    ],
)
