/*
 * Aargau Cloud Plattform API
 *
 * An API specification for communication between the ACP Self Service Frontend and Backend systems
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: acp@ag.ch
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Application {
    /// Name of the application
    #[serde(rename = "name")]
    pub name: String,
    /// Unique id of the application
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Unique Software id from CMDB
    #[serde(rename = "software_id", skip_serializing_if = "Option::is_none")]
    pub software_id: Option<String>,
    /// Timestamp of creation
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    /// Timestamp of last modification
    #[serde(rename = "last_modify", skip_serializing_if = "Option::is_none")]
    pub last_modify: Option<i32>,
    #[serde(rename = "tech_owner")]
    pub tech_owner: Box<models::Contact>,
    #[serde(rename = "org_owner")]
    pub org_owner: Box<models::Contact>,
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<models::Environment>>,
}

impl Application {
    pub fn new(name: String, tech_owner: models::Contact, org_owner: models::Contact) -> Application {
        Application {
            name,
            id: None,
            software_id: None,
            created: None,
            last_modify: None,
            tech_owner: Box::new(tech_owner),
            org_owner: Box::new(org_owner),
            environments: None,
        }
    }
}

