load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abacuz",
    srcs = glob(["**/*.rs"]),
    crate = "abacuz",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/qinpel-srv/0.2.1:qinpel_srv",
    ],
)
