load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptor_std",
    srcs = glob(["**/*.rs"]),
    crate = "acceptor_std",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accepts/0.0.2:accepts",
    ],
)
