load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acacia",
    srcs = glob(["**/*.rs"]),
    crate = "acacia",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nalgebra/0.1.0:nalgebra",
        "//third-party/rust/crates/quickcheck/0.1.40:quickcheck",
        "//third-party/rust/crates/quickcheck_macros/0.1.40:quickcheck_macros",
    ],
)
