load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_rust_embed_responder",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_rust_embed_responder",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
