load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adborc",
    srcs = glob(["**/*.rs"]),
    crate = "adborc",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/blake2/0.10.6:blake2",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/hostname/0.3.1:hostname",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pathsearch/0.2.0:pathsearch",
        "//third-party/rust/crates/portpicker/0.1.1:portpicker",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/snow/0.9.6:snow",
        "//third-party/rust/crates/socket2/0.4.10:socket2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
