load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrpc_core",
    srcs = glob(["**/*.rs"]),
    crate = "actrpc_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrpc-core-macros/0.1.0:actrpc_core_macros",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.28.0:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
