load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_zero",
    srcs = glob(["**/*.rs"]),
    crate = "act_zero",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
