load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori",
    srcs = glob(["**/*.rs"]),
    crate = "actori",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-rt/1.0.0:actori_rt",
        "//third-party/rust/crates/actori_derive/0.5.0:actori_derive",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/crossbeam-channel/0.4.4:crossbeam_channel",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.10.2:parking_lot",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/tokio-util/0.2.0:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
