load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin_app",
    srcs = glob(["**/*.rs"]),
    crate = "admin_app",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/apdu-dispatch/0.1.2:apdu_dispatch",
        "//third-party/rust/crates/ctaphid-dispatch/0.1.1:ctaphid_dispatch",
        "//third-party/rust/crates/delog/0.1.8:delog",
        "//third-party/rust/crates/iso7816/0.1.4:iso7816",
        "//third-party/rust/crates/trussed/0.1.0:trussed",
    ],
)
