load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_plus_auth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_plus_auth",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-plus-error/0.1.0:actix_plus_error",
        "//third-party/rust/crates/actix-plus-utils/0.1.0:actix_plus_utils",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/argon2/0.1.5:argon2",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/jsonwebtoken/7.2.0:jsonwebtoken",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
