load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_rs_tokio",
    srcs = glob(["**/*.rs"]),
    crate = "act_rs_tokio",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act_rs/0.4.0:act_rs",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
