load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acroform_pdf",
    srcs = glob(["**/*.rs"]),
    crate = "acroform_pdf",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acroform-pdf-derive/0.0.6:acroform_pdf_derive",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/datasize/0.2.15:datasize",
        "//third-party/rust/crates/deflate/1.0.0:deflate",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/istring/0.3.4:istring",
        "//third-party/rust/crates/itertools/0.13.0:itertools",
        "//third-party/rust/crates/libflate/2.3.1:libflate",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/snafu/0.8.9:snafu",
        "//third-party/rust/crates/weezl/0.1.12:weezl",
    ],
)
