load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abakadabra",
    srcs = glob(["**/*.rs"]),
    crate = "abakadabra",
    crate_root = "lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
