load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accuweather",
    srcs = glob(["**/*.rs"]),
    crate = "accuweather",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/mockito/0.23.3:mockito",
        "//third-party/rust/crates/reqwest/0.9.24:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
