load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_framed",
    srcs = glob(["**/*.rs"]),
    crate = "actix_framed",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.2.0:actix_codec",
        "//third-party/rust/crates/actix-http/1.0.1:actix_http",
        "//third-party/rust/crates/actix-router/0.2.7:actix_router",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
    ],
)
