load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_wsb",
    srcs = glob(["**/*.rs"]),
    crate = "actix_wsb",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-ws/0.3.1:actix_ws",
    ],
)
