load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abe_policy",
    srcs = glob(["**/*.rs"]),
    crate = "abe_policy",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
