load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_settings",
    srcs = glob(["**/*.rs"]),
    crate = "actix_settings",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/2.2.2:actix_http",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/ioe/0.4.0:ioe",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/toml/0.5.11:toml",
    ],
)
