load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acmev02",
    srcs = glob(["**/*.rs"]),
    crate = "acmev02",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/error-chain/0.12.4:error_chain",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/simple_asn1/0.5.4:simple_asn1",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
