load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_request_uuid",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_request_uuid",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
