import { AJLanguage } from "models/testing.slint";
import { AJDateTime } from "models/others.slint";
import { AJProblem, AJSubgroup } from "models/problems.slint";
import { AJAdminLevel } from "models/users.slint";

export global AJWelcomeCallbacks {
    callback login(login: string, password: string);
    callback register(login: string, password: string, password-confirmation: string);
}

export global AJHomeCallbacks {
    callback enter-contest(id: int);
    callback create-contest(name: string, starts-at: AJDateTime, ends-at: AJDateTime, statements-url: string, editorial-url: string, hidden: bool, upsolving-opened: bool, hide-solutions: bool);
    callback update-contest(id: int, name: string, starts-at: AJDateTime, ends-at: AJDateTime, statements-url: string, editorial-url: string, hidden: bool, upsolving-opened: bool, hide-solutions: bool);
    callback delete-contest(id: int, login: string, password: string, password-confirmation: string, deletion-confirmation: bool);
    callback logout();
    callback delete-account(login: string, password: string, password-confirmation: string, deletion-confirmation: bool);
}

export global AJContestCallbacks {
    callback pick-solution-file();
    callback submit(language: AJLanguage, contest-id: int, problem-id: int);
    callback retest-problem(id: int);
    callback open-profile(id: int);
    callback change-user-admin-level(id: int, admin_level: AJAdminLevel);
    callback delete-user-account(id: int, login: string, password: string, password-confirmation: string, deletion-confirmation: bool);
    callback download-submission(index: int);
}

export global AJProblemsCallbacks {
    callback pick-problem-archive();
    callback create-problem();
    callback delete-problem(id: int, login: string, password: string, password-confirmation: string, deletion-confirmation: bool);
}

export global AJAppCallbacks {
    callback reload();
    callback open-link(url: string);
}
