load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ab_av1",
    srcs = glob(["**/*.rs"]),
    crate = "ab_av1",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/atty/0.2.14:atty",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/console/0.15.1:console",
        "//third-party/rust/crates/ffprobe/0.3.3:ffprobe",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/humantime/2.4.0:humantime",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shell-escape/0.1.5:shell_escape",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio-process-stream/0.3.0:tokio_process_stream",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
