load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_thiserror_derive",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_thiserror_derive",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
