load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp_did",
    srcs = glob(["**/*.rs"]),
    crate = "acdp_did",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp-primitives/0.6.0:acdp_primitives",
        "//third-party/rust/crates/acdp-safe-http/0.6.0:acdp_safe_http",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/p256/0.13.2:p256",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
