load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx_cloud",
    srcs = glob(["**/*.rs"]),
    crate = "adminx_cloud",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adminx-attachments/3.1.0:adminx_attachments",
        "//third-party/rust/crates/adminx-core/3.1.0:adminx_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/object_store/0.14.1:object_store",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
