load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cortex-a/5.1.6:cortex_a",
    ],
)
