ABA(5)
; SPDX-FileCopyrightText: 2023 Gustavo Coutinho de Souza <dev@onemoresuza.mailer.me>
; 
; SPDX-License-Identifier: ISC

; REUSE-IgnoreStart
# NAME

aba - address book file

# SYNTAX

The address book file is made of only TOML arrays of tables, like so:

	\[\[address\]\]++
name = "John Doe"++
email = "johndoe@mail.org"

# SEE ALSO

*aba(1)*

# AUTHORS

Maintained by _Coutinho de Souza_ <dev@onemoresuza.mailer.me>.

# SOURCE CODE

The source code is available at <https://sr.ht/~onemoresuza/aba>.
; REUSE-IgnoreEnd
