load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_governor",
    srcs = glob(["**/*.rs"]),
    crate = "actix_governor",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/governor/0.3.2:governor",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
