load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acdp",
    srcs = glob(["**/*.rs"]),
    crate = "acdp",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp/0.6.1:acdp",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
