load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advisorygraphen_runtime",
    srcs = glob(["**/*.rs"]),
    crate = "advisorygraphen_runtime",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advisorygraphen-core/0.1.3:advisorygraphen_core",
        "//third-party/rust/crates/advisorygraphen-interpretation/0.1.3:advisorygraphen_interpretation",
        "//third-party/rust/crates/advisorygraphen-lift/0.1.3:advisorygraphen_lift",
        "//third-party/rust/crates/advisorygraphen-projection/0.1.3:advisorygraphen_projection",
        "//third-party/rust/crates/advisorygraphen-reasoning/0.1.3:advisorygraphen_reasoning",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/higher-graphen-core/0.5.0:higher_graphen_core",
        "//third-party/rust/crates/higher-graphen-reasoning/0.5.0:higher_graphen_reasoning",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
