load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abineo_analytics_collector",
    srcs = glob(["**/*.rs"]),
    crate = "abineo_analytics_collector",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/phf/0.11.3:phf",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uaparser/0.6.4:uaparser",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
