load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acro",
    srcs = glob(["**/*.rs"]),
    crate = "acro",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/csv/1.4.0:csv",
    ],
)
