load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aaa",
    srcs = glob(["**/*.rs"]),
    crate = "aaa",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossterm/0.22.1:crossterm",
        "//third-party/rust/crates/exitcode/1.1.2:exitcode",
        "//third-party/rust/crates/rs3a/1.0.6:rs3a",
    ],
)
