load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abjad",
    srcs = glob(["**/*.rs"]),
    crate = "abjad",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
    ],
)
