load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_swagger",
    srcs = glob(["**/*.rs"]),
    crate = "actix_swagger",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/take_mut/0.2.2:take_mut",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
