load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_mpr121",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_mpr121",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/i2cdev/0.4.4:i2cdev",
    ],
)
