load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aas_types",
    srcs = glob(["**/*.rs"]),
    crate = "aas_types",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/rcf-commitment/0.1.3:rcf_commitment",
        "//third-party/rust/crates/rcf-types/0.1.3:rcf_types",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
