load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "address_literal",
    srcs = glob(["**/*.rs"]),
    crate = "address_literal",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/primitive-types/0.10.1:primitive_types",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
