load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ogn",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ogn",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/backoff/0.1.6:backoff",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-codec/0.1.2:tokio_codec",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
    ],
)
