load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accursed_unutterable_type_id",
    srcs = glob(["**/*.rs"]),
    crate = "accursed_unutterable_type_id",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
