load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "activity_build",
    srcs = glob(["**/*.rs"]),
    crate = "activity_build",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/dirs-next/2.0.0:dirs_next",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
