load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionoscope",
    srcs = glob(["**/*.rs"]),
    crate = "actionoscope",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dotenv/0.15.0:dotenv",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/git2/0.20.4:git2",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
    ],
)
