load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_primitives",
    srcs = glob(["**/*.rs"]),
    crate = "ac_primitives",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/impl-serde/0.5.0:impl_serde",
        "//third-party/rust/crates/parity-scale-codec/3.7.5:parity_scale_codec",
        "//third-party/rust/crates/primitive-types/0.13.1:primitive_types",
        "//third-party/rust/crates/scale-info/2.11.6:scale_info",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sp-application-crypto/39.0.0:sp_application_crypto",
        "//third-party/rust/crates/sp-core/35.0.0:sp_core",
        "//third-party/rust/crates/sp-crypto-hashing/0.1.0:sp_crypto_hashing",
        "//third-party/rust/crates/sp-runtime-interface/29.0.1:sp_runtime_interface",
        "//third-party/rust/crates/sp-runtime/40.1.0:sp_runtime",
        "//third-party/rust/crates/sp-staking/37.0.0:sp_staking",
        "//third-party/rust/crates/sp-version/38.0.0:sp_version",
        "//third-party/rust/crates/sp-weights/31.1.0:sp_weights",
    ],
)
