load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_gitignore_cli",
    srcs = glob(["**/*.rs"]),
    crate = "add_gitignore_cli",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/inquire/0.7.5:inquire",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
