load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adnix",
    srcs = glob(["**/*.rs"]),
    crate = "adnix",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/ureq/0.12.1:ureq",
    ],
)
