load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_csrf",
    srcs = glob(["**/*.rs"]),
    crate = "actix_csrf",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/cookie/0.15.2:cookie",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
