load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_rsi",
    srcs = glob(["**/*.rs"]),
    crate = "add_rsi",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
