load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acrudjson",
    srcs = glob(["**/*.rs"]),
    crate = "acrudjson",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bigdecimal/0.4.10:bigdecimal",
        "//third-party/rust/crates/crc32fast/1.5.0:crc32fast",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sled/0.34.7:sled",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/zerocopy/0.7.35:zerocopy",
    ],
)
