load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "achitek_ls",
    srcs = glob(["**/*.rs"]),
    crate = "achitek_ls",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/achitekfile/0.3.0:achitekfile",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/lexopt/0.3.2:lexopt",
        "//third-party/rust/crates/lsp-server/0.7.9:lsp_server",
        "//third-party/rust/crates/lsp-types/0.97.0:lsp_types",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/terafile/0.1.1:terafile",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/tree-sitter/0.26.12:tree_sitter",
    ],
)
