load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adam_core_rs_coords",
    srcs = glob(["**/*.rs"]),
    crate = "adam_core_rs_coords",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrow-array/54.3.1:arrow_array",
        "//third-party/rust/crates/arrow-buffer/54.3.1:arrow_buffer",
        "//third-party/rust/crates/arrow-schema/54.3.1:arrow_schema",
        "//third-party/rust/crates/erfars/0.2.0:erfars",
        "//third-party/rust/crates/faer/0.22.6:faer",
        "//third-party/rust/crates/nalgebra/0.33.3:nalgebra",
        "//third-party/rust/crates/parquet/54.3.1:parquet",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/statrs/0.18.0:statrs",
    ],
)
