load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abci2",
    srcs = glob(["**/*.rs"]),
    crate = "abci2",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/protobuf/2.10.1:protobuf",
    ],
)
