load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addressable_pairing_heap",
    srcs = glob(["**/*.rs"]),
    crate = "addressable_pairing_heap",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.3.23:rand",
        "//third-party/rust/crates/stash/0.1.6:stash",
        "//third-party/rust/crates/unreachable/0.1.1:unreachable",
    ],
)
