load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_admin_macros",
    srcs = glob(["**/*.rs"]),
    crate = "actix_admin_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bae/0.1.7:bae",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
