load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actix_swagger",
    srcs = glob(["**/*.rs"]),
    crate = "actix_swagger",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
