load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adf_bdd",
    srcs = glob(["**/*.rs"]),
    crate = "adf_bdd",
    crate_root = "src/main.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adf_bdd/0.3.1:adf_bdd",
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.24.1:strum",
    ],
)
