load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "AthenaEngine",
    srcs = glob(["**/*.rs"]),
    crate = "AthenaEngine",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
