name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    permissions:
      # read workflow runs and history
      actions: read
      # checkout repository contents
      contents: read
      # upload SARIF results to GitHub Security tab
      security-events: write
      # OIDC token for GitHub API authentication
      id-token: write
    uses: luxass/shared-workflows/.github/workflows/reusable-ci-security.yaml@306df1ba2ab60f117e6e05c2f736e3f2bd4a0366 # v0.8.2
