load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adx",
    srcs = glob(["**/*.rs"]),
    crate = "adx",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/color-eyre/0.5.11:color_eyre",
        "//third-party/rust/crates/roxmltree/0.14.1:roxmltree",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/surf/2.3.2:surf",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
