load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "AISHub_data_collector",
    srcs = glob(["**/*.rs"]),
    crate = "AISHub_data_collector",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
