load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adrnaln",
    srcs = glob(["**/*.rs"]),
    crate = "adrnaln",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/opentelemetry-jaeger/0.16.0:opentelemetry_jaeger",
        "//third-party/rust/crates/opentelemetry/0.17.0:opentelemetry",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/signal-hook/0.3.18:signal_hook",
        "//third-party/rust/crates/socket2/0.5.10:socket2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-opentelemetry/0.17.4:tracing_opentelemetry",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
