load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abar",
    srcs = glob(["**/*.rs"]),
    crate = "abar",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/getopts/0.2.24:getopts",
    ],
)
