load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori_web_actors",
    srcs = glob(["**/*.rs"]),
    crate = "actori_web_actors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-codec/0.2.0:actori_codec",
        "//third-party/rust/crates/actori-http/1.0.1:actori_http",
        "//third-party/rust/crates/actori-web/2.0.0:actori_web",
        "//third-party/rust/crates/actori/0.9.0:actori",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
    ],
)
