load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acyclib",
    srcs = glob(["**/*.rs"]),
    crate = "acyclib",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/rand_distr/0.5.1:rand_distr",
    ],
)
