load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_feather_rp2040_thinkink",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_feather_rp2040_thinkink",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/fugit/0.3.9:fugit",
        "//third-party/rust/crates/rp2040-hal/0.11.0:rp2040_hal",
    ],
)
