load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionguard",
    srcs = glob(["**/*.rs"]),
    crate = "actionguard",
    crate_root = "actionguard/policy.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
