load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_deep_research",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_deep_research",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-acl/0.3.0:a3s_acl",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/comrak/0.36.0:comrak",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/whatlang/0.16.4:whatlang",
    ],
)
