load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accept_language",
    srcs = glob(["**/*.rs"]),
    crate = "accept_language",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
)
