load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_contrib_rest",
    srcs = glob(["**/*.rs"]),
    crate = "actix_contrib_rest",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-web-validator/7.0.0:actix_web_validator",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/awc/3.8.2:awc",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/validator/0.20.0:validator",
    ],
)
