load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptemoji",
    srcs = glob(["**/*.rs"]),
    crate = "adaptemoji",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/image/0.25.10:image",
    ],
)
