load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility_ng",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility_ng",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accessibility-sys-ng/0.1.3:accessibility_sys_ng",
        "//third-party/rust/crates/cocoa/0.24.1:cocoa",
        "//third-party/rust/crates/core-foundation/0.9.4:core_foundation",
        "//third-party/rust/crates/core-graphics-types/0.1.3:core_graphics_types",
        "//third-party/rust/crates/objc/0.2.7:objc",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
