load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "address_artisan",
    srcs = glob(["**/*.rs"]),
    crate = "address_artisan",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitcoin/0.32.102:bitcoin",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/secp256k1/0.29.1:secp256k1",
    ],
)
