load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acto",
    srcs = glob(["**/*.rs"]),
    crate = "acto",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
