load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a_flags",
    srcs = glob(["**/*.rs"]),
    crate = "a_flags",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
    ],
)
