load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_config",
    srcs = glob(["**/*.rs"]),
    crate = "actr_config",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actr-protocol/0.2.1:actr_protocol",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
