load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abspath",
    srcs = glob(["**/*.rs"]),
    crate = "abspath",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/mhlog/1.1.0:mhlog",
    ],
)
