load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_core",
    srcs = glob(["**/*.rs"]),
    crate = "aa_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
    ],
)
