load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_reactive",
    srcs = glob(["**/*.rs"]),
    crate = "acton_reactive",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acton-ern/2.0.0:acton_ern",
        "//third-party/rust/crates/acton-macro/8.2.0:acton_macro",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/derive-new/0.7.0:derive_new",
        "//third-party/rust/crates/dyn-clone/1.0.20:dyn_clone",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/static_assertions/1.1.0:static_assertions",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tracing-appender/0.2.5:tracing_appender",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/xdg/2.5.2:xdg",
    ],
)
