load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addchain",
    srcs = glob(["**/*.rs"]),
    crate = "addchain",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-bigint/0.3.3:num_bigint",
        "//third-party/rust/crates/num-integer/0.1.47:num_integer",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
