load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_layer_driver",
    srcs = glob(["**/*.rs"]),
    crate = "action_layer_driver",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chia-protocol/0.26.0:chia_protocol",
        "//third-party/rust/crates/chia-puzzles/0.20.3:chia_puzzles",
        "//third-party/rust/crates/chia-wallet-sdk/0.30.0:chia_wallet_sdk",
        "//third-party/rust/crates/chia/0.26.0:chia",
        "//third-party/rust/crates/clvm-traits/0.26.0:clvm_traits",
        "//third-party/rust/crates/clvm-utils/0.26.0:clvm_utils",
        "//third-party/rust/crates/clvmr/0.14.0:clvmr",
        "//third-party/rust/crates/hex-literal/0.4.1:hex_literal",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
