load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ais",
    srcs = glob(["**/*.rs"]),
    crate = "ais",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acuity-index-substrate-api/0.3.0:acuity_index_substrate_api",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/byte-unit/5.2.5:byte_unit",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/subxt/0.42.1:subxt",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
