load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_postgres",
    srcs = glob(["**/*.rs"]),
    crate = "actix_postgres",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/bb8-postgres/0.8.1:bb8_postgres",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
