load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acap_logging",
    srcs = glob(["**/*.rs"]),
    crate = "acap_logging",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libsyslog/0.1.1:libsyslog",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
