load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_runner",
    srcs = glob(["**/*.rs"]),
    crate = "adk_runner",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-artifact/0.5.0:adk_artifact",
        "//third-party/rust/crates/adk-core/0.5.0:adk_core",
        "//third-party/rust/crates/adk-plugin/0.5.0:adk_plugin",
        "//third-party/rust/crates/adk-session/0.5.0:adk_session",
        "//third-party/rust/crates/adk-skill/0.5.0:adk_skill",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
