load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adrift",
    srcs = glob(["**/*.rs"]),
    crate = "adrift",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adrift_core/0.0.10:adrift_core",
        "//third-party/rust/crates/adrift_macros/0.0.10:adrift_macros",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
