load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advreader",
    srcs = glob(["**/*.rs"]),
    crate = "advreader",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/encoding_rs2/0.8.36:encoding_rs2",
        "//third-party/rust/crates/flume/0.12.0:flume",
    ],
)
