load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ip_filter",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ip_filter",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/glob/0.3.4:glob",
    ],
)
