load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abuseipdb",
    srcs = glob(["**/*.rs"]),
    crate = "abuseipdb",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/jsonapi/0.6.6:jsonapi",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
    ],
)
