load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_plus_error",
    srcs = glob(["**/*.rs"]),
    crate = "actix_plus_error",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
    ],
)
