/*
 * Ably Chat REST API
 *
 * REST API for [Ably Chat](https://ably.com/docs/chat).  This specification describes the HTTP surface of the Ably Chat REST API (path prefix `/chat/v4`) that the official Chat client SDKs use for request/response operations such as sending, editing, deleting and querying messages, message reactions and room occupancy.  ## Scope & provenance Ably does **not** publish an official OpenAPI document for the Chat REST API (the official `ably/open-specs` `platform-v1.yaml` covers only the generic pub/sub REST API: `/channels`, `/push`, `/keys`, `/stats`, `/time`). This document was reconstructed from the `@ably/chat` JavaScript SDK v1.4.0 REST layer (`src/core/chat-api.ts`, `src/core/rest-types.ts`) together with Ably's documented REST conventions (host, authentication, versioning, pagination, error envelope).  It therefore covers the endpoints the client SDK exercises. It is **not** an exhaustive description of every server capability, and there are intentionally no endpoints for creating or deleting rooms: Chat rooms are channel-backed and implicit — they are not provisioned via REST.  ## Realtime vs REST Many Chat features (presence, typing indicators, room reactions, subscribing to live messages and reaction summaries) are delivered over Ably's realtime/pub-sub transport, not this REST API, and are out of scope here. 
 *
 * The version of the OpenAPI document: 4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientIdCounts : Aggregated per-client counts for a `multiple` reaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientIdCounts {
    /// Total count across all clients (sum of per-client counts).
    #[serde(rename = "total")]
    pub total: i32,
    /// Map of client ID to that client's reaction count.
    #[serde(rename = "clientIds")]
    pub client_ids: std::collections::HashMap<String, i32>,
    /// Total count contributed by unidentified clients.
    #[serde(rename = "totalUnidentified")]
    pub total_unidentified: i32,
    /// Whether the `clientIds` map was truncated.
    #[serde(rename = "clipped", skip_serializing_if = "Option::is_none")]
    pub clipped: Option<bool>,
    /// Total number of distinct client IDs that reacted.
    #[serde(rename = "totalClientIds", skip_serializing_if = "Option::is_none")]
    pub total_client_ids: Option<i32>,
}

impl ClientIdCounts {
    /// Aggregated per-client counts for a `multiple` reaction.
    pub fn new(total: i32, client_ids: std::collections::HashMap<String, i32>, total_unidentified: i32) -> ClientIdCounts {
        ClientIdCounts {
            total,
            client_ids,
            total_unidentified,
            clipped: None,
            total_client_ids: None,
        }
    }
}

