/*
 * Ably Chat REST API
 *
 * REST API for [Ably Chat](https://ably.com/docs/chat).  This specification describes the HTTP surface of the Ably Chat REST API (path prefix `/chat/v4`) that the official Chat client SDKs use for request/response operations such as sending, editing, deleting and querying messages, message reactions and room occupancy.  ## Scope & provenance Ably does **not** publish an official OpenAPI document for the Chat REST API (the official `ably/open-specs` `platform-v1.yaml` covers only the generic pub/sub REST API: `/channels`, `/push`, `/keys`, `/stats`, `/time`). This document was reconstructed from the `@ably/chat` JavaScript SDK v1.4.0 REST layer (`src/core/chat-api.ts`, `src/core/rest-types.ts`) together with Ably's documented REST conventions (host, authentication, versioning, pagination, error envelope).  It therefore covers the endpoints the client SDK exercises. It is **not** an exhaustive description of every server capability, and there are intentionally no endpoints for creating or deleting rooms: Chat rooms are channel-backed and implicit — they are not provisioned via REST.  ## Realtime vs REST Many Chat features (presence, typing indicators, room reactions, subscribing to live messages and reaction summaries) are delivered over Ably's realtime/pub-sub transport, not this REST API, and are out of scope here. 
 *
 * The version of the OpenAPI document: 4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageReactions : Summary of reactions on a message, grouped by reaction type. Each map is keyed by the reaction name (e.g. an emoji). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageReactions {
    #[serde(rename = "unique", skip_serializing_if = "Option::is_none")]
    pub unique: Option<std::collections::HashMap<String, models::ClientIdList>>,
    #[serde(rename = "distinct", skip_serializing_if = "Option::is_none")]
    pub distinct: Option<std::collections::HashMap<String, models::ClientIdList>>,
    #[serde(rename = "multiple", skip_serializing_if = "Option::is_none")]
    pub multiple: Option<std::collections::HashMap<String, models::ClientIdCounts>>,
}

impl MessageReactions {
    /// Summary of reactions on a message, grouped by reaction type. Each map is keyed by the reaction name (e.g. an emoji). 
    pub fn new() -> MessageReactions {
        MessageReactions {
            unique: None,
            distinct: None,
            multiple: None,
        }
    }
}

