load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/httparse/1.10.1:httparse",
        "//third-party/rust/crates/local-waker/0.1.4:local_waker",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/memchr/2.8.3:memchr",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_plain/1.0.2:serde_plain",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
