load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actuate",
    srcs = glob(["**/*.rs"]),
    crate = "actuate",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actuate-macros/0.2.0:actuate_macros",
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/crossbeam-queue/0.3.13:crossbeam_queue",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hashbrown/0.15.5:hashbrown",
        "//third-party/rust/crates/slotmap/1.1.1:slotmap",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/typeid/1.0.3:typeid",
    ],
)
