load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accepted",
    srcs = glob(["**/*.rs"]),
    crate = "accepted",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/config/0.9.3:config",
        "//third-party/rust/crates/dirs/1.0.5:dirs",
        "//third-party/rust/crates/jsonrpc-core/8.0.1:jsonrpc_core",
        "//third-party/rust/crates/racer/2.2.2:racer",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shellexpand/1.1.1:shellexpand",
        "//third-party/rust/crates/syntect/2.1.0:syntect",
        "//third-party/rust/crates/termion/1.5.6:termion",
        "//third-party/rust/crates/unicode-width/0.1.14:unicode_width",
    ],
)
