load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_pack",
    srcs = glob(["**/*.rs"]),
    crate = "actr_pack",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/zip/2.4.2:zip",
    ],
)
