load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abyo_speculate",
    srcs = glob(["**/*.rs"]),
    crate = "abyo_speculate",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/candle-core/0.8.4:candle_core",
        "//third-party/rust/crates/candle-nn/0.8.4:candle_nn",
        "//third-party/rust/crates/candle-transformers/0.8.4:candle_transformers",
        "//third-party/rust/crates/hf-hub/0.4.3:hf_hub",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_distr/0.4.3:rand_distr",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokenizers/0.20.4:tokenizers",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
