load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add6_64b",
    srcs = glob(["**/*.rs"]),
    crate = "add6_64b",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add3/4.0.0:add3",
    ],
)
