load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adblock",
    srcs = glob(["**/*.rs"]),
    crate = "adblock",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/idna/1.1.0:idna",
        "//third-party/rust/crates/itertools/0.13.0:itertools",
        "//third-party/rust/crates/memchr/2.8.3:memchr",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rmp-serde/0.15.5:rmp_serde",
        "//third-party/rust/crates/seahash/3.0.7:seahash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
