load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_thiserror",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_thiserror",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-thiserror-derive/0.2.7:actix_web_thiserror_derive",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
