load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm_blackbox_solver",
    srcs = glob(["**/*.rs"]),
    crate = "acvm_blackbox_solver",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes/0.9.2:aes",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/cbc/0.2.1:cbc",
        "//third-party/rust/crates/keccak/0.2.1:keccak",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
