load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_awp",
    srcs = glob(["**/*.rs"]),
    crate = "adk_awp",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/2.0.0:adk_core",
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/awp-types/2.0.0:awp_types",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
