load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_validated_forms",
    srcs = glob(["**/*.rs"]),
    crate = "actix_validated_forms",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-multipart/0.2.0:actix_multipart",
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/err-derive/0.2.4:err_derive",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/validator/0.10.1:validator",
    ],
)
