load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acute_ecs",
    srcs = glob(["**/*.rs"]),
    crate = "acute_ecs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/legion/0.2.4:legion",
    ],
)
