load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_files",
    srcs = glob(["**/*.rs"]),
    crate = "actix_files",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/0.2.11:actix_http",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/derive_more/0.15.0:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/percent-encoding/1.0.1:percent_encoding",
        "//third-party/rust/crates/v_htmlescape/0.4.5:v_htmlescape",
    ],
)
