load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_rs_smol",
    srcs = glob(["**/*.rs"]),
    crate = "act_rs_smol",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act_rs/0.4.0:act_rs",
        "//third-party/rust/crates/smol/2.0.2:smol",
    ],
)
