load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adn_server",
    srcs = glob(["**/*.rs"]),
    crate = "adn_server",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rusqlite/0.39.0:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/tree-sitter-python/0.25.0:tree_sitter_python",
        "//third-party/rust/crates/tree-sitter-typescript/0.23.2:tree_sitter_typescript",
        "//third-party/rust/crates/tree-sitter/0.26.12:tree_sitter",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
