import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJWelcomeCallbacks } from "../aj-callbacks.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJButton } from "../components/aj-button.slint";

export component RegisterPage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJText {
            text: "создание аккаунта";
            type: AJTextType.Heading;
        }

        login := AJInput {
            placeholder: "логин";
        }

        password := AJInput {
            placeholder: "пароль";
            type: AJInputType.Password;
        }

        password-confirmation := AJInput {
            placeholder: "подтвердите пароль";
            type: AJInputType.Password;
        }

        master-password := AJInput {
            placeholder: "мастер-пароль";
            type: AJInputType.Password;
        }

        AJButton {
            text: "создать аккаунт >>";
            clicked => {
                AJWelcomeCallbacks.register(login.text, password.text, password-confirmation.text, master-password.text)
            }
        }

        AJButton {
            text: "<< назад";
            clicked => {
                AJAppState.page = 0
            }
        }
    }
}
