load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acir",
    srcs = glob(["**/*.rs"]),
    crate = "acir",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir_field/0.1.0:acir_field",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/rmp-serde/1.3.1:rmp_serde",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
