load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adts_core",
    srcs = glob(["**/*.rs"]),
    crate = "adts_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
