load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_model",
    srcs = glob(["**/*.rs"]),
    crate = "adk_model",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/0.3.2:adk_core",
        "//third-party/rust/crates/adk-telemetry/0.3.2:adk_telemetry",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
