load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/httparse/1.10.1:httparse",
        "//third-party/rust/crates/local-waker/0.1.4:local_waker",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/twoway/0.2.2:twoway",
    ],
)
