load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addrezz",
    srcs = glob(["**/*.rs"]),
    crate = "addrezz",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/addrezz_core/0.1.0:addrezz_core",
    ],
)
