load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp_wasm",
    srcs = glob(["**/*.rs"]),
    crate = "acp_wasm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/serde-wasm-bindgen/0.6.5:serde_wasm_bindgen",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/wasm-bindgen-futures/0.4.77:wasm_bindgen_futures",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
        "//third-party/rust/crates/web-sys/0.3.104:web_sys",
    ],
)
