load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aalto",
    srcs = glob(["**/*.rs"]),
    crate = "aalto",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
    ],
)
