load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actually",
    srcs = glob(["**/*.rs"]),
    crate = "actually",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arboard/3.6.1:arboard",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/claude-code-agent-sdk/0.1.39:claude_code_agent_sdk",
        "//third-party/rust/crates/crossterm/0.29.0:crossterm",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/ratatui/0.30.2:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
