load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_web_abi",
    srcs = glob(["**/*.rs"]),
    crate = "actr_web_abi",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/serde-wasm-bindgen/0.6.5:serde_wasm_bindgen",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/wasm-bindgen-futures/0.4.77:wasm_bindgen_futures",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
