load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_script_core",
    srcs = glob(["**/*.rs"]),
    crate = "adana_script_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/libloading/0.8.9:libloading",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/strum/0.25.0:strum",
    ],
)
