load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_response",
    srcs = glob(["**/*.rs"]),
    crate = "actix_response",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-response-macro/1.0.1:actix_response_macro",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
