load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_doip",
    srcs = glob(["**/*.rs"]),
    crate = "ace_doip",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-core/0.2.2:ace_core",
        "//third-party/rust/crates/ace-macros/0.2.2:ace_macros",
        "//third-party/rust/crates/ace-proto/0.2.2:ace_proto",
        "//third-party/rust/crates/ace-sim/0.2.2:ace_sim",
        "//third-party/rust/crates/ace-uds/0.2.2:ace_uds",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/heapless/0.9.3:heapless",
    ],
)
