load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_testing",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_testing",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-core/0.19.2:abstract_core",
        "//third-party/rust/crates/cosmwasm-schema/1.5.11:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/3.1.1:cw_asset",
        "//third-party/rust/crates/cw-multi-test/0.16.6:cw_multi_test",
        "//third-party/rust/crates/cw-ownable/0.5.1:cw_ownable",
        "//third-party/rust/crates/cw-storage-plus/1.1.0:cw_storage_plus",
        "//third-party/rust/crates/cw2/1.1.2:cw2",
        "//third-party/rust/crates/derive_builder/0.12.0:derive_builder",
        "//third-party/rust/crates/rstest/0.17.0:rstest",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/speculoos/0.11.0:speculoos",
    ],
)
