load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acty",
    srcs = glob(["**/*.rs"]),
    crate = "acty",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/trait-variant/0.1.3:trait_variant",
    ],
)
