load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acick_atcoder",
    srcs = glob(["**/*.rs"]),
    crate = "acick_atcoder",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/humantime/2.4.0:humantime",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/maplit/1.0.2:maplit",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.10.10:reqwest",
        "//third-party/rust/crates/scraper/0.11.0:scraper",
        "//third-party/rust/crates/strum/0.18.0:strum",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
    ],
)
