load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acm",
    srcs = glob(["**/*.rs"]),
    crate = "acm",
    crate_root = "src/acm.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/common_macros/0.1.1:common_macros",
        "//third-party/rust/crates/failure/0.1.8:failure",
    ],
)
