load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_aht10",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_aht10",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
    ],
)
