load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acir_field",
    srcs = glob(["**/*.rs"]),
    crate = "acir_field",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake2/0.9.2:blake2",
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
