load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_service",
    srcs = glob(["**/*.rs"]),
    crate = "acton_service",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/figment/0.10.19:figment",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/jsonwebtoken/10.4.0:jsonwebtoken",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/xdg/3.0.0:xdg",
    ],
)
