load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "account_state",
    srcs = glob(["**/*.rs"]),
    crate = "account_state",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/common-types/0.1.0:common_types",
        "//third-party/rust/crates/derive_more/0.15.0:derive_more",
        "//third-party/rust/crates/journaldb/0.2.0:journaldb",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/lru-cache/0.1.2:lru_cache",
        "//third-party/rust/crates/parking_lot/0.9.0:parking_lot",
        "//third-party/rust/crates/patricia-trie-vapory/0.1.1:patricia_trie_vapory",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tetsy-bytes/0.1.4:tetsy_bytes",
        "//third-party/rust/crates/tetsy-hash-db/0.15.3:tetsy_hash_db",
        "//third-party/rust/crates/tetsy-keccak-hash/0.4.0:tetsy_keccak_hash",
        "//third-party/rust/crates/tetsy-keccak-hasher/0.1.1:tetsy_keccak_hasher",
        "//third-party/rust/crates/tetsy-kvdb/0.3.2:tetsy_kvdb",
        "//third-party/rust/crates/tetsy-memory-db/0.18.1:tetsy_memory_db",
        "//third-party/rust/crates/tetsy-rlp/0.4.5:tetsy_rlp",
        "//third-party/rust/crates/tetsy-trie-db/0.19.2:tetsy_trie_db",
        "//third-party/rust/crates/tetsy-util-mem/0.3.0:tetsy_util_mem",
        "//third-party/rust/crates/trie-vm-factories/0.1.0:trie_vm_factories",
        "//third-party/rust/crates/vapcore-pod/0.1.0:vapcore_pod",
        "//third-party/rust/crates/vapory-types/0.8.0:vapory_types",
    ],
)
