load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "about_system",
    srcs = glob(["**/*.rs"]),
    crate = "about_system",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cpuid/0.1.1:cpuid",
        "//third-party/rust/crates/quick-error/1.2.3:quick_error",
        "//third-party/rust/crates/semver/0.9.0:semver",
    ],
)
