load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_orm",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_orm",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
