load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_cpu",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_cpu",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
)
