load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aditjind_crate",
    srcs = glob(["**/*.rs"]),
    crate = "aditjind_crate",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.11.0:base64",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/dyn-clone/1.0.20:dyn_clone",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_with/1.0.0:serde_with",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/void/1.0.2:void",
    ],
)
