load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_sdk",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-bloodhound/1.3.3:adhammer_bloodhound",
        "//third-party/rust/crates/adhammer-checks/1.3.3:adhammer_checks",
        "//third-party/rust/crates/adhammer-collector/1.3.3:adhammer_collector",
        "//third-party/rust/crates/adhammer-core/1.3.3:adhammer_core",
        "//third-party/rust/crates/adhammer-graph/1.3.3:adhammer_graph",
        "//third-party/rust/crates/adhammer-kerberos/1.3.3:adhammer_kerberos",
        "//third-party/rust/crates/adhammer-ldap/1.3.3:adhammer_ldap",
        "//third-party/rust/crates/adhammer-report/1.3.3:adhammer_report",
        "//third-party/rust/crates/adhammer-secrets/1.3.3:adhammer_secrets",
        "//third-party/rust/crates/adhammer-sysvol/1.3.3:adhammer_sysvol",
    ],
)
