load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_acl",
    srcs = glob(["**/*.rs"]),
    crate = "ad_acl",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/windows-sddl/0.1.1:windows_sddl",
    ],
)
