load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_correlation_id",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_correlation_id",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
