load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acmer",
    srcs = glob(["**/*.rs"]),
    crate = "acmer",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dashmap/5.5.3:dashmap",
        "//third-party/rust/crates/papaleguas/0.0.5:papaleguas",
        "//third-party/rust/crates/pem-rfc7468/0.6.0:pem_rfc7468",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rcgen/0.10.0:rcgen",
        "//third-party/rust/crates/rustls-pemfile/1.0.4:rustls_pemfile",
        "//third-party/rust/crates/rustls/0.20.9:rustls",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-rustls/0.23.4:tokio_rustls",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/x509-cert/0.1.1:x509_cert",
    ],
)
