load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_tram_types",
    srcs = glob(["**/*.rs"]),
    crate = "ac_tram_types",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async_timing_util/0.1.14:async_timing_util",
        "//third-party/rust/crates/mungos/0.4.22:mungos",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/strum/0.25.0:strum",
        "//third-party/rust/crates/strum_macros/0.25.3:strum_macros",
        "//third-party/rust/crates/typeshare/1.0.5:typeshare",
    ],
)
