load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actions_github",
    srcs = glob(["**/*.rs"]),
    crate = "actions_github",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/json/0.12.4:json",
    ],
)
