load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_raft",
    srcs = glob(["**/*.rs"]),
    crate = "actix_raft",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.6.5:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
