load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abistr",
    srcs = glob(["**/*.rs"]),
    crate = "abistr",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abistr-macros/0.1.0:abistr_macros",
    ],
)
