import { AJTheme } from "../aj-theme.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJButton } from "aj-button.slint";
import { AJIcon } from "aj-icon.slint";

export component AJDropdown inherits Rectangle {
    in property <[string]> variants;
    in property <bool> secondary;
    in-out property <int> current-index;

    property <bool> opened: false;

    width: self.preferred-width + 2 * AJTheme.fit-space;
    height: 30px;

    background: AJTheme.button;

    border-radius: AJTheme.border-radius;

    if opened: Rectangle {
        x: 0;
        y: parent.height + AJTheme.spacing;
        clip: true;

        width: min(list.preferred-width, 150px);
        height: min(list.preferred-height + 2 * AJTheme.padding, 150px);

        border-radius: AJTheme.border-radius;
        background: AJTheme.secondary-container;

        scroll := ScrollView {
            list := VerticalLayout {
                padding: AJTheme.padding;
                spacing: AJTheme.spacing;

                for variant[index] in variants: AJButton {
                    text: variant;
                    clicked => {
                        current-index = index;
                        opened = !opened;
                    }
                }
            }
        }

        Rectangle {
            visible: scroll.viewport-y < 0;
            x: 0;
            y: 0;
            width: parent.width;
            height: 24px;
            background: @linear-gradient(0deg, AJTheme.secondary-container.transparentize(100%), AJTheme.secondary-container.transparentize(0%));
        }

        Rectangle {
            visible: scroll.viewport-y + scroll.viewport-height > scroll.height;
            x: 0;
            y: parent.height - self.height;
            width: parent.width;
            height: 24px;
            background: @linear-gradient(180deg, AJTheme.secondary-container.transparentize(100%), AJTheme.secondary-container.transparentize(0%));
        }

        Rectangle {
            visible: scroll.viewport-x < 0;
            x: 0;
            y: 0;
            width: 24px;
            height: parent.height;
            background: @linear-gradient(-90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
        }

        Rectangle {
            visible: scroll.viewport-x + scroll.viewport-width > scroll.width;
            x: parent.width - self.width;
            y: 0;
            width: 24px;
            height: parent.height;
            background: @linear-gradient(90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
        }
    }

    AJButton {
        text: variants.length > 0 ? variants[current_index] : "–";

        background: secondary ? AJTheme.secondary-container : AJTheme.button;

        width: 100%;

        text-halign: left;

        AJIcon {
            source: opened ? @image-url("../../radix-icons/triangle-up.svg") : @image-url("../../radix-icons/triangle-down.svg");
            x: parent.width - self.width - AJTheme.fit-space;
            y: (parent.height - self.height) / 2;
        }

        clicked => {
            opened = !opened;
        }
    }
}
