import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJContestCallbacks } from "../aj-callbacks.slint";
import { AJLeaderboardRow } from "../models/contests.slint";
import { AJTotalVerdict } from "../models/testing.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJButton } from "aj-button.slint";
import { AJIcon } from "aj-icon.slint";

export component AJLeaderboard inherits Rectangle {
    property <int> problems-cnt: AJContestState.problems.length;
    property <[AJLeaderboardRow]> rows: AJContestState.leaderboard-rows;

    width: 715px;
    height: 420px;

    background: AJTheme.primary-container;

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "Таблица лидеров";
            type: AJTextType.Heading;
            color: AJTheme.container-text;
        }

        AJText {
            visible: rows.length == 0;
            text: "Таблица лидеров недоступна до конца контеста";
            type: AJTextType.Medium;
            font-italic: true;
            color: AJTheme.container-text;
        }

        Rectangle {
            visible: rows.length != 0;
            clip: true;
            border-radius: AJTheme.border-radius;

            scroll := ScrollView {
                GridLayout {
                    spacing: AJTheme.spacing;

                    Row {
                        AJText {
                            text: "#";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: "участник";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        for index in problems-cnt: AJText {
                            text: "\{index + 1}";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: "=";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }
                    }

                    for row[index] in rows: Row {
                        AJText {
                            text: index + 1;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJButton {
                            text: row.username;
                            background: AJTheme.secondary-container;
                            text-halign: right;

                            AJIcon {
                                source: @image-url("../../radix-icons/person.svg");
                                x: AJTheme.fit-space;
                                y: (parent.height - self.height) / 2;
                            }

                            clicked => {
                                AJContestCallbacks.open-profile(row.user-id)
                            }
                        }

                        for score in row.scores: AJText {
                            text: score;
                            font-weight: score == 100 ? AJTheme.font-weight-heading : AJTheme.font-weight-paragraph;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: row.total-score;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }
                    }
                }
            }

            Rectangle {
                visible: scroll.viewport-y < 0;
                x: 0;
                y: 0;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(0deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-y + scroll.viewport-height > scroll.height;
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(180deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x < 0;
                x: 0;
                y: 0;
                width: 64px;
                height: parent.height;
                background: @linear-gradient(-90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x + scroll.viewport-width > scroll.width;
                x: parent.width - self.width;
                y: 0;
                width: 64px;
                height: parent.height;
                background: @linear-gradient(90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }
        }
    }
}
