import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJSubmission, AJTotalVerdict } from "../models/testing.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJSubgroupCard } from "aj-subgroup-card.slint";
import { AJSubgroupResultCard } from "aj-subgroup-result-card.slint";
import { AJTestResultCard } from "aj-test-result-card.slint";
import { AJDropdown } from "aj-dropdown.slint";

export component AJSubmissionCard inherits Rectangle {
    property <AJSubmission> submission: AJContestState.submissions[AJContestState.current-submission-index];

    width: 355px;
    height: 304px;

    background: AJTheme.primary-container;

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "Посылка #\{AJContestState.submissions[AJContestState.current-submission-index].id}";
            color: AJTheme.container-text;
            type: AJTextType.Heading;
        }

        variant-dropdown := AJDropdown {
            z: 100;
            secondary: true;
            variants: ["подгруппы", "тесты"];
        }

        AJText {
            text: variant-dropdown.current-index == 0 ? "Результаты подгрупп" : "Результаты тестов";
            color: AJTheme.container-text;
            type: AJTextType.Medium;
        }

        Rectangle {
            clip: true;
            border-radius: AJTheme.border-radius;

            scroll := ScrollView {
                VerticalLayout {
                    spacing: AJTheme.spacing;

                    if variant-dropdown.current-index == 0: VerticalLayout {
                        spacing: AJTheme.spacing;

                        for subgroup-result[index] in submission.subgroups-results: AJSubgroupResultCard {
                            index: index;
                        }
                    }

                    if variant-dropdown.current-index == 1: VerticalLayout {
                        spacing: AJTheme.spacing;

                        for test-result[index] in submission.tests-results: AJTestResultCard {
                            index: index;
                        }
                    }
                }
            }

            Rectangle {
                visible: scroll.viewport-y < 0;
                x: 0;
                y: 0;
                width: parent.width;
                height: 24px;
                background: @linear-gradient(0deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-y + scroll.viewport-height > scroll.height;
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 24px;
                background: @linear-gradient(180deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x < 0;
                x: 0;
                y: 0;
                width: 24px;
                height: parent.height;
                background: @linear-gradient(-90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x + scroll.viewport-width > scroll.width;
                x: parent.width - self.width;
                y: 0;
                width: 24px;
                height: parent.height;
                background: @linear-gradient(90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }
        }
    }
}
