load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts_tag",
    srcs = glob(["**/*.rs"]),
    crate = "acts_tag",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acts-tag-derive/0.1.0:acts_tag_derive",
        "//third-party/rust/crates/acts-tag-value/0.1.0:acts_tag_value",
    ],
)
