load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adf",
    srcs = glob(["**/*.rs"]),
    crate = "adf",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quick-xml/0.38.4:quick_xml",
    ],
)
