load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_event_log_parser",
    srcs = glob(["**/*.rs"]),
    crate = "ad_event_log_parser",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/pest/2.8.8:pest",
        "//third-party/rust/crates/pest_derive/2.8.8:pest_derive",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
