load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpica",
    srcs = glob(["**/*.rs"]),
    crate = "acpica",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/spin/0.10.1:spin",
    ],
)
