load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts_channel",
    srcs = glob(["**/*.rs"]),
    crate = "acts_channel",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/prost-types/0.11.9:prost_types",
        "//third-party/rust/crates/prost/0.11.9:prost",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic/0.8.3:tonic",
    ],
)
