load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_astra",
    srcs = glob(["**/*.rs"]),
    crate = "ad_astra",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ad-astra-export/1.0.0:ad_astra_export",
        "//third-party/rust/crates/cast/0.3.0:cast",
        "//third-party/rust/crates/compact_str/0.7.1:compact_str",
        "//third-party/rust/crates/lady-deirdre/2.2.0:lady_deirdre",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/strsim/0.11.1:strsim",
    ],
)
