load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "absorb",
    srcs = glob(["**/*.rs"]),
    crate = "absorb",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.29.0:crossterm",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/ratatui/0.30.2:ratatui",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
