load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actrpc",
    srcs = glob(["**/*.rs"]),
    crate = "actrpc",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrpc-core/0.1.0:actrpc_core",
        "//third-party/rust/crates/actrpc-interceptor/0.1.0:actrpc_interceptor",
        "//third-party/rust/crates/actrpc-orchestrator/0.1.0:actrpc_orchestrator",
        "//third-party/rust/crates/actrpc-transport/0.1.0:actrpc_transport",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
