load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a_mutex",
    srcs = glob(["**/*.rs"]),
    crate = "a_mutex",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/auto_impl/1.3.0:auto_impl",
        "//third-party/rust/crates/bb8-redis/0.11.0:bb8_redis",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/redis/0.21.8:redis",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.0.0:tracing",
    ],
)
