load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_action",
    srcs = glob(["**/*.rs"]),
    crate = "adk_action",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/0.8.4:adk_core",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
