load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_ir",
    srcs = glob(["**/*.rs"]),
    crate = "adze_ir",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
