load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_form_data",
    srcs = glob(["**/*.rs"]),
    crate = "actix_form_data",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-multipart/0.6.2:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/streem/0.2.0:streem",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
