load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addresshashing",
    srcs = glob(["**/*.rs"]),
    crate = "addresshashing",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake2/0.10.6:blake2",
        "//third-party/rust/crates/digest/0.10.7:digest",
    ],
)
