Set Shell zsh
Set Theme "Catppuccin Frappe"
Set WindowBar "Rings"
Set BorderRadius 10
Set LoopOffset 85%
Set Margin 20

Sleep 3s
Type "cargo run --quiet --example fruit_market -- -- git https://github.com/GovCraft/acton-reactive"
Sleep 1.5s
Enter
Sleep 5s
Type "s"
Sleep 1s
Type "s"
Sleep 500ms
Type "s"
Sleep 500ms
Type "?"
Sleep 1.5s
Type "s"
Sleep 500ms
Type "ss"
Sleep 500ms
Type "?s"
Sleep 500ms
Type "s"
Sleep 15s
Type "q"
Sleep 1.5s
