load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acctl",
    srcs = glob(["**/*.rs"]),
    crate = "acctl",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/mechutil/0.7.5:mechutil",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-tungstenite/0.21.0:tokio_tungstenite",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/zip/2.4.2:zip",
    ],
)
