load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abitious_decmpfs",
    srcs = glob(["**/*.rs"]),
    crate = "abitious_decmpfs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/zstd/0.13.3:zstd",
    ],
)
