load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts_store_sqlite",
    srcs = glob(["**/*.rs"]),
    crate = "acts_store_sqlite",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acts/0.16.1:acts",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/r2d2/0.8.10:r2d2",
        "//third-party/rust/crates/r2d2_sqlite/0.25.0:r2d2_sqlite",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/sea-query-rusqlite/0.7.0:sea_query_rusqlite",
        "//third-party/rust/crates/sea-query/0.32.7:sea_query",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
