load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_hash",
    srcs = glob(["**/*.rs"]),
    crate = "actix_hash",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/digest/0.10.7:digest",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/local-channel/0.1.5:local_channel",
        "//third-party/rust/crates/subtle/2.6.1:subtle",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
