load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu_base",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu_base",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/awi/0.7.1:awi",
        "//third-party/rust/crates/cgmath/0.15.0:cgmath",
        "//third-party/rust/crates/euler/0.3.0:euler",
    ],
)
