load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_screen",
    srcs = glob(["**/*.rs"]),
    crate = "adi_screen",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aci_png/0.7.0:aci_png",
        "//third-party/rust/crates/adi_clock/0.3.0:adi_clock",
        "//third-party/rust/crates/adi_gpu/0.11.0:adi_gpu",
        "//third-party/rust/crates/fonterator/0.1.0:fonterator",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/palette/0.2.1:palette",
    ],
)
