load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acumen",
    srcs = glob(["**/*.rs"]),
    crate = "acumen",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rustix/0.38.44:rustix",
    ],
)
