load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adabraka_ui",
    srcs = glob(["**/*.rs"]),
    crate = "adabraka_ui",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/gpui/0.2.2:gpui",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/smol/2.0.2:smol",
        "//third-party/rust/crates/tree-sitter-sequel/0.3.11:tree_sitter_sequel",
        "//third-party/rust/crates/tree-sitter/0.25.10:tree_sitter",
        "//third-party/rust/crates/unicode-segmentation/1.13.3:unicode_segmentation",
    ],
)
