load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_request_hook",
    srcs = glob(["**/*.rs"]),
    crate = "actix_request_hook",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
    ],
)
