load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_disk_use",
    srcs = glob(["**/*.rs"]),
    crate = "acme_disk_use",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
