load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adequate",
    srcs = glob(["**/*.rs"]),
    crate = "adequate",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strfmt/0.2.5:strfmt",
    ],
)
