load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acr",
    srcs = glob(["**/*.rs"]),
    crate = "acr",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arboard/3.6.1:arboard",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/indicatif/0.18.6:indicatif",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/scraper/0.26.0:scraper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shlex/1.3.0:shlex",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
