load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adenosine_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adenosine_cli",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/atty/0.2.14:atty",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/colored_json/3.2.0:colored_json",
        "//third-party/rust/crates/data-encoding/2.11.1:data_encoding",
        "//third-party/rust/crates/dotenvy/0.15.7:dotenvy",
        "//third-party/rust/crates/env_logger/0.7.1:env_logger",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
        "//third-party/rust/crates/termcolor/1.4.1:termcolor",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
