load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa_derive",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/darling/0.9.0:darling",
        "//third-party/rust/crates/ident_case/1.0.1:ident_case",
        "//third-party/rust/crates/proc-macro2/0.4.30:proc_macro2",
        "//third-party/rust/crates/quote/0.6.13:quote",
        "//third-party/rust/crates/syn/0.15.44:syn",
        "//third-party/rust/crates/synstructure/0.10.2:synstructure",
    ],
)
