load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionable",
    srcs = glob(["**/*.rs"]),
    crate = "actionable",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionable-macros/0.1.1:actionable_macros",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
