load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adoc",
    srcs = glob(["**/*.rs"]),
    crate = "adoc",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/asciidoc-html5/0.1.4:asciidoc_html5",
        "//third-party/rust/crates/asciidoc-parser/0.29.19:asciidoc_parser",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/glob/0.3.4:glob",
    ],
)
