load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_smb",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_smb",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-ntlm/0.0.1:adhammer_ntlm",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
