load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_gemini",
    srcs = glob(["**/*.rs"]),
    crate = "adk_gemini",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/eventsource-stream/0.2.3:eventsource_stream",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/mime_guess/2.0.5:mime_guess",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/snafu/0.8.9:snafu",
        "//third-party/rust/crates/strum/0.28.0:strum",
        "//third-party/rust/crates/strum_macros/0.28.0:strum_macros",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
