load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adns_zone",
    srcs = glob(["**/*.rs"]),
    crate = "adns_zone",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adns-proto/0.1.0:adns_proto",
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_with/3.22.0:serde_with",
    ],
)
