import { AJTheme } from "../aj-theme.slint";
import { AJAppState, AJProblemsState, AJUserState } from "../aj-state.slint";
import { AJProblemsCallbacks, AJAppCallbacks } from "../aj-callbacks.slint";
import { AJAdminLevel } from "../models/users.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJDropdown } from "../components/aj-dropdown.slint";
import { AJProblemCard } from "../components/aj-problem-card.slint";
import { AJCheckbox } from "../components/aj-checkbox.slint";
import { AJIcon } from "../components/aj-icon.slint";

export component ProblemsPage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJButton {
            text: "назад";
            text-halign: right;

            AJIcon {
                source: @image-url("../../radix-icons/reset.svg");
                x: AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }
            clicked => {
                AJAppState.page = 3;
            }
        }

        HorizontalLayout {
            spacing: AJTheme.spacing;

            AJText {
                text: "Задачи";
                width: self.min-width;
                type: AJTextType.Heading;
            }

            AJButton {
                text: AJProblemsState.problem-picked ? "изменить задачу для добавления (\{AJProblemsState.problem-archive-name})" : "выбрать задачу для добавления";

                text-halign: left;

                AJIcon {
                    source: AJProblemsState.problem-picked ? @image-url("../../radix-icons/pencil-1.svg") : @image-url("../../radix-icons/upload.svg");
                    x: parent.width - self.width - AJTheme.fit-space;
                    y: (parent.height - self.height) / 2;
                }

                clicked => {
                    AJProblemsCallbacks.pick-problem-archive()
                }
            }

            AJButton {
                text: "создать";

                text-halign: left;

                AJIcon {
                    source: @image-url("../../radix-icons/plus.svg");
                    x: parent.width - self.width - AJTheme.fit-space;
                    y: (parent.height - self.height) / 2;
                }

                clicked => {
                    AJProblemsCallbacks.create-problem()
                }
            }
        }

        AJCheckbox {
            visible: AJUserState.user.admin-level == AJAdminLevel.Owner;
            text: "все задачи";
            value <=> AJProblemsState.all-problems;
            changed value => {
                AJAppCallbacks.reload()
            }
        }

        if AJProblemsState.problems.length == 0:
        AJText {
            text: "Задач пока что нет";
            type: AJTextType.Medium;
            font-italic: true;
        }

        if AJProblemsState.problems.length != 0:
        Rectangle {
            clip: true;
            border-radius: AJTheme.border-radius;
            height: 600px;

            scroll := ScrollView {
                VerticalLayout {
                    spacing: AJTheme.spacing;

                    for problem in AJProblemsState.problems: AJProblemCard {
                        show-id: true;
                        problem: problem;
                    }
                }
            }

            Rectangle {
                visible: scroll.viewport-y < 0;
                x: 0;
                y: 0;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(0deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-y + scroll.viewport-height > scroll.height;
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(180deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x < 0;
                x: 0;
                y: 0;
                width: 64px;
                height: parent.height;
                background: @linear-gradient(-90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }

            Rectangle {
                visible: scroll.viewport-x + scroll.viewport-width > scroll.width;
                x: parent.width - self.width;
                y: 0;
                width: 64px;
                height: parent.height;
                background: @linear-gradient(90deg, AJTheme.primary-container.transparentize(100%), AJTheme.primary-container.transparentize(0%));
            }
        }
    }
}
