load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actpub",
    srcs = glob(["**/*.rs"]),
    crate = "actpub",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actpub-activitystreams/0.2.3:actpub_activitystreams",
        "//third-party/rust/crates/actpub-core/0.2.3:actpub_core",
        "//third-party/rust/crates/actpub-httpsig/0.2.3:actpub_httpsig",
        "//third-party/rust/crates/actpub-nodeinfo/0.2.3:actpub_nodeinfo",
        "//third-party/rust/crates/actpub-webfinger/0.2.3:actpub_webfinger",
    ],
)
