stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: rust:latest
  artifacts:
    paths:
      - "target/"
  script:
    - cargo build --verbose
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cargo-test-job:
  stage: test
  image: rust:latest
  dependencies:
    - build-job
  script:
    - cargo test --verbose
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

cargo-clippy-job:
  stage: test
  image: rust:latest
  dependencies:
    - build-job
  script:
    - cargo clippy --verbose
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

cargo-merge-request-bump-job:
  stage: test
  image: rust:latest
  script:
    - chmod +x ./ci/check-version-bumped.bash
    - ./ci/check-version-bumped.bash
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

cargo-publish-job:
  stage: deploy
  image: rust:latest
  dependencies:
    - build-job
  script:
    - cargo publish --token $CRATES_IO_TOKEN --verbose
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
