load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acquery",
    srcs = glob(["**/*.rs"]),
    crate = "acquery",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aclneko/0.16.7:aclneko",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.16.4:console",
        "//third-party/rust/crates/nix/0.31.3:nix",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
