load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abrase_cli",
    srcs = glob(["**/*.rs"]),
    crate = "abrase_cli",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abrase/0.3.1:abrase",
        "//third-party/rust/crates/myriad-rs/0.3.1:myriad_rs",
        "//third-party/rust/crates/polka-rs/0.3.1:polka_rs",
        "//third-party/rust/crates/polka-rustc/0.3.1:polka_rustc",
    ],
)
