load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accrete",
    srcs = glob(["**/*.rs"]),
    crate = "accrete",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
