load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acrylic",
    srcs = glob(["**/*.rs"]),
    crate = "acrylic",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/png/0.17.16:png",
    ],
)
