load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_micro",
    srcs = glob(["**/*.rs"]),
    crate = "acme_micro",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
    ],
)
