[book]
title = "The Acuity Index Book"
authors = ["Jonathan Brown"]
language = "en"
src = "src"

[build]
build-dir = "../docs"

[output.html]
git-repository-url = "https://github.com/acuity-network/acuity-index"
default-theme = "navy"
preferred-dark-theme = "navy"
site-url = "/acuity-index/"
