load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity_vocabulary_derive",
    srcs = glob(["**/*.rs"]),
    crate = "activity_vocabulary_derive",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/maplit/1.0.2:maplit",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
