load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_4_jwt_auth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_4_jwt_auth",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/sanitize-filename/0.3.0:sanitize_filename",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
