load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable_derive/0.2.0:abi_stable_derive",
        "//third-party/rust/crates/abi_stable_derive_lib/0.2.0:abi_stable_derive_lib",
        "//third-party/rust/crates/core_extensions/0.1.20:core_extensions",
        "//third-party/rust/crates/generational-arena/0.2.9:generational_arena",
        "//third-party/rust/crates/libloading/0.5.2:libloading",
        "//third-party/rust/crates/lock_api/0.1.5:lock_api",
        "//third-party/rust/crates/parking_lot/0.7.1:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
    ],
)
