load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_httpauth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_httpauth",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
    ],
)
