load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_paging",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_paging",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
