load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aamva_parser_rs",
    srcs = glob(["**/*.rs"]),
    crate = "aamva_parser_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
