load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adev",
    srcs = glob(["**/*.rs"]),
    crate = "adev",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/androkit/0.2.0:androkit",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/inquire/0.6.2:inquire",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
