load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_use_ocr",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_use_ocr",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-use-core/0.2.2:a3s_use_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
