load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_tera_page",
    srcs = glob(["**/*.rs"]),
    crate = "actix_tera_page",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tera/1.20.1:tera",
    ],
)
