load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "address_formatter",
    srcs = glob(["**/*.rs"]),
    crate = "address_formatter",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/enum-map/1.1.1:enum_map",
        "//third-party/rust/crates/handlebars/4.5.0:handlebars",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/strum/0.23.0:strum",
        "//third-party/rust/crates/strum_macros/0.23.1:strum_macros",
        "//third-party/rust/crates/yaml-rust/0.4.5:yaml_rust",
    ],
)
