load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acp_hub",
    srcs = glob(["**/*.rs"]),
    crate = "acp_hub",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acp-hub-core/0.1.2:acp_hub_core",
        "//third-party/rust/crates/agent-client-protocol-conductor/0.15.1:agent_client_protocol_conductor",
        "//third-party/rust/crates/agent-client-protocol-http/0.1.1:agent_client_protocol_http",
        "//third-party/rust/crates/agent-client-protocol/0.15.1:agent_client_protocol",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rmcp/1.8.0:rmcp",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
