load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actiondb",
    srcs = glob(["**/*.rs"]),
    crate = "actiondb",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/serde/0.7.15:serde",
        "//third-party/rust/crates/serde_json/0.7.4:serde_json",
        "//third-party/rust/crates/serde_yaml/0.2.5:serde_yaml",
        "//third-party/rust/crates/uuid/0.1.18:uuid",
    ],
)
