load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adrop",
    srcs = glob(["**/*.rs"]),
    crate = "adrop",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
    ],
)
