load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absmartly_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "absmartly_sdk",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
