load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_csrf_middleware",
    srcs = glob(["**/*.rs"]),
    crate = "actix_csrf_middleware",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.13.0:hmac",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/subtle/2.6.1:subtle",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
