load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_tram_types",
    srcs = glob(["**/*.rs"]),
    crate = "ac_tram_types",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async_timing_util/0.1.14:async_timing_util",
        "//third-party/rust/crates/bson/2.15.0:bson",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/strum_macros/0.24.3:strum_macros",
    ],
)
