load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaclaw_security",
    srcs = glob(["**/*.rs"]),
    crate = "adaclaw_security",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adaclaw-core/0.1.0:adaclaw_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chacha20poly1305/0.10.1:chacha20poly1305",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/secrecy/0.8.0:secrecy",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
