load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_protobuf",
    srcs = glob(["**/*.rs"]),
    crate = "actix_protobuf",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/prost/0.5.0:prost",
    ],
)
