load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acknowledge",
    srcs = glob(["**/*.rs"]),
    crate = "acknowledge",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/cacache/13.1.0:cacache",
        "//third-party/rust/crates/cargo_toml/0.20.5:cargo_toml",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crates_io_api/0.11.0:crates_io_api",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/handlebars/5.1.2:handlebars",
        "//third-party/rust/crates/octocrab/0.38.0:octocrab",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.26.3:strum",
        "//third-party/rust/crates/strum_macros/0.26.4:strum_macros",
        "//third-party/rust/crates/tokio/1.35.0:tokio",
        "//third-party/rust/crates/unfmt/0.2.3:unfmt",
        "//third-party/rust/crates/unfmt_macros/0.2.3:unfmt_macros",
    ],
)
