load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminix",
    srcs = glob(["**/*.rs"]),
    crate = "adminix",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adminix_macro/0.0.1:adminix_macro",
    ],
)
