load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aduib_rpc",
    srcs = glob(["**/*.rs"]),
    crate = "aduib_rpc",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/memchr/2.8.3:memchr",
        "//third-party/rust/crates/prost-types/0.13.5:prost_types",
        "//third-party/rust/crates/prost/0.13.5:prost",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic/0.12.3:tonic",
    ],
)
