load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adrs",
    srcs = glob(["**/*.rs"]),
    crate = "adrs",
    crate_root = "src/main.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adrs-core/0.6.2:adrs_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/edit/0.1.5:edit",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/whoami/1.6.1:whoami",
    ],
)
