load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_browser",
    srcs = glob(["**/*.rs"]),
    crate = "adk_browser",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/1.0.0:adk_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thirtyfour/0.35.0:thirtyfour",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
