load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acct",
    srcs = glob(["**/*.rs"]),
    crate = "acct",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/users/0.8.1:users",
    ],
)
