load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_qu_ai_nt_core",
    srcs = glob(["**/*.rs"]),
    crate = "ac_qu_ai_nt_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cozo/0.7.6:cozo",
        "//third-party/rust/crates/llama-cpp-2/0.1.154:llama_cpp_2",
        "//third-party/rust/crates/ocrs/0.9.0:ocrs",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rten/0.13.1:rten",
        "//third-party/rust/crates/snafu/0.8.9:snafu",
    ],
)
