load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_provider",
    srcs = glob(["**/*.rs"]),
    crate = "acme_provider",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
