load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aba",
    srcs = glob(["**/*.rs"]),
    crate = "aba",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/mailparse/0.14.1:mailparse",
        "//third-party/rust/crates/miette/5.10.0:miette",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rust-fuzzy-search/0.1.1:rust_fuzzy_search",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
