load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_taos",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_taos",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adbc_core/0.21.0:adbc_core",
        "//third-party/rust/crates/arrow-array/57.3.1:arrow_array",
        "//third-party/rust/crates/arrow-schema/57.3.1:arrow_schema",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/deadpool/0.10.0:deadpool",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/taos/0.12.3:taos",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
