load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_utils",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advent-of-utils-macros/0.1.0:advent_of_utils_macros",
    ],
)
