load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acto",
    srcs = glob(["**/*.rs"]),
    crate = "acto",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/smol_str/0.1.24:smol_str",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
