use async_graphql::dynamic::*;

pub fn build_filter_primitives() -> Vec<InputObject> {
    vec![
        InputObject::new("IntFilter")
            .description("Filter conditions for integer fields")
            .field(InputValue::new("eq", TypeRef::named(TypeRef::INT)).description("Equal to"))
            .field(InputValue::new("ne", TypeRef::named(TypeRef::INT)).description("Not equal to"))
            .field(InputValue::new("gt", TypeRef::named(TypeRef::INT)).description("Greater than"))
            .field(InputValue::new("ge", TypeRef::named(TypeRef::INT)).description("Greater than or equal to"))
            .field(InputValue::new("lt", TypeRef::named(TypeRef::INT)).description("Less than"))
            .field(InputValue::new("le", TypeRef::named(TypeRef::INT)).description("Less than or equal to"))
            .field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::INT)).description("Matches any value in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::INT)).description("Does not match any value in the list"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("FloatFilter")
            .description("Filter conditions for floating-point fields")
            .field(InputValue::new("eq", TypeRef::named("StringOrNumber")).description("Equal to"))
            .field(InputValue::new("ne", TypeRef::named("StringOrNumber")).description("Not equal to"))
            .field(InputValue::new("gt", TypeRef::named("StringOrNumber")).description("Greater than"))
            .field(InputValue::new("ge", TypeRef::named("StringOrNumber")).description("Greater than or equal to"))
            .field(InputValue::new("lt", TypeRef::named("StringOrNumber")).description("Less than"))
            .field(InputValue::new("le", TypeRef::named("StringOrNumber")).description("Less than or equal to"))
            .field(InputValue::new("in", TypeRef::named_nn_list("StringOrNumber")).description("Matches any value in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list("StringOrNumber")).description("Does not match any value in the list"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("StringFilter")
            .description("Filter conditions for string fields")
            .field(InputValue::new("is", TypeRef::named(TypeRef::STRING)).description("Exact match"))
            .field(InputValue::new("not", TypeRef::named(TypeRef::STRING)).description("Not equal to"))
            .field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::STRING)).description("Matches any value in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::STRING)).description("Does not match any value in the list"))
            .field(InputValue::new("like", TypeRef::named(TypeRef::STRING)).description("SQL LIKE pattern match (use % as wildcard)"))
            .field(InputValue::new("notLike", TypeRef::named(TypeRef::STRING)).description("SQL NOT LIKE pattern match"))
            .field(InputValue::new("includes", TypeRef::named(TypeRef::STRING)).description("Contains substring (case-sensitive)"))
            .field(InputValue::new("notIncludes", TypeRef::named(TypeRef::STRING)).description("Does not contain substring (case-sensitive)"))
            .field(InputValue::new("startsWith", TypeRef::named(TypeRef::STRING)).description("Starts with prefix (case-sensitive)"))
            .field(InputValue::new("endsWith", TypeRef::named(TypeRef::STRING)).description("Ends with suffix (case-sensitive)"))
            .field(InputValue::new("likeCaseInsensitive", TypeRef::named(TypeRef::STRING)).description("SQL ILIKE pattern match (case-insensitive)"))
            .field(InputValue::new("notLikeCaseInsensitive", TypeRef::named(TypeRef::STRING)).description("SQL NOT ILIKE pattern match (case-insensitive)"))
            .field(InputValue::new("includesCaseInsensitive", TypeRef::named(TypeRef::STRING)).description("Contains substring (case-insensitive)"))
            .field(InputValue::new("notIncludesCaseInsensitive", TypeRef::named(TypeRef::STRING)).description("Does not contain substring (case-insensitive)"))
            .field(InputValue::new("startsWithCaseInsensitive", TypeRef::named(TypeRef::STRING)).description("Starts with prefix (case-insensitive)"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("RelativeTimeInput")
            .description("Relative time offset from now. Specify one field.")
            .field(InputValue::new("minutes_ago", TypeRef::named(TypeRef::INT)).description("Minutes ago from now"))
            .field(InputValue::new("hours_ago", TypeRef::named(TypeRef::INT)).description("Hours ago from now"))
            .field(InputValue::new("days_ago", TypeRef::named(TypeRef::INT)).description("Days ago from now")),
        InputObject::new("DateTimeFilter")
            .description("Filter conditions for datetime fields. Values accept ISO 8601 format.")
            .field(InputValue::new("is", TypeRef::named("DateTime")).description("Exact datetime match"))
            .field(InputValue::new("not", TypeRef::named("DateTime")).description("Not equal to"))
            .field(InputValue::new("after", TypeRef::named("DateTime")).description("Strictly after (>)"))
            .field(InputValue::new("before", TypeRef::named("DateTime")).description("Strictly before (<)"))
            .field(InputValue::new("since", TypeRef::named("DateTime")).description("On or after (>=)"))
            .field(InputValue::new("till", TypeRef::named("DateTime")).description("On or before (<=)"))
            .field(InputValue::new("in", TypeRef::named_nn_list("DateTime")).description("Matches any datetime in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list("DateTime")).description("Does not match any datetime in the list"))
            .field(InputValue::new("since_relative", TypeRef::named("RelativeTimeInput")).description("On or after a relative time (e.g. {hours_ago: 24})"))
            .field(InputValue::new("till_relative", TypeRef::named("RelativeTimeInput")).description("On or before a relative time"))
            .field(InputValue::new("after_relative", TypeRef::named("RelativeTimeInput")).description("Strictly after a relative time"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("DateFilter")
            .description("Filter conditions for date fields. Values accept YYYY-MM-DD format.")
            .field(InputValue::new("is", TypeRef::named("DateTime")).description("Exact date match"))
            .field(InputValue::new("not", TypeRef::named("DateTime")).description("Not equal to"))
            .field(InputValue::new("after", TypeRef::named("DateTime")).description("Strictly after (>)"))
            .field(InputValue::new("before", TypeRef::named("DateTime")).description("Strictly before (<)"))
            .field(InputValue::new("since", TypeRef::named("DateTime")).description("On or after (>=)"))
            .field(InputValue::new("till", TypeRef::named("DateTime")).description("On or before (<=)"))
            .field(InputValue::new("in", TypeRef::named_nn_list("DateTime")).description("Matches any date in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list("DateTime")).description("Does not match any date in the list"))
            .field(InputValue::new("since_relative", TypeRef::named("RelativeTimeInput")).description("On or after a relative time"))
            .field(InputValue::new("till_relative", TypeRef::named("RelativeTimeInput")).description("On or before a relative time"))
            .field(InputValue::new("after_relative", TypeRef::named("RelativeTimeInput")).description("Strictly after a relative time"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("BoolFilter")
            .description("Filter conditions for boolean fields")
            .field(InputValue::new("eq", TypeRef::named(TypeRef::BOOLEAN)).description("Equal to"))
            .field(InputValue::new("is", TypeRef::named(TypeRef::BOOLEAN)).description("Equal to (Bitquery-compatible alias for eq)"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("DecimalFilter")
            .description("Filter conditions for high-precision decimal fields (values passed as strings to preserve precision)")
            .field(InputValue::new("eq", TypeRef::named(TypeRef::STRING)).description("Equal to"))
            .field(InputValue::new("ne", TypeRef::named(TypeRef::STRING)).description("Not equal to"))
            .field(InputValue::new("gt", TypeRef::named(TypeRef::STRING)).description("Greater than"))
            .field(InputValue::new("ge", TypeRef::named(TypeRef::STRING)).description("Greater than or equal to"))
            .field(InputValue::new("lt", TypeRef::named(TypeRef::STRING)).description("Less than"))
            .field(InputValue::new("le", TypeRef::named(TypeRef::STRING)).description("Less than or equal to"))
            .field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::STRING)).description("Matches any value in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::STRING)).description("Does not match any value in the list"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
        InputObject::new("BigIntFilter")
            .description("Filter conditions for arbitrary-precision integer fields (Bitquery OLAP_BigInteger). Values are strings to preserve precision beyond i64/f64 range.")
            .field(InputValue::new("eq", TypeRef::named(TypeRef::STRING)).description("Equal to"))
            .field(InputValue::new("ne", TypeRef::named(TypeRef::STRING)).description("Not equal to"))
            .field(InputValue::new("gt", TypeRef::named(TypeRef::STRING)).description("Greater than"))
            .field(InputValue::new("ge", TypeRef::named(TypeRef::STRING)).description("Greater than or equal to"))
            .field(InputValue::new("lt", TypeRef::named(TypeRef::STRING)).description("Less than"))
            .field(InputValue::new("le", TypeRef::named(TypeRef::STRING)).description("Less than or equal to"))
            .field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::STRING)).description("Matches any value in the list"))
            .field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::STRING)).description("Does not match any value in the list"))
            .field(InputValue::new("is", TypeRef::named(TypeRef::STRING)).description("Exact match (Bitquery-compatible alias for eq)"))
            .field(InputValue::new("not", TypeRef::named(TypeRef::STRING)).description("Not equal to (Bitquery-compatible alias for ne)"))
            .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL")),
    ]
}

pub fn build_enum_filter(enum_name: &str) -> InputObject {
    let filter_name = format!("{enum_name}Filter");
    InputObject::new(&filter_name)
        .description(format!("Filter conditions for {enum_name} enum values"))
        .field(InputValue::new("is", TypeRef::named(enum_name)).description("Exact match"))
        .field(InputValue::new("not", TypeRef::named(enum_name)).description("Not equal to"))
        .field(InputValue::new("in", TypeRef::named_nn_list(enum_name)).description("Matches any value in the list"))
        .field(InputValue::new("notIn", TypeRef::named_nn_list(enum_name)).description("Does not match any value in the list"))
        .field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)).description("True to match NULL, false to match non-NULL"))
}

pub fn build_limit_input() -> InputObject {
    InputObject::new("LimitInput")
        .description("Pagination control for query results")
        .field(InputValue::new("count", TypeRef::named(TypeRef::INT)).description("Maximum number of records to return"))
        .field(InputValue::new("offset", TypeRef::named(TypeRef::INT)).description("Number of records to skip"))
}
