import { AJTheme } from "../aj-theme.slint";
import { AJText } from "aj-text.slint";

export component AJButton inherits Rectangle {
    in property <string> text;
    in property <bool> align-left;

    in property <brush> text-color: AJTheme.button-text;

    callback clicked();

    width: self.min-width + AJTheme.fit-space;
    height: 30px;
    transform-scale: touch-area.has-hover ? AJTheme.hovered-scale : 100%;

    background: AJTheme.button;

    border-radius: AJTheme.border-radius;

    touch-area := TouchArea {
        width: parent.width;
        height: parent.height;

        clicked => {
            clicked()
        }
    }

    HorizontalLayout {
        padding-left: align-left ? AJTheme.fit-space: 0px;
        padding-right: align-left ? AJTheme.fit-space: 0px;

        AJText {
            text: text;
            horizontal-alignment: align-left ? left : center;
            vertical-alignment: center;
            color: text-color;
        }

        @children
    }

    animate transform-scale {
        duration: AJTheme.animation-duration-short;
        easing: ease-in-out;
    }
}
