import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJContest, AJContestStatus } from "../models/contests.slint";
import { AJHomeCallbacks, AJAppCallbacks } from "../aj-callbacks.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJDateTimeText } from "aj-datetime-text.slint";
import { AJInput, AJInputType } from "aj-input.slint";
import { AJDateTimeInput } from "aj-datetime-input.slint";
import { AJButton } from "aj-button.slint";
import { AJCheckbox } from "aj-checkbox.slint";

export component AJContestCard inherits Rectangle {
    in property <int> index;
    in property <bool> show-enter-button;

    property <AJContest> contest: AJAppState.contests[index];

    width: self.min-width + AJTheme.fit-space;
    height: 200px;

    background: {
        if contest.status == AJContestStatus.BeforeStart {
            AJTheme.contest-before-start
        } else if contest.status == AJContestStatus.Ongoing {
            AJTheme.contest-ongoing
        } else if contest.status == AJContestStatus.Finished {
            AJTheme.contest-finished
        } else {
            AJTheme.contest-upsolving
        }
    };

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        alignment: start;
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        HorizontalLayout {
            AJText {
                text: "#\{contest.id} \{contest.name}";
                type: AJTextType.Heading;
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: {
                    if contest.status == AJContestStatus.BeforeStart {
                        AJTheme.contest-before-start-text
                    } else if contest.status == AJContestStatus.Ongoing {
                        AJTheme.contest-ongoing-text
                    } else if contest.status == AJContestStatus.Finished {
                        AJTheme.contest-finished-text
                    } else {
                        AJTheme.contest-upsolving-text;
                    }
                }
            }

            AJText {
                text: {
                    if contest.status == AJContestStatus.BeforeStart {
                        "не начался"
                    } else if contest.status == AJContestStatus.Ongoing {
                        "идёт"
                    } else if contest.status == AJContestStatus.Finished {
                        "завершён"
                    } else {
                        "дорешка"
                    }
                };
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: AJTheme.contest-status-text;
            }
        }

        if !contest.statements-url.is-empty || !contest.editorial-url.is-empty:
        HorizontalLayout {
            spacing: AJTheme.spacing;

            if !contest.statements-url.is-empty:
            AJButton {
                text: "условия задач";
                background: {
                    if contest.status == AJContestStatus.Finished {
                        AJTheme.secondary-container
                    } else {
                        AJTheme.button
                    }
                };
                clicked => {
                    AJAppCallbacks.open-link(contest.statements-url)
                }
            }

            if !contest.editorial-url.is-empty:
            AJButton {
                text: "разбор задач";
                background: {
                    if contest.status == AJContestStatus.Finished {
                        AJTheme.secondary-container
                    } else {
                        AJTheme.button
                    }
                };
                clicked => {
                    AJAppCallbacks.open-link(contest.editorial-url)
                }
            }
        }

        HorizontalLayout {
            AJText {
                text: "начало в";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: {
                    if contest.status == AJContestStatus.BeforeStart {
                        AJTheme.contest-before-start-text
                    } else if contest.status == AJContestStatus.Ongoing {
                        AJTheme.contest-ongoing-text
                    } else if contest.status == AJContestStatus.Finished {
                        AJTheme.contest-finished-text
                    } else {
                        AJTheme.contest-upsolving-text;
                    }
                }
            }

            AJDateTimeText {
                date-time: contest.starts-at;
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: {
                    if contest.status == AJContestStatus.BeforeStart {
                        AJTheme.contest-before-start-text
                    } else if contest.status == AJContestStatus.Ongoing {
                        AJTheme.contest-ongoing-text
                    } else if contest.status == AJContestStatus.Finished {
                        AJTheme.contest-finished-text
                    } else {
                        AJTheme.contest-upsolving-text;
                    }
                }
            }
        }

        HorizontalLayout {
            AJText {
                text: "конец в";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: {
                    if contest.status == AJContestStatus.BeforeStart {
                        AJTheme.contest-before-start-text
                    } else if contest.status == AJContestStatus.Ongoing {
                        AJTheme.contest-ongoing-text
                    } else if contest.status == AJContestStatus.Finished {
                        AJTheme.contest-finished-text
                    } else {
                        AJTheme.contest-upsolving-text;
                    }
                }
            }

            AJDateTimeText {
                date-time: contest.ends-at;
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: {
                    if contest.status == AJContestStatus.BeforeStart {
                        AJTheme.contest-before-start-text
                    } else if contest.status == AJContestStatus.Ongoing {
                        AJTheme.contest-ongoing-text
                    } else if contest.status == AJContestStatus.Finished {
                        AJTheme.contest-finished-text
                    } else {
                        AJTheme.contest-upsolving-text;
                    }
                }
            }
        }

        HorizontalLayout {
            visible: (contest.status != AJContestStatus.BeforeStart || contest.can-manage) && show-enter-button;
            spacing: AJTheme.spacing;

            AJButton {
                text: "войти >>";
                background: transparent;
                clicked => {
                    AJHomeCallbacks.enter-contest(index);
                }
            }

            edit-contest-popup := PopupWindow {
                close-policy: PopupClosePolicy.close-on-click-outside;

                function close-popup() {
                    self.close()
                }

                Rectangle {
                    background: AJTheme.secondary-container;

                    border-radius: AJTheme.border-radius;

                    VerticalLayout {
                        padding: AJTheme.padding;
                        spacing: AJTheme.spacing;

                        name := AJInput {
                            text: contest.name;
                            placeholder: "название";
                        }

                        AJText {
                            text: "начало в";
                            color: AJTheme.container-text;
                        }

                        starts-at := AJDateTimeInput {
                            default-date-time: contest.starts-at;
                        }

                        AJText {
                            text: "конец в";
                            color: AJTheme.container-text;
                        }

                        ends-at := AJDateTimeInput {
                            default-date-time: contest.ends-at;
                        }

                        statements-url := AJInput {
                            text: contest.statements-url;
                            placeholder: "ссылка на условия";
                        }

                        editorial-url := AJInput {
                            text: contest.editorial-url;
                            placeholder: "ссылка на разбор";
                        }

                        hidden := AJCheckbox {
                            value: contest.hidden;
                            text: "скрыть";
                        }

                        upsolving-opened := AJCheckbox {
                            value: contest.upsolving-opened;
                            text: "открыть дорешку";
                        }

                        hide-solutions := AJCheckbox {
                            value: contest.hide-solutions;
                            text: "скрыть решения";
                        }

                        AJButton {
                            text: "изменить //";
                            clicked => {
                                AJHomeCallbacks.update-contest(contest.id, name.text, starts-at.date-time, ends-at.date-time, statements-url.text, editorial-url.text, hidden.value, upsolving-opened.value, hide-solutions.value)
                            }
                        }

                        AJButton {
                            text: "<< отменить";
                            clicked => {
                                close-popup()
                            }
                        }
                    }
                }
            }

            AJButton {
                visible: contest.can-manage;
                text: "изменить //";
                background: transparent;
                clicked => {
                    edit_contest_popup.show()
                }
            }

            delete-contest-popup := PopupWindow {
                close-policy: PopupClosePolicy.close-on-click-outside;

                function close-popup() {
                    self.close()
                }

                Rectangle {
                    background: AJTheme.secondary-container;

                    border-radius: AJTheme.border-radius;

                    VerticalLayout {
                        padding: AJTheme.padding;
                        spacing: AJTheme.spacing;

                        AJText {
                            text: "Требуется рут-доступ";
                            type: AJTextType.Medium;
                            color: AJTheme.container-text;
                        }

                        login := AJInput {
                            placeholder: "логин";
                        }

                        password := AJInput {
                            placeholder: "пароль";
                            type: AJInputType.Password;
                        }

                        password-confirmation := AJInput {
                            placeholder: "подтвердите пароль";
                            type: AJInputType.Password;
                        }

                        deletion-confirmation := AJCheckbox {
                            text: "подтвердите удаление";
                        }

                        AJButton {
                            text: "удалить \\\\";
                            clicked => {
                                AJHomeCallbacks.delete-contest(contest.id, login.text, password.text, password-confirmation.text, deletion-confirmation.value)
                            }
                        }

                        AJButton {
                            text: "<< отменить";
                            clicked => {
                                close-popup()
                            }
                        }
                    }
                }
            }

            AJButton {
                visible: contest.can-manage;
                text: "удалить \\\\";
                background: transparent;

                clicked => {
                    delete-contest-popup.show()
                }
            }
        }
    }
}
