import { AJTheme } from "../aj-theme.slint";
import { AJText } from "aj-text.slint";
import { AJButton } from "aj-button.slint";

export component AJCheckbox inherits HorizontalLayout {
    in property <string> text;
    in-out property <bool> value;

    spacing: AJTheme.spacing;

    AJButton {
        align-left: true;

        text: text;

        text-color: value ? AJTheme.contest-ongoing-text : AJTheme.error-text;

        background: value ? AJTheme.contest-ongoing : AJTheme.contest-before-start;

        AJText {
            text: value ? "✓" : "✗";

            horizontal-alignment: right;
            vertical-alignment: center;

            color: value ? AJTheme.contest-ongoing-text : AJTheme.error-text;
        }

        clicked => {
            value = !value;
        }
    }
}
