import { AJTheme } from "../aj-theme.slint";
import { ListView, ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJButton } from "aj-button.slint";

export component AJDropdown inherits Rectangle {
    in property <[string]> variants;
    in property <bool> secondary;
    in-out property <int> current-index;

    property <bool> opened: false;

    width: self.preferred-width + AJTheme.fit-space;
    height: 30px;

    background: AJTheme.button;

    border-radius: AJTheme.border-radius;

    if opened: Rectangle {
        x: 0;
        y: parent.height + AJTheme.spacing;
        clip: true;

        width: max(root.width, 100px);
        height: max(list.preferred-height + 2 * AJTheme.padding, 100px);

        border-radius: AJTheme.border-radius;
        background: AJTheme.secondary-container;

        ScrollView {
            list := VerticalLayout {
                padding: AJTheme.padding;
                spacing: AJTheme.spacing;

                for variant[index] in variants: AJButton {
                    text: variant;
                    clicked => {
                        current-index = index;
                        opened = !opened;
                    }
                }
            }
        }

        Rectangle {
            x: 0;
            y: parent.height - self.height;
            width: parent.width;
            height: 64px;
            background: @linear-gradient(180deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(50%));
        }
    }

    AJButton {
        align-left: true;

        text: variants.length > 0 ? variants[current_index] : "–";

        background: secondary ? AJTheme.secondary-container : AJTheme.button;

        width: 100%;

        AJText {
            text: opened ? "▲" : "▼";

            horizontal-alignment: right;
            vertical-alignment: center;

            color: AJTheme.button-text;
        }

        clicked => {
            opened = !opened;
        }
    }
}
