import { AJTheme } from "../aj-theme.slint";
import { AJText, AJTextType } from "aj-text.slint";
import "../../fonts/JetBrainsMono-2.304/fonts/variable/JetBrainsMono[wght].ttf";
import "../../fonts/JetBrainsMono-2.304/fonts/variable/JetBrainsMono-Italic[wght].ttf";

export enum AJInputType {
    Text,
    Password,
    Int,
}

export component AJInput inherits Rectangle {
    in property <AJInputType> type;
    in property <string> placeholder;
    in-out property <string> text;

    width: self.preferred-width + AJTheme.fit-space;
    height: 30px;
    clip: true;

    background: AJTheme.button;

    border-radius: AJTheme.border-radius;

    flick := Flickable {
        width: 100%;
        height: 100%;
        viewport-width: max(self.width, input.preferred-width);
        interactive: true;

        input := TextInput {
            width: max(parent.width, self.preferred-width);
            height: 100%;
            input-type: {
                if type == AJInputType.Text {
                    InputType.text
                } else if type == AJInputType.Password {
                    InputType.password
                } else {
                    InputType.number
                }
            };
            text <=> text;
            font-family: "JetBrains Mono";
            font-size: AJTheme.font-size-paragraph;
            horizontal-alignment: center;
            vertical-alignment: center;
            color: AJTheme.button-text;

            cursor-position-changed(position) => {
                if position.x + flick.viewport-x < 0 {
                    flick.viewport-x= -position.x;
                } else if position.x + flick.viewport-x > flick.width - self.text-cursor-width {
                    flick.viewport-x = flick.width - self.text-cursor-width - position.x;
                }
            }
        }
    }

    AJText {
        width: 100%;
        height: 100%;
        visible: text.is-empty;
        text: placeholder;
        font-italic: true;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: AJTheme.button-text;
    }
}
