load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adjust",
    srcs = glob(["**/*.rs"]),
    crate = "adjust",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adjust_macro/0.1.3:adjust_macro",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/diesel/2.3.12:diesel",
        "//third-party/rust/crates/dotenv/0.15.0:dotenv",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis/0.28.2:redis",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
