load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_editor",
    srcs = glob(["**/*.rs"]),
    crate = "ad_editor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ad_event/0.2.0:ad_event",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/ninep/0.2.2:ninep",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/unicode-width/0.2.2:unicode_width",
    ],
)
