load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accept_header",
    srcs = glob(["**/*.rs"]),
    crate = "accept_header",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/snafu/0.7.5:snafu",
    ],
)
