load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_server_config",
    srcs = glob(["**/*.rs"]),
    crate = "actix_server_config",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.1.31:futures",
    ],
)
