load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable_shared",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable_shared",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/core_extensions/0.1.20:core_extensions",
    ],
)
