load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acap",
    srcs = glob(["**/*.rs"]),
    crate = "acap",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rand/0.7.3:rand",
    ],
)
