load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actpub_core",
    srcs = glob(["**/*.rs"]),
    crate = "actpub_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actpub-activitystreams/0.2.3:actpub_activitystreams",
        "//third-party/rust/crates/actpub-httpsig/0.2.3:actpub_httpsig",
        "//third-party/rust/crates/aws-lc-rs/1.18.0:aws_lc_rs",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/multibase/0.9.3:multibase",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_jcs/0.2.0:serde_jcs",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
