load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_sandbox",
    srcs = glob(["**/*.rs"]),
    crate = "aa_sandbox",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/wasmtime-wasi/46.0.2:wasmtime_wasi",
        "//third-party/rust/crates/wasmtime/46.0.2:wasmtime",
    ],
)
