load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_tls",
    srcs = glob(["**/*.rs"]),
    crate = "actix_tls",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.3.0:actix_codec",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-utils/2.0.0:actix_utils",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
    ],
)
