load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abcperf_generic_client",
    srcs = glob(["**/*.rs"]),
    crate = "abcperf_generic_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abcperf/0.10.0:abcperf",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-channel/1.9.0:async_channel",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derivative/2.2.0:derivative",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/quinn/0.10.2:quinn",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/rustls/0.21.12:rustls",
        "//third-party/rust/crates/s2n-quic/1.86.0:s2n_quic",
        "//third-party/rust/crates/serde-bytes-repr/0.1.5:serde_bytes_repr",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shared-ids/0.10.0:shared_ids",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/warp/0.3.7:warp",
    ],
)
