load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admiral",
    srcs = glob(["**/*.rs"]),
    crate = "admiral",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/admiral-derive/0.1.0:admiral_derive",
        "//third-party/rust/crates/admiral-types/0.1.0:admiral_types",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/rustc-test/0.3.1:rustc_test",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
