load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_block_ai_crawling",
    srcs = glob(["**/*.rs"]),
    crate = "actix_block_ai_crawling",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/ipnet/2.12.1:ipnet",
        "//third-party/rust/crates/iprange/0.6.7:iprange",
    ],
)
