load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adler",
    srcs = glob(["**/*.rs"]),
    crate = "adler",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adler-core/0.15.1:adler_core",
        "//third-party/rust/crates/adler-mcp/0.15.1:adler_mcp",
        "//third-party/rust/crates/adler-server/0.15.1:adler_server",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/clap_mangen/0.3.2:clap_mangen",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/indicatif/0.18.6:indicatif",
        "//third-party/rust/crates/open/5.4.1:open",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/secrecy/0.10.3:secrecy",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
