load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aam_rs",
    srcs = glob(["**/*.rs"]),
    crate = "aam_rs",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aam-core/2.9.0:aam_core",
        "//third-party/rust/crates/aam-derive/2.9.0:aam_derive",
    ],
)
