load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_server_config",
    srcs = glob(["**/*.rs"]),
    crate = "actix_server_config",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
    ],
)
