load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad1_forensic",
    srcs = glob(["**/*.rs"]),
    crate = "ad1_forensic",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ad1-core/0.1.2:ad1_core",
        "//third-party/rust/crates/forensicnomicon/1.11.1:forensicnomicon",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
