load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_lib",
    srcs = glob(["**/*.rs"]),
    crate = "act_lib",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/swc_common/0.33.26:swc_common",
        "//third-party/rust/crates/swc_ecma_ast/0.112.8:swc_ecma_ast",
        "//third-party/rust/crates/swc_ecma_parser/0.143.16:swc_ecma_parser",
    ],
)
