load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advanced_string_generator",
    srcs = glob(["**/*.rs"]),
    crate = "advanced_string_generator",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
