load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_zero_ext",
    srcs = glob(["**/*.rs"]),
    crate = "act_zero_ext",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-zero/0.4.0:act_zero",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
