load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "rust_lib1",
    srcs = glob(["**/*.rs"]),
    crate = "rust_lib1",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
