load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ARGenus",
    srcs = glob(["**/*.rs"]),
    crate = "ARGenus",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bzip2/0.5.2:bzip2",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/extsort-iter/0.3.1:extsort_iter",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
        "//third-party/rust/crates/zip/2.4.2:zip",
        "//third-party/rust/crates/zstd/0.13.3:zstd",
    ],
)
