load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adn",
    srcs = glob(["**/*.rs"]),
    crate = "adn",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/toml_edit/0.22.27:toml_edit",
    ],
)
