load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acidalia",
    srcs = glob(["**/*.rs"]),
    crate = "acidalia",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acidalia_core/0.1.0:acidalia_core",
        "//third-party/rust/crates/acidalia_proc_macros/0.1.0:acidalia_proc_macros",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/crossbeam-channel/0.4.4:crossbeam_channel",
        "//third-party/rust/crates/dashmap/4.0.2:dashmap",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/imgui-wgpu/0.14.0:imgui_wgpu",
        "//third-party/rust/crates/imgui-winit-support/0.7.1:imgui_winit_support",
        "//third-party/rust/crates/imgui/0.7.0:imgui",
        "//third-party/rust/crates/shaderc/0.7.4:shaderc",
        "//third-party/rust/crates/wgpu/0.7.1:wgpu",
        "//third-party/rust/crates/winit/0.24.0:winit",
    ],
)
