load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_casbin_auth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_casbin_auth",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/casbin/0.8.5:casbin",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
