load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acute_app",
    srcs = glob(["**/*.rs"]),
    crate = "acute_app",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acute_core/0.1.1:acute_core",
        "//third-party/rust/crates/acute_ecs/0.1.0:acute_ecs",
        "//third-party/rust/crates/acute_scenes/0.1.0:acute_scenes",
        "//third-party/rust/crates/acute_window/0.1.1:acute_window",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
