load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "address_translation",
    srcs = glob(["**/*.rs"]),
    crate = "address_translation",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ipnet/2.12.1:ipnet",
    ],
)
