load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adler32_checksum_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adler32_checksum_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/criterion/0.4.0:criterion",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
