load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr",
    srcs = glob(["**/*.rs"]),
    crate = "addr",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/psl-types/2.0.11:psl_types",
    ],
)
