load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adx",
    srcs = glob(["**/*.rs"]),
    crate = "adx",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/color-eyre/0.6.5:color_eyre",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/roxmltree/0.18.1:roxmltree",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
