load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_integers",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_integers",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num/0.2.1:num",
    ],
)
