load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi_gpu_base/0.2.0:adi_gpu_base",
        "//third-party/rust/crates/adi_gpu_opengl/0.1.0:adi_gpu_opengl",
        "//third-party/rust/crates/adi_gpu_vulkan/0.2.0:adi_gpu_vulkan",
        "//third-party/rust/crates/afi/0.3.2:afi",
        "//third-party/rust/crates/ami/0.6.0:ami",
    ],
)
