load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acto_rs",
    srcs = glob(["**/*.rs"]),
    crate = "acto_rs",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/lossyq/0.1.19:lossyq",
        "//third-party/rust/crates/parking_lot/0.2.8:parking_lot",
        "//third-party/rust/crates/time/0.1.45:time",
    ],
)
