load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abackus",
    srcs = glob(["**/*.rs"]),
    crate = "abackus",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/earlgrey/0.2.4:earlgrey",
        "//third-party/rust/crates/lexers/0.0.6:lexers",
    ],
)
