load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activities",
    srcs = glob(["**/*.rs"]),
    crate = "activities",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_builder/0.9.0:derive_builder",
        "//third-party/rust/crates/isolang/1.0.0:isolang",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/typetag/0.1.8:typetag",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
