load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actors",
    srcs = glob(["**/*.rs"]),
    crate = "actors",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
