load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_script_core",
    srcs = glob(["**/*.rs"]),
    crate = "adana_script_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
