load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad9361_rs",
    srcs = glob(["**/*.rs"]),
    crate = "ad9361_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cpp/0.5.11:cpp",
        "//third-party/rust/crates/cty/0.2.2:cty",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/managed/0.8.0:managed",
        "//third-party/rust/crates/paste/1.0.15:paste",
    ],
)
