load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_pipeline_bootstrap",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_pipeline_bootstrap",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
