load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abortable_parser",
    srcs = glob(["**/*.rs"]),
    crate = "abortable_parser",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
