load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acid_rain",
    srcs = glob(["**/*.rs"]),
    crate = "acid_rain",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.27.0:crossterm",
        "//third-party/rust/crates/ezemoji/0.2.1:ezemoji",
        "//third-party/rust/crates/itertools/0.12.1:itertools",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
