load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ABC_Game_Engine",
    srcs = glob(["**/*.rs"]),
    crate = "ABC_Game_Engine",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ABC-ECS/0.2.1:ABC_ECS",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/fxhash/0.2.1:fxhash",
        "//third-party/rust/crates/gilrs/0.10.10:gilrs",
        "//third-party/rust/crates/glam/0.27.0:glam",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rapier2d/0.19.0:rapier2d",
        "//third-party/rust/crates/rodio/0.17.3:rodio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
