load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_security_core",
    srcs = glob(["**/*.rs"]),
    crate = "actix_security_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/derive_more/1.0.0:derive_more",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
