load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori_cors",
    srcs = glob(["**/*.rs"]),
    crate = "actori_cors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-service/1.0.5:actori_service",
        "//third-party/rust/crates/actori-web/2.0.0:actori_web",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
