load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "Alice_Database_DBMS",
    srcs = glob(["**/*.rs"]),
    crate = "Alice_Database_DBMS",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/simplelog/0.12.2:simplelog",
    ],
)
