load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abol_codegen",
    srcs = glob(["**/*.rs"]),
    crate = "abol_codegen",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abol-core/0.1.0:abol_core",
        "//third-party/rust/crates/abol-parser/0.1.0:abol_parser",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/heck/0.5.0:heck",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
    ],
)
