load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_tombstone",
    srcs = glob(["**/*.rs"]),
    crate = "ad_tombstone",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ad-secdesc/0.1.2:ad_secdesc",
        "//third-party/rust/crates/ldap3/0.12.1:ldap3",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
