load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_bincode",
    srcs = glob(["**/*.rs"]),
    crate = "actix_bincode",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bincode/2.0.1:bincode",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
