load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_network",
    srcs = glob(["**/*.rs"]),
    crate = "acme_network",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libp2p/0.45.1:libp2p",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/pretty_env_logger/0.4.0:pretty_env_logger",
    ],
)
