load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adduce",
    srcs = glob(["**/*.rs"]),
    crate = "adduce",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/optional_struct/0.4.1:optional_struct",
        "//third-party/rust/crates/pulldown-cmark/0.11.3:pulldown_cmark",
        "//third-party/rust/crates/rss/2.1.0:rss",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
