load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_server",
    srcs = glob(["**/*.rs"]),
    crate = "actix_server",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/0.1.0:actix_rt",
        "//third-party/rust/crates/actix-service/0.2.2:actix_service",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mio/0.6.23:mio",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-reactor/0.1.12:tokio_reactor",
        "//third-party/rust/crates/tokio-signal/0.2.9:tokio_signal",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
