load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acat",
    srcs = glob(["**/*.rs"]),
    crate = "acat",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/random_color/0.4.4:random_color",
    ],
)
