load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_graphs",
    srcs = glob(["**/*.rs"]),
    crate = "acme_graphs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acme-core/0.3.1:acme_core",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/petgraph/0.6.5:petgraph",
        "//third-party/rust/crates/smart-default/0.7.1:smart_default",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
