load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_common_syntax_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_common_syntax_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
