load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adocs",
    srcs = glob(["**/*.rs"]),
    crate = "adocs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/camino/1.2.5:camino",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/notify/8.2.0:notify",
        "//third-party/rust/crates/pathdiff/0.2.3:pathdiff",
        "//third-party/rust/crates/rmcp/0.16.0:rmcp",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/ulid/1.2.1:ulid",
    ],
)
