load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu_base",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu_base",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/afi/0.3.2:afi",
        "//third-party/rust/crates/ami/0.6.0:ami",
        "//third-party/rust/crates/awi/0.3.0:awi",
    ],
)
