load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ably_auth_openapi",
    srcs = glob(["**/*.rs"]),
    crate = "ably_auth_openapi",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
