load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actions_toolkit_sys",
    srcs = glob(["**/*.rs"]),
    crate = "actions_toolkit_sys",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cfg-if/0.1.10:cfg_if",
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
