load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acton",
    srcs = glob(["**/*.rs"]),
    crate = "acton",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acton-service/0.11.0:acton_service",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/directories/5.0.1:directories",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/minijinja/2.23.0:minijinja",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rust-embed/8.12.0:rust_embed",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
