load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder_viz",
    srcs = glob(["**/*.rs"]),
    crate = "adder_viz",
    crate_root = "src/main.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adder-codec-rs/0.4.9:adder_codec_rs",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-recursion/1.1.1:async_recursion",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/eframe/0.26.2:eframe",
        "//third-party/rust/crates/egui/0.26.2:egui",
        "//third-party/rust/crates/egui_file/0.16.3:egui_file",
        "//third-party/rust/crates/egui_plot/0.26.2:egui_plot",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/ndarray-image/0.3.0:ndarray_image",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rfd/0.10.0:rfd",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/strum_macros/0.24.3:strum_macros",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/video-rs-adder-dep/0.4.1:video_rs_adder_dep",
    ],
)
