load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility_rs",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accessibility-scraper/0.0.6:accessibility_scraper",
        "//third-party/rust/crates/accessibility-tree/0.0.6:accessibility_tree",
        "//third-party/rust/crates/contrast/0.1.1:contrast",
        "//third-party/rust/crates/cssparser/0.27.2:cssparser",
        "//third-party/rust/crates/ego-tree/0.6.3:ego_tree",
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/markup5ever/0.11.0:markup5ever",
        "//third-party/rust/crates/rgb/0.8.53:rgb",
        "//third-party/rust/crates/rust-i18n/2.3.1:rust_i18n",
        "//third-party/rust/crates/selectors/0.22.0:selectors",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/strum/0.25.0:strum",
        "//third-party/rust/crates/strum_macros/0.25.3:strum_macros",
        "//third-party/rust/crates/taffy/0.4.4:taffy",
    ],
)
