load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_backoff",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_backoff",
    crate_root = "src/lib/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pretty_env_logger/0.3.1:pretty_env_logger",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
