load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activitystreams-kinds/0.2.1:activitystreams_kinds",
        "//third-party/rust/crates/iri-string/0.5.6:iri_string",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
