load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_sled_cache",
    srcs = glob(["**/*.rs"]),
    crate = "actix_sled_cache",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-threadpool/0.1.2:actix_threadpool",
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sled-extensions/0.2.0:sled_extensions",
    ],
)
