load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_checks",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_checks",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-core/1.3.3:adhammer_core",
        "//third-party/rust/crates/adhammer-graph/1.3.3:adhammer_graph",
        "//third-party/rust/crates/windows-sddl/0.1.1:windows_sddl",
    ],
)
