load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adom",
    srcs = glob(["**/*.rs"]),
    crate = "adom",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/tokio-postgres/0.5.5:tokio_postgres",
    ],
)
