load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accepts_macros",
    srcs = glob(["**/*.rs"]),
    crate = "accepts_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
    ],
)
