load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adnl",
    srcs = glob(["**/*.rs"]),
    crate = "adnl",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes/0.8.4:aes",
        "//third-party/rust/crates/ciborium-io/0.2.2:ciborium_io",
        "//third-party/rust/crates/ctr/0.9.2:ctr",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
