load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_adxl355_async",
    srcs = glob(["**/*.rs"]),
    crate = "adi_adxl355_async",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi-adxl355/0.2.0:adi_adxl355",
        "//third-party/rust/crates/micromath/2.1.0:micromath",
    ],
)
