load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_store",
    srcs = glob(["**/*.rs"]),
    crate = "act_store",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/fs2/0.4.3:fs2",
        "//third-party/rust/crates/oci-client/0.17.0:oci_client",
        "//third-party/rust/crates/oci-spec/0.9.0:oci_spec",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
