load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_data",
    srcs = glob(["**/*.rs"]),
    crate = "acme_data",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
    ],
)
