load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abbegm",
    srcs = glob(["**/*.rs"]),
    crate = "abbegm",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/prost/0.10.4:prost",
    ],
)
