load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_box_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_box_sdk",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-box-core/0.7.0:a3s_box_core",
        "//third-party/rust/crates/a3s-box-runtime/0.7.0:a3s_box_runtime",
        "//third-party/rust/crates/a3s-common/0.1.1:a3s_common",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
