version: 2

project_name: acta

before:
  hooks:
    - rustup default stable
    - bash -c 'command -v cargo-zigbuild &>/dev/null || pip3 install cargo-zigbuild'
    - cargo fmt --all -- --check
    - cargo clippy --all-features -- -D warnings
    - cargo test --all
    - cargo test --all --all-features
    - cargo test --all --no-default-features
    - cargo publish --manifest-path crates/acta-build/Cargo.toml --dry-run --allow-dirty
    - cargo publish --dry-run --allow-dirty

builds:
  - id: acta-linux-amd64-v2
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
      - --package=acta-debug
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: acta-linux-amd64-v3
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
      - --package=acta-debug
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

  - id: acta-linux-arm64
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
      - --package=acta-debug

  - id: acta-linux-armv7
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - armv7-unknown-linux-gnueabihf
    flags:
      - --release
      - --all-features
      - --package=acta-debug

  - id: acta-windows-amd64-v2
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
      - --package=acta-debug
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: acta-windows-amd64-v3
    builder: rust
    command: build
    tool: ./scripts/cargo-or-zigbuild.py
    binary: acta-debug
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
      - --package=acta-debug
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

source:
  enabled: false

archives:
  - id: linux-amd64-v2
    ids:
      - acta-linux-amd64-v2
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64_v2"
    formats:
      - tar.gz
    files: &common_archive_files
      - LICENSE
      - README.md

  - id: linux-amd64-v3
    ids:
      - acta-linux-amd64-v3
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64_v3"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: linux-arm64
    ids:
      - acta-linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: linux-armv7
    ids:
      - acta-linux-armv7
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_armv7"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: windows-amd64-v2
    ids:
      - acta-windows-amd64-v2
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64_v2"
    formats:
      - zip
    files: *common_archive_files

  - id: windows-amd64-v3
    ids:
      - acta-windows-amd64-v3
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64_v3"
    formats:
      - zip
    files: *common_archive_files

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github

release:
  github:
    owner: Sn0wo2
    name: acta
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
