load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adqa_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adqa_cli",
    crate_root = "src/cli_main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pyo3/0.23.5:pyo3",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)

rust_binary(
    name = "adqa_tui",
    srcs = glob(["**/*.rs"]),
    crate = "adqa_tui",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pyo3/0.23.5:pyo3",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
