load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_mark",
    srcs = glob(["**/*.rs"]),
    crate = "actix_mark",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-files/0.6.10:actix_files",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/pulldown-cmark/0.12.2:pulldown_cmark",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
