import { AJTheme } from "../aj-theme.slint";
import { AJText } from "aj-text.slint";
import { AJButton } from "aj-button.slint";

export component AJCheckbox inherits HorizontalLayout {
    in property <string> text;
    in-out property <bool> value;

    spacing: AJTheme.spacing;

    AJButton {
        text: value ? "✓" : "✗";
        background: value ? AJTheme.button : transparent;
        clicked => {
            value = !value;
        }
    }

    AJText {
        text: text;
        vertical-alignment: center;
        color: AJTheme.container-text;
    }
}
