load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab_glyph",
    srcs = glob(["**/*.rs"]),
    crate = "ab_glyph",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ab_glyph_rasterizer/0.1.10:ab_glyph_rasterizer",
        "//third-party/rust/crates/owned_ttf_parser/0.7.0:owned_ttf_parser",
    ],
)
