load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acick",
    srcs = glob(["**/*.rs"]),
    crate = "acick",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acick-atcoder/0.2.0:acick_atcoder",
        "//third-party/rust/crates/acick-config/0.2.0:acick_config",
        "//third-party/rust/crates/acick-util/0.2.0:acick_util",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/getset/0.1.7:getset",
        "//third-party/rust/crates/humantime-serde/1.1.1:humantime_serde",
        "//third-party/rust/crates/itertools/0.9.0:itertools",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
        "//third-party/rust/crates/strum/0.19.5:strum",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
