load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accumulator_plus",
    srcs = glob(["**/*.rs"]),
    crate = "accumulator_plus",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake2-rfc/0.2.18:blake2_rfc",
        "//third-party/rust/crates/num-bigint-dig/0.8.6:num_bigint_dig",
        "//third-party/rust/crates/num-integer/0.1.47:num_integer",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
    ],
)
