load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acyclic_network",
    srcs = glob(["**/*.rs"]),
    crate = "acyclic_network",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fixedbitset/0.1.9:fixedbitset",
        "//third-party/rust/crates/rand/0.4.6:rand",
    ],
)
