load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actus_controller",
    srcs = glob(["**/*.rs"]),
    crate = "actus_controller",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actus-controller-macros/1.1.0:actus_controller_macros",
        "//third-party/rust/crates/actus-reply/1.1.0:actus_reply",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
