load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "AS5600_Driver",
    srcs = glob(["**/*.rs"]),
    crate = "AS5600_Driver",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
