load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_loginmanager",
    srcs = glob(["**/*.rs"]),
    crate = "actix_loginmanager",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/loginmanager-codegen/0.0.1:loginmanager_codegen",
        "//third-party/rust/crates/rust-crypto/0.2.36:rust_crypto",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
