load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdc",
    srcs = glob(["**/*.rs"]),
    crate = "acdc",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cesrox/0.1.8:cesrox",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/rmp-serde/0.15.5:rmp_serde",
        "//third-party/rust/crates/said/0.4.3:said",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_cbor/0.11.2:serde_cbor",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
