load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3mo_lib",
    srcs = glob(["**/*.rs"]),
    crate = "a3mo_lib",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake2b_simd/0.5.11:blake2b_simd",
        "//third-party/rust/crates/custom_error/1.9.2:custom_error",
        "//third-party/rust/crates/faster-hex/0.3.1:faster_hex",
        "//third-party/rust/crates/indextree/3.3.0:indextree",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rusqlite/0.20.0:rusqlite",
        "//third-party/rust/crates/rustc-test/0.3.1:rustc_test",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_indextree/0.1.0:serde_indextree",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.1.45:time",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/xorshift/0.1.3:xorshift",
    ],
)
