load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aargvark",
    srcs = glob(["**/*.rs"]),
    crate = "aargvark",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aargvark_proc_macros/3.2.0:aargvark_proc_macros",
        "//third-party/rust/crates/comfy-table/7.2.2:comfy_table",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/convert_case/0.6.0:convert_case",
        "//third-party/rust/crates/textwrap/0.16.2:textwrap",
        "//third-party/rust/crates/unicode-width/0.1.14:unicode_width",
    ],
)
