load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_jwtauth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_jwtauth",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/jsonwebtoken/7.2.0:jsonwebtoken",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
