load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_opentelemetry",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_opentelemetry",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/opentelemetry-semantic-conventions/0.8.0:opentelemetry_semantic_conventions",
        "//third-party/rust/crates/opentelemetry/0.16.0:opentelemetry",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
