load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aces",
    srcs = glob(["**/*.rs"]),
    crate = "aces",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit-vec/0.6.3:bit_vec",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/fern/0.5.9:fern",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/string_cache/0.8.9:string_cache",
        "//third-party/rust/crates/varisat/0.2.2:varisat",
        "//third-party/rust/crates/yaml-rust/0.4.5:yaml_rust",
    ],
)
