load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder123",
    srcs = glob(["**/*.rs"]),
    crate = "adder123",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add_one123/0.1.0:add_one123",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
