load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_service_compat",
    srcs = glob(["**/*.rs"]),
    crate = "actr_service_compat",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actr-protocol/0.3.12:actr_protocol",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/proto-fingerprint/0.1.0:proto_fingerprint",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
