load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_static_files",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_static_files",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/static-files/0.2.5:static_files",
    ],
)
