load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_dom",
    srcs = glob(["**/*.rs"]),
    crate = "active_dom",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
        "//third-party/rust/crates/web-sys/0.3.104:web_sys",
    ],
)
