load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_array",
    srcs = glob(["**/*.rs"]),
    crate = "ach_array",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ach-cell/0.2.5:ach_cell",
    ],
)
