load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abc_rs",
    srcs = glob(["**/*.rs"]),
    crate = "abc_rs",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aig/0.3.3:aig",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
    ],
)
