load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adf_bdd",
    srcs = glob(["**/*.rs"]),
    crate = "adf_bdd",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/biodivine-lib-bdd/0.4.2:biodivine_lib_bdd",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/derivative/2.2.0:derivative",
        "//third-party/rust/crates/lexical-sort/0.3.1:lexical_sort",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/roaring/0.10.12:roaring",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.24.1:strum",
    ],
)
