load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "act",
    srcs = glob(["**/*.rs"]),
    crate = "act",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-file/0.0.1:act_file",
    ],
)
