load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_paging",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_paging",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
    ],
)
