load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acode_plugin_cli",
    srcs = glob(["**/*.rs"]),
    crate = "acode_plugin_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.16.4:console",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/indicatif/0.18.6:indicatif",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/zip/4.6.1:zip",
    ],
)
