load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_kit",
    srcs = glob(["**/*.rs"]),
    crate = "adb_kit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
