load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "httpsig_policy",
    srcs = glob(["**/*.rs"]),
    crate = "httpsig_policy",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aauth-httpsig/0.1.0:aauth_httpsig",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
