load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abci2",
    srcs = glob(["**/*.rs"]),
    crate = "abci2",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/integer-encoding/1.1.7:integer_encoding",
        "//third-party/rust/crates/protobuf/2.28.0:protobuf",
    ],
)
