load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_parser",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_parser",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/pest/2.8.8:pest",
        "//third-party/rust/crates/pest_derive/2.8.8:pest_derive",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
