load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a3s",
    srcs = glob(["**/*.rs"]),
    crate = "a3s",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-code-core/4.3.3:a3s_code_core",
        "//third-party/rust/crates/a3s-tui/0.1.14:a3s_tui",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
