load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acursor",
    srcs = glob(["**/*.rs"]),
    crate = "acursor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/concat-idents/1.1.5:concat_idents",
    ],
)
