load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acm",
    srcs = glob(["**/*.rs"]),
    crate = "acm",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/confy/0.6.1:confy",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/inquire/0.6.2:inquire",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/spinoff/0.8.0:spinoff",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
        "//third-party/rust/crates/which/6.0.3:which",
    ],
)
