load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpu",
    srcs = glob(["**/*.rs"]),
    crate = "acpu",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/unimem/0.2.0:unimem",
    ],
)
