load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a8e_test_support",
    srcs = glob(["**/*.rs"]),
    crate = "a8e_test_support",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/rmcp/0.15.0:rmcp",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
