load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp_ffi",
    srcs = glob(["**/*.rs"]),
    crate = "acp_ffi",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
