load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa_generator",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa_generator",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/handlebars/2.0.4:handlebars",
        "//third-party/rust/crates/hashbrown/0.4.0:hashbrown",
        "//third-party/rust/crates/heck/0.3.3:heck",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/semver/0.9.0:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
