load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_dispatch_core",
    srcs = glob(["**/*.rs"]),
    crate = "action_dispatch_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aho-corasick/1.1.5:aho_corasick",
        "//third-party/rust/crates/inventory/0.3.24:inventory",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
