name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-binstall

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy -- -D warnings

      - name: test
        run: cargo test

      - name: a9-lint
        run: |
          cargo binstall a9-lint --no-confirm --only-signed-urls || cargo install --git https://github.com/ars-vivendi/a9-lint.git --branch main
          cargo a9-lint --check
