import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJLeaderboardRow } from "../models/contests.slint";
import { AJTotalVerdict } from "../models/testing.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";

export component AJLeaderboard inherits Rectangle {
    property <int> problems-cnt: AJContestState.problems.length;
    property <[AJLeaderboardRow]> rows: AJContestState.leaderboard-rows;

    width: 50%;
    height: 500px;

    background: AJTheme.primary-container;

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "Таблица лидеров";
            type: AJTextType.Heading;
            color: AJTheme.container-text;
        }

        AJText {
            visible: rows.length == 0;
            text: "Таблица лидеров недоступна до конца контеста";
            type: AJTextType.Medium;
            font-italic: true;
            color: AJTheme.container-text;
        }

        Rectangle {
            visible: rows.length != 0;
            clip: true;
            border-radius: AJTheme.border-radius;

            ScrollView {
                GridLayout {
                    spacing: AJTheme.spacing;

                    Row {
                        AJText {
                            text: "#";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: "участник";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        for index in problems-cnt: AJText {
                            text: "\{index + 1}";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: "=";
                            font-italic: true;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }
                    }

                    for row[index] in rows: Row {
                        AJText {
                            text: index + 1;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: row.username;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        for score in row.scores: AJText {
                            text: score;
                            font-weight: score == 100 ? AJTheme.font-weight-heading : AJTheme.font-weight-paragraph;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }

                        AJText {
                            text: row.total-score;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: AJTheme.container-text;
                        }
                    }
                }
            }

            Rectangle {
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(180deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(50%));
            }
        }
    }
}
