load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_linked",
    srcs = glob(["**/*.rs"]),
    crate = "ach_linked",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ach-cell/0.2.5:ach_cell",
        "//third-party/rust/crates/ach-util/0.2.5:ach_util",
        "//third-party/rust/crates/spin_loop/0.2.5:spin_loop",
    ],
)
