load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aead",
    srcs = glob(["**/*.rs"]),
    crate = "aead",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/generic-array/0.14.9:generic_array",
    ],
)
