load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab_radix_trie",
    srcs = glob(["**/*.rs"]),
    crate = "ab_radix_trie",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
