load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_httpauth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_httpauth",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
    ],
)
