load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_report",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_report",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-core/1.3.3:adhammer_core",
        "//third-party/rust/crates/adhammer-graph/1.3.3:adhammer_graph",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
