load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_storage",
    srcs = glob(["**/*.rs"]),
    crate = "aa_storage",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
