load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_secrets",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_secrets",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes/0.8.4:aes",
        "//third-party/rust/crates/cbc/0.1.2:cbc",
        "//third-party/rust/crates/dcerpc/0.2.3:dcerpc",
        "//third-party/rust/crates/des/0.8.1:des",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/rc4/0.1.0:rc4",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
