load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_one",
    srcs = glob(["**/*.rs"]),
    crate = "add_one",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-bigint/0.2.6:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
