load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abserde",
    srcs = glob(["**/*.rs"]),
    crate = "abserde",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/dirs/4.0.0:dirs",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
