load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity",
    srcs = glob(["**/*.rs"]),
    crate = "activity",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activity-macros/0.1.3:activity_macros",
        "//third-party/rust/crates/activity-sys/0.1.3:activity_sys",
        "//third-party/rust/crates/serde-wasm-bindgen/0.4.5:serde_wasm_bindgen",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
