load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actplane_runtime",
    srcs = glob(["**/*.rs"]),
    crate = "actplane_runtime",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actplane-ifc-compiler/0.1.8:actplane_ifc_compiler",
        "//third-party/rust/crates/ebpf-ifc-engine/0.1.8:ebpf_ifc_engine",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/rmcp/1.8.0:rmcp",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
