load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_client",
    srcs = glob(["**/*.rs"]),
    crate = "acme_client",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.7.0:base64",
        "//third-party/rust/crates/error-chain/0.11.0:error_chain",
        "//third-party/rust/crates/hyper/0.10.16:hyper",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/openssl/0.9.24:openssl",
        "//third-party/rust/crates/reqwest/0.6.2:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
