load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abraxis",
    srcs = glob(["**/*.rs"]),
    crate = "abraxis",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/q_compress/0.11.7:q_compress",
    ],
)
