load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adns_client",
    srcs = glob(["**/*.rs"]),
    crate = "adns_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adns-proto/0.1.0:adns_proto",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
