load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl372",
    srcs = glob(["**/*.rs"]),
    crate = "adxl372",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/modular-bitfield/0.13.1:modular_bitfield",
    ],
)
