load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrpc_interceptor",
    srcs = glob(["**/*.rs"]),
    crate = "actrpc_interceptor",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrpc-core/0.1.0:actrpc_core",
        "//third-party/rust/crates/actrpc-orchestrator/0.1.0:actrpc_orchestrator",
        "//third-party/rust/crates/globset/0.4.20:globset",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
