load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_use_core",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_use_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/olpc-cjson/0.1.4:olpc_cjson",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
