load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ac_qu_ai_nt_core",
    srcs = glob(["**/*.rs"]),
    crate = "ac_qu_ai_nt_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/llama-cpp-2/0.1.64:llama_cpp_2",
        "//third-party/rust/crates/llama-cpp-sys-2/0.1.64:llama_cpp_sys_2",
    ],
)
