load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aabb2",
    srcs = glob(["**/*.rs"]),
    crate = "aabb2",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/number_traits/0.2.4:number_traits",
        "//third-party/rust/crates/vec2/0.1.5:vec2",
    ],
)
