load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abs_expr",
    srcs = glob(["**/*.rs"]),
    crate = "abs_expr",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abs-expr-macros/0.1.0:abs_expr_macros",
    ],
)
