load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_idempotent",
    srcs = glob(["**/*.rs"]),
    crate = "actix_idempotent",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-session/0.10.1:actix_session",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/deadpool-redis/0.16.0:deadpool_redis",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tower-layer/0.3.3:tower_layer",
        "//third-party/rust/crates/tower-service/0.3.3:tower_service",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
