load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adguard_flm",
    srcs = glob(["**/*.rs"]),
    crate = "adguard_flm",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono-tz/0.8.6:chrono_tz",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/faster-hex/0.10.0:faster_hex",
        "//third-party/rust/crates/include_dir/0.7.4:include_dir",
        "//third-party/rust/crates/md5/0.7.0:md5",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rusqlite/0.30.0:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
