load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abyss_promise",
    srcs = glob(["**/*.rs"]),
    crate = "abyss_promise",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
    ],
)
