load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adobe_font_parser",
    srcs = glob(["**/*.rs"]),
    crate = "adobe_font_parser",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/decorum/0.3.1:decorum",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/nom-language/0.1.0:nom_language",
        "//third-party/rust/crates/nom/8.0.0:nom",
        "//third-party/rust/crates/slotmap/1.1.1:slotmap",
        "//third-party/rust/crates/tiny-skia/0.11.4:tiny_skia",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
