load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts_store_postgres",
    srcs = glob(["**/*.rs"]),
    crate = "acts_store_postgres",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acts/0.17.2:acts",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/sea-query-binder/0.7.0:sea_query_binder",
        "//third-party/rust/crates/sea-query/0.32.7:sea_query",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sqlx/0.8.6:sqlx",
    ],
)
