load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adler_server",
    srcs = glob(["**/*.rs"]),
    crate = "adler_server",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adler-core/0.13.0:adler_core",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/fastrand/2.5.0:fastrand",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/mime_guess/2.0.5:mime_guess",
        "//third-party/rust/crates/rust-embed/8.12.0:rust_embed",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
