load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_7segment",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_7segment",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ascii/1.1.0:ascii",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/ht16k33/0.4.0:ht16k33",
    ],
)
