load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ws",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ws",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-util/0.2.0:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
