load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin_sep",
    srcs = glob(["**/*.rs"]),
    crate = "admin_sep",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/soroban-sdk/27.0.5:soroban_sdk",
    ],
)
