load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_jwt_auth_middleware_derive",
    srcs = glob(["**/*.rs"]),
    crate = "actix_jwt_auth_middleware_derive",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
