load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_core",
    srcs = glob(["**/*.rs"]),
    crate = "acme_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bson/2.15.0:bson",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/config/0.13.4:config",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/pretty_env_logger/0.4.0:pretty_env_logger",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
