load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adept",
    srcs = glob(["**/*.rs"]),
    crate = "adept",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/owo-colors/4.3.0:owo_colors",
        "//third-party/rust/crates/pulldown-cmark/0.12.2:pulldown_cmark",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tiktoken-rs/0.12.0:tiktoken_rs",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
