import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJSubmission, AJTotalVerdict } from "../models/testing.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJSubgroupCard } from "aj-subgroup-card.slint";
import { AJSubgroupResultCard } from "aj-subgroup-result-card.slint";
import { AJTestResultCard } from "aj-test-result-card.slint";
import { AJDropdown } from "aj-dropdown.slint";

export component AJSubmissionCard inherits Rectangle {
    property <AJSubmission> submission: AJContestState.submissions[AJContestState.current-submission-index];

    width: 100%;
    height: 270px;

    background: AJTheme.primary-container;

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "Посылка #\{AJContestState.submissions[AJContestState.current-submission-index].id}";
            color: AJTheme.container-text;
            type: AJTextType.Heading;
        }

        variant-dropdown := AJDropdown {
            variants: ["подгруппы", "тесты"];
        }

        AJText {
            text: variant-dropdown.current-index == 0 ? "Результаты подгрупп" : "Результаты тестов";
            color: AJTheme.container-text;
            type: AJTextType.Medium;
        }

        Rectangle {
            clip: true;
            border-radius: AJTheme.border-radius;

            ScrollView {
                VerticalLayout {
                    spacing: AJTheme.spacing;

                    if variant-dropdown.current-index == 0: VerticalLayout {
                        spacing: AJTheme.spacing;

                        for subgroup-result[index] in submission.subgroups-results: AJSubgroupResultCard {
                            index: index;
                        }
                    }

                    if variant-dropdown.current-index == 1: VerticalLayout {
                        spacing: AJTheme.spacing;

                        for test-result[index] in submission.tests-results: AJTestResultCard {
                            index: index;
                        }
                    }
                }
            }

            Rectangle {
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(180deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(50%));
            }
        }
    }
}
