load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abcgen",
    srcs = glob(["**/*.rs"]),
    crate = "abcgen",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abcgen-attributes/0.3.2:abcgen_attributes",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
