load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adif",
    srcs = glob(["**/*.rs"]),
    crate = "adif",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/lexical/5.2.2:lexical",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
