load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark_sys",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark_sys",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libloading/0.8.9:libloading",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
