// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../act-gir/build
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "ActUserAccountType", sizeof(ActUserAccountType), alignof(ActUserAccountType));
    printf("%s;%zu;%zu\n", "ActUserClass", sizeof(ActUserClass), alignof(ActUserClass));
    printf("%s;%zu;%zu\n", "ActUserManager", sizeof(ActUserManager), alignof(ActUserManager));
    printf("%s;%zu;%zu\n", "ActUserManagerClass", sizeof(ActUserManagerClass), alignof(ActUserManagerClass));
    printf("%s;%zu;%zu\n", "ActUserManagerError", sizeof(ActUserManagerError), alignof(ActUserManagerError));
    printf("%s;%zu;%zu\n", "ActUserPasswordMode", sizeof(ActUserPasswordMode), alignof(ActUserPasswordMode));
    return 0;
}
