load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abol_core",
    srcs = glob(["**/*.rs"]),
    crate = "abol_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
