load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_box_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_box_sdk",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-box-core/3.1.0:a3s_box_core",
        "//third-party/rust/crates/a3s-box-runtime/3.1.0:a3s_box_runtime",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sysinfo/0.30.13:sysinfo",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
