load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "achitek_source",
    srcs = glob(["**/*.rs"]),
    crate = "achitek_source",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tree-sitter/0.26.12:tree_sitter",
    ],
)
