load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adiscord",
    srcs = glob(["**/*.rs"]),
    crate = "adiscord",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adiscord-types/0.0.2:adiscord_types",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
    ],
)
