load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_webfinger",
    srcs = glob(["**/*.rs"]),
    crate = "actix_webfinger",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
