load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aci_png",
    srcs = glob(["**/*.rs"]),
    crate = "aci_png",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/png/0.9.0:png",
    ],
)
