load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_os",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_os",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-ica/0.6.3:abstract_ica",
        "//third-party/rust/crates/cosmwasm-schema/1.5.11:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/2.4.0:cw_asset",
        "//third-party/rust/crates/cw-controllers/1.1.2:cw_controllers",
        "//third-party/rust/crates/cw-semver/1.0.14:cw_semver",
        "//third-party/rust/crates/cw-storage-plus/1.2.0:cw_storage_plus",
        "//third-party/rust/crates/cw2/1.1.2:cw2",
        "//third-party/rust/crates/cw20-base/1.1.2:cw20_base",
        "//third-party/rust/crates/cw20/1.1.2:cw20",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
