load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adofai_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adofai_rs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_jsonrc/0.1.0:serde_jsonrc",
    ],
)
