load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_similarity",
    srcs = glob(["**/*.rs"]),
    crate = "aa_similarity",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aa-name/0.1.4:aa_name",
    ],
)
