load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_diesel_actor",
    srcs = glob(["**/*.rs"]),
    crate = "actix_diesel_actor",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/diesel/1.4.8:diesel",
        "//third-party/rust/crates/dotenv/0.13.0:dotenv",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
