load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_location",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_location",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
