load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstraps",
    srcs = glob(["**/*.rs"]),
    crate = "abstraps",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/color-eyre/0.5.11:color_eyre",
        "//third-party/rust/crates/downcast-rs/1.2.1:downcast_rs",
        "//third-party/rust/crates/indenter/0.3.4:indenter",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/yansi/0.5.1:yansi",
    ],
)
