load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_dns_client",
    srcs = glob(["**/*.rs"]),
    crate = "acme_dns_client",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
