load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_integers",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_integers",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num/0.4.3:num",
    ],
)
