load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_tx",
    srcs = glob(["**/*.rs"]),
    crate = "active_tx",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activeledger/0.1.1:activeledger",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
