load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_jwt_validator_middleware",
    srcs = glob(["**/*.rs"]),
    crate = "actix_jwt_validator_middleware",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-httpauth/0.5.1:actix_web_httpauth",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/display_json/0.1.3:display_json",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/jonases-tracing-util/0.1.0:jonases_tracing_util",
        "//third-party/rust/crates/jwks-client/0.2.0:jwks_client",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
