import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJWelcomeCallbacks } from "../aj-callbacks.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJButton } from "../components/aj-button.slint";

export component LoginPage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJText {
            text: "вход в аккаунт";
            type: AJTextType.Heading;
        }

        login := AJInput {
            placeholder: "логин";
        }

        password := AJInput {
            placeholder: "пароль";
            type: AJInputType.Password;
        }

        AJButton {
            text: "войти >>";
            clicked => {
                AJWelcomeCallbacks.login(login.text, password.text)
            }
        }

        AJButton {
            text: "<< назад";
            clicked => {
                AJAppState.page = 0
            }
        }
    }
}
