load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx",
    srcs = glob(["**/*.rs"]),
    crate = "adminx",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adminx-core/0.1.0:adminx_core",
    ],
)
