load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_timeout",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_timeout",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/foldhash/0.2.0:foldhash",
        "//third-party/rust/crates/hdrhistogram/7.6.0:hdrhistogram",
    ],
)
