load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adler_mcp",
    srcs = glob(["**/*.rs"]),
    crate = "adler_mcp",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adler-core/0.16.0:adler_core",
        "//third-party/rust/crates/adler-server/0.16.0:adler_server",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rmcp/1.8.0:rmcp",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
