load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acorde",
    srcs = glob(["**/*.rs"]),
    crate = "acorde",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acorde-core/0.1.1:acorde_core",
        "//third-party/rust/crates/acorde-io/0.1.1:acorde_io",
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
