load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix",
    srcs = glob(["**/*.rs"]),
    crate = "actix",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix_derive/0.5.0:actix_derive",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/crossbeam-channel/0.4.4:crossbeam_channel",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-channel/0.3.34:futures_channel",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/parking_lot/0.10.2:parking_lot",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/tokio-util/0.3.1:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
