load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori_service",
    srcs = glob(["**/*.rs"]),
    crate = "actori_service",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
    ],
)
