load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_version_control",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_version_control",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-macros/0.11.0:abstract_macros",
        "//third-party/rust/crates/abstract-os/0.11.1:abstract_os",
        "//third-party/rust/crates/abstract-sdk/0.11.0:abstract_sdk",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-controllers/1.1.2:cw_controllers",
        "//third-party/rust/crates/cw-semver/1.0.14:cw_semver",
        "//third-party/rust/crates/cw-storage-plus/1.2.0:cw_storage_plus",
        "//third-party/rust/crates/cw2/1.1.2:cw2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
