load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_atspi_common",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_atspi_common",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.15.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.23.0:accesskit_consumer",
        "//third-party/rust/crates/atspi-common/0.3.0:atspi_common",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/zvariant/3.15.2:zvariant",
    ],
)
