load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adc",
    srcs = glob(["**/*.rs"]),
    crate = "adc",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
    ],
)
