load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_log_parser",
    srcs = glob(["**/*.rs"]),
    crate = "access_log_parser",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
