load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abfall",
    srcs = glob(["**/*.rs"]),
    crate = "abfall",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
    ],
)
