load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acpd",
    srcs = glob(["**/*.rs"]),
    crate = "acpd",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acp-protocol/0.6.0:acp_protocol",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/daemonize/0.5.0:daemonize",
        "//third-party/rust/crates/nix/0.29.0:nix",
        "//third-party/rust/crates/notify/8.2.0:notify",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
