load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_secdesc",
    srcs = glob(["**/*.rs"]),
    crate = "ad_secdesc",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
