load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ioframe",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ioframe",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-current-thread/0.1.7:tokio_current_thread",
    ],
)
