load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_prost_build",
    srcs = glob(["**/*.rs"]),
    crate = "actix_prost_build",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/prettyplease/0.2.37:prettyplease",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/prost-build/0.13.5:prost_build",
        "//third-party/rust/crates/prost-reflect/0.14.7:prost_reflect",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
