load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adguard_toggle",
    srcs = glob(["**/*.rs"]),
    crate = "adguard_toggle",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/gtk4-layer-shell/0.4.0:gtk4_layer_shell",
        "//third-party/rust/crates/gtk4/0.9.7:gtk4",
        "//third-party/rust/crates/ksni/0.2.2:ksni",
        "//third-party/rust/crates/notify-rust/4.18.0:notify_rust",
        "//third-party/rust/crates/open/5.4.1:open",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/resvg/0.45.1:resvg",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
