load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_jsonschema",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_jsonschema",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/jsonschema/0.16.1:jsonschema",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
