load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ada_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "ada_sdk",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic-prost/0.14.6:tonic_prost",
        "//third-party/rust/crates/tonic/0.14.6:tonic",
    ],
)
