load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_session_surrealdb",
    srcs = glob(["**/*.rs"]),
    crate = "actix_session_surrealdb",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-session/0.9.0:actix_session",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/surrealdb/2.6.5:surrealdb",
    ],
)
