load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel_derive",
    srcs = glob(["**/*.rs"]),
    crate = "accel_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dirs/2.0.2:dirs",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/maplit/1.0.2:maplit",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/toml/0.5.11:toml",
    ],
)
