load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_spanner",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_spanner",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adbc_core/0.23.0:adbc_core",
        "//third-party/rust/crates/arrow-array/58.4.0:arrow_array",
        "//third-party/rust/crates/arrow-schema/58.4.0:arrow_schema",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/google-cloud-auth/1.15.0:google_cloud_auth",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
