load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acrylic_wayland",
    srcs = glob(["**/*.rs"]),
    crate = "acrylic_wayland",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acrylic/0.3.5:acrylic",
        "//third-party/rust/crates/memmap/0.7.0:memmap",
        "//third-party/rust/crates/simple_logger/4.3.3:simple_logger",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/wayland-client/0.30.2:wayland_client",
        "//third-party/rust/crates/wayland-protocols/0.30.1:wayland_protocols",
    ],
)
