load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable_host_api",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable_host_api",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable/0.11.3:abi_stable",
    ],
)
