load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abi_typegen",
    srcs = glob(["**/*.rs"]),
    crate = "abi_typegen",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi-typegen-codegen/0.2.0:abi_typegen_codegen",
        "//third-party/rust/crates/abi-typegen-config/0.2.0:abi_typegen_config",
        "//third-party/rust/crates/abi-typegen-core/0.2.0:abi_typegen_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dotenvy/0.15.7:dotenvy",
        "//third-party/rust/crates/notify/6.1.1:notify",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
