load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_ble_fs_client",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_ble_fs_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
