load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_util",
    srcs = glob(["**/*.rs"]),
    crate = "ach_util",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/atomic_macro/0.1.2:atomic_macro",
    ],
)
