load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrix_proto",
    srcs = glob(["**/*.rs"]),
    crate = "actrix_proto",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/tonic-prost/0.14.6:tonic_prost",
        "//third-party/rust/crates/tonic/0.14.6:tonic",
    ],
)
