load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_dispatch",
    srcs = glob(["**/*.rs"]),
    crate = "action_dispatch",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/action_dispatch_core/0.1.0:action_dispatch_core",
        "//third-party/rust/crates/action_dispatch_macro/0.1.0:action_dispatch_macro",
    ],
)
