load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_cors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_cors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
    ],
)
