load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "activate",
    srcs = glob(["**/*.rs"]),
    crate = "activate",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
