load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_memory",
    srcs = glob(["**/*.rs"]),
    crate = "adk_memory",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/0.3.2:adk_core",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
    ],
)
