load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_atspi_common",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_atspi_common",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.24.1:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.34.0:accesskit_consumer",
        "//third-party/rust/crates/atspi-common/0.13.0:atspi_common",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/zvariant/5.14.0:zvariant",
    ],
)
