load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme",
    srcs = glob(["**/*.rs"]),
    crate = "acme",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acme-core/0.3.1:acme_core",
    ],
)
