load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a9_prettyplease",
    srcs = glob(["**/*.rs"]),
    crate = "a9_prettyplease",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
