load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advanced_algorithms",
    srcs = glob(["**/*.rs"]),
    crate = "advanced_algorithms",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-complex/0.4.6:num_complex",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
