load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admerge",
    srcs = glob(["**/*.rs"]),
    crate = "admerge",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteseeker/0.2.1:byteseeker",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
