load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab1024_ega",
    srcs = glob(["**/*.rs"]),
    crate = "ab1024_ega",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embed-doc-image/0.1.4:embed_doc_image",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/num_enum/0.7.6:num_enum",
    ],
)
