load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts",
    srcs = glob(["**/*.rs"]),
    crate = "acts",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acts-tag/0.2.0:acts_tag",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/criterion/0.4.0:criterion",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/lru/0.8.1:lru",
        "//third-party/rust/crates/nanoid/0.4.0:nanoid",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rhai/1.25.1:rhai",
        "//third-party/rust/crates/rocksdb/0.20.1:rocksdb",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
