load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advisorygraphen_core",
    srcs = glob(["**/*.rs"]),
    crate = "advisorygraphen_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/higher-graphen-core/0.7.1:higher_graphen_core",
        "//third-party/rust/crates/higher-graphen-structure/0.7.1:higher_graphen_structure",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
