load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_search",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_search",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/scraper/0.22.0:scraper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
