load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerometer",
    srcs = glob(["**/*.rs"]),
    crate = "accelerometer",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/micromath/0.2.2:micromath",
    ],
)
