load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_runtime",
    srcs = glob(["**/*.rs"]),
    crate = "actr_runtime",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actr-framework/0.4.21:actr_framework",
        "//third-party/rust/crates/actr-protocol/0.4.21:actr_protocol",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
