load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_acn",
    srcs = glob(["**/*.rs"]),
    crate = "acton_acn",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
