load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_actors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_actors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.4.2:actix_codec",
        "//third-party/rust/crates/actix/0.12.0:actix",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/bytestring/1.5.1:bytestring",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
