load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_gps",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_gps",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serialport/3.3.0:serialport",
    ],
)
