load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark_dns",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark_dns",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/clap/4.5.61:clap",
        "//third-party/rust/crates/flume/0.11.1:flume",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hickory-client/0.25.2:hickory_client",
        "//third-party/rust/crates/hickory-proto/0.25.2:hickory_proto",
        "//third-party/rust/crates/hickory-server/0.25.2:hickory_server",
        "//third-party/rust/crates/inotify/0.11.4:inotify",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nix/0.30.1:nix",
        "//third-party/rust/crates/syslog/7.0.0:syslog",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
