name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  rust-ci:
    name: Rust CI
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/rust-ci.yaml
