#!/bin/bash

set -e

cargo test --all-features
cargo test --target wasm32-unknown-unknown --features wasm_bindgen

source env/bin/activate
bash src/interfaces/pyo3/tests/test.sh

cargo build --all-features --release
