load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_cw4_stake",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_cw4_stake",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-cw2/1.2.2:abstract_cw2",
        "//third-party/rust/crates/abstract-cw20/3.0.0:abstract_cw20",
        "//third-party/rust/crates/abstract-cw4/1.2.2:abstract_cw4",
        "//third-party/rust/crates/cosmwasm-schema/1.5.11:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-controllers/1.1.2:cw_controllers",
        "//third-party/rust/crates/cw-orch/0.24.1:cw_orch",
        "//third-party/rust/crates/cw-storage-plus/1.2.0:cw_storage_plus",
        "//third-party/rust/crates/cw-utils/1.0.3:cw_utils",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
