load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "Agentic_rs",
    srcs = glob(["**/*.rs"]),
    crate = "Agentic_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/ollama-rs/0.1.9:ollama_rs",
        "//third-party/rust/crates/pdf-extract/0.7.12:pdf_extract",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/scraper/0.19.1:scraper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
