load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_snowflake",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_snowflake",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adbc_core/0.20.0:adbc_core",
        "//third-party/rust/crates/adbc_driver_manager/0.20.0:adbc_driver_manager",
        "//third-party/rust/crates/adbc_ffi/0.20.0:adbc_ffi",
        "//third-party/rust/crates/arrow-array/56.2.1:arrow_array",
        "//third-party/rust/crates/arrow-schema/56.2.1:arrow_schema",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
