load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/iai/0.1.1:iai",
    ],
)
