load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_rewrite",
    srcs = glob(["**/*.rs"]),
    crate = "actix_rewrite",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/mod_rewrite/0.2.0:mod_rewrite",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
    ],
)
