load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abc_rs",
    srcs = glob(["**/*.rs"]),
    crate = "abc_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aig/0.2.9:aig",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
    ],
)
