load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_ess",
    srcs = glob(["**/*.rs"]),
    crate = "ad_ess",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rug/1.30.0:rug",
    ],
)
