load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbyss_psl",
    srcs = glob(["**/*.rs"]),
    crate = "adbyss_psl",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.7.8:ahash",
        "//third-party/rust/crates/unicode-bidi/0.3.18:unicode_bidi",
        "//third-party/rust/crates/unicode-normalization/0.1.25:unicode_normalization",
    ],
)
