load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adaptive_card_mcp",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_card_mcp",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adaptive-card-core/0.1.0:adaptive_card_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/rmcp/1.8.0:rmcp",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
