load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abrasive",
    srcs = glob(["**/*.rs"]),
    crate = "abrasive",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abrasive-protocol/0.0.1:abrasive_protocol",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/ignore/0.4.33:ignore",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rustls-pemfile/2.2.0:rustls_pemfile",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tungstenite/0.23.0:tungstenite",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
