load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa2nucaln",
    srcs = glob(["**/*.rs"]),
    crate = "aa2nucaln",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/atty/0.2.14:atty",
        "//third-party/rust/crates/bio/0.41.0:bio",
        "//third-party/rust/crates/clap/3.2.25:clap",
    ],
)
