load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "util",
    srcs = glob(["**/*.rs"]),
    crate = "util",
    crate_root = "src/util/mod.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/indicatif/0.16.2:indicatif",
    ],
)
