load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptxmr",
    srcs = glob(["**/*.rs"]),
    crate = "acceptxmr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/monero/0.16.0:monero",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sled/0.34.7:sled",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
