use crate::type_mapper::{Target, overload_suffix, safe_param_name, sol_type_to_ts};
use abi_typegen_core::types::{AbiEvent, AbiFunction, ContractIr, StateMutability};
use std::collections::HashMap;

const TARGET: Target = Target::Ethers;

/// Generates `<ContractName>.ethers.ts` — a typed ethers v6 contract interface.
pub fn render_ethers_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str("import { Contract, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n\n",
        ir.name, ir.name
    ));

    // Interface — standalone (not extending Contract) to avoid index signature
    // conflicts with ethers v6's BaseContractMethod constraint.
    out.push_str(&format!("export interface {}Contract {{\n", ir.name));

    // Count overloaded function names.
    // Use &str keys to avoid cloning function names into the maps.
    let mut name_counts: HashMap<&str, u32> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    for f in &ir.functions {
        let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
        let overloaded;
        let method_name: &str = if count > 1 {
            overloaded = format!("{}{}", f.name, overload_suffix(&f.inputs));
            &overloaded
        } else {
            &f.name
        };
        out.push_str(&render_function_sig(method_name, f));
    }

    // Event filters
    if !ir.events.is_empty() {
        out.push_str("  filters: {\n");
        for event in &ir.events {
            out.push_str(&render_event_filter(event));
        }
        out.push_str("  };\n");
    }

    out.push_str("}\n\n");

    // connect factory function
    out.push_str(&format!(
        "export function connect{}(address: string, runner: ContractRunner): {}Contract {{\n",
        ir.name, ir.name
    ));
    out.push_str(&format!(
        "  return new Contract(address, {}Abi, runner) as unknown as {}Contract;\n",
        ir.name, ir.name
    ));
    out.push_str("}\n");

    out
}

fn render_function_sig(method_name: &str, f: &AbiFunction) -> String {
    let params = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}: {}",
                safe_param_name(&p.name, i),
                sol_type_to_ts(&p.ty, TARGET)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    let return_type = match f.state_mutability {
        StateMutability::Pure | StateMutability::View => {
            let out_types: Vec<String> = f
                .outputs
                .iter()
                .map(|p| sol_type_to_ts(&p.ty, TARGET))
                .collect();
            match out_types.len() {
                0 => "Promise<void>".into(),
                1 => format!("Promise<{}>", out_types[0]),
                _ => {
                    let all_named = f.outputs.iter().all(|p| !p.name.is_empty());
                    if all_named {
                        let fields: Vec<String> = f
                            .outputs
                            .iter()
                            .enumerate()
                            .map(|(i, p)| {
                                format!(
                                    "{}: {}",
                                    safe_param_name(&p.name, i),
                                    sol_type_to_ts(&p.ty, TARGET)
                                )
                            })
                            .collect();
                        format!("Promise<{{ {} }}>", fields.join("; "))
                    } else {
                        format!("Promise<[{}]>", out_types.join(", "))
                    }
                }
            }
        }
        _ => "Promise<ContractTransactionResponse>".into(),
    };

    format!("  {}({}): {};\n", method_name, params, return_type)
}

fn render_event_filter(event: &AbiEvent) -> String {
    let params = event
        .inputs
        .iter()
        .enumerate()
        .filter(|(_, p)| p.indexed)
        .map(|(i, p)| {
            format!(
                "{}?: {} | null",
                safe_param_name(&p.name, i),
                sol_type_to_ts(&p.ty, TARGET)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("    {}({}): EventFilter;\n", event.name, params)
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    #[test]
    fn contains_imports() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("import { Contract, type ContractRunner"));
        assert!(out.contains("import { ERC20Abi } from './ERC20.abi.js'"));
    }

    #[test]
    fn exports_interface() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("export interface ERC20Contract {"));
    }

    #[test]
    fn view_fn_returns_promise() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("balanceOf(account: string): Promise<bigint>;"));
    }

    #[test]
    fn write_fn_returns_transaction_response() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains(
            "transfer(to: string, amount: bigint): Promise<ContractTransactionResponse>;"
        ));
    }

    #[test]
    fn event_filters_block() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("filters: {"));
        assert!(out.contains("Transfer(from?: string | null, to?: string | null): EventFilter;"));
    }

    #[test]
    fn connect_factory_fn() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains(
            "export function connectERC20(address: string, runner: ContractRunner): ERC20Contract {"
        ));
    }

    #[test]
    fn vault_overloads_get_signature_based_names() {
        let out = render_ethers_file(&vault());
        assert!(
            out.contains("depositUint256("),
            "Expected depositUint for deposit(uint256), got:\n{out}"
        );
        assert!(
            out.contains("depositUint256Address("),
            "Expected depositUint256Address for deposit(uint256, address), got:\n{out}"
        );
        // Old numbered names should not appear
        assert!(
            !out.contains("deposit_0("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
        assert!(
            !out.contains("deposit_1("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
    }

    #[test]
    fn vault_tuple_output_is_inline_type() {
        let out = render_ethers_file(&vault());
        assert!(out.contains("getPosition(user: string): Promise<{"));
        assert!(out.contains("shares: bigint"));
    }

    // --- Hand-built IR tests below ---

    use abi_typegen_core::types::{AbiEventParam, AbiParam, SolType};

    /// Helper to build a minimal ContractIr with the given functions and events.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn view_fn_returning_void() {
        let ir = make_ir(
            "Minimal",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("ping(): Promise<void>;"),
            "Expected `Promise<void>` for view fn with no outputs, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_returning_multiple_outputs() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getPair(): Promise<{ a: string; b: bigint }>;"),
            "Expected `Promise<{{ a: string; b: bigint }}>` for multi-output view fn with named outputs, got:\n{out}"
        );
    }

    #[test]
    fn contract_with_no_events_omits_filters() {
        let ir = make_ir(
            "NoEvents",
            vec![AbiFunction {
                name: "doSomething".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            !out.contains("filters"),
            "Expected no `filters` block when there are no events, got:\n{out}"
        );
    }

    #[test]
    fn contract_with_no_functions() {
        let ir = make_ir(
            "EventOnly",
            vec![],
            vec![AbiEvent {
                name: "Ping".to_string(),
                inputs: vec![AbiEventParam {
                    name: "sender".to_string(),
                    ty: SolType::Address,
                    indexed: true,
                    internal_type: None,
                }],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_ethers_file(&ir);
        // The interface should still contain the filters block
        assert!(
            out.contains("filters: {"),
            "Expected `filters` block even with no functions, got:\n{out}"
        );
        assert!(
            out.contains("Ping(sender?: string | null): EventFilter;"),
            "Expected Ping filter, got:\n{out}"
        );
        // There should be no function signatures (lines starting with two spaces
        // that look like function declarations, but filters block is fine).
        // Specifically, no line matching `  someName(` outside the filters block.
        let interface_start = out.find("Contract {").expect("interface");
        let filters_start = out.find("filters: {").expect("filters");
        let between = &out[interface_start..filters_start];
        // Between the opening brace and filters there should only be whitespace/newlines
        let trimmed = between
            .trim_start_matches(|c: char| c != '{')
            .trim_start_matches('{')
            .trim();
        assert!(
            trimmed.is_empty(),
            "Expected no function signatures before filters block, got:\n{between}"
        );
    }

    #[test]
    fn event_with_only_non_indexed_params() {
        let ir = make_ir(
            "LogOnly",
            vec![],
            vec![AbiEvent {
                name: "DataStored".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "key".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "value".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_ethers_file(&ir);
        // The filter function should have no parameters since nothing is indexed
        assert!(
            out.contains("DataStored(): EventFilter;"),
            "Expected filter with no params for non-indexed event, got:\n{out}"
        );
    }

    #[test]
    fn pure_fn_returns_promise() {
        let ir = make_ir(
            "MathLib",
            vec![AbiFunction {
                name: "add".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::Pure,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("add(a: bigint, b: bigint): Promise<bigint>;"),
            "Expected `Promise<bigint>` for pure fn, got:\n{out}"
        );
    }

    #[test]
    fn non_overloaded_fn_keeps_original_name() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("transfer(to: string, amount: bigint)"),
            "Expected `transfer(...)` without suffix, got:\n{out}"
        );
        assert!(
            !out.contains("transfer_0"),
            "Non-overloaded function should not get `_0` suffix, got:\n{out}"
        );
    }

    #[test]
    fn named_multi_return_produces_object_type() {
        let ir = make_ir(
            "Named",
            vec![AbiFunction {
                name: "getInfo".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "balance".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getInfo(): Promise<{ owner: string; balance: bigint }>;"),
            "Expected named object return type, got:\n{out}"
        );
    }

    #[test]
    fn unnamed_multi_return_produces_tuple_type() {
        let ir = make_ir(
            "Unnamed",
            vec![AbiFunction {
                name: "getValues".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getValues(): Promise<[string, bigint]>;"),
            "Expected positional tuple return type for unnamed outputs, got:\n{out}"
        );
    }

    #[test]
    fn mixed_named_unnamed_multi_return_produces_tuple() {
        let ir = make_ir(
            "Mixed",
            vec![AbiFunction {
                name: "getMixed".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getMixed(): Promise<[string, bigint]>;"),
            "Expected positional tuple when some outputs are unnamed, got:\n{out}"
        );
    }
}
