use crate::type_mapper::{overload_suffix, safe_param_name};
use abi_typegen_core::types::{AbiEvent, AbiFunction, ContractIr, SolType, StateMutability};
use std::collections::HashMap;

/// Maps a Solidity type to its ethers v5 TypeScript representation.
///
/// Key differences from the shared `sol_type_to_ts` (which targets ethers v6):
/// - `uint56`..`uint256` and `int56`..`int256` map to `BigNumber` (not `bigint`).
/// - `address` maps to `string`.
/// - `bytes` / `bytesN` map to `string`.
/// - Arrays are `T[]` (not `readonly T[]`).
/// - Fixed-size arrays are also `T[]` (not `readonly [T, T, ...]`).
/// - Tuple fields are rendered inline via recursion.
fn sol_type_to_ethers5(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "boolean".into(),
        SolType::StringType => "string".into(),

        SolType::Uint(bits) | SolType::Int(bits) => {
            if *bits <= 48 {
                "number".into()
            } else {
                "BigNumber".into()
            }
        }

        SolType::Address => "string".into(),

        SolType::Bytes | SolType::BytesN(_) => "string".into(),

        SolType::Array(inner) => {
            let inner_ts = sol_type_to_ethers5(inner);
            format!("{}[]", inner_ts)
        }

        SolType::FixedArray(inner, _n) => {
            let inner_ts = sol_type_to_ethers5(inner);
            format!("{}[]", inner_ts)
        }

        SolType::Tuple(components) => {
            let fields: Vec<String> = components
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    format!(
                        "{}: {}",
                        safe_param_name(&c.name, i),
                        sol_type_to_ethers5(&c.ty)
                    )
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        }
    }
}

/// Maps a Solidity type to the ethers v5 *input* TypeScript type.
///
/// For integer types > 48 bits, returns `BigNumberish` instead of `BigNumber`,
/// since inputs should accept `string | number | BigNumber`.
fn sol_type_to_ethers5_input(ty: &SolType) -> String {
    match ty {
        SolType::Uint(bits) | SolType::Int(bits) => {
            if *bits <= 48 {
                "number".into()
            } else {
                "BigNumberish".into()
            }
        }
        // For all other types, the input type is the same as the output type.
        _ => sol_type_to_ethers5(ty),
    }
}

/// Generates `<ContractName>.ethers5.ts` -- a typed ethers v5 contract interface.
pub fn render_ethers5_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str("import { ethers, BigNumber, BigNumberish } from 'ethers';\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n\n",
        ir.name, ir.name
    ));

    // Interface -- extends ethers.Contract
    out.push_str(&format!(
        "export interface {}Contract extends ethers.Contract {{\n",
        ir.name
    ));

    // Count overloaded function names.
    let mut name_counts: HashMap<&str, u32> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    for f in &ir.functions {
        let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
        let overloaded;
        let method_name: &str = if count > 1 {
            overloaded = format!("{}{}", f.name, overload_suffix(&f.inputs));
            &overloaded
        } else {
            &f.name
        };
        out.push_str(&render_function_sig(method_name, f));
    }

    // Event filters
    if !ir.events.is_empty() {
        out.push_str("  filters: {\n");
        for event in &ir.events {
            out.push_str(&render_event_filter(event));
        }
        out.push_str("  };\n");
    }

    out.push_str("}\n\n");

    // connect factory function
    out.push_str(&format!(
        "export function connect{}(\n  address: string,\n  signerOrProvider: ethers.Signer | ethers.providers.Provider,\n): {}Contract {{\n",
        ir.name, ir.name
    ));
    out.push_str(&format!(
        "  return new ethers.Contract(address, {}Abi, signerOrProvider) as unknown as {}Contract;\n",
        ir.name, ir.name
    ));
    out.push_str("}\n");

    out
}

/// Renders a single function signature line for an ethers v5 typed interface.
fn render_function_sig(method_name: &str, f: &AbiFunction) -> String {
    let params = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}: {}",
                safe_param_name(&p.name, i),
                sol_type_to_ethers5_input(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    let return_type = match f.state_mutability {
        StateMutability::Pure | StateMutability::View => {
            let out_types: Vec<String> = f
                .outputs
                .iter()
                .map(|p| sol_type_to_ethers5(&p.ty))
                .collect();
            match out_types.len() {
                0 => "Promise<void>".into(),
                1 => format!("Promise<{}>", out_types[0]),
                _ => {
                    let all_named = f.outputs.iter().all(|p| !p.name.is_empty());
                    if all_named {
                        let fields: Vec<String> = f
                            .outputs
                            .iter()
                            .enumerate()
                            .map(|(i, p)| {
                                format!(
                                    "{}: {}",
                                    safe_param_name(&p.name, i),
                                    sol_type_to_ethers5(&p.ty)
                                )
                            })
                            .collect();
                        format!("Promise<{{ {} }}>", fields.join("; "))
                    } else {
                        format!("Promise<[{}]>", out_types.join(", "))
                    }
                }
            }
        }
        _ => "Promise<ethers.ContractTransaction>".into(),
    };

    format!("  {}({}): {};\n", method_name, params, return_type)
}

/// Renders a single event filter method line for ethers v5.
fn render_event_filter(event: &AbiEvent) -> String {
    let params = event
        .inputs
        .iter()
        .enumerate()
        .filter(|(_, p)| p.indexed)
        .map(|(i, p)| {
            format!(
                "{}?: {} | null",
                safe_param_name(&p.name, i),
                sol_type_to_ethers5(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("    {}({}): ethers.EventFilter;\n", event.name, params)
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{AbiEventParam, AbiParam, SolType, TupleComponent};

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    /// Helper to build a minimal ContractIr with the given functions and events.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn header_and_imports() {
        let out = render_ethers5_file(&erc20());
        assert!(
            out.contains("// Auto-generated by abi-typegen. Do not edit manually."),
            "Missing auto-generated header"
        );
        assert!(
            out.contains("import { ethers, BigNumber, BigNumberish } from 'ethers';"),
            "Missing ethers v5 imports, got:\n{out}"
        );
        assert!(
            out.contains("import { ERC20Abi } from './ERC20.abi.js';"),
            "Missing ABI import, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_returns_promise_bignumber_for_uint256() {
        let out = render_ethers5_file(&erc20());
        assert!(
            out.contains("balanceOf(account: string): Promise<BigNumber>;"),
            "Expected `Promise<BigNumber>` for uint256 view return, got:\n{out}"
        );
    }

    #[test]
    fn write_fn_returns_contract_transaction() {
        let out = render_ethers5_file(&erc20());
        assert!(
            out.contains(
                "transfer(to: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;"
            ),
            "Expected `Promise<ethers.ContractTransaction>` for write fn, got:\n{out}"
        );
    }

    #[test]
    fn event_filters_with_indexed_params() {
        let out = render_ethers5_file(&erc20());
        assert!(out.contains("filters: {"), "Missing filters block");
        assert!(
            out.contains("Transfer(from?: string | null, to?: string | null): ethers.EventFilter;"),
            "Missing Transfer event filter, got:\n{out}"
        );
    }

    #[test]
    fn connect_factory_function_signature() {
        let out = render_ethers5_file(&erc20());
        assert!(
            out.contains("export function connectERC20("),
            "Missing connect factory function"
        );
        assert!(
            out.contains("signerOrProvider: ethers.Signer | ethers.providers.Provider,"),
            "Missing signerOrProvider parameter type, got:\n{out}"
        );
        assert!(
            out.contains("): ERC20Contract {"),
            "Missing return type, got:\n{out}"
        );
        assert!(
            out.contains(
                "return new ethers.Contract(address, ERC20Abi, signerOrProvider) as unknown as ERC20Contract;"
            ),
            "Missing factory body, got:\n{out}"
        );
    }

    #[test]
    fn overloaded_function_handling() {
        let out = render_ethers5_file(&vault());
        assert!(
            out.contains("depositUint256("),
            "Expected depositUint256 for deposit(uint256), got:\n{out}"
        );
        assert!(
            out.contains("depositUint256Address("),
            "Expected depositUint256Address for deposit(uint256, address), got:\n{out}"
        );
        // Old numbered names should not appear
        assert!(
            !out.contains("deposit_0("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
        assert!(
            !out.contains("deposit_1("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
    }

    #[test]
    fn interface_extends_ethers_contract() {
        let out = render_ethers5_file(&erc20());
        assert!(
            out.contains("export interface ERC20Contract extends ethers.Contract {"),
            "Expected interface to extend ethers.Contract, got:\n{out}"
        );
    }

    #[test]
    fn small_uint_is_number() {
        assert_eq!(sol_type_to_ethers5(&SolType::Uint(8)), "number");
        assert_eq!(sol_type_to_ethers5(&SolType::Uint(48)), "number");
    }

    #[test]
    fn large_uint_is_bignumber() {
        assert_eq!(sol_type_to_ethers5(&SolType::Uint(56)), "BigNumber");
        assert_eq!(sol_type_to_ethers5(&SolType::Uint(256)), "BigNumber");
    }

    #[test]
    fn large_int_is_bignumber() {
        assert_eq!(sol_type_to_ethers5(&SolType::Int(64)), "BigNumber");
        assert_eq!(sol_type_to_ethers5(&SolType::Int(256)), "BigNumber");
    }

    #[test]
    fn small_int_is_number() {
        assert_eq!(sol_type_to_ethers5(&SolType::Int(8)), "number");
        assert_eq!(sol_type_to_ethers5(&SolType::Int(48)), "number");
    }

    #[test]
    fn address_is_string() {
        assert_eq!(sol_type_to_ethers5(&SolType::Address), "string");
    }

    #[test]
    fn bytes_is_string() {
        assert_eq!(sol_type_to_ethers5(&SolType::Bytes), "string");
        assert_eq!(sol_type_to_ethers5(&SolType::BytesN(32)), "string");
    }

    #[test]
    fn dynamic_array_is_not_readonly() {
        let ty = SolType::Array(Box::new(SolType::Address));
        assert_eq!(sol_type_to_ethers5(&ty), "string[]");
    }

    #[test]
    fn fixed_array_is_plain_array() {
        let ty = SolType::FixedArray(Box::new(SolType::Uint(256)), 3);
        assert_eq!(sol_type_to_ethers5(&ty), "BigNumber[]");
    }

    #[test]
    fn tuple_inline_object() {
        let ty = SolType::Tuple(vec![
            TupleComponent {
                name: "shares".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            },
            TupleComponent {
                name: "token".into(),
                ty: SolType::Address,
                internal_type: None,
            },
        ]);
        assert_eq!(
            sol_type_to_ethers5(&ty),
            "{ shares: BigNumber; token: string }"
        );
    }

    #[test]
    fn input_param_large_uint_is_bignumberish() {
        assert_eq!(
            sol_type_to_ethers5_input(&SolType::Uint(256)),
            "BigNumberish"
        );
        assert_eq!(
            sol_type_to_ethers5_input(&SolType::Uint(64)),
            "BigNumberish"
        );
    }

    #[test]
    fn input_param_small_uint_is_number() {
        assert_eq!(sol_type_to_ethers5_input(&SolType::Uint(8)), "number");
        assert_eq!(sol_type_to_ethers5_input(&SolType::Uint(48)), "number");
    }

    #[test]
    fn view_fn_returning_void() {
        let ir = make_ir(
            "Minimal",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("ping(): Promise<void>;"),
            "Expected `Promise<void>` for view fn with no outputs, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_returning_multiple_outputs() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("getPair(): Promise<{ a: string; b: BigNumber }>;"),
            "Expected `Promise<{{ a: string; b: BigNumber }}>` for multi-output view fn with named outputs, got:\n{out}"
        );
    }

    #[test]
    fn contract_with_no_events_omits_filters() {
        let ir = make_ir(
            "NoEvents",
            vec![AbiFunction {
                name: "doSomething".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            !out.contains("filters"),
            "Expected no `filters` block when there are no events, got:\n{out}"
        );
    }

    #[test]
    fn event_with_only_non_indexed_params() {
        let ir = make_ir(
            "LogOnly",
            vec![],
            vec![AbiEvent {
                name: "DataStored".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "key".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "value".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("DataStored(): ethers.EventFilter;"),
            "Expected filter with no params for non-indexed event, got:\n{out}"
        );
    }

    #[test]
    fn pure_fn_returns_promise() {
        let ir = make_ir(
            "MathLib",
            vec![AbiFunction {
                name: "add".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::Pure,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("add(a: BigNumberish, b: BigNumberish): Promise<BigNumber>;"),
            "Expected `Promise<BigNumber>` for pure fn with BigNumberish inputs, got:\n{out}"
        );
    }

    #[test]
    fn vault_tuple_output_is_inline_type() {
        let out = render_ethers5_file(&vault());
        assert!(
            out.contains("getPosition(user: string): Promise<{"),
            "Expected tuple output for getPosition, got:\n{out}"
        );
        assert!(
            out.contains("shares: BigNumber"),
            "Expected BigNumber for shares field in tuple, got:\n{out}"
        );
    }

    #[test]
    fn non_overloaded_fn_keeps_original_name() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("transfer(to: string, amount: BigNumberish)"),
            "Expected `transfer(...)` without suffix, got:\n{out}"
        );
        assert!(
            !out.contains("transfer_0"),
            "Non-overloaded function should not get `_0` suffix, got:\n{out}"
        );
    }

    #[test]
    fn named_multi_return_produces_object_type() {
        let ir = make_ir(
            "Named",
            vec![AbiFunction {
                name: "getInfo".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "balance".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("getInfo(): Promise<{ owner: string; balance: BigNumber }>;"),
            "Expected named object return type, got:\n{out}"
        );
    }

    #[test]
    fn unnamed_multi_return_produces_tuple_type() {
        let ir = make_ir(
            "Unnamed",
            vec![AbiFunction {
                name: "getValues".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("getValues(): Promise<[string, BigNumber]>;"),
            "Expected positional tuple return type for unnamed outputs, got:\n{out}"
        );
    }

    #[test]
    fn mixed_named_unnamed_multi_return_produces_tuple() {
        let ir = make_ir(
            "Mixed",
            vec![AbiFunction {
                name: "getMixed".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers5_file(&ir);
        assert!(
            out.contains("getMixed(): Promise<[string, BigNumber]>;"),
            "Expected positional tuple when some outputs are unnamed, got:\n{out}"
        );
    }
}
