use crate::type_mapper::{overload_suffix, safe_param_name};
use abi_typegen_core::types::{ContractIr, SolType, TupleComponent};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

/// Kotlin hard keywords that cannot be used as identifiers.
///
/// This supplements the JS/TS reserved-word check in `safe_param_name` with
/// words that are legal identifiers in JavaScript but keywords in Kotlin
/// (e.g. `fun`, `val`, `when`, `object`, `is`, `as`).
const KOTLIN_KEYWORDS: &[&str] = &[
    "as",
    "break",
    "class",
    "continue",
    "do",
    "else",
    "false",
    "for",
    "fun",
    "if",
    "in",
    "interface",
    "is",
    "null",
    "object",
    "package",
    "return",
    "super",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "typeof",
    "val",
    "var",
    "when",
    "while",
];

/// Converts a parameter name to a Kotlin-safe identifier.
///
/// Checks both JS/TS reserved words (via `safe_param_name`) and Kotlin keywords,
/// since names like `fun`, `val`, `when`, `is`, `as` are valid in TypeScript but
/// keywords in Kotlin.
fn kotlin_safe_param_name(name: &str, index: usize) -> String {
    let base = safe_param_name(name, index);
    if KOTLIN_KEYWORDS.contains(&base.as_str()) {
        format!("_{}", base)
    } else {
        base
    }
}

/// Generates `<ContractName>.kt` — a Kotlin source file with data classes
/// compatible with web3j.
pub fn render_kotlin_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n\n");
    out.push_str("package contracts\n");

    // Conditional BigInteger import
    if ir_uses_big_integer(ir) {
        out.push_str("\nimport java.math.BigInteger\n");
    }

    // Count function name occurrences for overload detection
    let mut name_counts: HashMap<&str, u32> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    // Function param data classes
    for f in &ir.functions {
        if f.inputs.is_empty() {
            continue;
        }
        let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
        let suffix = if count > 1 {
            overload_suffix(&f.inputs)
        } else {
            String::new()
        };
        let class_name = format!(
            "{}{}{}Params",
            ir.name,
            f.name.to_upper_camel_case(),
            suffix
        );

        out.push('\n');
        // KDoc comment
        if let Some(ref natspec) = f.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/**\n * Parameters for the `{}` function.\n * {}\n */\n",
                    f.name, notice
                ));
            } else {
                out.push_str(&format!(
                    "/**\n * Parameters for the `{}` function.\n */\n",
                    f.name
                ));
            }
        } else {
            out.push_str(&format!(
                "/**\n * Parameters for the `{}` function.\n */\n",
                f.name
            ));
        }

        out.push_str(&format!("data class {}(\n", class_name));
        for (i, param) in f.inputs.iter().enumerate() {
            let prop_name = kotlin_safe_param_name(&param.name, i);
            let kt_type = sol_type_to_kotlin(&param.ty);
            out.push_str(&format!("    val {}: {},\n", prop_name, kt_type));
        }
        out.push_str(")\n");
    }

    // Event data classes
    for event in &ir.events {
        let class_name = format!("{}{}Event", ir.name, event.name);

        out.push('\n');
        if let Some(ref natspec) = event.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/**\n * The `{}` event.\n * {}\n */\n",
                    event.name, notice
                ));
            } else {
                out.push_str(&format!("/**\n * The `{}` event.\n */\n", event.name));
            }
        } else {
            out.push_str(&format!("/**\n * The `{}` event.\n */\n", event.name));
        }

        out.push_str(&format!("data class {}(\n", class_name));
        for (i, param) in event.inputs.iter().enumerate() {
            let prop_name = kotlin_safe_param_name(&param.name, i);
            let kt_type = sol_type_to_kotlin(&param.ty);
            out.push_str(&format!("    val {}: {},\n", prop_name, kt_type));
        }
        out.push_str(")\n");
    }

    // Error data classes
    for error in &ir.errors {
        if error.inputs.is_empty() {
            continue;
        }
        let class_name = format!("{}{}Error", ir.name, error.name);

        out.push('\n');
        if let Some(ref natspec) = error.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/**\n * The `{}` error.\n * {}\n */\n",
                    error.name, notice
                ));
            } else {
                out.push_str(&format!("/**\n * The `{}` error.\n */\n", error.name));
            }
        } else {
            out.push_str(&format!("/**\n * The `{}` error.\n */\n", error.name));
        }

        out.push_str(&format!("data class {}(\n", class_name));
        for (i, param) in error.inputs.iter().enumerate() {
            let prop_name = kotlin_safe_param_name(&param.name, i);
            let kt_type = sol_type_to_kotlin(&param.ty);
            out.push_str(&format!("    val {}: {},\n", prop_name, kt_type));
        }
        out.push_str(")\n");
    }

    // Ensure file ends with exactly one newline
    if !out.ends_with('\n') {
        out.push('\n');
    }

    out
}

/// Converts a Solidity type to its Kotlin type representation.
fn sol_type_to_kotlin(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "Boolean".into(),
        SolType::StringType => "String".into(),
        SolType::Address => "String".into(),
        SolType::Bytes | SolType::BytesN(_) => "ByteArray".into(),

        SolType::Uint(bits) => {
            if *bits <= 8 {
                "UByte".into()
            } else if *bits <= 16 {
                "UShort".into()
            } else if *bits <= 32 {
                "UInt".into()
            } else if *bits <= 64 {
                "ULong".into()
            } else {
                "BigInteger".into()
            }
        }

        SolType::Int(bits) => {
            if *bits <= 8 {
                "Byte".into()
            } else if *bits <= 16 {
                "Short".into()
            } else if *bits <= 32 {
                "Int".into()
            } else if *bits <= 64 {
                "Long".into()
            } else {
                "BigInteger".into()
            }
        }

        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            let inner_kt = sol_type_to_kotlin(inner);
            format!("List<{}>", inner_kt)
        }

        SolType::Tuple(components) => render_inline_data_class(components),
    }
}

/// Renders an inline Kotlin type for tuple types.
///
/// Since Kotlin does not support anonymous inline data classes, tuples are
/// rendered as a `Map<String, Any>` placeholder. In practice, top-level tuples
/// become their own named data class, so this is only hit for nested tuples.
fn render_inline_data_class(components: &[TupleComponent]) -> String {
    if components.is_empty() {
        return "Map<String, Any>".into();
    }
    // For nested tuples we produce a descriptive map type since Kotlin does not
    // support anonymous struct literals.
    let _ = components;
    "Map<String, Any>".into()
}

/// Returns `true` if any type in the contract IR maps to `BigInteger`.
fn ir_uses_big_integer(ir: &ContractIr) -> bool {
    let check_params = |params: &[abi_typegen_core::types::AbiParam]| -> bool {
        params.iter().any(|p| type_uses_big_integer(&p.ty))
    };
    let check_event_params = |params: &[abi_typegen_core::types::AbiEventParam]| -> bool {
        params.iter().any(|p| type_uses_big_integer(&p.ty))
    };

    ir.functions
        .iter()
        .any(|f| !f.inputs.is_empty() && check_params(&f.inputs))
        || ir.events.iter().any(|e| check_event_params(&e.inputs))
        || ir
            .errors
            .iter()
            .any(|e| !e.inputs.is_empty() && check_params(&e.inputs))
}

/// Returns `true` if the given Solidity type maps to a Kotlin type that uses `BigInteger`.
fn type_uses_big_integer(ty: &SolType) -> bool {
    match ty {
        SolType::Uint(bits) | SolType::Int(bits) => *bits > 64,
        SolType::Array(inner) | SolType::FixedArray(inner, _) => type_uses_big_integer(inner),
        SolType::Tuple(components) => components.iter().any(|c| type_uses_big_integer(&c.ty)),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{
        AbiError, AbiEvent, AbiEventParam, AbiFunction, AbiParam, NatSpec, SolType, StateMutability,
    };

    /// Helper to build a minimal ContractIr.
    fn make_ir(
        name: &str,
        functions: Vec<AbiFunction>,
        events: Vec<AbiEvent>,
        errors: Vec<AbiError>,
    ) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors,
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    fn token_ir() -> ContractIr {
        make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![AbiEvent {
                name: "Transfer".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "from".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
            vec![AbiError {
                name: "InsufficientBalance".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "account".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "available".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "required".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                natspec: None,
            }],
        )
    }

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    // ── Test 1: Header and package ─────────────────────────────────────

    #[test]
    fn kotlin_contains_header_and_package() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("// Auto-generated by abi-typegen. Do not edit manually."),
            "Expected auto-generated header, got:\n{out}"
        );
        assert!(
            out.contains("package contracts"),
            "Expected `package contracts`, got:\n{out}"
        );
    }

    // ── Test 2: Function params data class ─────────────────────────────

    #[test]
    fn kotlin_contains_transfer_params_data_class() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("data class TokenTransferParams("),
            "Expected `data class TokenTransferParams(`, got:\n{out}"
        );
        assert!(
            out.contains("    val to: String,"),
            "Expected field `val to: String,`, got:\n{out}"
        );
        assert!(
            out.contains("    val amount: BigInteger,"),
            "Expected field `val amount: BigInteger,`, got:\n{out}"
        );
    }

    // ── Test 3: Event data class ───────────────────────────────────────

    #[test]
    fn kotlin_event_data_class_generated() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("data class TokenTransferEvent("),
            "Expected `data class TokenTransferEvent(`, got:\n{out}"
        );
        assert!(
            out.contains("    val from: String,"),
            "Expected event field `val from: String,`, got:\n{out}"
        );
        assert!(
            out.contains("    val to: String,"),
            "Expected event field `val to: String,`, got:\n{out}"
        );
        assert!(
            out.contains("    val amount: BigInteger,"),
            "Expected event field `val amount: BigInteger,`, got:\n{out}"
        );
    }

    // ── Test 4: Error data class ───────────────────────────────────────

    #[test]
    fn kotlin_error_data_class_generated() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("data class TokenInsufficientBalanceError("),
            "Expected `data class TokenInsufficientBalanceError(`, got:\n{out}"
        );
        assert!(
            out.contains("    val account: String,"),
            "Expected error field `val account: String,`, got:\n{out}"
        );
        assert!(
            out.contains("    val available: BigInteger,"),
            "Expected error field `val available: BigInteger,`, got:\n{out}"
        );
        assert!(
            out.contains("    val required: BigInteger,"),
            "Expected error field `val required: BigInteger,`, got:\n{out}"
        );
    }

    // ── Test 5: BigInteger import ──────────────────────────────────────

    #[test]
    fn kotlin_imports_big_integer_when_needed() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("import java.math.BigInteger"),
            "Expected BigInteger import, got:\n{out}"
        );
    }

    #[test]
    fn kotlin_no_big_integer_import_when_not_needed() {
        let ir = make_ir(
            "Simple",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![AbiParam {
                    name: "flag".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            !out.contains("import java.math.BigInteger"),
            "Should not import BigInteger when no big types are used, got:\n{out}"
        );
    }

    // ── Test 6: Skip functions with no inputs ──────────────────────────

    #[test]
    fn kotlin_skips_params_for_no_input_functions() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "totalSupply".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            !out.contains("TotalSupplyParams"),
            "Should not generate params class for functions with no inputs, got:\n{out}"
        );
    }

    // ── Test 7: Type mappings ──────────────────────────────────────────

    #[test]
    fn kotlin_type_mapping_uint_widths() {
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(8)), "UByte");
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(16)), "UShort");
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(32)), "UInt");
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(64)), "ULong");
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(128)), "BigInteger");
        assert_eq!(sol_type_to_kotlin(&SolType::Uint(256)), "BigInteger");
    }

    #[test]
    fn kotlin_type_mapping_int_widths() {
        assert_eq!(sol_type_to_kotlin(&SolType::Int(8)), "Byte");
        assert_eq!(sol_type_to_kotlin(&SolType::Int(16)), "Short");
        assert_eq!(sol_type_to_kotlin(&SolType::Int(32)), "Int");
        assert_eq!(sol_type_to_kotlin(&SolType::Int(64)), "Long");
        assert_eq!(sol_type_to_kotlin(&SolType::Int(128)), "BigInteger");
        assert_eq!(sol_type_to_kotlin(&SolType::Int(256)), "BigInteger");
    }

    #[test]
    fn kotlin_type_mapping_basic_types() {
        assert_eq!(sol_type_to_kotlin(&SolType::Bool), "Boolean");
        assert_eq!(sol_type_to_kotlin(&SolType::StringType), "String");
        assert_eq!(sol_type_to_kotlin(&SolType::Address), "String");
        assert_eq!(sol_type_to_kotlin(&SolType::Bytes), "ByteArray");
        assert_eq!(sol_type_to_kotlin(&SolType::BytesN(32)), "ByteArray");
        assert_eq!(sol_type_to_kotlin(&SolType::BytesN(4)), "ByteArray");
    }

    #[test]
    fn kotlin_type_mapping_arrays() {
        let dynamic = SolType::Array(Box::new(SolType::Address));
        assert_eq!(sol_type_to_kotlin(&dynamic), "List<String>");

        let fixed = SolType::FixedArray(Box::new(SolType::Uint(256)), 3);
        assert_eq!(sol_type_to_kotlin(&fixed), "List<BigInteger>");
    }

    // ── Test 8: KDoc comments ──────────────────────────────────────────

    #[test]
    fn kotlin_kdoc_comments_on_classes() {
        let out = render_kotlin_file(&token_ir());
        assert!(
            out.contains("/**\n * Parameters for the `transfer` function.\n */"),
            "Expected KDoc on params class, got:\n{out}"
        );
        assert!(
            out.contains("/**\n * The `Transfer` event.\n */"),
            "Expected KDoc on event class, got:\n{out}"
        );
        assert!(
            out.contains("/**\n * The `InsufficientBalance` error.\n */"),
            "Expected KDoc on error class, got:\n{out}"
        );
    }

    // ── Test 9: NatSpec notice in KDoc ─────────────────────────────────

    #[test]
    fn kotlin_natspec_notice_included() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![AbiParam {
                    name: "to".to_string(),
                    ty: SolType::Address,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: Some(NatSpec {
                    notice: Some("Transfers tokens to a recipient.".to_string()),
                    dev: None,
                    params: Default::default(),
                    returns: Default::default(),
                }),
            }],
            vec![],
            vec![],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            out.contains("Transfers tokens to a recipient."),
            "Expected NatSpec notice in KDoc, got:\n{out}"
        );
    }

    // ── Test 10: ERC20 fixture ─────────────────────────────────────────

    #[test]
    fn kotlin_erc20_fixture_generates_valid_output() {
        let ir = erc20();
        let out = render_kotlin_file(&ir);
        assert!(out.contains("package contracts"));
        assert!(out.contains("import java.math.BigInteger"));
        assert!(out.contains("data class ERC20TransferParams("));
        assert!(out.contains("data class ERC20TransferEvent("));
        assert!(out.contains("data class ERC20ApprovalEvent("));
    }

    // ── Test 11: Trailing commas ───────────────────────────────────────

    #[test]
    fn kotlin_trailing_commas_on_fields() {
        let out = render_kotlin_file(&token_ir());
        // Every `val` line inside a data class should end with a trailing comma
        for line in out.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("val ") {
                assert!(
                    trimmed.ends_with(','),
                    "Expected trailing comma on field line: {trimmed}"
                );
            }
        }
    }

    // ── Test 12: Empty-input errors are skipped ────────────────────────

    #[test]
    fn kotlin_overloaded_deposit_produces_distinct_classes() {
        let ir = make_ir(
            "Vault",
            vec![
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![
                        AbiParam {
                            name: "amount".to_string(),
                            ty: SolType::Uint(256),
                            internal_type: None,
                        },
                        AbiParam {
                            name: "recipient".to_string(),
                            ty: SolType::Address,
                            internal_type: None,
                        },
                    ],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
            ],
            vec![],
            vec![],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            out.contains("data class VaultDepositUint256Params("),
            "Expected `data class VaultDepositUint256Params(`, got:\n{out}"
        );
        assert!(
            out.contains("data class VaultDepositUint256AddressParams("),
            "Expected `data class VaultDepositUint256AddressParams(`, got:\n{out}"
        );
        // Ensure no duplicates
        let count = out.matches("data class VaultDepositUint256Params(").count();
        assert_eq!(
            count, 1,
            "Expected exactly 1 VaultDepositUint256Params, found {count}"
        );
    }

    #[test]
    fn kotlin_keywords_escaped_in_field_names() {
        assert_eq!(kotlin_safe_param_name("fun", 0), "_fun");
        assert_eq!(kotlin_safe_param_name("val", 0), "_val");
        assert_eq!(kotlin_safe_param_name("when", 0), "_when");
        assert_eq!(kotlin_safe_param_name("object", 0), "_object");
        assert_eq!(kotlin_safe_param_name("is", 0), "_is");
        assert_eq!(kotlin_safe_param_name("as", 0), "_as");
        assert_eq!(kotlin_safe_param_name("typealias", 0), "_typealias");
        // Non-keywords should pass through unchanged
        assert_eq!(kotlin_safe_param_name("amount", 0), "amount");
        assert_eq!(kotlin_safe_param_name("from", 0), "from");
        assert_eq!(kotlin_safe_param_name("to", 0), "to");
    }

    #[test]
    fn kotlin_fun_param_escaped() {
        let ir = make_ir(
            "Dispatcher",
            vec![AbiFunction {
                name: "dispatch".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "fun".to_string(),
                        ty: SolType::Uint(8),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "data".to_string(),
                        ty: SolType::Bytes,
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            out.contains("val _fun: UByte"),
            "Expected `_fun` field (escaped Kotlin keyword), got:\n{out}"
        );
        assert!(
            out.contains("val data: ByteArray"),
            "Expected `data` field unchanged, got:\n{out}"
        );
    }

    #[test]
    fn kotlin_skips_errors_with_no_inputs() {
        let ir = make_ir(
            "Vault",
            vec![],
            vec![],
            vec![AbiError {
                name: "Unauthorized".to_string(),
                inputs: vec![],
                natspec: None,
            }],
        );
        let out = render_kotlin_file(&ir);
        assert!(
            !out.contains("Unauthorized"),
            "Should not generate data class for errors with no inputs, got:\n{out}"
        );
    }
}
