//! Rust/Alloy code generation from Solidity ABI intermediate representation.

use crate::type_mapper::{overload_suffix, safe_param_name};
use abi_typegen_core::types::{AbiEventParam, AbiParam, ContractIr, SolType, StateMutability};
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::collections::{BTreeSet, HashMap};

/// Known Alloy/std imports that we conditionally include.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Import {
    Address,
    Bytes,
    FixedBytes,
    U256,
    I256,
}

impl Import {
    fn as_str(self) -> &'static str {
        match self {
            Import::Address => "Address",
            Import::Bytes => "Bytes",
            Import::FixedBytes => "FixedBytes",
            Import::U256 => "U256",
            Import::I256 => "I256",
        }
    }
}

/// Generates `<ContractName>.rs` — Rust structs compatible with Alloy.
pub fn render_rust_file(ir: &ContractIr) -> String {
    let mut out = String::new();
    let mut imports = BTreeSet::new();
    let mut structs = Vec::new();

    // Count function name occurrences for overload detection
    let mut name_counts: HashMap<&str, u32> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    // Functions — params and returns structs
    for f in &ir.functions {
        if !f.inputs.is_empty() {
            let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
            let suffix = if count > 1 {
                overload_suffix(&f.inputs)
            } else {
                String::new()
            };
            let struct_name = format!(
                "{}{}{}Params",
                ir.name,
                f.name.to_upper_camel_case(),
                suffix
            );
            let doc = natspec_doc_comment(
                &format!("Parameters for the `{}` function.", f.name),
                &f.natspec,
            );
            structs.push(render_struct(
                &struct_name,
                &doc,
                &params_to_fields(&f.inputs),
                &mut imports,
            ));
        }

        // Returns struct for view/pure with multiple outputs
        if matches!(
            f.state_mutability,
            StateMutability::Pure | StateMutability::View
        ) && f.outputs.len() > 1
        {
            let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
            let suffix = if count > 1 {
                overload_suffix(&f.inputs)
            } else {
                String::new()
            };
            let struct_name = format!(
                "{}{}{}Returns",
                ir.name,
                f.name.to_upper_camel_case(),
                suffix
            );
            let doc = natspec_doc_comment(
                &format!("Return values for the `{}` function.", f.name),
                &f.natspec,
            );
            structs.push(render_struct(
                &struct_name,
                &doc,
                &params_to_fields(&f.outputs),
                &mut imports,
            ));
        }
    }

    // Events
    for event in &ir.events {
        let struct_name = format!("{}{}Event", ir.name, event.name.to_upper_camel_case());
        let doc = natspec_doc_comment(&format!("The `{}` event.", event.name), &event.natspec);
        structs.push(render_struct(
            &struct_name,
            &doc,
            &event_params_to_fields(&event.inputs),
            &mut imports,
        ));
    }

    // Errors
    for error in &ir.errors {
        let struct_name = format!("{}{}Error", ir.name, error.name.to_upper_camel_case());
        let doc = natspec_doc_comment(&format!("The `{}` error.", error.name), &error.natspec);
        structs.push(render_struct(
            &struct_name,
            &doc,
            &params_to_fields(&error.inputs),
            &mut imports,
        ));
    }

    // File header
    out.push_str("//! Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str(&format!(
        "//! Type definitions for the {} contract.\n",
        ir.name
    ));
    out.push('\n');

    // Imports — only include types that are actually used
    if !imports.is_empty() {
        let alloy_imports: Vec<&str> = imports.iter().map(|i| i.as_str()).collect();
        out.push_str(&format!(
            "use alloy_primitives::{{{}}};\n",
            alloy_imports.join(", ")
        ));
    }
    out.push_str("use serde::{Deserialize, Serialize};\n");

    // Append all structs
    for s in &structs {
        out.push('\n');
        out.push_str(s);
    }

    out
}

/// A field in a generated struct.
struct FieldDef {
    name: String,
    ty: String,
    sol_ty: SolType,
}

/// Rust keywords that cannot be used as identifiers without `r#` prefix.
///
/// This supplements the JS/TS reserved-word check in `safe_param_name` with
/// words that are legal identifiers in JavaScript but keywords in Rust
/// (e.g. `type`, `fn`, `self`, `as`).
const RUST_KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
    "where", "while", "yield",
];

/// Converts a parameter name to a Rust-safe snake_case field name.
///
/// Checks both JS/TS reserved words (via `safe_param_name`) and Rust keywords,
/// since names like `type` are valid in TypeScript but keywords in Rust.
fn rust_safe_param_name(name: &str, index: usize) -> String {
    let base = safe_param_name(name, index);
    let snake = base.to_snake_case();
    if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("_{}", snake)
    } else {
        snake
    }
}

/// Converts ABI params (function inputs/outputs, error inputs) into field definitions.
fn params_to_fields(params: &[AbiParam]) -> Vec<FieldDef> {
    params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let field_name = rust_safe_param_name(&p.name, i);
            FieldDef {
                name: field_name,
                ty: sol_type_to_rust(&p.ty),
                sol_ty: p.ty.clone(),
            }
        })
        .collect()
}

/// Converts ABI event params into field definitions.
fn event_params_to_fields(params: &[AbiEventParam]) -> Vec<FieldDef> {
    params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let field_name = rust_safe_param_name(&p.name, i);
            FieldDef {
                name: field_name,
                ty: sol_type_to_rust(&p.ty),
                sol_ty: p.ty.clone(),
            }
        })
        .collect()
}

/// Renders a single Rust struct with derives and doc comments.
fn render_struct(
    name: &str,
    doc: &str,
    fields: &[FieldDef],
    imports: &mut BTreeSet<Import>,
) -> String {
    let mut out = String::new();

    // Collect imports from field types
    for field in fields {
        collect_imports(&field.sol_ty, imports);
    }

    // Doc comment
    out.push_str(doc);

    // Derive and struct declaration
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", name));

    for field in fields {
        out.push_str(&format!("    pub {}: {},\n", field.name, field.ty));
    }

    out.push_str("}\n");
    out
}

/// Builds a doc comment string from a summary line and optional NatSpec.
fn natspec_doc_comment(
    summary: &str,
    natspec: &Option<abi_typegen_core::types::NatSpec>,
) -> String {
    let mut doc = format!("/// {}\n", summary);
    if let Some(ns) = natspec {
        if let Some(notice) = &ns.notice {
            doc.push_str(&format!("///\n/// {}\n", notice));
        }
        if let Some(dev) = &ns.dev {
            doc.push_str(&format!("///\n/// Dev: {}\n", dev));
        }
    }
    doc
}

/// Inspects a [`SolType`] and records which Alloy imports the rendered type requires.
fn collect_imports(sol_ty: &SolType, imports: &mut BTreeSet<Import>) {
    match sol_ty {
        SolType::Address => {
            imports.insert(Import::Address);
        }
        SolType::Bytes => {
            imports.insert(Import::Bytes);
        }
        SolType::BytesN(_) => {
            imports.insert(Import::FixedBytes);
        }
        SolType::Uint(bits) if *bits > 128 => {
            imports.insert(Import::U256);
        }
        SolType::Int(bits) if *bits > 128 => {
            imports.insert(Import::I256);
        }
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            collect_imports(inner, imports);
        }
        SolType::Tuple(fields) => {
            for f in fields {
                collect_imports(&f.ty, imports);
            }
        }
        // bool, string, uint≤128, int≤128 — no Alloy imports needed
        _ => {}
    }
}

/// Maps a Solidity type to its Rust/Alloy equivalent.
fn sol_type_to_rust(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "bool".into(),
        SolType::StringType => "String".into(),
        SolType::Address => "Address".into(),
        SolType::Bytes => "Bytes".into(),
        SolType::BytesN(n) => format!("FixedBytes<{}>", n),

        SolType::Uint(bits) => uint_to_rust(*bits),
        SolType::Int(bits) => int_to_rust(*bits),

        SolType::Array(inner) => {
            let inner_ty = sol_type_to_rust(inner);
            format!("Vec<{}>", inner_ty)
        }

        SolType::FixedArray(inner, n) => {
            let inner_ty = sol_type_to_rust(inner);
            format!("[{}; {}]", inner_ty, n)
        }

        SolType::Tuple(components) => {
            // For tuple types, generate an inline tuple (or a named struct
            // would require a separate definition). We use a Rust tuple here.
            if components.is_empty() {
                "()".into()
            } else {
                let fields: Vec<String> =
                    components.iter().map(|c| sol_type_to_rust(&c.ty)).collect();
                format!("({})", fields.join(", "))
            }
        }
    }
}

/// Maps `uintN` bit width to the smallest Rust unsigned type that fits.
fn uint_to_rust(bits: u16) -> String {
    match bits {
        0..=8 => "u8".into(),
        9..=16 => "u16".into(),
        17..=32 => "u32".into(),
        33..=64 => "u64".into(),
        65..=128 => "u128".into(),
        _ => "U256".into(),
    }
}

/// Maps `intN` bit width to the smallest Rust signed type that fits.
fn int_to_rust(bits: u16) -> String {
    match bits {
        0..=8 => "i8".into(),
        9..=16 => "i16".into(),
        17..=32 => "i32".into(),
        33..=64 => "i64".into(),
        65..=128 => "i128".into(),
        _ => "I256".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{
        AbiError, AbiEvent, AbiEventParam, AbiFunction, AbiParam, NatSpec, SolType, TupleComponent,
    };

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    /// Helper to build a minimal ContractIr.
    fn make_ir(
        name: &str,
        functions: Vec<AbiFunction>,
        events: Vec<AbiEvent>,
        errors: Vec<AbiError>,
    ) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors,
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    // --- Test 1: Contains `use alloy_primitives` ---
    #[test]
    fn contains_alloy_primitives_import() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("use alloy_primitives"),
            "Expected alloy_primitives import, got:\n{out}"
        );
    }

    // --- Test 2: Contains `pub struct TokenTransferParams` ---
    #[test]
    fn contains_transfer_params_struct() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub struct TokenTransferParams"),
            "Expected `pub struct TokenTransferParams`, got:\n{out}"
        );
    }

    // --- Test 3: Field names are snake_case ---
    #[test]
    fn field_names_are_snake_case() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transferFrom".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "fromAddress".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "toAddress".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "tokenAmount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub from_address: Address"),
            "Expected snake_case field `from_address`, got:\n{out}"
        );
        assert!(
            out.contains("pub to_address: Address"),
            "Expected snake_case field `to_address`, got:\n{out}"
        );
        assert!(
            out.contains("pub token_amount: U256"),
            "Expected snake_case field `token_amount`, got:\n{out}"
        );
    }

    // --- Test 4: Contains Serialize, Deserialize derives ---
    #[test]
    fn contains_serde_derives() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("Serialize, Deserialize"),
            "Expected Serialize, Deserialize derives, got:\n{out}"
        );
    }

    // --- Test 5: Contains `pub to: Address` ---
    #[test]
    fn contains_address_field() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub to: Address"),
            "Expected `pub to: Address`, got:\n{out}"
        );
    }

    // --- Test 6: Event struct generated with correct name ---
    #[test]
    fn event_struct_generated() {
        let ir = make_ir(
            "Token",
            vec![],
            vec![AbiEvent {
                name: "Transfer".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "from".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub struct TokenTransferEvent"),
            "Expected `pub struct TokenTransferEvent`, got:\n{out}"
        );
        assert!(
            out.contains("pub from: Address"),
            "Expected `pub from: Address` in event struct, got:\n{out}"
        );
    }

    // --- Additional coverage ---

    #[test]
    fn error_struct_generated() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("pub struct ERC20Erc20InsufficientBalanceError"),
            "Expected error struct, got:\n{out}"
        );
    }

    #[test]
    fn skips_functions_with_no_inputs() {
        let out = render_rust_file(&erc20());
        // `name()`, `symbol()`, `decimals()`, `totalSupply()` have no inputs
        assert!(
            !out.contains("NameParams"),
            "Should not generate Params struct for zero-input function, got:\n{out}"
        );
        assert!(
            !out.contains("SymbolParams"),
            "Should not generate Params struct for zero-input function, got:\n{out}"
        );
    }

    #[test]
    fn generates_params_for_functions_with_inputs() {
        let out = render_rust_file(&erc20());
        // transfer has inputs
        assert!(
            out.contains("pub struct ERC20TransferParams"),
            "Expected ERC20TransferParams, got:\n{out}"
        );
        // balanceOf has inputs
        assert!(
            out.contains("pub struct ERC20BalanceOfParams"),
            "Expected ERC20BalanceOfParams, got:\n{out}"
        );
    }

    #[test]
    fn only_imports_used_types() {
        let ir = make_ir(
            "Simple",
            vec![AbiFunction {
                name: "setFlag".to_string(),
                inputs: vec![AbiParam {
                    name: "flag".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        // bool doesn't require alloy_primitives at all
        assert!(
            !out.contains("use alloy_primitives"),
            "Should not import alloy_primitives when only bool is used, got:\n{out}"
        );
    }

    #[test]
    fn file_header_contains_contract_name() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("//! Type definitions for the ERC20 contract."),
            "Expected contract name in header, got:\n{out}"
        );
    }

    #[test]
    fn doc_comment_on_struct() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("/// Parameters for the `transfer` function."),
            "Expected doc comment, got:\n{out}"
        );
    }

    #[test]
    fn vault_event_struct() {
        let out = render_rust_file(&vault());
        assert!(
            out.contains("pub struct VaultDepositedEvent"),
            "Expected VaultDepositedEvent struct, got:\n{out}"
        );
    }

    #[test]
    fn vault_error_struct() {
        let out = render_rust_file(&vault());
        assert!(
            out.contains("pub struct VaultInsufficientSharesError"),
            "Expected VaultInsufficientSharesError struct, got:\n{out}"
        );
    }

    #[test]
    fn vault_params_for_overloaded_functions() {
        let out = render_rust_file(&vault());
        // Both deposit overloads should generate disambiguated params structs
        assert!(
            out.contains("pub struct VaultDepositUint256Params"),
            "Expected VaultDepositUint256Params struct, got:\n{out}"
        );
        assert!(
            out.contains("pub struct VaultDepositUint256AddressParams"),
            "Expected VaultDepositUint256AddressParams struct, got:\n{out}"
        );
    }

    #[test]
    fn type_mapping_uint_sizes() {
        assert_eq!(sol_type_to_rust(&SolType::Uint(8)), "u8");
        assert_eq!(sol_type_to_rust(&SolType::Uint(16)), "u16");
        assert_eq!(sol_type_to_rust(&SolType::Uint(32)), "u32");
        assert_eq!(sol_type_to_rust(&SolType::Uint(64)), "u64");
        assert_eq!(sol_type_to_rust(&SolType::Uint(128)), "u128");
        assert_eq!(sol_type_to_rust(&SolType::Uint(256)), "U256");
    }

    #[test]
    fn type_mapping_int_sizes() {
        assert_eq!(sol_type_to_rust(&SolType::Int(8)), "i8");
        assert_eq!(sol_type_to_rust(&SolType::Int(16)), "i16");
        assert_eq!(sol_type_to_rust(&SolType::Int(32)), "i32");
        assert_eq!(sol_type_to_rust(&SolType::Int(64)), "i64");
        assert_eq!(sol_type_to_rust(&SolType::Int(128)), "i128");
        assert_eq!(sol_type_to_rust(&SolType::Int(256)), "I256");
    }

    #[test]
    fn type_mapping_odd_widths() {
        // uint24 → next larger = u32
        assert_eq!(sol_type_to_rust(&SolType::Uint(24)), "u32");
        // uint48 → next larger = u64
        assert_eq!(sol_type_to_rust(&SolType::Uint(48)), "u64");
        // uint160 → U256 (no u160 primitive)
        assert_eq!(sol_type_to_rust(&SolType::Uint(160)), "U256");
        // int24 → i32
        assert_eq!(sol_type_to_rust(&SolType::Int(24)), "i32");
    }

    #[test]
    fn type_mapping_address() {
        assert_eq!(sol_type_to_rust(&SolType::Address), "Address");
    }

    #[test]
    fn type_mapping_bytes() {
        assert_eq!(sol_type_to_rust(&SolType::Bytes), "Bytes");
        assert_eq!(sol_type_to_rust(&SolType::BytesN(32)), "FixedBytes<32>");
        assert_eq!(sol_type_to_rust(&SolType::BytesN(1)), "FixedBytes<1>");
    }

    #[test]
    fn type_mapping_string() {
        assert_eq!(sol_type_to_rust(&SolType::StringType), "String");
    }

    #[test]
    fn type_mapping_array() {
        let ty = SolType::Array(Box::new(SolType::Address));
        assert_eq!(sol_type_to_rust(&ty), "Vec<Address>");
    }

    #[test]
    fn type_mapping_fixed_array() {
        let ty = SolType::FixedArray(Box::new(SolType::Uint(256)), 3);
        assert_eq!(sol_type_to_rust(&ty), "[U256; 3]");
    }

    #[test]
    fn type_mapping_tuple() {
        let ty = SolType::Tuple(vec![
            TupleComponent {
                name: "shares".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            },
            TupleComponent {
                name: "token".into(),
                ty: SolType::Address,
                internal_type: None,
            },
        ]);
        assert_eq!(sol_type_to_rust(&ty), "(U256, Address)");
    }

    #[test]
    fn type_mapping_bool() {
        assert_eq!(sol_type_to_rust(&SolType::Bool), "bool");
    }

    #[test]
    fn natspec_notice_in_doc_comment() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![AbiParam {
                    name: "to".to_string(),
                    ty: SolType::Address,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: Some(NatSpec {
                    notice: Some("Transfer tokens to a recipient".to_string()),
                    dev: None,
                    params: Default::default(),
                    returns: Default::default(),
                }),
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("/// Transfer tokens to a recipient"),
            "Expected NatSpec notice in doc comment, got:\n{out}"
        );
    }

    #[test]
    fn returns_struct_for_multi_output_view() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![AbiParam {
                    name: "id".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub struct MultiGetPairParams"),
            "Expected params struct, got:\n{out}"
        );
        assert!(
            out.contains("pub struct MultiGetPairReturns"),
            "Expected returns struct for multi-output view fn, got:\n{out}"
        );
    }

    #[test]
    fn no_returns_struct_for_single_output() {
        let ir = make_ir(
            "Single",
            vec![AbiFunction {
                name: "getValue".to_string(),
                inputs: vec![AbiParam {
                    name: "key".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            !out.contains("Returns"),
            "Should not generate Returns struct for single output, got:\n{out}"
        );
    }

    #[test]
    fn no_returns_struct_for_nonpayable() {
        let ir = make_ir(
            "Writer",
            vec![AbiFunction {
                name: "write".to_string(),
                inputs: vec![AbiParam {
                    name: "data".to_string(),
                    ty: SolType::Bytes,
                    internal_type: None,
                }],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            !out.contains("Returns"),
            "Should not generate Returns struct for non-view function, got:\n{out}"
        );
    }

    #[test]
    fn serde_import_always_present() {
        let ir = make_ir("Empty", vec![], vec![], vec![]);
        let out = render_rust_file(&ir);
        assert!(
            out.contains("use serde::{Deserialize, Serialize};"),
            "Expected serde import even with no structs, got:\n{out}"
        );
    }

    #[test]
    fn overloaded_deposit_produces_distinct_structs() {
        let ir = make_ir(
            "Vault",
            vec![
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![
                        AbiParam {
                            name: "amount".to_string(),
                            ty: SolType::Uint(256),
                            internal_type: None,
                        },
                        AbiParam {
                            name: "recipient".to_string(),
                            ty: SolType::Address,
                            internal_type: None,
                        },
                    ],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
            ],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub struct VaultDepositUint256Params"),
            "Expected `pub struct VaultDepositUint256Params`, got:\n{out}"
        );
        assert!(
            out.contains("pub struct VaultDepositUint256AddressParams"),
            "Expected `pub struct VaultDepositUint256AddressParams`, got:\n{out}"
        );
        // Ensure names are different (no duplicates)
        let count = out.matches("pub struct VaultDepositUint256Params").count();
        assert_eq!(
            count, 1,
            "Expected exactly 1 VaultDepositUint256Params, found {count}"
        );
    }

    #[test]
    fn rust_keywords_escaped_in_field_names() {
        assert_eq!(rust_safe_param_name("type", 0), "_type");
        assert_eq!(rust_safe_param_name("fn", 0), "_fn");
        assert_eq!(rust_safe_param_name("self", 0), "_self");
        assert_eq!(rust_safe_param_name("as", 0), "_as");
        assert_eq!(rust_safe_param_name("async", 0), "_async");
        assert_eq!(rust_safe_param_name("match", 0), "_match");
        assert_eq!(rust_safe_param_name("loop", 0), "_loop");
        assert_eq!(rust_safe_param_name("trait", 0), "_trait");
        // Non-keywords should pass through unchanged
        assert_eq!(rust_safe_param_name("amount", 0), "amount");
        assert_eq!(rust_safe_param_name("from", 0), "from");
        assert_eq!(rust_safe_param_name("to", 0), "to");
    }

    #[test]
    fn type_param_generates_valid_field() {
        let ir = make_ir(
            "Registry",
            vec![AbiFunction {
                name: "register".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "type".to_string(),
                        ty: SolType::Uint(8),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "name".to_string(),
                        ty: SolType::StringType,
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_rust_file(&ir);
        assert!(
            out.contains("pub _type: u8"),
            "Expected `_type` field (escaped Rust keyword), got:\n{out}"
        );
        assert!(
            out.contains("pub name: String"),
            "Expected `name` field unchanged, got:\n{out}"
        );
    }

    #[test]
    fn auto_generated_header() {
        let out = render_rust_file(&erc20());
        assert!(
            out.contains("//! Auto-generated by abi-typegen. Do not edit manually."),
            "Expected auto-generated header, got:\n{out}"
        );
    }
}
