use crate::type_mapper::{overload_suffix, safe_param_name};
use abi_typegen_core::types::{ContractIr, SolType, TupleComponent};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

/// Swift keywords that cannot be used as identifiers without backtick escaping.
///
/// This supplements the JS/TS reserved-word check in `safe_param_name` with
/// words that are legal identifiers in JavaScript but keywords in Swift
/// (e.g. `func`, `let`, `var`, `is`, `as`, `self`).
const SWIFT_KEYWORDS: &[&str] = &[
    "Any",
    "Self",
    "as",
    "associatedtype",
    "break",
    "case",
    "catch",
    "class",
    "continue",
    "default",
    "defer",
    "deinit",
    "do",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "for",
    "func",
    "guard",
    "if",
    "import",
    "in",
    "init",
    "inout",
    "internal",
    "is",
    "let",
    "nil",
    "open",
    "operator",
    "private",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "where",
    "while",
];

/// Converts a parameter name to a Swift-safe identifier.
///
/// Checks both JS/TS reserved words (via `safe_param_name`) and Swift keywords,
/// since names like `is`, `as`, `func`, `let` are valid in TypeScript but
/// keywords in Swift.
fn swift_safe_param_name(name: &str, index: usize) -> String {
    let base = safe_param_name(name, index);
    if SWIFT_KEYWORDS.contains(&base.as_str()) {
        format!("_{}", base)
    } else {
        base
    }
}

/// Generates `<ContractName>.swift` — a Swift source file with typed structs
/// compatible with web3swift.
pub fn render_swift_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n\n");

    // Imports
    out.push_str("import Foundation\n");
    if ir_uses_big(ir) {
        out.push_str("import BigInt\n");
    }
    out.push_str("import web3swift\n");

    // Count function name occurrences for overload detection
    let mut name_counts: HashMap<&str, u32> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    // Function param structs
    for f in &ir.functions {
        if f.inputs.is_empty() {
            continue;
        }
        let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
        let suffix = if count > 1 {
            overload_suffix(&f.inputs)
        } else {
            String::new()
        };
        let struct_name = format!(
            "{}{}{}Params",
            ir.name,
            f.name.to_upper_camel_case(),
            suffix
        );

        out.push('\n');
        // Doc comment
        if let Some(ref natspec) = f.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/// Parameters for the `{}` function.\n/// {}\n",
                    f.name, notice
                ));
            } else {
                out.push_str(&format!("/// Parameters for the `{}` function.\n", f.name));
            }
        } else {
            out.push_str(&format!("/// Parameters for the `{}` function.\n", f.name));
        }

        out.push_str(&format!("struct {} {{\n", struct_name));
        for (i, param) in f.inputs.iter().enumerate() {
            let field_name = swift_safe_param_name(&param.name, i);
            let swift_type = sol_type_to_swift(&param.ty);
            out.push_str(&format!("    let {}: {}\n", field_name, swift_type));
        }
        out.push_str("}\n");
    }

    // Event structs
    for event in &ir.events {
        let struct_name = format!("{}{}Event", ir.name, event.name);

        out.push('\n');
        if let Some(ref natspec) = event.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/// The `{}` event.\n/// {}\n",
                    event.name, notice
                ));
            } else {
                out.push_str(&format!("/// The `{}` event.\n", event.name));
            }
        } else {
            out.push_str(&format!("/// The `{}` event.\n", event.name));
        }

        out.push_str(&format!("struct {} {{\n", struct_name));
        for (i, param) in event.inputs.iter().enumerate() {
            let field_name = swift_safe_param_name(&param.name, i);
            let swift_type = sol_type_to_swift(&param.ty);
            out.push_str(&format!("    let {}: {}\n", field_name, swift_type));
        }
        out.push_str("}\n");
    }

    // Error structs
    for error in &ir.errors {
        if error.inputs.is_empty() {
            continue;
        }
        let struct_name = format!("{}{}Error", ir.name, error.name);

        out.push('\n');
        if let Some(ref natspec) = error.natspec {
            if let Some(ref notice) = natspec.notice {
                out.push_str(&format!(
                    "/// The `{}` error.\n/// {}\n",
                    error.name, notice
                ));
            } else {
                out.push_str(&format!("/// The `{}` error.\n", error.name));
            }
        } else {
            out.push_str(&format!("/// The `{}` error.\n", error.name));
        }

        out.push_str(&format!("struct {} {{\n", struct_name));
        for (i, param) in error.inputs.iter().enumerate() {
            let field_name = swift_safe_param_name(&param.name, i);
            let swift_type = sol_type_to_swift(&param.ty);
            out.push_str(&format!("    let {}: {}\n", field_name, swift_type));
        }
        out.push_str("}\n");
    }

    // Ensure file ends with exactly one newline
    if !out.ends_with('\n') {
        out.push('\n');
    }

    out
}

/// Converts a Solidity type to its Swift type representation.
fn sol_type_to_swift(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "Bool".into(),
        SolType::StringType => "String".into(),
        SolType::Address => "EthereumAddress".into(),
        SolType::Bytes | SolType::BytesN(_) => "Data".into(),

        SolType::Uint(bits) => {
            if *bits <= 8 {
                "UInt8".into()
            } else if *bits <= 16 {
                "UInt16".into()
            } else if *bits <= 32 {
                "UInt32".into()
            } else if *bits <= 64 {
                "UInt64".into()
            } else {
                "BigUInt".into()
            }
        }

        SolType::Int(bits) => {
            if *bits <= 8 {
                "Int8".into()
            } else if *bits <= 16 {
                "Int16".into()
            } else if *bits <= 32 {
                "Int32".into()
            } else if *bits <= 64 {
                "Int64".into()
            } else {
                "BigInt".into()
            }
        }

        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            let inner_swift = sol_type_to_swift(inner);
            format!("[{}]", inner_swift)
        }

        SolType::Tuple(components) => render_inline_struct(components),
    }
}

/// Renders an inline Swift struct literal type for tuple types.
/// Since Swift doesn't have anonymous struct literals like Go, we use a tuple
/// with labeled elements.
fn render_inline_struct(components: &[TupleComponent]) -> String {
    if components.is_empty() {
        return "()".into();
    }
    let fields: Vec<String> = components
        .iter()
        .enumerate()
        .map(|(i, c)| {
            let name = swift_safe_param_name(&c.name, i);
            let swift_type = sol_type_to_swift(&c.ty);
            format!("{}: {}", name, swift_type)
        })
        .collect();
    format!("({})", fields.join(", "))
}

/// Returns `true` if any type in the contract IR uses `BigUInt` or `BigInt`.
fn ir_uses_big(ir: &ContractIr) -> bool {
    let check_params = |params: &[abi_typegen_core::types::AbiParam]| -> bool {
        params.iter().any(|p| type_uses_big(&p.ty))
    };
    let check_event_params = |params: &[abi_typegen_core::types::AbiEventParam]| -> bool {
        params.iter().any(|p| type_uses_big(&p.ty))
    };

    ir.functions
        .iter()
        .any(|f| check_params(&f.inputs) || check_params(&f.outputs))
        || ir.events.iter().any(|e| check_event_params(&e.inputs))
        || ir.errors.iter().any(|e| check_params(&e.inputs))
}

/// Returns `true` if the given Solidity type maps to a Swift type that uses
/// `BigUInt` or `BigInt`.
fn type_uses_big(ty: &SolType) -> bool {
    match ty {
        SolType::Uint(bits) | SolType::Int(bits) => *bits > 64,
        SolType::Array(inner) | SolType::FixedArray(inner, _) => type_uses_big(inner),
        SolType::Tuple(components) => components.iter().any(|c| type_uses_big(&c.ty)),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{
        AbiError, AbiEvent, AbiEventParam, AbiFunction, AbiParam, NatSpec, SolType, StateMutability,
    };

    /// Helper to build a minimal ContractIr.
    fn make_ir(
        name: &str,
        functions: Vec<AbiFunction>,
        events: Vec<AbiEvent>,
        errors: Vec<AbiError>,
    ) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors,
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    fn token_ir() -> ContractIr {
        make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![AbiEvent {
                name: "Transfer".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "from".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
            vec![AbiError {
                name: "InsufficientBalance".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "account".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "available".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "required".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                natspec: None,
            }],
        )
    }

    #[test]
    fn swift_contains_header() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("Auto-generated by abi-typegen. Do not edit manually."),
            "Expected header comment, got:\n{out}"
        );
    }

    #[test]
    fn swift_contains_imports() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("import Foundation"),
            "Expected Foundation import, got:\n{out}"
        );
        assert!(
            out.contains("import web3swift"),
            "Expected web3swift import, got:\n{out}"
        );
    }

    #[test]
    fn swift_contains_transfer_params_struct() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("struct TokenTransferParams {"),
            "Expected `struct TokenTransferParams`, got:\n{out}"
        );
        assert!(
            out.contains("let to: EthereumAddress"),
            "Expected `let to: EthereumAddress`, got:\n{out}"
        );
        assert!(
            out.contains("let amount: BigUInt"),
            "Expected `let amount: BigUInt`, got:\n{out}"
        );
    }

    #[test]
    fn swift_event_struct_generated() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("struct TokenTransferEvent {"),
            "Expected `struct TokenTransferEvent`, got:\n{out}"
        );
        assert!(
            out.contains("let from: EthereumAddress"),
            "Expected event field `let from: EthereumAddress`, got:\n{out}"
        );
    }

    #[test]
    fn swift_error_struct_generated() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("struct TokenInsufficientBalanceError {"),
            "Expected `struct TokenInsufficientBalanceError`, got:\n{out}"
        );
        assert!(
            out.contains("let account: EthereumAddress"),
            "Expected error field `let account: EthereumAddress`, got:\n{out}"
        );
        assert!(
            out.contains("let available: BigUInt"),
            "Expected error field `let available: BigUInt`, got:\n{out}"
        );
        assert!(
            out.contains("let required: BigUInt"),
            "Expected error field `let required: BigUInt`, got:\n{out}"
        );
    }

    #[test]
    fn swift_imports_bigint_when_needed() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("import BigInt"),
            "Expected `import BigInt`, got:\n{out}"
        );
    }

    #[test]
    fn swift_no_bigint_import_when_not_needed() {
        let ir = make_ir(
            "Simple",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![AbiParam {
                    name: "flag".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            !out.contains("import BigInt"),
            "Should not import BigInt when no BigUInt/BigInt types are used, got:\n{out}"
        );
    }

    #[test]
    fn swift_skips_params_struct_for_no_input_functions() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "totalSupply".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            !out.contains("TotalSupplyParams"),
            "Should not generate params struct for functions with no inputs, got:\n{out}"
        );
    }

    #[test]
    fn swift_type_mapping_uint_widths() {
        assert_eq!(sol_type_to_swift(&SolType::Uint(8)), "UInt8");
        assert_eq!(sol_type_to_swift(&SolType::Uint(16)), "UInt16");
        assert_eq!(sol_type_to_swift(&SolType::Uint(32)), "UInt32");
        assert_eq!(sol_type_to_swift(&SolType::Uint(64)), "UInt64");
        assert_eq!(sol_type_to_swift(&SolType::Uint(128)), "BigUInt");
        assert_eq!(sol_type_to_swift(&SolType::Uint(256)), "BigUInt");
    }

    #[test]
    fn swift_type_mapping_int_widths() {
        assert_eq!(sol_type_to_swift(&SolType::Int(8)), "Int8");
        assert_eq!(sol_type_to_swift(&SolType::Int(16)), "Int16");
        assert_eq!(sol_type_to_swift(&SolType::Int(32)), "Int32");
        assert_eq!(sol_type_to_swift(&SolType::Int(64)), "Int64");
        assert_eq!(sol_type_to_swift(&SolType::Int(128)), "BigInt");
        assert_eq!(sol_type_to_swift(&SolType::Int(256)), "BigInt");
    }

    #[test]
    fn swift_type_mapping_basic_types() {
        assert_eq!(sol_type_to_swift(&SolType::Bool), "Bool");
        assert_eq!(sol_type_to_swift(&SolType::StringType), "String");
        assert_eq!(sol_type_to_swift(&SolType::Address), "EthereumAddress");
        assert_eq!(sol_type_to_swift(&SolType::Bytes), "Data");
        assert_eq!(sol_type_to_swift(&SolType::BytesN(32)), "Data");
        assert_eq!(sol_type_to_swift(&SolType::BytesN(4)), "Data");
    }

    #[test]
    fn swift_type_mapping_arrays() {
        let dynamic = SolType::Array(Box::new(SolType::Address));
        assert_eq!(sol_type_to_swift(&dynamic), "[EthereumAddress]");

        let fixed = SolType::FixedArray(Box::new(SolType::Uint(256)), 3);
        assert_eq!(sol_type_to_swift(&fixed), "[BigUInt]");
    }

    #[test]
    fn swift_doc_comments_on_structs() {
        let out = render_swift_file(&token_ir());
        assert!(
            out.contains("/// Parameters for the `transfer` function."),
            "Expected doc comment on params struct, got:\n{out}"
        );
        assert!(
            out.contains("/// The `Transfer` event."),
            "Expected doc comment on event struct, got:\n{out}"
        );
        assert!(
            out.contains("/// The `InsufficientBalance` error."),
            "Expected doc comment on error struct, got:\n{out}"
        );
    }

    #[test]
    fn swift_natspec_notice_included() {
        let natspec = NatSpec {
            notice: Some("Transfers tokens to a recipient.".to_string()),
            ..Default::default()
        };

        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![AbiParam {
                    name: "to".to_string(),
                    ty: SolType::Address,
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: Some(natspec),
            }],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            out.contains("/// Transfers tokens to a recipient."),
            "Expected NatSpec notice in doc comment, got:\n{out}"
        );
    }

    #[test]
    fn swift_erc20_fixture_generates_valid_output() {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        let ir = parse_artifact("ERC20", &json).unwrap();
        let out = render_swift_file(&ir);
        assert!(out.contains("import Foundation"));
        assert!(out.contains("import web3swift"));
        assert!(out.contains("struct ERC20TransferParams {"));
        assert!(out.contains("struct ERC20TransferEvent {"));
        assert!(out.contains("struct ERC20ApprovalEvent {"));
        assert!(out.contains("struct ERC20ERC20InsufficientBalanceError {"));
    }

    #[test]
    fn swift_tuple_type_rendered() {
        let ty = SolType::Tuple(vec![
            TupleComponent {
                name: "shares".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            },
            TupleComponent {
                name: "token".into(),
                ty: SolType::Address,
                internal_type: None,
            },
        ]);
        assert_eq!(
            sol_type_to_swift(&ty),
            "(shares: BigUInt, token: EthereumAddress)"
        );
    }

    #[test]
    fn swift_empty_tuple_type() {
        let ty = SolType::Tuple(vec![]);
        assert_eq!(sol_type_to_swift(&ty), "()");
    }

    #[test]
    fn swift_unnamed_params_get_positional_names() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "doSomething".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            out.contains("let arg0: BigUInt"),
            "Expected positional name arg0, got:\n{out}"
        );
        assert!(
            out.contains("let arg1: EthereumAddress"),
            "Expected positional name arg1, got:\n{out}"
        );
    }

    #[test]
    fn swift_overloaded_deposit_produces_distinct_structs() {
        let ir = make_ir(
            "Vault",
            vec![
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![
                        AbiParam {
                            name: "amount".to_string(),
                            ty: SolType::Uint(256),
                            internal_type: None,
                        },
                        AbiParam {
                            name: "recipient".to_string(),
                            ty: SolType::Address,
                            internal_type: None,
                        },
                    ],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
            ],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            out.contains("struct VaultDepositUint256Params {"),
            "Expected `struct VaultDepositUint256Params`, got:\n{out}"
        );
        assert!(
            out.contains("struct VaultDepositUint256AddressParams {"),
            "Expected `struct VaultDepositUint256AddressParams`, got:\n{out}"
        );
        // Ensure no duplicates
        let count = out.matches("struct VaultDepositUint256Params {").count();
        assert_eq!(
            count, 1,
            "Expected exactly 1 VaultDepositUint256Params, found {count}"
        );
    }

    #[test]
    fn swift_keywords_escaped_in_field_names() {
        assert_eq!(swift_safe_param_name("self", 0), "_self");
        assert_eq!(swift_safe_param_name("is", 0), "_is");
        assert_eq!(swift_safe_param_name("as", 0), "_as");
        assert_eq!(swift_safe_param_name("func", 0), "_func");
        assert_eq!(swift_safe_param_name("let", 0), "_let");
        assert_eq!(swift_safe_param_name("var", 0), "_var");
        assert_eq!(swift_safe_param_name("nil", 0), "_nil");
        assert_eq!(swift_safe_param_name("init", 0), "_init");
        assert_eq!(swift_safe_param_name("guard", 0), "_guard");
        // Non-keywords should pass through unchanged
        assert_eq!(swift_safe_param_name("amount", 0), "amount");
        assert_eq!(swift_safe_param_name("from", 0), "from");
        assert_eq!(swift_safe_param_name("to", 0), "to");
    }

    #[test]
    fn swift_self_param_escaped() {
        let ir = make_ir(
            "Proxy",
            vec![AbiFunction {
                name: "execute".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "self".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "data".to_string(),
                        ty: SolType::Bytes,
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
            vec![],
        );
        let out = render_swift_file(&ir);
        assert!(
            out.contains("let _self: EthereumAddress"),
            "Expected `_self` field (escaped Swift keyword), got:\n{out}"
        );
        assert!(
            out.contains("let data: Data"),
            "Expected `data` field unchanged, got:\n{out}"
        );
    }

    #[test]
    fn swift_skips_error_struct_with_no_inputs() {
        let ir = make_ir(
            "Token",
            vec![],
            vec![],
            vec![AbiError {
                name: "Unauthorized".to_string(),
                inputs: vec![],
                natspec: None,
            }],
        );
        let out = render_swift_file(&ir);
        assert!(
            !out.contains("Unauthorized"),
            "Should not generate error struct with no inputs, got:\n{out}"
        );
    }
}
