load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity_vocabulary_core",
    srcs = glob(["**/*.rs"]),
    crate = "activity_vocabulary_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/serde-value/0.7.0:serde_value",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
