load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_cors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_cors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/tinyvec/1.12.0:tinyvec",
    ],
)
