load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams_ext",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams_ext",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
