load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acacia",
    srcs = glob(["**/*.rs"]),
    crate = "acacia",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/itertools/0.9.0:itertools",
        "//third-party/rust/crates/nalgebra/0.21.1:nalgebra",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rand/0.7.3:rand",
    ],
)
