name: Update Homebrew Tap

on:
  release:
    types: [published]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-formula:
    permissions:
      contents: read
    uses: luxass/shared-workflows/.github/workflows/reusable-homebrew-tap.yaml@a8c7a9cba106c0d3c5c3267a17e7865a380c9779 # v0.7.3
    with:
      tap-repository: luxass/homebrew-tap
      formula-path: Formula/actioneer.rb
      formula-name: actioneer
    secrets:
      app-id: ${{ secrets.HOMEBREW_TAP_APP_ID }}
      app-private-key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
