load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adept_fmt",
    srcs = glob(["**/*.rs"]),
    crate = "adept_fmt",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adept-core/0.1.1:adept_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
