load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin_config",
    srcs = glob(["**/*.rs"]),
    crate = "admin_config",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
