load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adler_core",
    srcs = glob(["**/*.rs"]),
    crate = "adler_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/async-tungstenite/0.34.1:async_tungstenite",
        "//third-party/rust/crates/chromiumoxide/0.9.1:chromiumoxide",
        "//third-party/rust/crates/fastrand/2.5.0:fastrand",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/scraper/0.27.0:scraper",
        "//third-party/rust/crates/secrecy/0.10.3:secrecy",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
