load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_rest",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_rest",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-rest-macros/0.2.0:actix_web_rest_macros",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum/0.24.1:strum",
    ],
)
