load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl343",
    srcs = glob(["**/*.rs"]),
    crate = "adxl343",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accelerometer/0.4.0:accelerometer",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
    ],
)
