load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adyen",
    srcs = glob(["**/*.rs"]),
    crate = "adyen",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.12.3:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/rust_decimal/1.42.1:rust_decimal",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
    ],
)
