load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_test_macro",
    srcs = glob(["**/*.rs"]),
    crate = "acton_test_macro",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
