import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJWelcomeCallbacks } from "../aj-callbacks.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJIcon } from "../components/aj-icon.slint";

export component LoginPage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJButton {
            text: @tr("назад");
            text-halign: right;

            AJIcon {
                source: @image-url("../../radix-icons/reset.svg");
                x: AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }
            clicked => {
                AJAppState.page = 0
            }
        }

        AJText {
            text: @tr("Вход в аккаунт");
            type: AJTextType.Heading;
        }

        login := AJInput {
            placeholder: @tr("логин");
        }

        password := AJInput {
            placeholder: @tr("пароль");
            type: AJInputType.Password;
        }

        AJButton {
            text: @tr("войти");

            text-halign: left;

            AJIcon {
                source: @image-url("../../radix-icons/enter.svg");
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            clicked => {
                AJWelcomeCallbacks.login(login.text, password.text)
            }
        }
    }
}
