import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJWelcomeCallbacks } from "../aj-callbacks.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJIcon } from "../components/aj-icon.slint";

export component RegisterPage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJButton {
            text: @tr("назад");
            text-halign: right;

            AJIcon {
                source: @image-url("../../radix-icons/reset.svg");
                x: AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }
            clicked => {
                AJAppState.page = 0
            }
        }

        AJText {
            text: @tr("Создание аккаунта");
            type: AJTextType.Heading;
        }

        login := AJInput {
            placeholder: @tr("логин");
        }

        password := AJInput {
            placeholder: @tr("пароль");
            type: AJInputType.Password;
        }

        password-confirmation := AJInput {
            placeholder: @tr("подтвердите пароль");
            type: AJInputType.Password;
        }

        AJButton {
            text: @tr("создать аккаунт");

            text-halign: left;

            AJIcon {
                source: {
                    if !login.text.is-empty && !password.text.is-empty && password.text == password-confirmation.text {
                        @image-url("../../radix-icons/plus.svg")
                    } else {
                        @image-url("../../radix-icons/circle-backslash.svg")
                    }
                };
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            clicked => {
                if !login.text.is-empty && !password.text.is-empty && password.text == password-confirmation.text {
                    AJWelcomeCallbacks.register(login.text, password.text, password-confirmation.text);
                }
            }
        }
    }
}
