import { AJTheme } from "../aj-theme.slint";
import { AJAppState } from "../aj-state.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJIcon } from "../components/aj-icon.slint";

export component WelcomePage {
    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJText {
            text: @tr("Добро пожаловать!");
            type: AJTextType.Heading;
        }

        AJButton {
            text: @tr("войти");

            text-halign: left;

            AJIcon {
                source: @image-url("../../radix-icons/enter.svg");
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            clicked => {
                AJAppState.page = 1;
            }
        }

        AJButton {
            text: @tr("создать аккаунт");

            text-halign: left;

            AJIcon {
                source: @image-url("../../radix-icons/plus.svg");
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            clicked => {
                AJAppState.page = 2;
            }
        }
    }
}
