load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acs37800",
    srcs = glob(["**/*.rs"]),
    crate = "acs37800",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitfield-struct/0.12.1:bitfield_struct",
        "//third-party/rust/crates/bon/3.9.3:bon",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
