load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_test_utils",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_test_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapto_audit/0.2.5:adapto_audit",
        "//third-party/rust/crates/adapto_auth/0.2.5:adapto_auth",
        "//third-party/rust/crates/adapto_client_protocol/0.2.5:adapto_client_protocol",
        "//third-party/rust/crates/adapto_db/0.2.5:adapto_db",
        "//third-party/rust/crates/adapto_forms/0.2.5:adapto_forms",
        "//third-party/rust/crates/adapto_runtime/0.2.5:adapto_runtime",
        "//third-party/rust/crates/adapto_store/0.2.5:adapto_store",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
