load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr_mock",
    srcs = glob(["**/*.rs"]),
    crate = "addr_mock",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/addr-hal/0.1.1:addr_hal",
    ],
)
