load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_cw_multi_test",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_cw_multi_test",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bech32/0.11.1:bech32",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-storage-plus/2.0.0:cw_storage_plus",
        "//third-party/rust/crates/cw-utils/2.0.0:cw_utils",
        "//third-party/rust/crates/cw20-ics20/2.0.0:cw20_ics20",
        "//third-party/rust/crates/derivative/2.2.0:derivative",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/itertools/0.13.0:itertools",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/prost/0.13.5:prost",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
