load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adb_remote_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adb_remote_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.27.0:crossterm",
    ],
)
