load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_pubsub",
    srcs = glob(["**/*.rs"]),
    crate = "ach_pubsub",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ach-array/0.1.9:ach_array",
        "//third-party/rust/crates/ach-ring/0.1.10:ach_ring",
    ],
)
