load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aag_cli_tools",
    srcs = glob(["**/*.rs"]),
    crate = "aag_cli_tools",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/meval/0.2.0:meval",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
