load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actnel_lib",
    srcs = glob(["**/*.rs"]),
    crate = "actnel_lib",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.11.0:base64",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.9.9:sha2",
    ],
)
