load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_security",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_security",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/downcast-rs/1.2.1:downcast_rs",
        "//third-party/rust/crates/jsonwebtoken/7.2.0:jsonwebtoken",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
