load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads1x1x",
    srcs = glob(["**/*.rs"]),
    crate = "ads1x1x",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/nb/1.1.0:nb",
    ],
)
