load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adb_rs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/crossbeam-channel/0.3.9:crossbeam_channel",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/failure_derive/0.1.8:failure_derive",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-derive/0.2.5:num_derive",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/pretty-hex/0.1.1:pretty_hex",
    ],
)
