use clap::Parser as _;

use crate::{run, tests::sdd::*, Cli};

track_file!("ref/asciidoctor/docs/modules/html-backend/pages/index.adoc");

// Asciidoctor's "Generate HTML from AsciiDoc" page, tracked from the CLI crate.
// The page documents the default HTML output that `adoc` produces, so several
// of its CLI-facing claims have counterparts here: the output file carries the
// `.html` extension (see `output_file_extension_is_html`), running `asciidoctor
// my-document.adoc` converts the file and derives the `my-document.html` output
// name (see `converts_and_derives_output_file`), and the `-o -` form used to
// preview the HTML writes it to standard output (see
// `previews_html_on_stdout`). The `asciidoc-html5` crate verifies the API-level
// conversion, and the sdd tool merges the two crates' coverage.
//
// The rest is non-normative here: the converter-class and backend-registration
// facts are Asciidoctor internals, the Google Fonts warning concerns a default
// stylesheet this project does not embed yet, and the screenshot step has no
// CLI counterpart. The "Generate XHTML" section (and the sentence introducing
// it) is tracked as non-normative by deliberate project decision: `adoc` emits
// HTML5 syntax only and does not support Asciidoctor's `xhtml`/`xhtml5`
// backends (see the workspace README).

non_normative!(
    r#"
= Generate HTML from AsciiDoc
:navtitle: Generate HTML

Asciidoctor's default output format is HTML (specifically HTML 5).
That means when you run Asciidoctor without any parameters, it will produce HTML.
This page explains how to use Asciidoctor to convert AsciiDoc to HTML.

== Backend and converter

Asciidoctor's built-in HTML converter is registered for the `html` and `html5` backends.
The HTML converter generates HTML 5 that's styled with CSS3.
It may include JavaScript to support additional integrations, such as client-side syntax highlighting.

[horizontal]
Backend names:: `html`, `html5`
Converter class:: `Asciidoctor::Converter::Html5Converter`
Output format:: HTML
"#
);

// The horizontal list's final term: the HTML output file carries the `.html`
// extension. With no `-o`, `adoc` derives the output file name from the input
// by swapping its extension for `.html`, so its output always ends in `.html`.
#[test]
fn output_file_extension_is_html() {
    verifies!(
        r#"
Output file extension:: .html

"#
    );

    let source = "= Hello\n\nWorld.";
    let path =
        std::env::temp_dir().join(format!("adoc-html-backend-ext-{}.adoc", std::process::id()));
    let derived = path.with_extension("html");
    std::fs::write(&path, source).expect("write temp input");

    let cli = Cli::parse_from(["adoc", path.to_str().expect("temp path is UTF-8")]);
    let mut stdout = Vec::new();
    run(&cli, &mut stdout).expect("adoc converts the file");
    let wrote_derived = derived.exists();
    let _ = std::fs::remove_file(&path);
    let _ = std::fs::remove_file(&derived);

    assert!(stdout.is_empty(), "adoc wrote to stdout on success");
    assert_eq!(
        derived.extension().and_then(|e| e.to_str()),
        Some("html"),
        "derived output name should carry the .html extension"
    );
    assert!(
        wrote_derived,
        "adoc did not create the derived .html output file"
    );
}

non_normative!(
    r#"
WARNING: A standalone HTML document generated by the built-in HTML converter loads web fonts from Google Fonts, which are then referenced by the default stylesheet.
The xref:default-stylesheet.adoc[default stylesheet] makes use of web fonts to ensure the document renders consistently across platforms.
Concerns have been raised that Google Fonts do not comply with GDPR.
If this presents a problem, you can xref:default-stylesheet.adoc#disable-or-modify-the-web-fonts[opt out of the use of Google Fonts].
When this is done, the default stylesheet reverts to using generic font families (e.g., sans-serif), which are mapped to system fonts by your browser.
The consequence is that the appearance of the document will be different and system dependent due to a reliance on system fonts.

If the backend name is prefixed with `x` (e.g., `xhtml`), the converter will <<xhtml,generate XHTML>>, the XML variant of HTML.

== Generate HTML

In this section, we'll create a sample document, then process and convert it with Asciidoctor's built-in HTML converter.

=== Create and save an AsciiDoc document

. To follow along with the steps below, use your own AsciiDoc file or copy the contents of <<ex-my-doc>> into a new plaintext file.
+
.my-document.adoc
[#ex-my-doc,asciidoc]
----
include::example$my-document.adoc[tags=title;body]
----

. Make sure to save the file with the _.adoc_ file extension.

"#
);

// The walkthrough's core CLI step: `asciidoctor my-document.adoc` converts the
// file silently and, with no `-o`, derives the output name `my-document.html`
// from the input. This crate's `adoc` command mirrors that behavior, which this
// test drives end to end.
#[test]
fn converts_and_derives_output_file() {
    // The "Convert an AsciiDoc document to HTML" section and the command that
    // carries it out. Nothing is printed on success.
    verifies!(
        r#"
=== Convert an AsciiDoc document to HTML

To convert [.path]_my-document.adoc_ to HTML from the command line:

. Open a terminal.
. Switch to the directory that contains the [.path]_my-document.adoc_ document
. Call the Asciidoctor processor with the `asciidoctor` command, followed by the name of the document.
+
--
 $ asciidoctor my-document.adoc

"#
    );

    non_normative!(
        r#"
Remember, Asciidoctor's default converter is html5, so it isn't necessary to specify it with the `-b` command.
--

. You won't see any messages printed to the console.
Type `ls` to view the files in the directory or navigate to the directory in a file manager.
"#
    );

    // Listing the directory shows the derived _my-document.html_ file, whose name
    // Asciidoctor takes from the input document.
    verifies!(
        r#"
You should see a new file named [.path]_my-document.html_.
+
--
 $ ls
 my-document.adoc  my-document.html

Asciidoctor derives the name of the output document from the name of the input document.
"#
    );

    // Drive the closest equivalent of `asciidoctor my-document.adoc`: hand the
    // `adoc` CLI a `<name>.adoc` file with no `-o`, and confirm it derives
    // `<name>.html` (as `asciidoctor` derives `my-document.html`), writes a
    // complete HTML5 document there, and prints nothing.
    let source = "= Hello\n\nWorld.";
    let path = std::env::temp_dir().join(format!("adoc-html-backend-{}.adoc", std::process::id()));
    let derived = path.with_extension("html");
    std::fs::write(&path, source).expect("write temp input");

    let cli = Cli::parse_from(["adoc", path.to_str().expect("temp path is UTF-8")]);
    let mut stdout = Vec::new();
    run(&cli, &mut stdout).expect("adoc converts the file");

    // Snapshot the results and clean up before asserting, so a failing
    // assertion doesn't leak the temp files.
    let wrote_derived = derived.exists();
    let html = std::fs::read_to_string(&derived).unwrap_or_default();
    let _ = std::fs::remove_file(&path);
    let _ = std::fs::remove_file(&derived);

    assert!(stdout.is_empty(), "adoc wrote to stdout on success");
    assert!(wrote_derived, "adoc did not create the derived output file");
    assert!(html.starts_with("<!DOCTYPE html>"));
    assert!(html.contains("<title>Hello</title>"));
    assert!(html.trim_end().ends_with("</body>\n</html>"));
}

non_normative!(
    r#"
--

. Open [.path]_my-document.html_ in your web browser.
Your document should look like the image below.
+
--
image::my-document.png[]

The document's text, titles, and link are styled by the default Asciidoctor stylesheet, which is embedded in the HTML output.
As a result, you could save [.path]_my-document.html_ to any computer and it will look the same.
--

"#
);

// The preview command pipes `asciidoctor my-document.adoc -o -` into a terminal
// browser. The `-o -` half writes the rendered HTML to standard output, which
// this crate's `adoc` command mirrors.
#[test]
fn previews_html_on_stdout() {
    verifies!(
        r#"
. If you want to preview the HTML in the terminal, you can use this command instead:

 $ asciidoctor my-document.adoc -o - | w3m - -T text/html

"#
    );

    // Drive `adoc <file> -o -`: the dash forces the HTML to standard output, and
    // no derived file is written.
    let source = "= Hello\n\nWorld.";
    let path = std::env::temp_dir().join(format!(
        "adoc-html-backend-stdout-{}.adoc",
        std::process::id()
    ));
    let derived = path.with_extension("html");
    std::fs::write(&path, source).expect("write temp input");

    let cli = Cli::parse_from([
        "adoc",
        path.to_str().expect("temp path is UTF-8"),
        "-o",
        "-",
    ]);
    let mut stdout = Vec::new();
    run(&cli, &mut stdout).expect("adoc converts the file");
    let wrote_derived = derived.exists();
    let _ = std::fs::remove_file(&path);
    let _ = std::fs::remove_file(&derived);

    assert!(!wrote_derived, "`-o -` should not write a derived file");
    let html = String::from_utf8(stdout).expect("stdout is UTF-8");
    assert!(html.starts_with("<!DOCTYPE html>"));
    assert!(html.contains("<title>Hello</title>"));
    assert!(html.trim_end().ends_with("</body>\n</html>"));
}

non_normative!(
    r#"
[#xhtml]
== Generate XHTML

[horizontal]
Backend names:: `xhtml`, `xhtml5`
Converter class:: `Asciidoctor::Converter::Html5Converter`
Output format:: XML variant of HTML
Output file extension:: .html

.Produce XHTML using the xhtml5 backend option
 $ asciidoctor -b xhtml5 my-document.adoc

To produce XHTML instead of HTML when using converter templates, set the `htmlsyntax` attribute to `xml` in addition to the backend option:

.Produce XHTML using custom templates
 $ asciidoctor -T /path/to/templates -b slides -a htmlsyntax=xml my-document.adoc

.Black Box Decoded: XHTML and htmlsyntax
****
XHTML output is a special mode of the built-in HTML5 converter.
It is activated by prefixing the backend value with `x` (e.g., `xhtml` or `xhtml5`).
This hint implicitly assigns the `htmlsyntax` attribute to the value `xml`, which normally has the value `html`.

For all other converters, the `htmlsyntax` attribute is not set explicitly.
If you want a converter template that's written in Slim or Haml to output XHTML instead of the default HTML, you need to set the `htmlsyntax` attribute to `xml` explicitly.
Asciidoctor will pass on this preference to the Slim or Haml template engine by setting the `:format` option to `:html5`.
****
"#
);
