load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminapi",
    srcs = glob(["**/*.rs"]),
    crate = "adminapi",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/signature/2.2.0:signature",
        "//third-party/rust/crates/ssh-agent-client-rs/1.1.3:ssh_agent_client_rs",
        "//third-party/rust/crates/ssh-encoding/0.2.0:ssh_encoding",
        "//third-party/rust/crates/ssh-key/0.6.7:ssh_key",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
