load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advisor_output",
    srcs = glob(["**/*.rs"]),
    crate = "advisor_output",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advisor-core/0.1.0:advisor_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
