load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absurd",
    srcs = glob(["**/*.rs"]),
    crate = "absurd",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/convert_case/0.6.0:convert_case",
    ],
)
