load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_memory",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_memory",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
