load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acta_debug",
    srcs = glob(["**/*.rs"]),
    crate = "acta_debug",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acta/0.1.1:acta",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
