load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_telepathy_derive",
    srcs = glob(["**/*.rs"]),
    crate = "actix_telepathy_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
