load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_ts_format_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_ts_format_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
