load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abre",
    srcs = glob(["**/*.rs"]),
    crate = "abre",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
