load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acute",
    srcs = glob(["**/*.rs"]),
    crate = "acute",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acute_app/0.1.3:acute_app",
        "//third-party/rust/crates/acute_assets/0.1.0:acute_assets",
        "//third-party/rust/crates/acute_core/0.1.1:acute_core",
        "//third-party/rust/crates/acute_ecs/0.1.0:acute_ecs",
        "//third-party/rust/crates/acute_input/0.1.2:acute_input",
        "//third-party/rust/crates/acute_render/0.1.0:acute_render",
        "//third-party/rust/crates/acute_render_backend/0.1.2:acute_render_backend",
        "//third-party/rust/crates/acute_scenes/0.1.0:acute_scenes",
        "//third-party/rust/crates/acute_window/0.1.1:acute_window",
    ],
)
