load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytecount/0.6.9:bytecount",
        "//third-party/rust/crates/mod_exp/1.0.1:mod_exp",
    ],
)
