load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp_verify",
    srcs = glob(["**/*.rs"]),
    crate = "acdp_verify",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp-crypto/0.8.1:acdp_crypto",
        "//third-party/rust/crates/acdp-did/0.8.1:acdp_did",
        "//third-party/rust/crates/acdp-primitives/0.8.1:acdp_primitives",
        "//third-party/rust/crates/acdp-types/0.8.1:acdp_types",
        "//third-party/rust/crates/acdp-validation/0.8.1:acdp_validation",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
