load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_protobuf",
    srcs = glob(["**/*.rs"]),
    crate = "actix_protobuf",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.4.10:actix_web",
        "//third-party/rust/crates/actix/0.5.8:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/prost/0.2.3:prost",
    ],
)
