load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_daemon_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_daemon_utils",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.0.2:actix_rt",
        "//third-party/rust/crates/actix/0.11.1:actix",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
    ],
)
