load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abci",
    srcs = glob(["**/*.rs"]),
    crate = "abci",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/env_logger/0.7.1:env_logger",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/integer-encoding/1.1.7:integer_encoding",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/protobuf/2.28.0:protobuf",
        "//third-party/rust/crates/tokio/0.1.22:tokio",
    ],
)
