load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acrylic",
    srcs = glob(["**/*.rs"]),
    crate = "acrylic",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/hashbrown/0.12.3:hashbrown",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/microjson/0.1.6:microjson",
    ],
)
