load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acir",
    srcs = glob(["**/*.rs"]),
    crate = "acir",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.23.1:base64",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/num-bigint/0.5.1:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/num_enum/0.7.6:num_enum",
        "//third-party/rust/crates/rmp-serde/1.3.1:rmp_serde",
        "//third-party/rust/crates/serde-big-array/0.5.1:serde_big_array",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum/0.28.0:strum",
        "//third-party/rust/crates/strum_macros/0.28.0:strum_macros",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
