load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_storage",
    srcs = glob(["**/*.rs"]),
    crate = "active_storage",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dyn-clone/1.0.20:dyn_clone",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
