load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acap_logging",
    srcs = glob(["**/*.rs"]),
    crate = "acap_logging",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/syslog/6.1.1:syslog",
    ],
)
