load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aauth_core",
    srcs = glob(["**/*.rs"]),
    crate = "aauth_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aauth-httpsig-policy/0.1.0:aauth_httpsig_policy",
        "//third-party/rust/crates/aauth-httpsig/0.1.0:aauth_httpsig",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/getrandom/0.4.3:getrandom",
        "//third-party/rust/crates/rand_core/0.10.1:rand_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
