import { AJTheme } from "../aj-theme.slint";
import { AJDateTime } from "../models/others.slint";
import { AJInput } from "aj-input.slint";

export component AJDateTimeInput inherits HorizontalLayout {
    in-out property <AJDateTime> date-time: {
        year: year.text.to-float(),
        month: month.text.to-float(),
        day: day.text.to-float(),
        hour: hour.text.to-float(),
        minute: minute.text.to-float(),
        second: second.text.to-float(),
    };

    spacing: AJTheme.spacing;

    year := AJInput {
        placeholder: "год";
    }

    month := AJInput {
        placeholder: "мес";
    }

    day := AJInput {
        placeholder: "день";
    }

    hour := AJInput {
        placeholder: "час";
    }

    minute := AJInput {
        placeholder: "мин";
    }

    second := AJInput {
        placeholder: "сек";
    }
}
