load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_types",
    srcs = glob(["**/*.rs"]),
    crate = "act_types",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/ciborium/0.2.2:ciborium",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_with/3.22.0:serde_with",
    ],
)
