load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adana",
    srcs = glob(["**/*.rs"]),
    crate = "adana",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adana-script-core/0.16.2:adana_script_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arboard/3.6.1:arboard",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/nu-ansi-term/0.49.0:nu_ansi_term",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustyline-derive/0.10.0:rustyline_derive",
        "//third-party/rust/crates/rustyline/13.0.0:rustyline",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/slab_tree/0.3.2:slab_tree",
        "//third-party/rust/crates/strum/0.25.0:strum",
    ],
)
