load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abgleich_lib",
    srcs = glob(["**/*.rs"]),
    crate = "abgleich_lib",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/inquire/0.7.5:inquire",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml_ng/0.10.0:serde_yaml_ng",
        "//third-party/rust/crates/shlex/1.3.0:shlex",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
