load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_grants",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_grants",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
    ],
)
