load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminix_macro",
    srcs = glob(["**/*.rs"]),
    crate = "adminix_macro",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/maud/0.23.0:maud",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/sqlx/0.4.2:sqlx",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
