load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adobe_cmap_parser",
    srcs = glob(["**/*.rs"]),
    crate = "adobe_cmap_parser",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/pom/1.1.0:pom",
    ],
)
