load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "account_compression",
    srcs = glob(["**/*.rs"]),
    crate = "account_compression",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aligned-sized/1.1.0:aligned_sized",
        "//third-party/rust/crates/anchor-lang/0.29.0:anchor_lang",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/light-bounded-vec/1.1.0:light_bounded_vec",
        "//third-party/rust/crates/light-concurrent-merkle-tree/1.1.0:light_concurrent_merkle_tree",
        "//third-party/rust/crates/light-hash-set/1.2.0:light_hash_set",
        "//third-party/rust/crates/light-hasher/1.1.1:light_hasher",
        "//third-party/rust/crates/light-indexed-merkle-tree/1.1.0:light_indexed_merkle_tree",
        "//third-party/rust/crates/light-utils/1.1.0:light_utils",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/solana-security-txt/1.1.3:solana_security_txt",
    ],
)
