load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abcrypt",
    srcs = glob(["**/*.rs"]),
    crate = "abcrypt",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/argon2/0.5.3:argon2",
        "//third-party/rust/crates/blake2/0.10.6:blake2",
        "//third-party/rust/crates/chacha20poly1305/0.10.1:chacha20poly1305",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
