load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_identity",
    srcs = glob(["**/*.rs"]),
    crate = "actix_identity",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-session/0.9.0:actix_session",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
