load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ab_riscv_interpreter",
    srcs = glob(["**/*.rs"]),
    crate = "ab_riscv_interpreter",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ab-riscv-macros/0.0.1:ab_riscv_macros",
        "//third-party/rust/crates/ab-riscv-primitives/0.0.1:ab_riscv_primitives",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
