load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aadhaar",
    srcs = glob(["**/*.rs"]),
    crate = "aadhaar",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/roxmltree/0.20.0:roxmltree",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/rxing/0.8.6:rxing",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/strum/0.26.3:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/x509-parser/0.18.1:x509_parser",
        "//third-party/rust/crates/xml-sec/0.1.10:xml_sec",
        "//third-party/rust/crates/zip/8.6.0:zip",
    ],
)
