load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr_of",
    srcs = glob(["**/*.rs"]),
    crate = "addr_of",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aok/0.1.18:aok",
    ],
)
