load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_socket_io",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_socket_io",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-web-actors/4.3.0:actix_web_actors",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num_enum/0.7.6:num_enum",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
