load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adventurous",
    srcs = glob(["**/*.rs"]),
    crate = "adventurous",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
    ],
)
