load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "AudioSpeedHack",
    srcs = glob(["**/*.rs"]),
    crate = "AudioSpeedHack",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/config-file2/0.4.1:config_file2",
        "//third-party/rust/crates/goblin/0.10.7:goblin",
        "//third-party/rust/crates/include_assets/1.0.0:include_assets",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pretty_env_logger/0.5.0:pretty_env_logger",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum/0.27.2:strum",
        "//third-party/rust/crates/strum_macros/0.27.2:strum_macros",
        "//third-party/rust/crates/terminal-menu/3.1.0:terminal_menu",
        "//third-party/rust/crates/windows_registry_obj/0.1.0:windows_registry_obj",
    ],
)
