load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "achievements",
    srcs = glob(["**/*.rs"]),
    crate = "achievements",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/homedir/0.3.6:homedir",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
