load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptivemsg",
    srcs = glob(["**/*.rs"]),
    crate = "adaptivemsg",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adaptivemsg-macros/0.1.0:adaptivemsg_macros",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/inventory/0.3.24:inventory",
        "//third-party/rust/crates/postcard/1.1.3:postcard",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rmp-serde/1.2.0:rmp_serde",
        "//third-party/rust/crates/rmp/0.8.14:rmp",
        "//third-party/rust/crates/rmpv/1.0.2:rmpv",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
