load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abacus",
    srcs = glob(["**/*.rs"]),
    crate = "abacus",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/miette/7.6.0:miette",
        "//third-party/rust/crates/rustyline/17.0.2:rustyline",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unicode-width/0.1.14:unicode_width",
    ],
)
