load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_script",
    srcs = glob(["**/*.rs"]),
    crate = "adana_script",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adana-script-core/0.17.11:adana_script_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/slab_tree/0.3.2:slab_tree",
    ],
)
