load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr_symbolizer",
    srcs = glob(["**/*.rs"]),
    crate = "addr_symbolizer",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/msvc-demangler/0.11.0:msvc_demangler",
        "//third-party/rust/crates/pdb2/0.10.1:pdb2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
    ],
)
