load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actuate",
    srcs = glob(["**/*.rs"]),
    crate = "actuate",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hashbrown/0.14.5:hashbrown",
    ],
)
