load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_rs",
    srcs = glob(["**/*.rs"]),
    crate = "access_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ethers/2.0.14:ethers",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
