load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_screen",
    srcs = glob(["**/*.rs"]),
    crate = "adi_screen",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aci_png/0.5.2:aci_png",
        "//third-party/rust/crates/adi_clock/0.3.0:adi_clock",
        "//third-party/rust/crates/adi_gpu/0.1.0:adi_gpu",
        "//third-party/rust/crates/afi/0.3.2:afi",
        "//third-party/rust/crates/ami/0.5.0:ami",
        "//third-party/rust/crates/rusttype/0.3.0:rusttype",
    ],
)
