import { AJTheme } from "../aj-theme.slint";
import "../../fonts/JetBrainsMono-2.304/fonts/variable/JetBrainsMono[wght].ttf";
import "../../fonts/JetBrainsMono-2.304/fonts/variable/JetBrainsMono-Italic[wght].ttf";

export enum AJTextType {
    Paragraph,
    Medium,
    Heading
}

export component AJText inherits Text {
    in property <AJTextType> type;

    font-family: "JetBrains Mono";
    font-size: {
        if type == AJTextType.Paragraph {
            AJTheme.font-size-paragraph
        } else if type == AJTextType.Medium {
            AJTheme.font-size-medium
        } else {
            AJTheme.font-size-heading
        }
    }
    font-weight: {
        if type == AJTextType.Paragraph {
            AJTheme.font-weight-paragraph
        } else if type == AJTextType.Medium {
            AJTheme.font-weight-medium
        } else {
            AJTheme.font-weight-heading
        }
    }

    color: AJTheme.default-text;
}
