load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_rate_limiter",
    srcs = glob(["**/*.rs"]),
    crate = "actix_rate_limiter",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
