[package]
name = "adi"
version = "0.3.1"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.tech>"]
description = """
        Aldaron's Device Interface, or ADI is a rust library for creating \
        cross-platform applications and video games.  It's goal is to be an \
        powerful, easy-to-use, and minimal SDL-esque library.  It is developed \
        by Plop Grizzly.
"""
keywords = [ "Vulkan", "Graphics", "GUI", "Input", "Hardware" ]
categories = [
	"gui", "game-engines", "hardware-support", "multimedia",
	"rendering::graphics-api"
]
license = "MIT"
documentation = "http://plopgrizzly.tech/adi/"
homepage = "http://plopgrizzly.tech/adi/"
repository = "https://github.com/plopgrizzly/adi"
readme = "README.md"
exclude = [ "examples/*", "docs/*", ".gitignore", "TODO" ]

[dependencies]
adi_screen = "0.2.2"

[features]
checks = []
validation = []
