load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_lambda",
    srcs = glob(["**/*.rs"]),
    crate = "actix_lambda",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/aws_lambda_events/0.2.7:aws_lambda_events",
        "//third-party/rust/crates/crossbeam/0.7.3:crossbeam",
        "//third-party/rust/crates/lambda_http/0.1.1:lambda_http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/maplit/1.0.2:maplit",
        "//third-party/rust/crates/reqwest/0.9.24:reqwest",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/url/1.7.2:url",
    ],
)
