name: Create Release

# trigger workflow on new push to tags
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rust and cargo
        run: sudo apt install rustc cargo
      - name: Install toml-cli
        run: cargo install toml-cli
      - name: Build Project
        run: ./build-script.sh
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            adamantite-${{ github.ref_name }}-unknown-linux-gnu.tar.gz
            SHA256SUMS
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
