load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapter_extism",
    srcs = glob(["**/*.rs"]),
    crate = "adapter_extism",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapter/0.2.0:adapter",
        "//third-party/rust/crates/extism/1.30.0:extism",
    ],
)
