export enum AJSubgroupType {
    Sample,
    Main
}

export struct AJSubgroup {
    type: AJSubgroupType,
    tests: string,
    depends-on: string,
    score: int,
    score-per-test: int,
}

export enum AJProblemType {
    Default,
    Interactive,
    RunTwice
}

export struct AJProblem {
    id: int,
    owner-id: int,
    type: AJProblemType,
    problem-index: int,
    name: string,
    time-limit-ms: int,
    memory-limit-mb: int,
    subgroups: [AJSubgroup],
    can-manage: bool,
    merge-subgroups: bool,
}
