load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_cw_orch_polytone",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_cw_orch_polytone",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
    ],
)
