load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abacuz",
    srcs = glob(["**/*.rs"]),
    crate = "abacuz",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-files/0.5.0:actix_files",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rustls/0.18.1:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
