load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abnf_rfc5234",
    srcs = glob(["**/*.rs"]),
    crate = "abnf_rfc5234",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/pest/2.8.8:pest",
        "//third-party/rust/crates/pest_derive/2.8.8:pest_derive",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
