load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_input",
    srcs = glob(["**/*.rs"]),
    crate = "advent_input",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
    ],
)
