load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_ssr",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_ssr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapto_auth/0.2.5:adapto_auth",
        "//third-party/rust/crates/adapto_client_protocol/0.2.5:adapto_client_protocol",
        "//third-party/rust/crates/adapto_compiler/0.2.5:adapto_compiler",
        "//third-party/rust/crates/adapto_live/0.2.5:adapto_live",
        "//third-party/rust/crates/adapto_parser/0.2.5:adapto_parser",
        "//third-party/rust/crates/adapto_runtime/0.2.5:adapto_runtime",
        "//third-party/rust/crates/adapto_store/0.2.5:adapto_store",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.5.2:tower_http",
        "//third-party/rust/crates/tower/0.4.13:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
