load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_toolbox",
    srcs = glob(["**/*.rs"]),
    crate = "actix_toolbox",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-session/0.7.2:actix_session",
        "//third-party/rust/crates/actix-web/4.2.1:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/byte-unit/4.0.19:byte_unit",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/log4rs/1.2.0:log4rs",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rorm/0.4.3:rorm",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/uuid/1.2.2:uuid",
    ],
)
