load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_ns",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_ns",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/quick-error/1.2.3:quick_error",
        "//third-party/rust/crates/rand/0.3.23:rand",
        "//third-party/rust/crates/void/1.0.2:void",
    ],
)
