load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_chain",
    srcs = glob(["**/*.rs"]),
    crate = "actix_chain",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
