load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adabraka_refineable",
    srcs = glob(["**/*.rs"]),
    crate = "adabraka_refineable",
    crate_root = "src/refineable.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adabraka_derive_refineable/0.4.0:adabraka_derive_refineable",
    ],
)
