load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp_tunnel",
    srcs = glob(["**/*.rs"]),
    crate = "acp_tunnel",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/agent-client-protocol/1.0.1:agent_client_protocol",
        "//third-party/rust/crates/axum-server/0.8.0:axum_server",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/subtle/2.6.1:subtle",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-tungstenite/0.29.0:tokio_tungstenite",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.9.8:toml",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
