load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/accent/accent-0.0.0.crate",
    ],
    sha256 = "a3fed6cbe9502db710d7d972c99c2d269092aabbcdfa7ab912b4f9844057b387",
    type = "tar.gz",
    strip_prefix = "accent-0.0.0",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "accent",
    srcs = [":vendor"],
    crate = "accent",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
