load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_adapter_utils",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_adapter_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/4.0.0:cw_asset",
        "//third-party/rust/crates/cw20/2.0.0:cw20",
    ],
)
