load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ablf",
    srcs = glob(["**/*.rs"]),
    crate = "ablf",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/binrw/0.15.2:binrw",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/zune-inflate/0.2.54:zune_inflate",
    ],
)
