load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activecube_rs",
    srcs = glob(["**/*.rs"]),
    crate = "activecube_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-graphql/7.2.1:async_graphql",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tiny-keccak/2.0.2:tiny_keccak",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
