load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_oidc_token",
    srcs = glob(["**/*.rs"]),
    crate = "actix_oidc_token",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-web-httpauth/0.5.1:actix_web_httpauth",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/jonases-tracing-util/0.1.0:jonases_tracing_util",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
