import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJSubgroup, AJSubgroupType } from "../models/problems.slint";
import { AJText, AJTextType } from "aj-text.slint";

export component AJSubgroupCard inherits Rectangle {
    in property <int> index;

    property <AJSubgroup> subgroup: AJContestState.problems[AJContestState.current-problem-index].subgroups[index];

    width: self.min-width + AJTheme.fit-space;
    height: self.min-height + AJTheme.fit-space;

    background: AJTheme.secondary-container.with-alpha(0.4);

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "#\{index}";
            type: AJTextType.Medium;
            color: AJTheme.container-text;
        }

        HorizontalLayout {
            AJText {
                text: "тип";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }

            AJText {
                text: subgroup.type == AJSubgroupType.Main ? "основная" : "примеры";
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }
        }

        HorizontalLayout {
            AJText {
                text: "тесты";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }

            AJText {
                text: subgroup.tests;
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }
        }

        HorizontalLayout {
            AJText {
                text: "требуемые подгруппы";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }

            AJText {
                text: subgroup.depends-on.is-empty ? "-" : subgroup.depends-on;
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }
        }

        HorizontalLayout {
            AJText {
                text: "баллы";
                horizontal-stretch: 1;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }

            AJText {
                text: subgroup.score;
                font-italic: true;
                horizontal-stretch: 1;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: AJTheme.container-text;
            }
        }
    }
}
