load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme2_eab",
    srcs = glob(["**/*.rs"]),
    crate = "acme2_eab",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-futures/0.2.5:tracing_futures",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
