load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel_derive",
    srcs = glob(["**/*.rs"]),
    crate = "accel_derive",
    crate_root = "src/lib.rs",
    edition = "2015",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accel/0.1.0:accel",
        "//third-party/rust/crates/futures-await-quote/0.4.0:futures_await_quote",
        "//third-party/rust/crates/futures-await-syn/0.12.0:futures_await_syn",
        "//third-party/rust/crates/proc-macro2/0.1.10:proc_macro2",
        "//third-party/rust/crates/synom/0.11.3:synom",
    ],
)
