load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_remote",
    srcs = glob(["**/*.rs"]),
    crate = "add_remote",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/colour/0.3.1:colour",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/find_git/1.2.1:find_git",
        "//third-party/rust/crates/reqwest/0.9.24:reqwest",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/unwrap/1.2.1:unwrap",
    ],
)
