load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_jwt_auth_middleware",
    srcs = glob(["**/*.rs"]),
    crate = "actix_jwt_auth_middleware",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-jwt-auth-middleware-derive/0.1.1:actix_jwt_auth_middleware_derive",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/ed25519-dalek/1.0.1:ed25519_dalek",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/jwt-compact/0.5.0:jwt_compact",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_cbor/0.11.2:serde_cbor",
    ],
)
