load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads112c04",
    srcs = glob(["**/*.rs"]),
    crate = "ads112c04",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
