load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acir",
    srcs = glob(["**/*.rs"]),
    crate = "acir",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir_field/0.15.1:acir_field",
        "//third-party/rust/crates/brillig_vm/0.15.1:brillig_vm",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/rmp-serde/1.3.1:rmp_serde",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
