load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_core",
    srcs = glob(["**/*.rs"]),
    crate = "acton_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/derive-new/0.7.0:derive_new",
        "//third-party/rust/crates/dyn-clone/1.0.20:dyn_clone",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/static_assertions/1.1.0:static_assertions",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
