load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adof",
    srcs = glob(["**/*.rs"]),
    crate = "adof",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/git2/0.19.0:git2",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/webbrowser/1.2.4:webbrowser",
    ],
)
