load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abbrs",
    srcs = glob(["**/*.rs"]),
    crate = "abbrs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bitcode/0.6.9:bitcode",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/toml_edit/0.22.27:toml_edit",
        "//third-party/rust/crates/xdg/2.5.2:xdg",
    ],
)
