load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_io_http",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_io_http",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/http/0.2.12:http",
    ],
)
