import { AJTheme } from "../aj-theme.slint";
import { AJContestState } from "../aj-state.slint";
import { AJSubmission, AJTotalVerdict } from "../models/testing.slint";
import { ScrollView } from "std-widgets.slint";
import { AJText, AJTextType } from "aj-text.slint";
import { AJSubgroupCard } from "aj-subgroup-card.slint";
import { AJSubgroupResultCard } from "aj-subgroup-result-card.slint";

export component AJSubmissionCard inherits Rectangle {
    property <AJSubmission> submission: AJContestState.submissions[AJContestState.current-submission-index];

    width: 50%;
    height: 270px;

    background: AJTheme.primary-container;

    border-radius: AJTheme.border-radius;

    VerticalLayout {
        padding: AJTheme.padding;
        spacing: AJTheme.spacing;

        AJText {
            text: "Посылка #\{AJContestState.submissions[AJContestState.current-submission-index].id}";
            color: AJTheme.container-text;
            type: AJTextType.Heading;
        }

        AJText {
            text: "Результаты подгрупп";
            color: AJTheme.container-text;
            type: AJTextType.Medium;
        }

        Rectangle {
            clip: true;
            border-radius: AJTheme.border-radius;

            ScrollView {
                VerticalLayout {
                    spacing: AJTheme.spacing;

                    for subgroup-result[index] in submission.subgroups-results: AJSubgroupResultCard {
                        index: index;
                    }
                }
            }

            Rectangle {
                x: 0;
                y: parent.height - self.height;
                width: parent.width;
                height: 64px;
                background: @linear-gradient(180deg, AJTheme.background.transparentize(100%), AJTheme.background.transparentize(50%));
            }
        }
    }
}
