load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_casbin",
    srcs = glob(["**/*.rs"]),
    crate = "actix_casbin",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.9.0:actix",
        "//third-party/rust/crates/casbin/0.8.5:casbin",
    ],
)
