load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_dx",
    srcs = glob(["**/*.rs"]),
    crate = "acton_dx",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
