load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accord",
    srcs = glob(["**/*.rs"]),
    crate = "accord",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/0.8.23:serde",
        "//third-party/rust/crates/serde_json/0.8.6:serde_json",
    ],
)
