name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up cache
        uses: actions/cache@87396fe6b4d327202df854ff5b3e0a4ea3d77ac6
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-nightly-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-nightly-cargo-
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain update nightly
          rustup default nightly
      - name: Install Clippy
        run: rustup component add clippy
      - name: Lint code
        run: cargo clippy --all-features -- -D warnings
      - name: Install rustfmt
        run: rustup component add rustfmt --toolchain nightly
      - name: Check format
        run: cargo fmt --check
      - name: Install other tools
        run: |
          cargo install --locked cargo-deny || true
          cargo install --locked cargo-udeps || true
      - name: Check everything else
        run: |
          cargo deny check
          cargo udeps
  tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust-version:
          - stable
          - nightly
        feature-sets:
          - []
          - [white-spaces]
          - [literals]
          - [literals, comments]
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up cache
        uses: actions/cache@87396fe6b4d327202df854ff5b3e0a4ea3d77ac6
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-${{ matrix.rust-version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.rust-version }}-cargo-
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain update ${{ matrix.rust-version }}
          rustup default ${{ matrix.rust-version }}
      - name: Run tests
        run: cargo test --locked ${{ toJSON(matrix.feature-sets) != '[]' && format('--features {0}', join(matrix.feature-sets, ',')) || '' }}
