load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity_macros",
    srcs = glob(["**/*.rs"]),
    crate = "activity_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/wasm-bindgen-futures/0.4.77:wasm_bindgen_futures",
        "//third-party/rust/crates/wasm-bindgen-macro-support/0.2.127:wasm_bindgen_macro_support",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
    ],
)
