load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a11ywatch",
    srcs = glob(["**/*.rs"]),
    crate = "a11ywatch",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
