load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adv_shift_registers",
    srcs = glob(["**/*.rs"]),
    crate = "adv_shift_registers",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
