load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_realtime",
    srcs = glob(["**/*.rs"]),
    crate = "adk_realtime",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/0.6.0:adk_core",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/secrecy/0.10.3:secrecy",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
