load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_admin",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_admin",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-session/0.9.0:actix_session",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tera/1.20.1:tera",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
