load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a11ywatch",
    srcs = glob(["**/*.rs"]),
    crate = "a11ywatch",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/3.2.25:clap",
    ],
)
