load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/aead/aead-0.1.0.crate",
    ],
    sha256 = "c123029ce49fdb98fbb1ea946cf8cad5bc9d8cd6861804fa773bbbe6de7abfa0",
    type = "tar.gz",
    strip_prefix = "aead-0.1.0",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "aead",
    srcs = [":vendor"],
    crate = "aead",
    crate_root = "vendor/src/lib.rs",
    edition = "2018",
    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
