load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder_to_dvs",
    srcs = glob(["**/*.rs"]),
    crate = "adder_to_dvs",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adder-codec-core/0.3.5:adder_codec_core",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/video-rs/0.5.0:video_rs",
    ],
)
