load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/acoustix/acoustix-0.2.0.crate",
    ],
    sha256 = "1bf875c04d0fa8d02fe67f6ea0d7786f6ecd8b4c5ab4ef431140f6ce1183b83f",
    type = "tar.gz",
    strip_prefix = "acoustix-0.2.0",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "acoustix",
    srcs = [":vendor"],
    crate = "acoustix",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
