load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl345_eh_driver",
    srcs = glob(["**/*.rs"]),
    crate = "adxl345_eh_driver",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
