load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm",
    srcs = glob(["**/*.rs"]),
    crate = "acvm",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir/0.15.1:acir",
        "//third-party/rust/crates/acvm_stdlib/0.15.1:acvm_stdlib",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/blake2/0.10.6:blake2",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/k256/0.11.6:k256",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/sha3/0.10.9:sha3",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
