load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adui_dioxus",
    srcs = glob(["**/*.rs"]),
    crate = "adui_dioxus",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dioxus-html/0.7.10:dioxus_html",
        "//third-party/rust/crates/dioxus/0.7.10:dioxus",
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/wasm-bindgen-futures/0.4.77:wasm_bindgen_futures",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
        "//third-party/rust/crates/web-sys/0.3.104:web_sys",
    ],
)
