load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adfc",
    srcs = glob(["**/*.rs"]),
    crate = "adfc",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/jsonschema/0.26.2:jsonschema",
        "//third-party/rust/crates/pulldown-cmark/0.13.4:pulldown_cmark",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
