load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ada_judge_cli",
    srcs = glob(["**/*.rs"]),
    crate = "ada_judge_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ada-judge-public-models/0.7.0:ada_judge_public_models",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/directories/6.0.0:directories",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sqlx/0.8.6:sqlx",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
