load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl345_driver2",
    srcs = glob(["**/*.rs"]),
    crate = "adxl345_driver2",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/c2rust-bitfields/0.18.0:c2rust_bitfields",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
