load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adana_cache_command",
    srcs = glob(["**/*.rs"]),
    crate = "adana_cache_command",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arboard/3.6.1:arboard",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/nu-ansi-term/0.50.3:nu_ansi_term",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
