load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaclaw_memory",
    srcs = glob(["**/*.rs"]),
    crate = "adaclaw_memory",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adaclaw-core/0.1.0:adaclaw_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/r2d2/0.8.10:r2d2",
        "//third-party/rust/crates/r2d2_sqlite/0.24.0:r2d2_sqlite",
        "//third-party/rust/crates/rusqlite/0.31.0:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
