load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel",
    srcs = glob(["**/*.rs"]),
    crate = "accel",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accel-derive/0.3.0:accel_derive",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/cuda-driver-sys/0.3.0:cuda_driver_sys",
        "//third-party/rust/crates/derive-new/0.5.9:derive_new",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-derive/0.2.5:num_derive",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/paste/0.1.18:paste",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
