load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_money_market_standard",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_money_market_standard",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-adapter-utils/0.26.1:abstract_adapter_utils",
        "//third-party/rust/crates/abstract-adapter/0.26.1:abstract_adapter",
        "//third-party/rust/crates/abstract-sdk/0.26.1:abstract_sdk",
        "//third-party/rust/crates/abstract-std/0.26.1:abstract_std",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/4.0.0:cw_asset",
        "//third-party/rust/crates/cw-orch/0.27.0:cw_orch",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
