load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbshell",
    srcs = glob(["**/*.rs"]),
    crate = "adbshell",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/wait-timeout/0.2.1:wait_timeout",
    ],
)
