load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accountNovaFi",
    srcs = glob(["**/*.rs"]),
    crate = "accountNovaFi",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayref/0.3.9:arrayref",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/karima-anchor-lang/0.19.0:karima_anchor_lang",
        "//third-party/rust/crates/karima-anchor-spl/0.19.0:karima_anchor_spl",
        "//third-party/rust/crates/num-derive/0.3.3:num_derive",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/num_enum/0.5.11:num_enum",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/solana-program/1.18.26:solana_program",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
