load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/aead/aead-0.6.0-rc.7.crate",
    ],
    sha256 = "a6901123ca1812824ee1c21b59b5e6bf078673ed9b833910f4a7631e4a7d07e8",
    type = "tar.gz",
    strip_prefix = "aead-0.6.0-rc.7",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "aead",
    srcs = [":vendor"],
    crate = "aead",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",
    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
