load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_adxl355",
    srcs = glob(["**/*.rs"]),
    crate = "adi_adxl355",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/micromath/2.1.0:micromath",
    ],
)
