use super::sql::Field;
use serde::{Serialize, de::DeserializeOwned};
use sqlx::FromRow;
use sqlx::postgres::PgRow;
use std::fmt::Display;
use std::hash::Hash;
use std::str::FromStr;

/// Static metadata about a database-backed resource.
///
/// No runtime reflection: every piece of metadata is either a `const`
/// (known at compile time) or an associated type. The `#[derive(Entity)]`
/// macro in `ferrumec-admin-macros` generates this impl from struct
/// field/attribute annotations — see `examples/product.rs`.
pub trait Entity: for<'r> FromRow<'r, PgRow> + Serialize + Send + Sync + Unpin + 'static {
    /// Primary key type (Uuid, i64, ...).
    type Id: for<'a> sqlx::Encode<'a, sqlx::Postgres>
        + sqlx::Type<sqlx::Postgres>
        + Display
        + Clone
        + Eq
        + Hash
        + Send
        + Sync
        + DeserializeOwned
        + Serialize
        + FromStr;

    /// Payload accepted on `POST`. Also `Serialize` so the default
    /// `Repository::insert_columns` impl can read it back as a JSON object
    /// and look each field up by name against `FIELDS` — see `sql.rs`.
    type CreateDto: Serialize + DeserializeOwned + Send + Sync;

    /// Payload accepted on `PUT`/`PATCH`. `PATCH` treats every field as
    /// optional; implementors typically make all fields `Option<T>` and
    /// add `#[serde(skip_serializing_if = "Option::is_none")]` so an
    /// absent field is genuinely absent from the serialized object rather
    /// than present-as-null — that's what lets the default
    /// `update_columns` tell "leave this column alone" apart from
    /// "set this column to NULL".
    type UpdateDto: Serialize + DeserializeOwned + Send + Sync;

    /// Shape returned to clients. Often the entity itself, but kept
    /// separate so internal columns (password hashes, soft-delete flags)
    /// never leak into responses.
    type ResponseDto: Serialize + Send + Sync + From<Self>;

    /// SQL table name.
    const TABLE: &'static str;

    /// Primary key column name.
    const PK_COLUMN: &'static str = "id";

    /// All selectable columns, in the order the `FromRow` impl expects them.
    const COLUMNS: &'static [&'static str];

    /// `(column name, SqlType)` for every column the default
    /// `Repository::insert_columns`/`update_columns` should write. Used to
    /// pick the right typed `SqlValue` variant per field instead of
    /// binding everything as `jsonb`. Generated by `#[derive(Entity)]`
    /// from each field's Rust type — see `ferrumec-admin-macros`.
    const FIELDS: &'static [Field];

    /// Columns eligible for the `?search=` query param (ILIKE match).
    const SEARCHABLE: &'static [&'static str] = &[];

    /// Columns eligible for `?sort=field` / `?sort=-field`.
    const SORTABLE: &'static [&'static str] = &[];

    /// Columns eligible for `?field=value` equality filters.
    const FILTERABLE: &'static [&'static str] = &[];

    /// Soft-delete support: name of the boolean/timestamp column, if any.
    const SOFT_DELETE_COLUMN: Option<&'static str> = None;

    /// Extract the primary key from an instance (used after insert/update).
    fn id(&self) -> Self::Id;
}
