load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_policy",
    srcs = glob(["**/*.rs"]),
    crate = "act_policy",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-types/0.13.1:act_types",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/cidr/0.3.2:cidr",
        "//third-party/rust/crates/globset/0.4.20:globset",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shellexpand/3.1.2:shellexpand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
