load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_limitation",
    srcs = glob(["**/*.rs"]),
    crate = "actix_limitation",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis/0.16.0:redis",
        "//third-party/rust/crates/time/0.2.27:time",
    ],
)
