load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_conduits",
    srcs = glob(["**/*.rs"]),
    crate = "acme_conduits",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/mio/0.8.11:mio",
        "//third-party/rust/crates/scsys/0.1.42:scsys",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
