load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_core",
    srcs = glob(["**/*.rs"]),
    crate = "adk_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
