load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aaai_core",
    srcs = glob(["**/*.rs"]),
    crate = "aaai_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
