load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_engine",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_engine",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionqueue-core/0.1.2:actionqueue_core",
        "//third-party/rust/crates/actionqueue-executor-local/0.1.2:actionqueue_executor_local",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
