load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abcrypt",
    srcs = glob(["**/*.rs"]),
    crate = "abcrypt",
    crate_root = "src/main.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abcrypt/0.4.0:abcrypt",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/byte-unit/5.2.5:byte_unit",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/clap_complete_nushell/4.6.2:clap_complete_nushell",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/sysexits/0.8.5:sysexits",
    ],
)
