load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abitious_stub",
    srcs = glob(["**/*.rs"]),
    crate = "abitious_stub",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abitious-decmpfs/0.1.0:abitious_decmpfs",
    ],
)
