load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acorns",
    srcs = glob(["**/*.rs"]),
    crate = "acorns",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/askama/0.12.1:askama",
        "//third-party/rust/crates/bpaf/0.9.27:bpaf",
        "//third-party/rust/crates/bugzilla_query/1.2.1:bugzilla_query",
        "//third-party/rust/crates/color-eyre/0.6.5:color_eyre",
        "//third-party/rust/crates/counter/0.5.7:counter",
        "//third-party/rust/crates/include_dir/0.7.4:include_dir",
        "//third-party/rust/crates/jira_query/1.7.4:jira_query",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/simplelog/0.12.2:simplelog",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
