load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_rl",
    srcs = glob(["**/*.rs"]),
    crate = "actix_rl",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
