load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aas_cli",
    srcs = glob(["**/*.rs"]),
    crate = "aas_cli",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.27.0:crossterm",
        "//third-party/rust/crates/dashmap/5.5.3:dashmap",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/ratatui/0.26.3:ratatui",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rusqlite/0.31.0:rusqlite",
        "//third-party/rust/crates/rustyline/14.0.0:rustyline",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sysinfo/0.30.13:sysinfo",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.5.2:tower_http",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/which/6.0.3:which",
    ],
)
