load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "httpsig",
    srcs = glob(["**/*.rs"]),
    crate = "httpsig",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/ed25519-dalek/3.0.0:ed25519_dalek",
        "//third-party/rust/crates/getrandom/0.4.3:getrandom",
        "//third-party/rust/crates/p256/0.14.0:p256",
        "//third-party/rust/crates/p384/0.14.0:p384",
        "//third-party/rust/crates/rand_core/0.10.1:rand_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
