load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aaahhh",
    srcs = glob(["**/*.rs"]),
    crate = "aaahhh",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/dirs/4.0.0:dirs",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rdev/0.5.3:rdev",
        "//third-party/rust/crates/rodio/0.20.1:rodio",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sysinfo/0.38.4:sysinfo",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
        "//third-party/rust/crates/zip/2.4.2:zip",
    ],
)
