load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adder_one",
    srcs = glob(["**/*.rs"]),
    crate = "adder_one",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
