load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abbreviation",
    srcs = glob(["**/*.rs"]),
    crate = "abbreviation",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
