load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acorn",
    srcs = glob(["**/*.rs"]),
    crate = "acorn",
    crate_root = "src/bin/acorn.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)

rust_binary(
    name = "acorn",
    srcs = glob(["**/*.rs"]),
    crate = "acorn",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
