load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code_rust_runner",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code_rust_runner",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
