load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_time",
    srcs = glob(["**/*.rs"]),
    crate = "ad_time",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
