load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adm_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adm_cli",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/adm/0.1.0:adm",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/structopt/0.2.18:structopt",
        "//third-party/rust/crates/toml/0.4.10:toml",
    ],
)
