load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_rs_fluent",
    srcs = glob(["**/*.rs"]),
    crate = "adk_rs_fluent",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rs-adk/0.1.0:rs_adk",
        "//third-party/rust/crates/rs-genai/0.1.0:rs_genai",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
