load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_graph",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_graph",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-core/0.0.1:adhammer_core",
        "//third-party/rust/crates/adhammer-sddl/0.0.1:adhammer_sddl",
        "//third-party/rust/crates/petgraph/0.6.5:petgraph",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
