load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abus",
    srcs = glob(["**/*.rs"]),
    crate = "abus",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/serde_core/1.0.229:serde_core",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
