load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abyss_lang",
    srcs = glob(["**/*.rs"]),
    crate = "abyss_lang",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ariadne/0.6.0:ariadne",
        "//third-party/rust/crates/chumsky/0.11.2:chumsky",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/ordered-float/5.3.0:ordered_float",
        "//third-party/rust/crates/rustyline/17.0.2:rustyline",
    ],
)
