load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aa_fastlink",
    srcs = glob(["**/*.rs"]),
    crate = "aa_fastlink",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.52.4:tokio",
        "//third-party/rust/crates/warp/0.4.3:warp",
    ],
)
