load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adk_cli",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-agent/0.1.9:adk_agent",
        "//third-party/rust/crates/adk-artifact/0.1.9:adk_artifact",
        "//third-party/rust/crates/adk-core/0.1.9:adk_core",
        "//third-party/rust/crates/adk-model/0.1.9:adk_model",
        "//third-party/rust/crates/adk-runner/0.1.9:adk_runner",
        "//third-party/rust/crates/adk-server/0.1.9:adk_server",
        "//third-party/rust/crates/adk-session/0.1.9:adk_session",
        "//third-party/rust/crates/adk-telemetry/0.1.9:adk_telemetry",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rustyline/14.0.0:rustyline",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
