load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actiondb",
    srcs = glob(["**/*.rs"]),
    crate = "actiondb",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/maplit/0.1.6:maplit",
        "//third-party/rust/crates/serde/0.6.15:serde",
        "//third-party/rust/crates/serde_json/0.6.1:serde_json",
        "//third-party/rust/crates/uuid/0.1.18:uuid",
    ],
)
