load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actus",
    srcs = glob(["**/*.rs"]),
    crate = "actus",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actus-controller/1.1.0:actus_controller",
        "//third-party/rust/crates/actus-reply/1.1.0:actus_reply",
        "//third-party/rust/crates/actus-server/1.1.0:actus_server",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
    ],
)
