load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_zero",
    srcs = glob(["**/*.rs"]),
    crate = "act_zero",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/act-zero-macro/0.1.0:act_zero_macro",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
