load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarc",
    srcs = glob(["**/*.rs"]),
    crate = "aarc",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fast-smr/0.2.3:fast_smr",
    ],
)
