load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actorizor",
    srcs = glob(["**/*.rs"]),
    crate = "actorizor",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actorizor-macros/0.2.0:actorizor_macros",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
