load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ws",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ws",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.5.2:actix_codec",
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
