load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams_types",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams_types",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activitystreams-derive/0.2.0:activitystreams_derive",
        "//third-party/rust/crates/activitystreams-traits/0.2.0:activitystreams_traits",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
