load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarchmrs_types",
    srcs = glob(["**/*.rs"]),
    crate = "aarchmrs_types",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hex/0.4.3:hex",
    ],
)
