load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr2line",
    srcs = glob(["**/*.rs"]),
    crate = "addr2line",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/gimli/0.27.3:gimli",
    ],
)
