load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_middleware_oso",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_middleware_oso",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/oso/0.26.4:oso",
    ],
)
