load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/acoustix/acoustix-0.1.0.crate",
    ],
    sha256 = "f80effbc1002590723f31536f24d4da3b411ec8e09d2b10fbfdd4c14e97b192c",
    type = "tar.gz",
    strip_prefix = "acoustix-0.1.0",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "acoustix",
    srcs = [":vendor"],
    crate = "acoustix",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
