load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_rt",
    srcs = glob(["**/*.rs"]),
    crate = "actix_rt",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-threadpool/0.1.2:actix_threadpool",
        "//third-party/rust/crates/copyless/0.1.5:copyless",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/tokio-current-thread/0.1.7:tokio_current_thread",
        "//third-party/rust/crates/tokio-executor/0.1.10:tokio_executor",
        "//third-party/rust/crates/tokio-reactor/0.1.12:tokio_reactor",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
