load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach_util",
    srcs = glob(["**/*.rs"]),
    crate = "ach_util",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/atomic/0.6.1:atomic",
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/spin_loop/0.2.5:spin_loop",
    ],
)
