load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_storage",
    srcs = glob(["**/*.rs"]),
    crate = "adi_storage",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/whoami/0.2.4:whoami",
    ],
)
