load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_standby",
    srcs = glob(["**/*.rs"]),
    crate = "active_standby",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/more-asserts/0.2.2:more_asserts",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/slab/0.4.12:slab",
    ],
)
