load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_net",
    srcs = glob(["**/*.rs"]),
    crate = "actix_net",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mio/0.6.23:mio",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/tokio-codec/0.1.2:tokio_codec",
        "//third-party/rust/crates/tokio-current-thread/0.1.7:tokio_current_thread",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-reactor/0.1.12:tokio_reactor",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
        "//third-party/rust/crates/tokio/0.1.22:tokio",
        "//third-party/rust/crates/tower-service/0.1.0:tower_service",
        "//third-party/rust/crates/trust-dns-proto/0.5.0:trust_dns_proto",
        "//third-party/rust/crates/trust-dns-resolver/0.10.3:trust_dns_resolver",
    ],
)
