load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acr",
    srcs = glob(["**/*.rs"]),
    crate = "acr",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arboard/3.6.1:arboard",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/scraper/0.20.0:scraper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
