load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actpub_axum",
    srcs = glob(["**/*.rs"]),
    crate = "actpub_axum",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actpub-federation/0.2.3:actpub_federation",
        "//third-party/rust/crates/actpub-nodeinfo/0.2.3:actpub_nodeinfo",
        "//third-party/rust/crates/actpub-webfinger/0.2.3:actpub_webfinger",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
