load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_middleware_opa",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_middleware_opa",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/base64/0.10.1:base64",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/http/0.1.21:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/url/1.7.2:url",
    ],
)
