load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abol_parser",
    srcs = glob(["**/*.rs"]),
    crate = "abol_parser",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
