load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actions_core",
    srcs = glob(["**/*.rs"]),
    crate = "actions_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
