load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_redirect",
    srcs = glob(["**/*.rs"]),
    crate = "acme_redirect",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acme-micro/0.14.0:acme_micro",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clap_complete/4.6.9:clap_complete",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/config/0.15.25:config",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nix/0.31.3:nix",
        "//third-party/rust/crates/pem/3.0.6:pem",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
        "//third-party/rust/crates/uzers/0.12.2:uzers",
        "//third-party/rust/crates/x509-parser/0.18.1:x509_parser",
    ],
)
