load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_maps",
    srcs = glob(["**/*.rs"]),
    crate = "action_maps",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bevy_app/0.12.1:bevy_app",
        "//third-party/rust/crates/bevy_ecs/0.12.1:bevy_ecs",
        "//third-party/rust/crates/bevy_input/0.12.1:bevy_input",
        "//third-party/rust/crates/bevy_log/0.12.1:bevy_log",
        "//third-party/rust/crates/bevy_reflect/0.12.1:bevy_reflect",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
