load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_concurrency_bounded_map_core",
    srcs = glob(["**/*.rs"]),
    crate = "adze_concurrency_bounded_map_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-concurrency-plan-core/0.1.0:adze_concurrency_plan_core",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
