load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "form_data",
    srcs = glob(["**/*.rs"]),
    crate = "form_data",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/0.2.6:actix_rt",
        "//third-party/rust/crates/actix-threadpool/0.1.2:actix_threadpool",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/http/0.1.21:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
    ],
)
