load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_file",
    srcs = glob(["**/*.rs"]),
    crate = "act_file",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
