load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_typegen_codegen",
    srcs = glob(["**/*.rs"]),
    crate = "abi_typegen_codegen",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi-typegen-config/0.1.0:abi_typegen_config",
        "//third-party/rust/crates/abi-typegen-core/0.1.0:abi_typegen_core",
        "//third-party/rust/crates/heck/0.5.0:heck",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
