load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_sim",
    srcs = glob(["**/*.rs"]),
    crate = "ace_sim",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-core/0.5.5:ace_core",
    ],
)
