load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_determinism",
    srcs = glob(["**/*.rs"]),
    crate = "add_determinism",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/indoc/2.0.7:indoc",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pyo3/0.20.3:pyo3",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
