load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart_rfc7578",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart_rfc7578",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/common-multipart-rfc7578/0.3.1:common_multipart_rfc7578",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
