load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a_puzzle_a_day",
    srcs = glob(["**/*.rs"]),
    crate = "a_puzzle_a_day",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.15.11:console",
        "//third-party/rust/crates/crossterm/0.27.0:crossterm",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/ratatui/0.26.3:ratatui",
    ],
)
