load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_query_method_middleware",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_query_method_middleware",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/qstring/0.7.2:qstring",
    ],
)
