load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_jwt",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_jwt",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/jsonwebtoken/8.3.0:jsonwebtoken",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
