load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adarank",
    srcs = glob(["**/*.rs"]),
    crate = "adarank",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/encode_unicode/0.3.6:encode_unicode",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
