load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actor12",
    srcs = glob(["**/*.rs"]),
    crate = "actor12",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/downcast-rs/1.2.1:downcast_rs",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/metrics/0.23.1:metrics",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/take-once/0.1.3:take_once",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
