load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptxmr",
    srcs = glob(["**/*.rs"]),
    crate = "acceptxmr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/hyper-rustls/0.23.2:hyper_rustls",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/monero/0.18.2:monero",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sled/0.34.7:sled",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
