load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aauth",
    srcs = glob(["**/*.rs"]),
    crate = "aauth",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/jsonwebtoken/10.4.0:jsonwebtoken",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sfv/0.15.0:sfv",
        "//third-party/rust/crates/sha2/0.11.0:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
