load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aderyn_driver",
    srcs = glob(["**/*.rs"]),
    crate = "aderyn_driver",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aderyn_core/0.0.27:aderyn_core",
        "//third-party/rust/crates/foundry-config/0.2.0:foundry_config",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
    ],
)
