load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility_scraper",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility_scraper",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/cssparser/0.27.2:cssparser",
        "//third-party/rust/crates/ego-tree/0.6.3:ego_tree",
        "//third-party/rust/crates/fast_html5ever/0.26.6:fast_html5ever",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/selectors/0.22.0:selectors",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/tendril/0.4.3:tendril",
    ],
)
