load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adiscord",
    srcs = glob(["**/*.rs"]),
    crate = "adiscord",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dotenv_codegen/0.15.0:dotenv_codegen",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
