load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acc_reader",
    srcs = glob(["**/*.rs"]),
    crate = "acc_reader",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
