load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advreader",
    srcs = glob(["**/*.rs"]),
    crate = "advreader",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/encoding/0.2.33:encoding",
        "//third-party/rust/crates/flume/0.11.1:flume",
    ],
)
