load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actus_server",
    srcs = glob(["**/*.rs"]),
    crate = "actus_server",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actus-controller/1.1.0:actus_controller",
        "//third-party/rust/crates/actus-reply/1.1.0:actus_reply",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/http-body-util/0.1.4:http_body_util",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/hyper-util/0.1.20:hyper_util",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
