load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_sddl",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_sddl",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adhammer-core/0.0.1:adhammer_core",
        "//third-party/rust/crates/bitflags/2.13.1:bitflags",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
