load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_client",
    srcs = glob(["**/*.rs"]),
    crate = "adb_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/homedir/0.3.6:homedir",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-bigint-dig/0.6.1:num_bigint_dig",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rsa/0.3.0:rsa",
        "//third-party/rust/crates/rusb/0.9.4:rusb",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
