load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actix_cli",
    srcs = glob(["**/*.rs"]),
    crate = "actix_cli",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/convert_case/0.4.0:convert_case",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
        "//third-party/rust/crates/toml/0.4.10:toml",
    ],
)
