load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aderyn",
    srcs = glob(["**/*.rs"]),
    crate = "aderyn",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aderyn_driver/0.1.9:aderyn_driver",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/notify-debouncer-full/0.3.2:notify_debouncer_full",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
