load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actioneer",
    srcs = glob(["**/*.rs"]),
    crate = "actioneer",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anstream/1.0.0:anstream",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/clap-verbosity-flag/3.0.4:clap_verbosity_flag",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/owo-colors/4.3.0:owo_colors",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/yaml_serde/0.10.5:yaml_serde",
        "//third-party/rust/crates/yamlpath/1.29.0:yamlpath",
    ],
)
