load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a",
    srcs = glob(["**/*.rs"]),
    crate = "a",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bat/0.22.1:bat",
        "//third-party/rust/crates/copypasta-ext/0.4.4:copypasta_ext",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
