load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adb_wireless",
    srcs = glob(["**/*.rs"]),
    crate = "adb_wireless",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/flume/0.11.1:flume",
        "//third-party/rust/crates/mdns-sd/0.13.11:mdns_sd",
        "//third-party/rust/crates/qr2term/0.3.3:qr2term",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
