load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_storage",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_storage",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionqueue-core/0.1.2:actionqueue_core",
        "//third-party/rust/crates/crc32fast/1.5.0:crc32fast",
        "//third-party/rust/crates/postcard/1.1.3:postcard",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
