load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_nats",
    srcs = glob(["**/*.rs"]),
    crate = "actix_nats",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/nats/0.3.3:nats",
    ],
)
