load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adventure_rusoto_ecs",
    srcs = glob(["**/*.rs"]),
    crate = "adventure_rusoto_ecs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adventure/0.3.0:adventure",
        "//third-party/rust/crates/rusoto_core/0.37.0:rusoto_core",
        "//third-party/rust/crates/rusoto_ecs/0.37.0:rusoto_ecs",
    ],
)
