load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_speaker",
    srcs = glob(["**/*.rs"]),
    crate = "adi_speaker",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/nix/0.9.0:nix",
    ],
)
