load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abtc_adapters",
    srcs = glob(["**/*.rs"]),
    crate = "abtc_adapters",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abtc-domain/0.1.0:abtc_domain",
        "//third-party/rust/crates/abtc-ports/0.1.0:abtc_ports",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/secp256k1/0.29.1:secp256k1",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
