load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actpub_httpsig",
    srcs = glob(["**/*.rs"]),
    crate = "actpub_httpsig",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aws-lc-rs/1.18.0:aws_lc_rs",
        "//third-party/rust/crates/base64ct/1.8.3:base64ct",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/httpdate/1.0.3:httpdate",
        "//third-party/rust/crates/multibase/0.9.3:multibase",
        "//third-party/rust/crates/pem/3.0.6:pem",
        "//third-party/rust/crates/pkcs8/0.10.2:pkcs8",
        "//third-party/rust/crates/sfv/0.14.0:sfv",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/unsigned-varint/0.8.0:unsigned_varint",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
