load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_sentry",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_sentry",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-acl/0.3.0:a3s_acl",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/hcl-rs/0.18.7:hcl_rs",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
