load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abcperf_demo",
    srcs = glob(["**/*.rs"]),
    crate = "abcperf_demo",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abcperf-generic-client/0.10.0:abcperf_generic_client",
        "//third-party/rust/crates/abcperf-minbft/0.10.0:abcperf_minbft",
        "//third-party/rust/crates/abcperf-noop/0.10.0:abcperf_noop",
        "//third-party/rust/crates/abcperf/0.10.0:abcperf",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/usig/0.10.0:usig",
    ],
)
