load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_card_core",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_card_core",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/jsonschema/0.46.10:jsonschema",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
