load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acube",
    srcs = glob(["**/*.rs"]),
    crate = "acube",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acube-macros/0.1.0:acube_macros",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dashmap/5.5.3:dashmap",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/jsonwebtoken/9.3.1:jsonwebtoken",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/secrecy/0.8.0:secrecy",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.5.2:tower_http",
        "//third-party/rust/crates/tower/0.4.13:tower",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
