load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aarch64-cpu/10.0.0:aarch64_cpu",
        "//third-party/rust/crates/memory_addresses/0.2.3:memory_addresses",
        "//third-party/rust/crates/tock-registers/0.9.0:tock_registers",
    ],
)
