load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aca",
    srcs = glob(["**/*.rs"]),
    crate = "aca",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shell-escape/0.1.5:shell_escape",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.9.8:toml",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/which/6.0.3:which",
    ],
)
