load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_delay",
    srcs = glob(["**/*.rs"]),
    crate = "actix_delay",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/futures-timer/3.0.4:futures_timer",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
