load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abnf_parser",
    srcs = glob(["**/*.rs"]),
    crate = "abnf_parser",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quick-error/2.0.1:quick_error",
    ],
)
