load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_unix",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_unix",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.9.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.13.0:accesskit_consumer",
        "//third-party/rust/crates/async-channel/1.9.0:async_channel",
        "//third-party/rust/crates/atspi/0.8.7:atspi",
        "//third-party/rust/crates/futures-lite/1.13.0:futures_lite",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/zbus/3.15.2:zbus",
    ],
)
