load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_middleware_macro",
    srcs = glob(["**/*.rs"]),
    crate = "actix_middleware_macro",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/paste/1.0.15:paste",
    ],
)
