load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abtc_ports",
    srcs = glob(["**/*.rs"]),
    crate = "abtc_ports",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abtc-domain/0.1.0:abtc_domain",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
