load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_diesel",
    srcs = glob(["**/*.rs"]),
    crate = "actix_diesel",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/derive_more/0.13.0:derive_more",
        "//third-party/rust/crates/diesel/1.4.8:diesel",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/once_cell/0.1.8:once_cell",
        "//third-party/rust/crates/r2d2/0.8.10:r2d2",
    ],
)
