load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_easy_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_easy_multipart",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-multipart/0.4.0:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/multimap/0.8.3:multimap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
