load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acme_dns_rust",
    srcs = glob(["**/*.rs"]),
    crate = "acme_dns_rust",
    crate_root = "src/main.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acme-lib/0.8.2:acme_lib",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bcrypt/0.8.2:bcrypt",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.11.2:parking_lot",
        "//third-party/rust/crates/rustls/0.18.1:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/simplelog/0.8.0:simplelog",
        "//third-party/rust/crates/tokio-rustls/0.14.1:tokio_rustls",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
        "//third-party/rust/crates/toml/0.5.11:toml",
        "//third-party/rust/crates/trust-dns-client/0.19.7:trust_dns_client",
        "//third-party/rust/crates/trust-dns-server/0.19.7:trust_dns_server",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
        "//third-party/rust/crates/warp/0.2.5:warp",
    ],
)
