load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstracttui",
    srcs = glob(["**/*.rs"]),
    crate = "abstracttui",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/miniz_oxide/0.9.1:miniz_oxide",
        "//third-party/rust/crates/unicode-segmentation/1.13.3:unicode_segmentation",
        "//third-party/rust/crates/unicode-width/0.2.2:unicode_width",
    ],
)
