load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_xion",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_xion",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bech32/0.9.1:bech32",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-storage-plus/2.0.0:cw_storage_plus",
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/p256/0.13.2:p256",
        "//third-party/rust/crates/prost/0.13.5:prost",
        "//third-party/rust/crates/ripemd/0.1.3:ripemd",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tiny-keccak/2.0.2:tiny_keccak",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
