load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix",
    srcs = glob(["**/*.rs"]),
    crate = "actix",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/lazy_static/0.2.11:lazy_static",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/mio/0.6.23:mio",
        "//third-party/rust/crates/tokio-core/0.1.18:tokio_core",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
    ],
)
