load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adder_codec_core",
    srcs = glob(["**/*.rs"]),
    crate = "adder_codec_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bitstream-io/1.10.0:bitstream_io",
        "//third-party/rust/crates/enum_dispatch/0.3.13:enum_dispatch",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_bytes/0.11.19:serde_bytes",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
