load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_lite",
    srcs = glob(["**/*.rs"]),
    crate = "acme_lite",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/der/0.7.10:der",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
        "//third-party/rust/crates/x509-cert/0.2.5:x509_cert",
    ],
)
