load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_validation",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_validation",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
