load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accounting_core",
    srcs = glob(["**/*.rs"]),
    crate = "accounting_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bigdecimal/0.4.10:bigdecimal",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
