load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_money_market_standard",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_money_market_standard",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-adapter-utils/0.23.0:abstract_adapter_utils",
        "//third-party/rust/crates/abstract-adapter/0.23.0:abstract_adapter",
        "//third-party/rust/crates/abstract-sdk/0.23.0:abstract_sdk",
        "//third-party/rust/crates/abstract-std/0.23.0:abstract_std",
        "//third-party/rust/crates/cosmwasm-schema/1.5.11:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-asset/3.1.1:cw_asset",
        "//third-party/rust/crates/cw-orch/0.24.1:cw_orch",
        "//third-party/rust/crates/cw-storage-plus/1.2.0:cw_storage_plus",
        "//third-party/rust/crates/cw20/1.1.2:cw20",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
