load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel_stepper",
    srcs = glob(["**/*.rs"]),
    crate = "accel_stepper",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.4.12:arrayvec",
        "//third-party/rust/crates/libm/0.1.4:libm",
        "//third-party/rust/crates/void/1.0.2:void",
    ],
)
