load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_consumer",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_consumer",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.20.0:accesskit",
        "//third-party/rust/crates/hashbrown/0.15.5:hashbrown",
    ],
)
