load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abacus_rs",
    srcs = glob(["**/*.rs"]),
    crate = "abacus_rs",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.27.0:crossterm",
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/itertools/0.12.1:itertools",
        "//third-party/rust/crates/ratatui/0.26.3:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
