load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_wamp",
    srcs = glob(["**/*.rs"]),
    crate = "actix_wamp",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/0.2.11:actix_http",
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/awc/0.2.8:awc",
        "//third-party/rust/crates/base64/0.10.1:base64",
        "//third-party/rust/crates/crypto-mac/0.7.0:crypto_mac",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/hmac/0.7.1:hmac",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/rand/0.6.5:rand",
        "//third-party/rust/crates/rmp/0.8.15:rmp",
        "//third-party/rust/crates/rmpv/0.4.7:rmpv",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.8.2:sha2",
    ],
)
