load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ada_url",
    srcs = glob(["**/*.rs"]),
    crate = "ada_url",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
)
