load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_server_core",
    srcs = glob(["**/*.rs"]),
    crate = "adk_server_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rs-adk/0.5.0:rs_adk",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tower-http/0.5.2:tower_http",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
