load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "accio_string",
    srcs = glob(["**/*.rs"]),
    crate = "accio_string",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
