load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ace2json",
    srcs = glob(["**/*.rs"]),
    crate = "ace2json",
    crate_root = "src/bin/ace2json.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)

rust_binary(
    name = "json2ace",
    srcs = glob(["**/*.rs"]),
    crate = "json2ace",
    crate_root = "src/bin/json2ace.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
