load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_core",
    srcs = glob(["**/*.rs"]),
    crate = "action_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
