load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/typetag/0.1.8:typetag",
    ],
)
