load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adnl",
    srcs = glob(["**/*.rs"]),
    crate = "adnl",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes/0.8.4:aes",
        "//third-party/rust/crates/ctr/0.9.2:ctr",
        "//third-party/rust/crates/everscale-crypto/0.2.1:everscale_crypto",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
