load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adb_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adb_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adb_client/3.2.3:adb_client",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tabwriter/1.4.1:tabwriter",
    ],
)
