load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "act2txt",
    srcs = glob(["**/*.rs"]),
    crate = "act2txt",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/palette/0.7.7:palette",
    ],
)
