load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abc",
    srcs = glob(["**/*.rs"]),
    crate = "abc",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/miette/7.6.0:miette",
        "//third-party/rust/crates/rustyline/17.0.2:rustyline",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unicode-width/0.1.14:unicode_width",
    ],
)
