load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_logger_light",
    srcs = glob(["**/*.rs"]),
    crate = "actix_logger_light",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
