load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart_rfc7578",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart_rfc7578",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/common-multipart-rfc7578/0.1.2:common_multipart_rfc7578",
        "//third-party/rust/crates/futures/0.1.31:futures",
    ],
)
