load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstracttui_graph",
    srcs = glob(["**/*.rs"]),
    crate = "abstracttui_graph",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstracttui/0.3.1:abstracttui",
    ],
)
