load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_actors",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_actors",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.3.0:actix_codec",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures-channel/0.3.34:futures_channel",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
    ],
)
