load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a653rs_linux",
    srcs = glob(["**/*.rs"]),
    crate = "a653rs_linux",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a653rs-linux-core/0.2.2:a653rs_linux_core",
        "//third-party/rust/crates/a653rs/0.6.1:a653rs",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/memmap2/0.9.11:memmap2",
        "//third-party/rust/crates/nix/0.29.0:nix",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/oneshot/0.1.13:oneshot",
        "//third-party/rust/crates/polling/3.11.0:polling",
        "//third-party/rust/crates/procfs/0.16.0:procfs",
        "//third-party/rust/crates/tinyvec/1.12.0:tinyvec",
    ],
)
