load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aba_cache",
    srcs = glob(["**/*.rs"]),
    crate = "aba_cache",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/slab/0.4.12:slab",
    ],
)
