load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aatxe_bench",
    srcs = glob(["**/*.rs"]),
    crate = "aatxe_bench",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aatxe-core/0.1.1:aatxe_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
