load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aci",
    srcs = glob(["**/*.rs"]),
    crate = "aci",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/http-body-util/0.1.4:http_body_util",
        "//third-party/rust/crates/http-body/1.1.0:http_body",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/openapiv3/2.2.0:openapiv3",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.9.8:toml",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
