load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abomonation_derive",
    srcs = glob(["**/*.rs"]),
    crate = "abomonation_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/synstructure/0.12.6:synstructure",
    ],
)
