load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abbrev_num",
    srcs = glob(["**/*.rs"]),
    crate = "abbrev_num",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/rust_decimal/1.42.1:rust_decimal",
    ],
)
