load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abd_clam",
    srcs = glob(["**/*.rs"]),
    crate = "abd_clam",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/automl/0.2.9:automl",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/distances/1.8.0:distances",
        "//third-party/rust/crates/libm/0.2.16:libm",
        "//third-party/rust/crates/postcard/1.1.3:postcard",
        "//third-party/rust/crates/priority-queue/1.4.0:priority_queue",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/smartcore/0.2.1:smartcore",
    ],
)
