load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abrute",
    srcs = glob(["**/*.rs"]),
    crate = "abrute",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/digits/0.3.9:digits",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/rayon/0.8.2:rayon",
    ],
)
