load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "librespot",
    srcs = glob(["**/*.rs"]),
    crate = "librespot",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actinium226-librespot-connect/0.4.3:actinium226_librespot_connect",
        "//third-party/rust/crates/actinium226-librespot-playback/0.4.3:actinium226_librespot_playback",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/getopts/0.2.24:getopts",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/librespot-audio/0.4.2:librespot_audio",
        "//third-party/rust/crates/librespot-core/0.4.2:librespot_core",
        "//third-party/rust/crates/librespot-discovery/0.4.2:librespot_discovery",
        "//third-party/rust/crates/librespot-metadata/0.4.2:librespot_metadata",
        "//third-party/rust/crates/librespot-protocol/0.4.2:librespot_protocol",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rpassword/6.0.1:rpassword",
        "//third-party/rust/crates/sha-1/0.9.8:sha_1",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
