load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "filter_list_manager_ffi",
    srcs = glob(["**/*.rs"]),
    crate = "filter_list_manager_ffi",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adguard-flm/0.7.3:adguard_flm",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uniffi/0.25.3:uniffi",
    ],
)
