load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_tool",
    srcs = glob(["**/*.rs"]),
    crate = "adk_tool",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/1.0.0:adk_core",
        "//third-party/rust/crates/adk-rust-macros/1.0.0:adk_rust_macros",
        "//third-party/rust/crates/adk-telemetry/1.0.0:adk_telemetry",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
