load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitystreams_derive",
    srcs = glob(["**/*.rs"]),
    crate = "activitystreams_derive",
    crate_root = "src/lib.rs",
    edition = "2015",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/0.3.8:proc_macro2",
        "//third-party/rust/crates/quote/0.5.2:quote",
        "//third-party/rust/crates/syn/0.13.11:syn",
    ],
)
