load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart_extract",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart_extract",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-multipart-extract-derive/0.1.5:actix_multipart_extract_derive",
        "//third-party/rust/crates/actix-multipart/0.4.0:actix_multipart",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde-aux/3.1.0:serde_aux",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
