load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "action_proof",
    srcs = glob(["**/*.rs"]),
    crate = "action_proof",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/camino/1.2.5:camino",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dunce/1.0.5:dunce",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yml/0.0.12:serde_yml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
