load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_rs",
    srcs = glob(["**/*.rs"]),
    crate = "acme_rs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/flexi_logger/0.17.1:flexi_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/rouille/3.6.2:rouille",
        "//third-party/rust/crates/rpki/0.10.1:rpki",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
