load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_windows",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_windows",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.3.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.3.0:accesskit_consumer",
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/lazy-init/0.5.1:lazy_init",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/windows/0.27.0:windows",
    ],
)
