load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abpl_macros",
    srcs = glob(["**/*.rs"]),
    crate = "abpl_macros",
    crate_root = "src/lib.rs",
    edition = "2024",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/convert_case/0.11.0:convert_case",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/3.0.3:syn",
    ],
)
