load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acme_champion",
    srcs = glob(["**/*.rs"]),
    crate = "acme_champion",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/httparse/1.10.1:httparse",
        "//third-party/rust/crates/mio/1.2.2:mio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
