load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aafk_sober",
    srcs = glob(["**/*.rs"]),
    crate = "aafk_sober",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/evdev/0.12.2:evdev",
        "//third-party/rust/crates/glib/0.18.5:glib",
        "//third-party/rust/crates/gtk4/0.7.3:gtk4",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/ksni/0.2.2:ksni",
        "//third-party/rust/crates/nix/0.23.2:nix",
        "//third-party/rust/crates/notify-rust/4.18.0:notify_rust",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
