//! Parsing the two model JSON response shapes `create` deals with: the
//! authored skill candidate, and the generated eval dataset.

use serde::Deserialize;

use crate::candidate::strip_code_fence;
use crate::create::CreateError;

/// One companion file the model wants to write alongside SKILL.md.
#[derive(Debug, Clone, Deserialize)]
pub struct GeneratedCompanionFile {
    /// A relative path within the skill's own directory, e.g.
    /// `"REFERENCE.md"`. Validated (and resolved to an absolute path) by
    /// [`crate::resolve_companion_path`] before use.
    pub path: String,
    /// The file's full contents.
    pub content: String,
}

/// The model's raw JSON response to an authoring or repair request: a
/// complete candidate skill.
#[derive(Debug, Clone, Deserialize)]
pub struct GenerateResponse {
    /// The skill's frontmatter `name`.
    pub name: String,
    /// The skill's frontmatter `description`.
    pub description: String,
    /// Whether the skill should set `disable-model-invocation: true`.
    #[serde(default)]
    pub disable_model_invocation: bool,
    /// The SKILL.md Markdown body (no frontmatter).
    pub body: String,
    /// Companion files to write alongside SKILL.md.
    #[serde(default)]
    pub companion_files: Vec<GeneratedCompanionFile>,
}

impl GenerateResponse {
    /// Parse a model response as a [`GenerateResponse`], tolerating a
    /// markdown code fence around the JSON (see
    /// [`crate::candidate::strip_code_fence`]).
    ///
    /// # Errors
    /// Returns [`CreateError::MalformedResponse`] if the (fence-stripped)
    /// content is not valid JSON in the expected shape.
    pub fn parse(content: &str) -> Result<Self, CreateError> {
        let stripped = strip_code_fence(content.trim());
        serde_json::from_str(stripped)
            .map_err(|e| CreateError::MalformedResponse(format!("generate response: {e}")))
    }
}

/// One eval case as generated by the model, before `create` stamps it with
/// `schema_version` (see [`adept::evals::EvalCase`]).
#[derive(Debug, Clone, Deserialize)]
pub struct GeneratedEvalCase {
    /// The prompt the skill under test should handle.
    pub prompt: String,
    /// The assertions a harness would check the response against.
    #[serde(default)]
    pub assertions: Vec<adept::evals::Assertion>,
}

/// The model's raw JSON response to the eval-dataset generation request.
#[derive(Debug, Clone, Deserialize)]
pub struct EvalGenerationResponse {
    /// The generated cases.
    pub cases: Vec<GeneratedEvalCase>,
}

impl EvalGenerationResponse {
    /// Parse a model response as an [`EvalGenerationResponse`], tolerating a
    /// markdown code fence around the JSON.
    ///
    /// # Errors
    /// Returns [`CreateError::MalformedResponse`] if the (fence-stripped)
    /// content is not valid JSON in the expected shape.
    pub fn parse(content: &str) -> Result<Self, CreateError> {
        let stripped = strip_code_fence(content.trim());
        serde_json::from_str(stripped)
            .map_err(|e| CreateError::MalformedResponse(format!("eval generation response: {e}")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_plain_generate_response() {
        let parsed = GenerateResponse::parse(
            "{\"name\": \"demo\", \"description\": \"d\", \"body\": \"# Demo\\n\"}",
        )
        .unwrap();
        assert_eq!(parsed.name, "demo");
        assert!(!parsed.disable_model_invocation);
        assert!(parsed.companion_files.is_empty());
    }

    #[test]
    fn parses_fenced_generate_response() {
        let parsed = GenerateResponse::parse(
            "```json\n{\"name\": \"demo\", \"description\": \"d\", \"body\": \"# Demo\\n\"}\n```",
        )
        .unwrap();
        assert_eq!(parsed.name, "demo");
    }

    #[test]
    fn rejects_malformed_generate_response() {
        assert!(GenerateResponse::parse("not json").is_err());
    }

    #[test]
    fn parses_eval_generation_response() {
        let parsed = EvalGenerationResponse::parse(
            r#"{"cases": [{"prompt": "do it", "assertions": [{"kind": "contains", "value": "ok"}]}]}"#,
        )
        .unwrap();
        assert_eq!(parsed.cases.len(), 1);
        assert_eq!(parsed.cases[0].prompt, "do it");
    }
}
