load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_connector",
    srcs = glob(["**/*.rs"]),
    crate = "actix_connector",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-rt/0.1.0:actix_rt",
        "//third-party/rust/crates/actix-service/0.1.6:actix_service",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/trust-dns-proto/0.6.3:trust_dns_proto",
        "//third-party/rust/crates/trust-dns-resolver/0.10.3:trust_dns_resolver",
    ],
)
