load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ade_graph",
    srcs = glob(["**/*.rs"]),
    crate = "ade_graph",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ade-traits/0.1.0:ade_traits",
        "//third-party/rust/crates/fixedbitset/0.4.2:fixedbitset",
    ],
)
