load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "address_artisan",
    srcs = glob(["**/*.rs"]),
    crate = "address_artisan",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitcoin/0.32.102:bitcoin",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.29.0:crossterm",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/lru/0.16.4:lru",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/ocl/0.19.7:ocl",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/ratatui/0.29.0:ratatui",
        "//third-party/rust/crates/ripemd/0.1.3:ripemd",
        "//third-party/rust/crates/secp256k1/0.31.1:secp256k1",
        "//third-party/rust/crates/sysinfo/0.37.2:sysinfo",
        "//third-party/rust/crates/threadpool/1.8.1:threadpool",
    ],
)
