load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actson",
    srcs = glob(["**/*.rs"]),
    crate = "actson",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lexical/6.1.1:lexical",
    ],
)
