load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_uuid_registry",
    srcs = glob(["**/*.rs"]),
    crate = "active_uuid_registry",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
