load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessory",
    srcs = glob(["**/*.rs"]),
    crate = "accessory",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/macroific/2.0.0:macroific",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
