load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_jwt",
    srcs = glob(["**/*.rs"]),
    crate = "actix_jwt",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/jsonwebtoken/9.3.1:jsonwebtoken",
        "//third-party/rust/crates/pem/3.0.6:pem",
        "//third-party/rust/crates/pkcs8/0.10.2:pkcs8",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
