load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adamantite",
    srcs = glob(["**/*.rs"]),
    crate = "adamantite",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/sysinfo/0.38.4:sysinfo",
    ],
)
