load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acril_http",
    srcs = glob(["**/*.rs"]),
    crate = "acril_http",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/async-tls/0.12.0:async_tls",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/http-types/2.12.0:http_types",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
    ],
)
