load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abxbus_rust",
    srcs = glob(["**/*.rs"]),
    crate = "abxbus_rust",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dcontext/0.7.1:dcontext",
        "//third-party/rust/crates/event-listener/5.4.2:event_listener",
        "//third-party/rust/crates/futures-timer/3.0.4:futures_timer",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
