// This file is @generated by prost-build.
/// Stops/terminates a remote actor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Signal {
    #[prost(enumeration = "signal::Signal", tag = "1")]
    pub signal: i32,
}
/// Nested message and enum types in `Signal`.
pub mod signal {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Signal {
        Stop = 0,
        Terminate = 1,
    }
    impl Signal {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Stop => "STOP",
                Self::Terminate => "TERMINATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STOP" => Some(Self::Stop),
                "TERMINATE" => Some(Self::Terminate),
                _ => None,
            }
        }
    }
}
/// Sets/Unsets a supervisor for a remote actor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Supervisor {
    #[prost(oneof = "supervisor::Supervisor", tags = "1, 2")]
    pub supervisor: ::core::option::Option<supervisor::Supervisor>,
}
/// Nested message and enum types in `Supervisor`.
pub mod supervisor {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Supervisor {
        /// Sets a supervisor for a remote actor.
        #[prost(uint64, tag = "1")]
        Set(u64),
        /// Unsets a supervisor for a remote actor.
        #[prost(message, tag = "2")]
        Unset(()),
    }
}
/// Registers/Unregisters an observer for a remote actor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Observer {
    #[prost(oneof = "observer::Observer", tags = "1, 2")]
    pub observer: ::core::option::Option<observer::Observer>,
}
/// Nested message and enum types in `Observer`.
pub mod observer {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Observer {
        /// Registers an observer for a remote actor.
        #[prost(uint64, tag = "1")]
        Register(u64),
        /// Unregisters an observer for a remote actor.
        #[prost(uint64, tag = "2")]
        Unregister(u64),
    }
}
/// Pauses/Resumes a remote cron actor.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CronSignal {
    #[prost(enumeration = "cron_signal::CronSignal", tag = "1")]
    pub signal: i32,
}
/// Nested message and enum types in `CronSignal`.
pub mod cron_signal {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum CronSignal {
        Pause = 0,
        Resume = 1,
    }
    impl CronSignal {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Pause => "PAUSE",
                Self::Resume => "RESUME",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PAUSE" => Some(Self::Pause),
                "RESUME" => Some(Self::Resume),
                _ => None,
            }
        }
    }
}
/// Reports the status of the current actor to a remote actor.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SupervisionEvent {
    #[prost(oneof = "supervision_event::Event", tags = "1, 2, 3, 4")]
    pub event: ::core::option::Option<supervision_event::Event>,
}
/// Nested message and enum types in `SupervisionEvent`.
pub mod supervision_event {
    /// Warning message, which is used to report a recoverable error.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Warn {
        /// The index of the sender actor.
        #[prost(uint64, tag = "1")]
        pub actor_id: u64,
        /// The error message.
        #[prost(string, tag = "2")]
        pub err: ::prost::alloc::string::String,
    }
    /// Terminated message, which is used to report the termination of an actor.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Terminated {
        /// The index of the sender actor.
        #[prost(uint64, tag = "1")]
        pub actor_id: u64,
        /// The error message, which is used to report the reason for termination.
        #[prost(string, optional, tag = "2")]
        pub err: ::core::option::Option<::prost::alloc::string::String>,
    }
    /// Panicked message, which is used to report a panic.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Panicked {
        /// The index of the sender actor.
        #[prost(uint64, tag = "1")]
        pub actor_id: u64,
        /// The panic info.
        #[prost(string, tag = "2")]
        pub info: ::prost::alloc::string::String,
    }
    /// State message, which is used to report the state of an actor.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct State {
        /// The index of the sender actor.
        #[prost(uint64, tag = "1")]
        pub actor_id: u64,
        /// The state of the sender actor.
        #[prost(enumeration = "state::ActorState", tag = "2")]
        pub state: i32,
    }
    /// Nested message and enum types in `State`.
    pub mod state {
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum ActorState {
            Unstarted = 0,
            Starting = 1,
            Running = 2,
            Stopping = 3,
            Stopped = 4,
        }
        impl ActorState {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unstarted => "UNSTARTED",
                    Self::Starting => "STARTING",
                    Self::Running => "RUNNING",
                    Self::Stopping => "STOPPING",
                    Self::Stopped => "STOPPED",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "UNSTARTED" => Some(Self::Unstarted),
                    "STARTING" => Some(Self::Starting),
                    "RUNNING" => Some(Self::Running),
                    "STOPPING" => Some(Self::Stopping),
                    "STOPPED" => Some(Self::Stopped),
                    _ => None,
                }
            }
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        /// Reports a warning message.
        #[prost(message, tag = "1")]
        Warn(Warn),
        /// Reports a terminated message.
        #[prost(message, tag = "2")]
        Terminated(Terminated),
        /// Reports a panicked message.
        #[prost(message, tag = "3")]
        Panicked(Panicked),
        /// Reports a state message.
        #[prost(message, tag = "4")]
        State(State),
    }
}
