load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme2_slim",
    srcs = glob(["**/*.rs"]),
    crate = "acme2_slim",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/env_logger/0.8.4:env_logger",
        "//third-party/rust/crates/error-chain/0.12.4:error_chain",
        "//third-party/rust/crates/hyper/0.13.10:hyper",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.10.10:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
        "//third-party/rust/crates/warp/0.2.5:warp",
    ],
)
