load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ADuCM302x",
    srcs = glob(["**/*.rs"]),
    crate = "ADuCM302x",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bare-metal/0.2.5:bare_metal",
        "//third-party/rust/crates/cortex-m/0.5.11:cortex_m",
        "//third-party/rust/crates/vcell/0.1.3:vcell",
    ],
)
