load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abe",
    srcs = glob(["**/*.rs"]),
    crate = "abe",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.71:anyhow",
        "//third-party/rust/crates/arrayvec/0.7.2:arrayvec",
        "//third-party/rust/crates/base64/0.21.0:base64",
        "//third-party/rust/crates/bstr/1.13.1:bstr",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde/1.0.160:serde",
        "//third-party/rust/crates/thiserror/1.0.40:thiserror",
    ],
)
