load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_seesaw",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_seesaw",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
    ],
)
