load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_detached_jws_middleware",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_detached_jws_middleware",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-web-buffering/0.1.2:actix_web_buffering",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/detached-jws/0.2.1:detached_jws",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
