load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acceptxmr",
    srcs = glob(["**/*.rs"]),
    crate = "acceptxmr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/backoff/0.4.0:backoff",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/http-body-util/0.1.4:http_body_util",
        "//third-party/rust/crates/hyper-rustls/0.26.0:hyper_rustls",
        "//third-party/rust/crates/hyper-util/0.1.20:hyper_util",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/monero/0.20.0:monero",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.26.3:strum",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
