load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ably_chat",
    srcs = glob(["**/*.rs"]),
    crate = "ably_chat",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ably-chat-openapi/0.2.0:ably_chat_openapi",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
