load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advtools",
    srcs = glob(["**/*.rs"]),
    crate = "advtools",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/hashbrown/0.11.2:hashbrown",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/odds/0.4.0:odds",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
