load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acbc",
    srcs = glob(["**/*.rs"]),
    crate = "acbc",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nom/6.2.2:nom",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tinyvec/1.12.0:tinyvec",
    ],
)
