load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_prom",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_prom",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/prometheus/0.13.4:prometheus",
    ],
)
