load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a608_embedded",
    srcs = glob(["**/*.rs"]),
    crate = "a608_embedded",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/embedded-io/0.7.1:embedded_io",
    ],
)
