load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionidmap_updater",
    srcs = glob(["**/*.rs"]),
    crate = "actionidmap_updater",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nanoserde/0.1.37:nanoserde",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
