load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ogn",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ogn",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.5.8:actix",
        "//third-party/rust/crates/aprs-parser/0.1.1:aprs_parser",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-core/0.1.18:tokio_core",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
    ],
)
