load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ads101x",
    srcs = glob(["**/*.rs"]),
    crate = "ads101x",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal/0.2.7:embedded_hal",
        "//third-party/rust/crates/nb/0.1.3:nb",
    ],
)
