load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ackorelic",
    srcs = glob(["**/*.rs"]),
    crate = "ackorelic",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/diesel/1.4.8:diesel",
        "//third-party/rust/crates/lazy_static/1.2.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/newrelic-sys/0.1.0:newrelic_sys",
    ],
)
