//! Parser for RFC5234 Core Rule "ALPHA"
//!
//! ```text
//! ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z
//! ```
//!
//! <https://www.rfc-editor.org/rfc/rfc5234.html#appendix-B.1>
//!
//! We use the builtin `ASCII_ALPHA` from Pest:
//!
//! | Built-in rule | Equivalent            |
//! |---------------|-----------------------|
//! | `ASCII_ALPHA` | `'a'..'z' | 'A'..'Z'` |
//!
//! <https://pest.rs/book/grammars/built-ins.html#ascii-rules>

alpha = { ASCII_ALPHA }