// Auto-generated by abi-typegen. Do not edit manually.
pragma solidity >=0.8.0;

interface IExchange {
    struct FeeConfig {
        uint16 makerFeeBps;
        uint16 takerFeeBps;
        address feeRecipient;
        bool discountEnabled;
    }

    struct Order {
        address maker;
        address taker;
        address tokenIn;
        address tokenOut;
        uint256 amountIn;
        uint256 amountOut;
        uint256 nonce;
        uint64 deadline;
        bytes32 salt;
        uint8 orderType;
        FeeConfig fees;
    }

    struct Fill {
        bytes32 orderHash;
        uint256 amountFilled;
        uint256 amountRemaining;
        uint64 timestamp;
        address filler;
    }

    struct Pool {
        address token0;
        address token1;
        uint256 reserve0;
        uint256 reserve1;
        uint64 lastUpdate;
        uint16 feeBps;
        bool active;
    }

    struct Route {
        address[] path;
        uint256[] amounts;
        uint256 minOut;
        uint64 deadline;
    }

    error ContractPaused();

    error InsufficientBalance(address token, uint256 available, uint256 required);

    error InvalidOrder(string reason);

    error InvalidRoute(uint256 pathLength);

    error OrderAlreadyFilled(bytes32 orderHash);

    error OrderExpired(bytes32 orderHash, uint64 deadline);

    error PoolInactive(bytes32 poolId);

    error PoolNotFound(bytes32 poolId);

    error SlippageExceeded(uint256 expected, uint256 actual);

    error Unauthorized(address caller);

    error ZeroAmount();

    event Deposit(address indexed user, address indexed token, uint256 amount);

    event FeeCollected(address indexed recipient, address indexed token, uint256 amount);

    event OrderCancelled(bytes32 indexed orderHash, address indexed maker);

    event OrderFilled(bytes32 indexed orderHash, address indexed filler, uint256 amountFilled);

    event OrderPlaced(bytes32 indexed orderHash, address indexed maker, uint8 orderType);

    event OwnershipTransferred(address indexed from, address indexed to);

    event Paused(address indexed by);

    event PoolCreated(bytes32 indexed poolId, address token0, address token1, uint16 feeBps);

    event PoolUpdated(bytes32 indexed poolId, uint256 reserve0, uint256 reserve1);

    event Swap(address indexed user, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut);

    event Unpaused(address indexed by);

    event Withdrawal(address indexed user, address indexed token, uint256 amount);

    /// @notice Add liquidity to a pool
    function addLiquidity(bytes32 poolId, uint256 amount0, uint256 amount1) external;

    function balances(address arg0, address arg1) external view returns (uint256);

    /// @notice Place multiple orders in one transaction
    function batchPlaceOrders(Order[] calldata orderList) external returns (bytes32[] memory hashes);

    /// @notice Cancel an order
    function cancelOrder(bytes32 orderHash) external;

    /// @notice Create a new liquidity pool
    function createPool(address token0, address token1, uint16 feeBps) external returns (bytes32 poolId);

    function deposit(address token, uint256 amount) external;

    /// @notice Fill an existing order
    /// @param orderHash Hash of the order to fill
    /// @param amount Amount to fill
    function fillOrder(bytes32 orderHash, uint256 amount) external;

    function fills(bytes32 arg0, uint256 arg1) external view returns (bytes32 orderHash, uint256 amountFilled, uint256 amountRemaining, uint64 timestamp, address filler);

    /// @notice Get order details
    function getOrder(bytes32 orderHash) external view returns (Order memory);

    /// @notice Get all fills for an order
    function getOrderFills(bytes32 orderHash) external view returns (Fill[] memory);

    /// @notice Get pool info
    function getPool(bytes32 poolId) external view returns (Pool memory);

    /// @notice Get multiple pool states
    function getPoolStates(bytes32[] calldata poolIds) external view returns (Pool[] memory poolStates);

    /// @notice Get user balances for multiple tokens
    function getUserBalances(address user, address[] calldata tokens) external view returns (uint256[] memory amounts);

    function nonces(address arg0) external view returns (uint256);

    function orders(bytes32 arg0) external view returns (address maker, address taker, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut, uint256 nonce, uint64 deadline, bytes32 salt, uint8 orderType, FeeConfig memory fees);

    function owner() external view returns (address);

    function pause() external;

    function paused() external view returns (bool);

    /// @notice Place a new order
    /// @param order The order details
    /// @return orderHash The hash of the placed order
    function placeOrder(Order calldata order) external returns (bytes32 orderHash);

    function pools(bytes32 arg0) external view returns (address token0, address token1, uint256 reserve0, uint256 reserve1, uint64 lastUpdate, uint16 feeBps, bool active);

    /// @notice Quote a swap
    function quote(address tokenIn, address tokenOut, uint256 amountIn) external view returns (uint256 amountOut, uint256 fee);

    /// @notice Swap tokens through a single pool
    function swap(address tokenIn, address tokenOut, uint256 amountIn, uint256 minOut) external returns (uint256 amountOut);

    /// @notice Swap through a multi-hop route
    function swapRoute(Route calldata route) external returns (uint256 finalAmount);

    function totalFees() external view returns (uint256);

    function totalVolume() external view returns (uint256);

    function transferOwnership(address newOwner) external;

    function unpause() external;

    function withdraw(address token, uint256 amount) external;

    receive() external payable;
}
