load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_msgpack",
    srcs = glob(["**/*.rs"]),
    crate = "actix_msgpack",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/rmp-serde/1.3.1:rmp_serde",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
