load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "absorb",
    srcs = glob(["**/*.rs"]),
    crate = "absorb",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/crossterm/0.29.0:crossterm",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/ratatui/0.30.2:ratatui",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/tui-big-text/0.8.8:tui_big_text",
    ],
)
