load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_support",
    srcs = glob(["**/*.rs"]),
    crate = "active_support",
    crate_root = "src/mod.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
