load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "academic_journals_cli",
    srcs = glob(["**/*.rs"]),
    crate = "academic_journals_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/academic-journals/0.2.0:academic_journals",
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
