load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absolut",
    srcs = glob(["**/*.rs"]),
    crate = "absolut",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/absolut-macros/0.1.1:absolut_macros",
    ],
)
