load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpi",
    srcs = glob(["**/*.rs"]),
    crate = "acpi",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.10.3:bit_field",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
