load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_reqid",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_reqid",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
