load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addrezz_core",
    srcs = glob(["**/*.rs"]),
    crate = "addrezz_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/form_urlencoded/1.2.2:form_urlencoded",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
