load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abseil",
    srcs = glob(["**/*.rs"]),
    crate = "abseil",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/directories/6.0.0:directories",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
    ],
)
