load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_ntlm",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_ntlm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/md-5/0.10.6:md_5",
        "//third-party/rust/crates/md4/0.10.2:md4",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
