load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abort_if",
    srcs = glob(["**/*.rs"]),
    crate = "abort_if",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro-error/1.0.4:proc_macro_error",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
