load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actions_digest",
    srcs = glob(["**/*.rs"]),
    crate = "actions_digest",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/paw/1.0.0:paw",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
