load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts_package_state",
    srcs = glob(["**/*.rs"]),
    crate = "acts_package_state",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acts/0.20.1:acts",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/redis/0.31.0:redis",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
