load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptite",
    srcs = glob(["**/*.rs"]),
    crate = "adaptite",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hashbrown/0.17.1:hashbrown",
        "//third-party/rust/crates/runite/0.3.0:runite",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
