load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_testing",
    srcs = glob(["**/*.rs"]),
    crate = "actix_testing",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-macros/0.1.3:actix_macros",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/socket2/0.3.19:socket2",
    ],
)
