load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adx",
    srcs = glob(["**/*.rs"]),
    crate = "adx",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/indicatif/0.15.0:indicatif",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pretty_env_logger/0.4.0:pretty_env_logger",
        "//third-party/rust/crates/roxmltree/0.14.1:roxmltree",
        "//third-party/rust/crates/semver/0.11.0:semver",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/ureq/1.5.5:ureq",
    ],
)
