load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abut",
    srcs = glob(["**/*.rs"]),
    crate = "abut",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/liaise/0.1.6:liaise",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
