load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abu_provider",
    srcs = glob(["**/*.rs"]),
    crate = "abu_provider",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abu-base/0.1.0:abu_base",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/derive_builder/0.20.2:derive_builder",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.25.0:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
