load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpitool",
    srcs = glob(["**/*.rs"]),
    crate = "acpitool",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acpi_client/1.1.0:acpi_client",
        "//third-party/rust/crates/clap/2.34.0:clap",
    ],
)
