load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_helper_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_helper_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/utoipa/5.5.0:utoipa",
        "//third-party/rust/crates/validator/0.20.0:validator",
    ],
)
