load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adrs",
    srcs = glob(["**/*.rs"]),
    crate = "adrs",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adrs-core/0.4.0:adrs_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/edit/0.1.5:edit",
        "//third-party/rust/crates/whoami/1.6.1:whoami",
    ],
)
