load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adabraka_http_client",
    srcs = glob(["**/*.rs"]),
    crate = "adabraka_http_client",
    crate_root = "src/http_client.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adabraka_util/0.5.1:adabraka_util",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-compression/0.4.43:async_compression",
        "//third-party/rust/crates/async-fs/2.2.0:async_fs",
        "//third-party/rust/crates/async-tar/0.5.1:async_tar",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/http-body/1.1.0:http_body",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
