load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a_rs_jsonrpc",
    srcs = glob(["**/*.rs"]),
    crate = "a_rs_jsonrpc",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a-rs-jsonrpc-macros/0.1.0:a_rs_jsonrpc_macros",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/darling/0.23.0:darling",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/linkme/0.3.37:linkme",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
