load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acir_field",
    srcs = glob(["**/*.rs"]),
    crate = "acir_field",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ark-bn254/0.5.0:ark_bn254",
        "//third-party/rust/crates/ark-ff/0.5.0:ark_ff",
        "//third-party/rust/crates/ark-std/0.5.0:ark_std",
        "//third-party/rust/crates/cfg-if/1.0.4:cfg_if",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
