load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adventure_rusoto_sqs",
    srcs = glob(["**/*.rs"]),
    crate = "adventure_rusoto_sqs",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adventure/0.5.0:adventure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/rusoto_core/0.42.0:rusoto_core",
        "//third-party/rust/crates/rusoto_sqs/0.42.0:rusoto_sqs",
        "//third-party/rust/crates/sha2/0.8.2:sha2",
    ],
)
