load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm",
    srcs = glob(["**/*.rs"]),
    crate = "acvm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir/0.1.0:acir",
        "//third-party/rust/crates/acir_field/0.1.0:acir_field",
        "//third-party/rust/crates/blake2/0.9.2:blake2",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/indexmap/1.9.3:indexmap",
        "//third-party/rust/crates/k256/0.7.3:k256",
        "//third-party/rust/crates/num-bigint/0.4.8:num_bigint",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/sha2/0.9.9:sha2",
        "//third-party/rust/crates/sled/0.34.7:sled",
    ],
)
