load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abi_cafe",
    srcs = glob(["**/*.rs"]),
    crate = "abi_cafe",
    crate_root = "src/main.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cc/1.4.2:cc",
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/libloading/0.7.4:libloading",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/ron/0.7.1:ron",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/simplelog/0.11.2:simplelog",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
