load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_payments",
    srcs = glob(["**/*.rs"]),
    crate = "adk_payments",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-artifact/0.7.0:adk_artifact",
        "//third-party/rust/crates/adk-auth/0.7.0:adk_auth",
        "//third-party/rust/crates/adk-core/0.7.0:adk_core",
        "//third-party/rust/crates/adk-guardrail/0.7.0:adk_guardrail",
        "//third-party/rust/crates/adk-memory/0.7.0:adk_memory",
        "//third-party/rust/crates/adk-session/0.7.0:adk_session",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
