load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder_viz",
    srcs = glob(["**/*.rs"]),
    crate = "adder_viz",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adder-codec-core/0.1.2:adder_codec_core",
        "//third-party/rust/crates/adder-codec-rs/0.3.4:adder_codec_rs",
        "//third-party/rust/crates/bevy/0.9.1:bevy",
        "//third-party/rust/crates/bevy_editor_pls/0.2.0:bevy_editor_pls",
        "//third-party/rust/crates/bevy_egui/0.18.0:bevy_egui",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/egui_file/0.5.4:egui_file",
        "//third-party/rust/crates/opencv/0.66.0:opencv",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rfd/0.10.0:rfd",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/strum_macros/0.24.3:strum_macros",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
