load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsbx_json",
    srcs = glob(["**/*.rs"]),
    crate = "adsbx_json",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bitflags_serde_shim/0.2.5:bitflags_serde_shim",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_with/1.14.0:serde_with",
    ],
)
