load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "path_iter",
    srcs = glob(["**/*.rs"]),
    crate = "path_iter",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
)
