load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acp",
    srcs = glob(["**/*.rs"]),
    crate = "acp",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/rdf_utils/0.3.1:rdf_utils",
        "//third-party/rust/crates/rdf_vocabularies/0.2.0:rdf_vocabularies",
    ],
)
