load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_flash",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_flash",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.1.45:time",
    ],
)
