load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_sse",
    srcs = glob(["**/*.rs"]),
    crate = "active_sse",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.9.24:reqwest",
        "//third-party/rust/crates/sse-client/1.1.1:sse_client",
    ],
)
