load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/aead/aead-0.6.0-rc.3.crate",
    ],
    sha256 = "03d2d54c4d9e7006f132f615a167865bff927a79ca63d8f637237575ce0a9795",
    type = "tar.gz",
    strip_prefix = "aead-0.6.0-rc.3",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "aead",
    srcs = [":vendor"],
    crate = "aead",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",
    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
