load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adic_shape",
    srcs = glob(["**/*.rs"]),
    crate = "adic_shape",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adic/0.3.1:adic",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/itertools/0.14.0:itertools",
        "//third-party/rust/crates/petgraph/0.7.1:petgraph",
        "//third-party/rust/crates/svg/0.18.0:svg",
    ],
)
