load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_testing",
    srcs = glob(["**/*.rs"]),
    crate = "actix_testing",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-macros/0.1.3:actix_macros",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-server/1.0.4:actix_server",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/net2/0.2.39:net2",
    ],
)
