load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accumulo_access",
    srcs = glob(["**/*.rs"]),
    crate = "accumulo_access",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
