load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acuity_index_substrate_api",
    srcs = glob(["**/*.rs"]),
    crate = "acuity_index_substrate_api",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acuity-index-substrate/0.7.0:acuity_index_substrate",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-tungstenite/0.21.0:tokio_tungstenite",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
