load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acl_rs",
    srcs = glob(["**/*.rs"]),
    crate = "acl_rs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acl-sys/1.2.2:acl_sys",
        "//third-party/rust/crates/nix/0.26.4:nix",
    ],
)
