{{- if .Values.secrets.anthropicApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aas.fullname" . }}-secrets
  labels:
    {{- include "aas.labels" . | nindent 4 }}
type: Opaque
data:
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc }}
{{- end }}
