load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accessibility-sys/0.1.3:accessibility_sys",
        "//third-party/rust/crates/core-foundation/0.9.4:core_foundation",
    ],
)
