load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accumulator",
    srcs = glob(["**/*.rs"]),
    crate = "accumulator",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/lru_time_cache/0.2.7:lru_time_cache",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
