load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_utils",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-sink/0.3.34:futures_sink",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
    ],
)
