load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_winit",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_winit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.6.1:accesskit",
        "//third-party/rust/crates/parking_lot/0.11.2:parking_lot",
        "//third-party/rust/crates/winit/0.27.5:winit",
    ],
)
