load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addon_distributor",
    srcs = glob(["**/*.rs"]),
    crate = "addon_distributor",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/dialoguer/0.4.0:dialoguer",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
