import { AJTheme } from "../aj-theme.slint";
import { AJAppState, AJUserState } from "../aj-state.slint";
import { AJHomeCallbacks } from "../aj-callbacks.slint";
import { AJAccountData } from "../models/users.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJAdminBadge } from "../components/aj-admin-badge.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJDateTimeText } from "../components/aj-datetime-text.slint";
import { AJCheckbox } from "../components/aj-checkbox.slint";
import { AJIcon } from "../components/aj-icon.slint";

export component AccountProfilePage {
    property <AJAccountData> user: AJUserState.user;

    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJButton {
            text: "назад";
            text-halign: right;

            AJIcon {
                source: @image-url("../../radix-icons/reset.svg");
                x: AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }
            clicked => {
                AJAppState.page = 3
            }
        }

        AJText {
            text: "Профиль";
            type: AJTextType.Heading;
        }

        AJText {
            text: "ваш id";
            type: AJTextType.Medium;
        }

        AJText {
            text: user.id;
            font-italic: true;
        }

        AJText {
            text: "вы вошли как";
            type: AJTextType.Medium;
        }

        AJText {
            text: user.login;
            font-italic: true;
        }

        AJText {
            text: "ваш уровень админа";
            type: AJTextType.Medium;
        }

        AJAdminBadge {
            level: user.admin-level;
        }

        AJText {
            text: "аккаунт был создан";
            type: AJTextType.Medium;
        }

        AJDateTimeText {
            date-time: user.created-at;
            font-italic: true;
        }

        AJButton {
            text: "выйти";

            text-halign: left;

            AJIcon {
                source: @image-url("../../radix-icons/exit.svg");
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            clicked => {
                AJHomeCallbacks.logout()
            }
        }

        AJButton {
            text: "удалить аккаунт";
            background: AJTheme.container-error;
            text-color: AJTheme.error-text;

            text-halign: left;

            AJIcon {
                source: @image-url("../../radix-icons/trash.svg");
                color: AJTheme.error-text;
                x: parent.width - self.width - AJTheme.fit-space;
                y: (parent.height - self.height) / 2;
            }

            delete-account-popup := PopupWindow {
                close-policy: PopupClosePolicy.close-on-click-outside;

                function close-popup() {
                    self.close()
                }

                Rectangle {
                    background: AJTheme.secondary-container;

                    border-radius: AJTheme.border-radius;

                    VerticalLayout {
                        padding: AJTheme.padding;
                        spacing: AJTheme.spacing;

                        AJText {
                            text: "Требуется рут-доступ";
                            type: AJTextType.Medium;
                            color: AJTheme.container-text;
                        }

                        login := AJInput {
                            placeholder: "логин";
                        }

                        password := AJInput {
                            placeholder: "пароль";
                            type: AJInputType.Password;
                        }

                        password-confirmation := AJInput {
                            placeholder: "подтвердите пароль";
                            type: AJInputType.Password;
                        }

                        deletion-confirmation := AJCheckbox {
                            text: "подтвердите удаление";
                        }

                        AJButton {
                            text: "удалить";
                            background: AJTheme.container-error;
                            text-color: AJTheme.error-text;

                            text-halign: left;

                            AJIcon {
                                source: {
                                    if !login.text.is-empty && !password.text.is-empty && password.text == password-confirmation.text && deletion-confirmation.value {
                                        @image-url("../../radix-icons/trash.svg")
                                    } else {
                                        @image-url("../../radix-icons/circle-backslash.svg")
                                    }
                                };
                                color: AJTheme.error-text;
                                x: parent.width - self.width - AJTheme.fit-space;
                                y: (parent.height - self.height) / 2;
                            }

                            clicked => {
                                if !login.text.is-empty && !password.text.is-empty && password.text == password-confirmation.text && deletion-confirmation.value {
                                    AJHomeCallbacks.delete-account(login.text, password.text, password-confirmation.text, deletion-confirmation.value);
                                }
                            }
                        }

                        AJButton {
                            text: "отменить";
                            text-halign: right;

                            AJIcon {
                                source: @image-url("../../radix-icons/reset.svg");
                                x: AJTheme.fit-space;
                                y: (parent.height - self.height) / 2;
                            }
                            clicked => {
                                close-popup()
                            }
                        }
                    }
                }
            }
            clicked => {
                delete-account-popup.show()
            }
        }
    }
}
