load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_queue",
    srcs = glob(["**/*.rs"]),
    crate = "access_queue",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/event-listener/1.2.0:event_listener",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
    ],
)
