load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_middleware_etag",
    srcs = glob(["**/*.rs"]),
    crate = "actix_middleware_etag",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/xxhash-rust/0.8.18:xxhash_rust",
    ],
)
