load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "ads_proxy",
    srcs = glob(["**/*.rs"]),
    crate = "ads_proxy",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ads/0.4.4:ads",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/ctor/0.2.9:ctor",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
