load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adder_codec_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adder_codec_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
