load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_security",
    srcs = glob(["**/*.rs"]),
    crate = "actix_security",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-security-core/0.2.3:actix_security_core",
    ],
)
