load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_telepathy",
    srcs = glob(["**/*.rs"]),
    crate = "actix_telepathy",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-broker/0.3.1:actix_broker",
        "//third-party/rust/crates/actix/0.10.0:actix",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/env_logger/0.8.4:env_logger",
        "//third-party/rust/crates/flexbuffers/0.2.2:flexbuffers",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/parking_lot/0.11.2:parking_lot",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/tokio-util/0.3.1:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
    ],
)
