load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adc",
    srcs = glob(["**/*.rs"]),
    crate = "adc",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
    ],
)
