load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarch64_std",
    srcs = glob(["**/*.rs"]),
    crate = "aarch64_std",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aarch64-cpu/9.4.0:aarch64_cpu",
        "//third-party/rust/crates/tock-registers/0.8.1:tock_registers",
    ],
)
