load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admixture_harness",
    srcs = glob(["**/*.rs"]),
    crate = "admixture_harness",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/admixture-harness-macros/0.1.0:admixture_harness_macros",
        "//third-party/rust/crates/admixture/0.1.0:admixture",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/inventory/0.3.24:inventory",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
