load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abcdmiladfe",
    srcs = glob(["**/*.rs"]),
    crate = "abcdmiladfe",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/peg/0.8.6:peg",
    ],
)
