load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adamo",
    srcs = glob(["**/*.rs"]),
    crate = "adamo",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adamo-sys/0.1.101:adamo_sys",
    ],
)
