load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_utils",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-rt/0.1.0:actix_rt",
        "//third-party/rust/crates/actix-service/0.1.6:actix_service",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
