load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_framed",
    srcs = glob(["**/*.rs"]),
    crate = "actix_framed",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-http/0.2.11:actix_http",
        "//third-party/rust/crates/actix-router/0.1.5:actix_router",
        "//third-party/rust/crates/actix-rt/0.2.6:actix_rt",
        "//third-party/rust/crates/actix-server-config/0.1.2:actix_server_config",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-utils/0.4.7:actix_utils",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
