load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbyss_psl",
    srcs = glob(["**/*.rs"]),
    crate = "adbyss_psl",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.7.8:ahash",
        "//third-party/rust/crates/idna/0.2.3:idna",
        "//third-party/rust/crates/lazy_static/1.4.0:lazy_static",
        "//third-party/rust/crates/smartstring/0.2.10:smartstring",
    ],
)
