load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "AmanitaMuscaria",
    srcs = glob(["**/*.rs"]),
    crate = "AmanitaMuscaria",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base32/0.4.0:base32",
        "//third-party/rust/crates/base64/0.13.1:base64",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/blake2-rfc/0.2.18:blake2_rfc",
        "//third-party/rust/crates/bls-signatures/0.11.3:bls_signatures",
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pqcrypto-falcon/0.2.10:pqcrypto_falcon",
        "//third-party/rust/crates/pqcrypto-traits/0.3.5:pqcrypto_traits",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_chacha/0.3.1:rand_chacha",
        "//third-party/rust/crates/schnorrkel/0.10.2:schnorrkel",
        "//third-party/rust/crates/serde-big-array/0.3.3:serde_big_array",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/tiny-bip39/0.8.2:tiny_bip39",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
