load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abootcrafter",
    srcs = glob(["**/*.rs"]),
    crate = "abootcrafter",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/binrw/0.14.2:binrw",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
