load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adze_tablegen",
    srcs = glob(["**/*.rs"]),
    crate = "adze_tablegen",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adze-bdd-grid-core/0.1.0:adze_bdd_grid_core",
        "//third-party/rust/crates/adze-glr-core/0.8.0:adze_glr_core",
        "//third-party/rust/crates/adze-ir/0.8.0:adze_ir",
        "//third-party/rust/crates/adze-parsetable-metadata/0.1.0:adze_parsetable_metadata",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/rustc_version_runtime/0.1.5:rustc_version_runtime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
