load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act",
    srcs = glob(["**/*.rs"]),
    crate = "act",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ansi-escapes/0.1.1:ansi_escapes",
        "//third-party/rust/crates/rustc-serialize/0.3.25:rustc_serialize",
    ],
)
