load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advtools",
    srcs = glob(["**/*.rs"]),
    crate = "advtools",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.4.12:arrayvec",
        "//third-party/rust/crates/fxhash/0.2.1:fxhash",
        "//third-party/rust/crates/itertools/0.7.11:itertools",
        "//third-party/rust/crates/odds/0.3.1:odds",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
