load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abyss",
    srcs = glob(["**/*.rs"]),
    crate = "abyss",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abyss-core/0.6.1:abyss_core",
        "//third-party/rust/crates/abyss-interpreter/0.6.1:abyss_interpreter",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/rustyline/18.0.1:rustyline",
    ],
)
