load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaptive_distance_field",
    srcs = glob(["**/*.rs"]),
    crate = "adaptive_distance_field",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/humansize/1.1.1:humansize",
        "//third-party/rust/crates/nalgebra/0.35.0:nalgebra",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
