load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_test_lib",
    srcs = glob(["**/*.rs"]),
    crate = "ace_test_lib",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rust-crypto/0.2.36:rust_crypto",
    ],
)
