load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp",
    srcs = glob(["**/*.rs"]),
    crate = "acdp",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp-crypto/0.6.0:acdp_crypto",
        "//third-party/rust/crates/acdp-did/0.6.0:acdp_did",
        "//third-party/rust/crates/acdp-jcs/0.6.0:acdp_jcs",
        "//third-party/rust/crates/acdp-primitives/0.6.0:acdp_primitives",
        "//third-party/rust/crates/acdp-producer/0.6.0:acdp_producer",
        "//third-party/rust/crates/acdp-safe-http/0.6.0:acdp_safe_http",
        "//third-party/rust/crates/acdp-types/0.6.0:acdp_types",
        "//third-party/rust/crates/acdp-validation/0.6.0:acdp_validation",
        "//third-party/rust/crates/acdp-verify/0.6.0:acdp_verify",
    ],
)
