load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "add_remote",
    srcs = glob(["**/*.rs"]),
    crate = "add_remote",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/colour/2.1.0:colour",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/find_git/1.2.1:find_git",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
