load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_validator",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_validator",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-router/0.5.4:actix_router",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_qs/0.9.2:serde_qs",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/validator/0.15.0:validator",
    ],
)
