import { AJLanguage } from "models/testing.slint";
import { AJDateTime } from "models/others.slint";
import { AJProblem, AJSubgroup } from "models/problems.slint";

export global AJWelcomeCallbacks {
    callback login(login: string, password: string);
    callback register(login: string, password: string, password-confirmation: string, master-password: string);
}

export global AJHomeCallbacks {
    callback enter-contest(id: int);
    callback create-contest(name: string, starts-at: AJDateTime, ends-at: AJDateTime, statements-url: string);
    callback update-contest(id: int, name: string, starts-at: AJDateTime, ends-at: AJDateTime, statements-url: string);
    callback delete-contest(id: int, login: string, password: string, password-confirmation: string, deletion-confirmation: bool);
    callback logout();
}

export global AJContestCallbacks {
    callback pick-solution-file();
    callback submit(language: AJLanguage, contest-id: int, problem-id: int);
    callback retest-problem(id: int);
}

export global AJProblemsCallbacks {
    callback pick-problem-archive();
    callback create-problem();
}

export global AJAppCallbacks {
    callback reload();
}
