import { AJContest, AJLeaderboardRow } from "models/contests.slint";
import { AJProblem } from "models/problems.slint";
import { AJSubmission } from "models/testing.slint";
import { AJAccountData } from "models/users.slint";

export global AJUserState {
    in property <AJAccountData> user;
}

export global AJContestState {
    in property <int> index: -1;
    in property <[AJProblem]> problems;
    in property <[string]> problems-names;
    in property <int> current-problem-index;
    in property <[AJSubmission]> submissions;
    in property <int> current-submission-index;
    in property <[AJLeaderboardRow]> leaderboard-rows;
    in property <bool> solution-picked;
    in property <bool> all-submissions;
}

export global AJProblemsState {
    in property <[AJProblem]> problems;
    in property <bool> problem-picked;
}

export global AJAppState {
    in property <int> page: 0;
    in property <[AJContest]> contests;
    in property <[string]> contests-names;
    in property <string> version;
    in property <bool> can-create-contests;
}
