[package]
name = "acetylene_parser"
version = "0.1.0"
authors = ["Ashley Lake <lake@amphetamine.tokyo>"]
description = "A parser for chemical formulas."
# documentation = ""
# homepage = ""
repository = "https://gitlab.com/acetylene/acetylene-parser"
readme = "README.md"
license = "AGPL-3.0"
keywords = ["chemistry", "regex", "parsing", "bio", "informatics"]

[dependencies]
regex = "0.1"
lazy_static = "0.2.1"