load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhammer_ldap",
    srcs = glob(["**/*.rs"]),
    crate = "adhammer_ldap",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/ntlmssp/0.1.0:ntlmssp",
        "//third-party/rust/crates/smb2-client/0.2.1:smb2_client",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
