load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aderyn_driver",
    srcs = glob(["**/*.rs"]),
    crate = "aderyn_driver",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aderyn_core/0.0.20:aderyn_core",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
    ],
)
