load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_tls_alpn_01",
    srcs = glob(["**/*.rs"]),
    crate = "acme_tls_alpn_01",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/flashmap/0.1.0:flashmap",
        "//third-party/rust/crates/flume/0.11.1:flume",
        "//third-party/rust/crates/futures-timer/3.0.4:futures_timer",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/rcgen/0.14.9:rcgen",
        "//third-party/rust/crates/ring/0.17.14:ring",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
