load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerate_framework",
    srcs = glob(["**/*.rs"]),
    crate = "accelerate_framework",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accelerate-sys/0.2.1:accelerate_sys",
    ],
)
