load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsb",
    srcs = glob(["**/*.rs"]),
    crate = "adsb",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/nom/6.2.2:nom",
    ],
)
