load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad_editor",
    srcs = glob(["**/*.rs"]),
    crate = "ad_editor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/ninep/0.1.0:ninep",
    ],
)
