load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_windows",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_windows",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.7.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.7.1:accesskit_consumer",
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/lazy-init/0.5.1:lazy_init",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/windows/0.42.0:windows",
    ],
)
