load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_lua",
    srcs = glob(["**/*.rs"]),
    crate = "actix_lua",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.7.9:actix",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/rlua/0.14.2:rlua",
        "//third-party/rust/crates/tokio/0.1.22:tokio",
    ],
)
