load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_firebase_auth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_firebase_auth",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-httpauth/0.8.2:actix_web_httpauth",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/jsonwebtoken/9.3.1:jsonwebtoken",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
