load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abu_agent",
    srcs = glob(["**/*.rs"]),
    crate = "abu_agent",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abu-base/0.2.0:abu_base",
        "//third-party/rust/crates/abu-macros/0.2.0:abu_macros",
        "//third-party/rust/crates/abu-mcp/0.2.0:abu_mcp",
        "//third-party/rust/crates/abu-provider/0.2.0:abu_provider",
        "//third-party/rust/crates/abu-rag/0.2.0:abu_rag",
        "//third-party/rust/crates/abu-skill/0.2.0:abu_skill",
        "//third-party/rust/crates/abu-tool/0.2.0:abu_tool",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/dotenv/0.15.0:dotenv",
        "//third-party/rust/crates/meval/0.2.0:meval",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/thiserrorctx/1.0.0:thiserrorctx",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
