load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_opentelemetry",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_opentelemetry",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/1.0.9:actix_web",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/opentelemetry/0.1.5:opentelemetry",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
