load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_redis",
    srcs = glob(["**/*.rs"]),
    crate = "actix_redis",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-tls/3.5.0:actix_tls",
        "//third-party/rust/crates/actix/0.13.5:actix",
        "//third-party/rust/crates/backoff/0.4.0:backoff",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis-async/0.16.1:redis_async",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
