load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerator",
    srcs = glob(["**/*.rs"]),
    crate = "accelerator",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accelerator-macros/0.1.1:accelerator_macros",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/moka/0.12.16:moka",
        "//third-party/rust/crates/redis/1.5.0:redis",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/singleflight-async/0.2.0:singleflight_async",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
