load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_amqp",
    srcs = glob(["**/*.rs"]),
    crate = "actix_amqp",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.2.0:actix_codec",
        "//third-party/rust/crates/actix-connect/1.0.2:actix_connect",
        "//third-party/rust/crates/actix-router/0.2.7:actix_router",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-utils/1.0.6:actix_utils",
        "//third-party/rust/crates/amqp-codec/0.1.0:amqp_codec",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/bytestring/0.1.5:bytestring",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/fxhash/0.2.1:fxhash",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
    ],
)
