load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accounting",
    srcs = glob(["**/*.rs"]),
    crate = "accounting",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
