load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_daemon",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_daemon",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionqueue-core/0.1.2:actionqueue_core",
        "//third-party/rust/crates/actionqueue-storage/0.1.2:actionqueue_storage",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/prometheus/0.13.4:prometheus",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
