load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acopen",
    srcs = glob(["**/*.rs"]),
    crate = "acopen",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/webbrowser/0.6.0:webbrowser",
    ],
)
