load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activity_sys",
    srcs = glob(["**/*.rs"]),
    crate = "activity_sys",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/js-sys/0.3.104:js_sys",
        "//third-party/rust/crates/wasm-bindgen-futures/0.4.77:wasm_bindgen_futures",
        "//third-party/rust/crates/wasm-bindgen/0.2.127:wasm_bindgen",
        "//third-party/rust/crates/web-sys/0.3.104:web_sys",
    ],
)
