load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acta_maker_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "acta_maker_sdk",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/rand/0.9.5:rand",
        "//third-party/rust/crates/rand_xoshiro/0.7.0:rand_xoshiro",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_with/3.22.0:serde_with",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/strum/0.27.2:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
