load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin",
    srcs = glob(["**/*.rs"]),
    crate = "admin",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrix-proto/0.5.4:actrix_proto",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/nonce-auth/0.6.3:nonce_auth",
        "//third-party/rust/crates/pwrzv/0.7.0:pwrzv",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/sqlx/0.8.6:sqlx",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic/0.14.6:tonic",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
