load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility_rs",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accessibility-scraper/0.0.1:accessibility_scraper",
        "//third-party/rust/crates/accessibility-tree/0.0.1:accessibility_tree",
        "//third-party/rust/crates/cssparser/0.25.9:cssparser",
        "//third-party/rust/crates/ego-tree/0.6.3:ego_tree",
        "//third-party/rust/crates/getrandom/0.2.17:getrandom",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/markup5ever/0.11.0:markup5ever",
        "//third-party/rust/crates/selectors/0.21.0:selectors",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/slotmap/1.1.1:slotmap",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
        "//third-party/rust/crates/strum/0.25.0:strum",
        "//third-party/rust/crates/strum_macros/0.25.3:strum_macros",
        "//third-party/rust/crates/taffy/0.3.19:taffy",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
