load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_multipart",
    srcs = glob(["**/*.rs"]),
    crate = "actix_multipart",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/httparse/1.10.1:httparse",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/time/0.1.45:time",
        "//third-party/rust/crates/twoway/0.2.2:twoway",
    ],
)
