load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adb_client",
    srcs = glob(["**/*.rs"]),
    crate = "adb_client",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-bigint-dig/0.8.6:num_bigint_dig",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/num_enum/0.7.6:num_enum",
        "//third-party/rust/crates/quick-protobuf/0.8.1:quick_protobuf",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/rcgen/0.14.9:rcgen",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/rustls-pki-types/1.15.1:rustls_pki_types",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
