load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adic",
    srcs = glob(["**/*.rs"]),
    crate = "adic",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/itertools/0.13.0:itertools",
        "//third-party/rust/crates/num-prime/0.4.4:num_prime",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/overload/0.1.1:overload",
    ],
)
