load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu_vulkan",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu_vulkan",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adi_gpu_base/0.1.0:adi_gpu_base",
        "//third-party/rust/crates/afi/0.3.2:afi",
        "//third-party/rust/crates/ami/0.6.0:ami",
        "//third-party/rust/crates/asi_vulkan/0.3.0:asi_vulkan",
        "//third-party/rust/crates/awi/0.2.0:awi",
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
