load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abol_server",
    srcs = glob(["**/*.rs"]),
    crate = "abol_server",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abol-core/0.1.0:abol_core",
        "//third-party/rust/crates/abol-rt/0.1.0:abol_rt",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/moka/0.12.16:moka",
    ],
)
