load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adam_fov_rs",
    srcs = glob(["**/*.rs"]),
    crate = "adam_fov_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/glam/0.29.3:glam",
        "//third-party/rust/crates/sark_grids/0.6.2:sark_grids",
    ],
)
