load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abrase",
    srcs = glob(["**/*.rs"]),
    crate = "abrase",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/polka-rs/0.1.0:polka_rs",
    ],
)
