load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acryl",
    srcs = glob(["**/*.rs"]),
    crate = "acryl",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base58/0.1.0:base58",
        "//third-party/rust/crates/blake2/0.7.1:blake2",
        "//third-party/rust/crates/curve25519-dalek/1.2.6:curve25519_dalek",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/sha2/0.8.2:sha2",
        "//third-party/rust/crates/sha3/0.8.2:sha3",
    ],
)
