load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a3s_code",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_code",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-code-core/0.9.5:a3s_code_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
