load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ogn",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ogn",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.10.0:actix",
        "//third-party/rust/crates/backoff/0.2.1:backoff",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-util/0.3.1:tokio_util",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
