load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adventurex_2025_shitfounder",
    srcs = glob(["**/*.rs"]),
    crate = "adventurex_2025_shitfounder",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
