load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa_core",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/canonical-path/2.0.2:canonical_path",
        "//third-party/rust/crates/fs-err/3.3.1:fs_err",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
    ],
)
