load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_proxy_protocol",
    srcs = glob(["**/*.rs"]),
    crate = "actix_proxy_protocol",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/2.11.0:actix_rt",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/proxyproto/0.2.1:proxyproto",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
