load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_prom",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_prom",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/2.2.2:actix_http",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/prometheus/0.10.0:prometheus",
    ],
)
