load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aad",
    srcs = glob(["**/*.rs"]),
    crate = "aad",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
