load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_code_macro",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_code_macro",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/paste/1.0.15:paste",
    ],
)
