load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "act2txt",
    srcs = glob(["**/*.rs"]),
    crate = "act2txt",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/gumdrop/0.8.1:gumdrop",
        "//third-party/rust/crates/palette/0.7.7:palette",
    ],
)
