matrix:
  RUST: [stable]

services:
  - name: db
    image: postgres
    environment:
      POSTGRES_USER: activityforge_test
      POSTGRES_PASSWORD: activityforge_test
      POSTGRES_DB_NAME: activityforge_test

steps:
  lint:
    image: rust
    when:
      - event: manual
      - event: pull_request
      - event: push
    commands:
      - export CARGO_TERM_COLOR=always
      - rustup component add clippy rustfmt
      - cargo clippy --all --tests -- -D warnings
      - cargo fmt --check --all

  build:
    image: rust
    when:
      - event: manual
      - event: pull_request
      - event: push
    commands:
      - export CARGO_TERM_COLOR=always
      - cargo build
      - cargo build --release

  test:
    image: rust
    when:
      - event: manual
      - event: pull_request
      - event: push
    environment:
      POSTGRES_HOST: db
    commands:
      - export CARGO_TERM_COLOR=always
      - cargo check
      - cargo test --all
      - cargo test --all --features e2e-tests,ci

