load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abs_cli",
    srcs = glob(["**/*.rs"]),
    crate = "abs_cli",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/coloredpp/0.3.0:coloredpp",
    ],
)
