load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aarambh_net",
    srcs = glob(["**/*.rs"]),
    crate = "aarambh_net",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
