load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_ratelimit",
    srcs = glob(["**/*.rs"]),
    crate = "actix_ratelimit",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/actix/0.9.0:actix",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
