load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_app",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_app",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapto_client_protocol/0.1.2:adapto_client_protocol",
        "//third-party/rust/crates/adapto_store/0.1.2:adapto_store",
        "//third-party/rust/crates/adapto_ui/0.1.2:adapto_ui",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
