load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actori_testing",
    srcs = glob(["**/*.rs"]),
    crate = "actori_testing",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-macros/0.1.1:actori_macros",
        "//third-party/rust/crates/actori-rt/1.0.0:actori_rt",
        "//third-party/rust/crates/actori-server/1.0.1:actori_server",
        "//third-party/rust/crates/actori-service/1.0.5:actori_service",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/net2/0.2.39:net2",
    ],
)
