load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acetewm",
    srcs = glob(["**/*.rs"]),
    crate = "acetewm",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/borsh/0.10.4:borsh",
        "//third-party/rust/crates/bpaf/0.9.27:bpaf",
        "//third-party/rust/crates/color-eyre/0.5.11:color_eyre",
        "//third-party/rust/crates/convert_case/0.6.0:convert_case",
        "//third-party/rust/crates/ego-tree/0.6.3:ego_tree",
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/html5ever/0.26.0:html5ever",
        "//third-party/rust/crates/lazy-regex/2.5.0:lazy_regex",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/scraper/0.16.0:scraper",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
