load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accountable_refcell",
    srcs = glob(["**/*.rs"]),
    crate = "accountable_refcell",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/backtrace/0.3.76:backtrace",
    ],
)
