load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad9912",
    srcs = glob(["**/*.rs"]),
    crate = "ad9912",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arbitrary-int/1.3.0:arbitrary_int",
        "//third-party/rust/crates/bitbybit/1.4.0:bitbybit",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
