load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_files",
    srcs = glob(["**/*.rs"]),
    crate = "actix_files",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/askama_escape/0.10.3:askama_escape",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/http-range/0.1.5:http_range",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/mime_guess/2.0.5:mime_guess",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
    ],
)
