load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhdreading_site_kit",
    srcs = glob(["**/*.rs"]),
    crate = "adhdreading_site_kit",
    crate_root = "rust/src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
