load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "addbib",
    srcs = glob(["**/*.rs"]),
    crate = "addbib",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/hayagriva/0.8.1:hayagriva",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
