load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advisorygraphen_lift",
    srcs = glob(["**/*.rs"]),
    crate = "advisorygraphen_lift",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advisorygraphen-core/0.1.3:advisorygraphen_core",
        "//third-party/rust/crates/advisorygraphen-interpretation/0.1.3:advisorygraphen_interpretation",
        "//third-party/rust/crates/higher-graphen-core/0.5.0:higher_graphen_core",
        "//third-party/rust/crates/higher-graphen-structure/0.5.0:higher_graphen_structure",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
