load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstractgraph",
    srcs = glob(["**/*.rs"]),
    crate = "abstractgraph",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num/0.2.1:num",
        "//third-party/rust/crates/priority-queue/0.5.4:priority_queue",
    ],
)
