load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_use_ocr",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_use_ocr",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-use-core/0.1.3:a3s_use_core",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/clipper2/0.5.3:clipper2",
        "//third-party/rust/crates/fs2/0.4.3:fs2",
        "//third-party/rust/crates/image/0.25.5:image",
        "//third-party/rust/crates/imageproc/0.25.0:imageproc",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rmcp/0.8.5:rmcp",
        "//third-party/rust/crates/schemars/1.2.2:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tar/0.4.46:tar",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
