load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_friendly_json_extractor",
    srcs = glob(["**/*.rs"]),
    crate = "actix_friendly_json_extractor",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_path_to_error/0.1.20:serde_path_to_error",
    ],
)
