load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_proto",
    srcs = glob(["**/*.rs"]),
    crate = "ace_proto",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-core/0.2.2:ace_core",
        "//third-party/rust/crates/heapless/0.9.3:heapless",
    ],
)
