load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advmac",
    srcs = glob(["**/*.rs"]),
    crate = "advmac",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/snafu/0.7.5:snafu",
    ],
)
