load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adana",
    srcs = glob(["**/*.rs"]),
    crate = "adana",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adana-cache-command/0.18.8:adana_cache_command",
        "//third-party/rust/crates/adana-db/0.18.8:adana_db",
        "//third-party/rust/crates/adana-script-core/0.18.8:adana_script_core",
        "//third-party/rust/crates/adana-script/0.18.8:adana_script",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nu-ansi-term/0.50.3:nu_ansi_term",
        "//third-party/rust/crates/rustyline-derive/0.11.1:rustyline_derive",
        "//third-party/rust/crates/rustyline/16.0.0:rustyline",
    ],
)
