load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "academic_journals",
    srcs = glob(["**/*.rs"]),
    crate = "academic_journals",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rkyv/0.8.18:rkyv",
    ],
)
