load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "aasvg",
    srcs = glob(["**/*.rs"]),
    crate = "aasvg",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aasvg/1.0.0:aasvg",
        "//third-party/rust/crates/facet-args/0.34.0:facet_args",
        "//third-party/rust/crates/facet/0.34.0:facet",
    ],
)
