load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activitypub",
    srcs = glob(["**/*.rs"]),
    crate = "activitypub",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/activitystreams-derive/0.1.1:activitystreams_derive",
        "//third-party/rust/crates/activitystreams-traits/0.1.0:activitystreams_traits",
        "//third-party/rust/crates/activitystreams-types/0.2.3:activitystreams_types",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
