load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addr_symbolizer",
    srcs = glob(["**/*.rs"]),
    crate = "addr_symbolizer",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/msvc-demangler/0.10.1:msvc_demangler",
        "//third-party/rust/crates/pdb/0.8.0:pdb",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/ureq/2.12.1:ureq",
    ],
)
