load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder_boring_run",
    srcs = glob(["**/*.rs"]),
    crate = "adder_boring_run",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add-one-boring/0.1.0:add_one_boring",
    ],
)
