load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adsabs",
    srcs = glob(["**/*.rs"]),
    crate = "adsabs",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adsabs-macro/0.1.1:adsabs_macro",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dirs/4.0.0:dirs",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
