load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acid_rs",
    srcs = glob(["**/*.rs"]),
    crate = "acid_rs",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/angelmarkup/1.1.0:angelmarkup",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/cleasy/1.0.0:cleasy",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/extract-frontmatter/2.1.0:extract_frontmatter",
        "//third-party/rust/crates/file-serve/0.1.1:file_serve",
        "//third-party/rust/crates/fs_extra/1.3.0:fs_extra",
        "//third-party/rust/crates/git2/0.14.4:git2",
        "//third-party/rust/crates/kstring/1.0.6:kstring",
        "//third-party/rust/crates/liquid/0.24.0:liquid",
        "//third-party/rust/crates/markdown/0.3.0:markdown",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
