load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_schema",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_schema",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-schema-macro/0.2.0:actix_web_schema_macro",
    ],
)
