load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi",
    srcs = glob(["**/*.rs"]),
    crate = "abi",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi-macro/0.1.2:abi_macro",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
