load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_responder_macro",
    srcs = glob(["**/*.rs"]),
    crate = "actix_responder_macro",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/proc-macro-error/1.0.4:proc_macro_error",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/trybuild/1.0.120:trybuild",
        "//third-party/rust/crates/typed-builder/0.7.1:typed_builder",
    ],
)
