load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abci",
    srcs = glob(["**/*.rs"]),
    crate = "abci",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/integer-encoding/1.1.7:integer_encoding",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/protobuf/2.28.0:protobuf",
    ],
)
