load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "activeledger",
    srcs = glob(["**/*.rs"]),
    crate = "activeledger",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.10.1:base64",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.9.24:reqwest",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
