load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_aggregator",
    srcs = glob(["**/*.rs"]),
    crate = "actix_aggregator",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.10.0:actix",
    ],
)
