load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adk_rust",
    srcs = glob(["**/*.rs"]),
    crate = "adk_rust",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adk-core/0.1.9:adk_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
