load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_ica",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_ica",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-sdk/0.24.1:abstract_sdk",
        "//third-party/rust/crates/alloy-sol-types/0.7.7:alloy_sol_types",
        "//third-party/rust/crates/alloy/0.2.1:alloy",
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-orch/0.27.0:cw_orch",
        "//third-party/rust/crates/cw-ownable/2.1.0:cw_ownable",
        "//third-party/rust/crates/cw-storage-plus/2.0.0:cw_storage_plus",
        "//third-party/rust/crates/map-macro/0.3.0:map_macro",
        "//third-party/rust/crates/polytone-evm/0.1.0:polytone_evm",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
