load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp_client",
    srcs = glob(["**/*.rs"]),
    crate = "acdp_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acdp-crypto/0.1.5:acdp_crypto",
        "//third-party/rust/crates/acdp-did/0.2.2:acdp_did",
        "//third-party/rust/crates/acdp-primitives/0.4.0:acdp_primitives",
        "//third-party/rust/crates/acdp-safe-http/0.2.2:acdp_safe_http",
        "//third-party/rust/crates/acdp-types/0.3.2:acdp_types",
        "//third-party/rust/crates/acdp-validation/0.3.2:acdp_validation",
        "//third-party/rust/crates/acdp-verify/0.3.2:acdp_verify",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
