load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adv_fs_utils",
    srcs = glob(["**/*.rs"]),
    crate = "adv_fs_utils",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytesize/1.3.3:bytesize",
        "//third-party/rust/crates/crossbeam/0.8.4:crossbeam",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/indicatif/0.17.11:indicatif",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
