load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abtc_domain",
    srcs = glob(["**/*.rs"]),
    crate = "abtc_domain",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chacha20poly1305/0.10.1:chacha20poly1305",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hkdf/0.12.4:hkdf",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/ripemd/0.1.3:ripemd",
        "//third-party/rust/crates/secp256k1/0.29.1:secp256k1",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
