load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl343_i2c_generic",
    srcs = glob(["**/*.rs"]),
    crate = "adxl343_i2c_generic",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_setters/0.1.9:derive_setters",
        "//third-party/rust/crates/embedded-hal-mock/0.11.1:embedded_hal_mock",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/lsm6ds3tr/0.2.2:lsm6ds3tr",
        "//third-party/rust/crates/modular-bitfield/0.13.1:modular_bitfield",
        "//third-party/rust/crates/simple-mermaid/0.2.0:simple_mermaid",
    ],
)
