load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_server",
    srcs = glob(["**/*.rs"]),
    crate = "actix_server",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.3.0:actix_codec",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-utils/2.0.0:actix_utils",
        "//third-party/rust/crates/futures-channel/0.3.34:futures_channel",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mio-uds/0.6.8:mio_uds",
        "//third-party/rust/crates/mio/0.6.23:mio",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/socket2/0.3.19:socket2",
    ],
)
