load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-router/0.2.7:actix_router",
        "//third-party/rust/crates/actix-threadpool/0.3.3:actix_threadpool",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/encoding_rs/0.8.35:encoding_rs",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/fxhash/0.2.1:fxhash",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/parking_lot/0.9.0:parking_lot",
        "//third-party/rust/crates/pin-project/0.4.30:pin_project",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/time/0.1.45:time",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
