load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accel",
    srcs = glob(["**/*.rs"]),
    crate = "accel",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cuda-sys/0.2.0:cuda_sys",
        "//third-party/rust/crates/procedurals/0.2.3:procedurals",
    ],
)
