load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_core",
    srcs = glob(["**/*.rs"]),
    crate = "acme_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum-core/0.3.4:axum_core",
        "//third-party/rust/crates/config/0.13.4:config",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/scsys/0.1.42:scsys",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
    ],
)
