load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_clean_path",
    srcs = glob(["**/*.rs"]),
    crate = "actix_clean_path",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/path-clean/0.1.0:path_clean",
    ],
)
