load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_flash_messages",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_flash_messages",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/time/0.2.27:time",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
