load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abra",
    srcs = glob(["**/*.rs"]),
    crate = "abra",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/0.5.3:byteorder",
        "//third-party/rust/crates/chrono/0.2.25:chrono",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/maplit/0.1.6:maplit",
        "//third-party/rust/crates/roaring/0.4.2:roaring",
        "//third-party/rust/crates/rustc-serialize/0.3.25:rustc_serialize",
        "//third-party/rust/crates/unicode-segmentation/0.1.3:unicode_segmentation",
    ],
)
