load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_requestid",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_requestid",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/rand/0.5.6:rand",
    ],
)
