[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
#changelog_config = "config/git-cliff.toml" # use a custom git-cliff configuration
dependencies_update = true # update dependencies with `cargo update`
git_release_enable = true # disable GitHub/Gitea releases
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_name = "release {{ package }} v{{ version }}" # template for the PR name
pr_labels = ["release"] # add the `release` label to the release Pull Request
#publish = false
semver_check = false # disable API breaking changes checks
