load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_cw_plus_interface",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_cw_plus_interface",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abstract-cw1-subkeys/1.3.0:abstract_cw1_subkeys",
        "//third-party/rust/crates/abstract-cw1-whitelist/1.3.0:abstract_cw1_whitelist",
        "//third-party/rust/crates/abstract-cw1/1.2.2:abstract_cw1",
        "//third-party/rust/crates/abstract-cw20-base/1.3.0:abstract_cw20_base",
        "//third-party/rust/crates/abstract-cw20-ics20/1.3.0:abstract_cw20_ics20",
        "//third-party/rust/crates/abstract-cw3-fixed-multisig/1.3.0:abstract_cw3_fixed_multisig",
        "//third-party/rust/crates/abstract-cw3-flex-multisig/1.3.0:abstract_cw3_flex_multisig",
        "//third-party/rust/crates/abstract-cw4-group/1.3.0:abstract_cw4_group",
        "//third-party/rust/crates/abstract-cw4-stake/1.3.0:abstract_cw4_stake",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/cw-orch/0.19.3:cw_orch",
    ],
)
