load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aead",
    srcs = glob(["**/*.rs"]),
    crate = "aead",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/inout/0.2.2:inout",
    ],
)
