load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_rest",
    srcs = glob(["**/*.rs"]),
    crate = "actix_rest",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
