load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aa_sms",
    srcs = glob(["**/*.rs"]),
    crate = "aa_sms",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/derive_builder/0.20.2:derive_builder",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
