load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_validator",
    srcs = glob(["**/*.rs"]),
    crate = "action_validator",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/valico/3.6.1:valico",
    ],
)
