load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aead",
    srcs = glob(["**/*.rs"]),
    crate = "aead",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crypto-common/0.1.7:crypto_common",
        "//third-party/rust/crates/generic-array/0.14.9:generic_array",
    ],
)
