load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

filegroup(
    name = "package_src",
    srcs = glob(["**"], exclude = ["BUCK"]),
)

cargo_manifest(
    name = "manifest",
    vendor = ":package_src",
)

rust_library(
    name = "aead",
    srcs = glob(["**/*.rs"]),
    crate = "aead",
    crate_root = "src/lib.rs",
    edition = "2021",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
