load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_consumer",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_consumer",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.3.0:accesskit",
        "//third-party/rust/crates/im/15.1.0:im",
        "//third-party/rust/crates/parking_lot/0.11.2:parking_lot",
    ],
)
