load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_core",
    srcs = glob(["**/*.rs"]),
    crate = "acme_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/smart-default/0.7.1:smart_default",
        "//third-party/rust/crates/strum/0.26.3:strum",
    ],
)
