load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acick_config",
    srcs = glob(["**/*.rs"]),
    crate = "acick_config",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acick-util/0.1.1:acick_util",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/getset/0.1.7:getset",
        "//third-party/rust/crates/heck/0.3.3:heck",
        "//third-party/rust/crates/humantime-serde/1.1.1:humantime_serde",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/semver/0.9.0:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.8.26:serde_yaml",
        "//third-party/rust/crates/tera/1.20.1:tera",
        "//third-party/rust/crates/tokio/0.2.25:tokio",
    ],
)
