load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_identity",
    srcs = glob(["**/*.rs"]),
    crate = "actix_identity",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-session/0.7.2:actix_session",
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/time/0.3.55:time",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
