load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acts",
    srcs = glob(["**/*.rs"]),
    crate = "acts",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/globset/0.4.20:globset",
        "//third-party/rust/crates/hocon/0.9.0:hocon",
        "//third-party/rust/crates/inventory/0.3.24:inventory",
        "//third-party/rust/crates/jsonschema/0.30.0:jsonschema",
        "//third-party/rust/crates/moka/0.12.16:moka",
        "//third-party/rust/crates/nanoid/0.4.0:nanoid",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rquickjs/0.9.0:rquickjs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_repr/0.1.21:serde_repr",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/strum/0.27.2:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
