load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_http_test",
    srcs = glob(["**/*.rs"]),
    crate = "actix_http_test",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.3.0:actix_codec",
        "//third-party/rust/crates/actix-connect/2.0.0:actix_connect",
        "//third-party/rust/crates/actix-rt/1.1.1:actix_rt",
        "//third-party/rust/crates/actix-server/1.0.4:actix_server",
        "//third-party/rust/crates/actix-service/1.0.6:actix_service",
        "//third-party/rust/crates/actix-testing/1.0.1:actix_testing",
        "//third-party/rust/crates/actix-utils/2.0.0:actix_utils",
        "//third-party/rust/crates/awc/2.0.3:awc",
        "//third-party/rust/crates/base64/0.12.3:base64",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
        "//third-party/rust/crates/slab/0.4.12:slab",
        "//third-party/rust/crates/socket2/0.3.19:socket2",
        "//third-party/rust/crates/time/0.2.27:time",
    ],
)
