load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_extensible_rate_limit",
    srcs = glob(["**/*.rs"]),
    crate = "actix_extensible_rate_limit",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
