load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adxl345_async",
    srcs = glob(["**/*.rs"]),
    crate = "adxl345_async",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal-async/1.0.0:embedded_hal_async",
    ],
)
