load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acick_util",
    srcs = glob(["**/*.rs"]),
    crate = "acick_util",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bytefmt/0.1.7:bytefmt",
        "//third-party/rust/crates/console/0.9.2:console",
        "//third-party/rust/crates/getset/0.0.9:getset",
        "//third-party/rust/crates/humantime-serde/1.1.1:humantime_serde",
        "//third-party/rust/crates/indicatif/0.14.0:indicatif",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/shellexpand/1.1.1:shellexpand",
        "//third-party/rust/crates/strum/0.17.1:strum",
        "//third-party/rust/crates/webbrowser/0.5.5:webbrowser",
    ],
)
