load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abrute",
    srcs = glob(["**/*.rs"]),
    crate = "abrute",
    crate_root = "src/main.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/array_tool/1.0.3:array_tool",
        "//third-party/rust/crates/clap/2.26.2:clap",
        "//third-party/rust/crates/digits/1.1.1:digits",
        "//third-party/rust/crates/num_cpus/1.7.0:num_cpus",
        "//third-party/rust/crates/rayon/0.8.2:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tempdir/0.3.7:tempdir",
        "//third-party/rust/crates/tiny_http/0.5.9:tiny_http",
    ],
)
