load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absolute_unit",
    srcs = glob(["**/*.rs"]),
    crate = "absolute_unit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/approx/0.5.1:approx",
        "//third-party/rust/crates/glam/0.29.3:glam",
        "//third-party/rust/crates/hashbag/0.1.13:hashbag",
        "//third-party/rust/crates/nalgebra/0.33.2:nalgebra",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/ordered-float/4.6.0:ordered_float",
    ],
)
