load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_error",
    srcs = glob(["**/*.rs"]),
    crate = "actix_error",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-error-derive/0.2.11:actix_error_derive",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
