load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "forge_skills",
    srcs = glob(["**/*.rs"]),
    crate = "forge_skills",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
