load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adacore_zynqmp",
    srcs = glob(["**/*.rs"]),
    crate = "adacore_zynqmp",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aarch64-cpu/10.0.0:aarch64_cpu",
        "//third-party/rust/crates/arbitrary-int/1.3.0:arbitrary_int",
        "//third-party/rust/crates/arm-gic/0.6.1:arm_gic",
        "//third-party/rust/crates/bitbybit/1.4.0:bitbybit",
        "//third-party/rust/crates/derive-mmio/0.6.2:derive_mmio",
        "//third-party/rust/crates/embedded-io/0.6.1:embedded_io",
        "//third-party/rust/crates/spin/0.10.1:spin",
    ],
)
