load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton",
    srcs = glob(["**/*.rs"]),
    crate = "acton",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/ctrlc/3.5.2:ctrlc",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/eui48/1.1.0:eui48",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/ipaddress/0.1.3:ipaddress",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/netlink-packet-route/0.10.0:netlink_packet_route",
        "//third-party/rust/crates/nom/7.1.3:nom",
        "//third-party/rust/crates/pnet/0.29.0:pnet",
        "//third-party/rust/crates/rtnetlink/0.9.1:rtnetlink",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
        "//third-party/rust/crates/tokio-test/0.4.5:tokio_test",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
