load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "able",
    srcs = glob(["**/*.rs"]),
    crate = "able",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
)
