load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "AjusteOnuDeReferencia",
    srcs = glob(["**/*.rs"]),
    crate = "AjusteOnuDeReferencia",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ssh2/0.9.6:ssh2",
    ],
)
