load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_server",
    srcs = glob(["**/*.rs"]),
    crate = "actix_server",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mio-uds/0.6.8:mio_uds",
        "//third-party/rust/crates/mio/0.6.23:mio",
        "//third-party/rust/crates/net2/0.2.39:net2",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/slab/0.4.12:slab",
    ],
)
