load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_derive",
    srcs = glob(["**/*.rs"]),
    crate = "acme_derive",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],
    proc_macro = True,

    visibility = ["PUBLIC"],
)
