load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actions_templates",
    srcs = glob(["**/*.rs"]),
    crate = "actions_templates",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/handlebars/5.1.2:handlebars",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
