load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actor_core_client",
    srcs = glob(["**/*.rs"]),
    crate = "actor_core_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/eventsource-client/0.14.0:eventsource_client",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_cbor/0.11.2:serde_cbor",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-tungstenite/0.26.2:tokio_tungstenite",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/tungstenite/0.26.2:tungstenite",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
