load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abridge",
    srcs = glob(["**/*.rs"]),
    crate = "abridge",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/substring/1.4.5:substring",
    ],
)
