load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_codegen",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_codegen",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quote/0.6.13:quote",
        "//third-party/rust/crates/syn/0.15.44:syn",
    ],
)
