load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_taskqueue",
    srcs = glob(["**/*.rs"]),
    crate = "actix_taskqueue",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.9.0:actix",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/crossbeam/0.7.3:crossbeam",
    ],
)
