load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adhp",
    srcs = glob(["**/*.rs"]),
    crate = "adhp",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
