load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advmac_rs",
    srcs = glob(["**/*.rs"]),
    crate = "advmac_rs",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arrayvec/0.7.8:arrayvec",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
