load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_auth",
    srcs = glob(["**/*.rs"]),
    crate = "actix_auth",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-identity/0.2.1:actix_identity",
        "//third-party/rust/crates/actix-web/2.0.0:actix_web",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
