load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a3s",
    srcs = glob(["**/*.rs"]),
    crate = "a3s",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a3s-boot/0.1.4:a3s_boot",
        "//third-party/rust/crates/a3s-code-core/4.3.0:a3s_code_core",
        "//third-party/rust/crates/a3s-memory/0.1.2:a3s_memory",
        "//third-party/rust/crates/a3s-tui/0.1.6:a3s_tui",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
