load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adl2rsdm",
    srcs = glob(["**/*.rs"]),
    crate = "adl2rsdm",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
    ],
)
