load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "cargo_a9_lint",
    srcs = glob(["**/*.rs"]),
    crate = "cargo_a9_lint",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
