load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acm",
    srcs = glob(["**/*.rs"]),
    crate = "acm",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-openai/0.18.3:async_openai",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
        "//third-party/rust/crates/inquire/0.6.2:inquire",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/spinoff/0.8.0:spinoff",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/which/5.0.0:which",
    ],
)
