load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acari",
    srcs = glob(["**/*.rs"]),
    crate = "acari",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acari-lib/0.1.12:acari_lib",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dirs/2.0.2:dirs",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
