load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acled_api",
    srcs = glob(["**/*.rs"]),
    crate = "acled_api",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.26.3:strum",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
