load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adx",
    srcs = glob(["**/*.rs"]),
    crate = "adx",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/indicatif/0.14.0:indicatif",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/roxmltree/0.10.1:roxmltree",
        "//third-party/rust/crates/ureq/0.12.1:ureq",
    ],
)
