load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actordb",
    srcs = glob(["**/*.rs"]),
    crate = "actordb",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/prost-types/0.12.6:prost_types",
        "//third-party/rust/crates/prost/0.12.6:prost",
        "//third-party/rust/crates/ractor/0.9.8:ractor",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
