load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accounts_service_sys",
    srcs = glob(["**/*.rs"]),
    crate = "accounts_service_sys",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/gio-sys/0.21.5:gio_sys",
        "//third-party/rust/crates/glib-sys/0.21.5:glib_sys",
        "//third-party/rust/crates/gobject-sys/0.21.5:gobject_sys",
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
