load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aamva",
    srcs = glob(["**/*.rs"]),
    crate = "aamva",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/rxing/0.8.6:rxing",
        "//third-party/rust/crates/strum/0.26.3:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
