load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abandonment_issues",
    srcs = glob(["**/*.rs"]),
    crate = "abandonment_issues",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
