load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acpi",
    srcs = glob(["**/*.rs"]),
    crate = "acpi",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bit_field/0.9.0:bit_field",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/typenum/1.20.1:typenum",
    ],
)
