load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_limiter",
    srcs = glob(["**/*.rs"]),
    crate = "actix_limiter",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-utils/3.0.1:actix_utils",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/deadpool-redis/0.22.1:deadpool_redis",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis/0.32.7:redis",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
