load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm_backend_barretenberg",
    srcs = glob(["**/*.rs"]),
    crate = "acvm_backend_barretenberg",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acvm/0.11.0:acvm",
        "//third-party/rust/crates/blake2/0.9.2:blake2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
