load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adic_shape",
    srcs = glob(["**/*.rs"]),
    crate = "adic_shape",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adic/0.5.2:adic",
        "//third-party/rust/crates/bon/3.9.3:bon",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/icondata_fi/0.0.10:icondata_fi",
        "//third-party/rust/crates/itertools/0.15.0:itertools",
        "//third-party/rust/crates/num/0.4.3:num",
        "//third-party/rust/crates/petgraph/0.8.3:petgraph",
        "//third-party/rust/crates/svg/0.18.0:svg",
    ],
)
