load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adlx",
    srcs = glob(["**/*.rs"]),
    crate = "adlx",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/libloading/0.8.9:libloading",
    ],
)
