load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_interop",
    srcs = glob(["**/*.rs"]),
    crate = "actix_interop",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.12.0:actix",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
        "//third-party/rust/crates/scoped-tls-hkt/0.1.5:scoped_tls_hkt",
    ],
)
