load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "account",
    srcs = glob(["**/*.rs"]),
    crate = "account",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bip32/0.5.3:bip32",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/x25519-dalek/2.0.1:x25519_dalek",
    ],
)
