load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acidalia",
    srcs = glob(["**/*.rs"]),
    crate = "acidalia",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acidalia_core/0.2.0:acidalia_core",
        "//third-party/rust/crates/acidalia_proc_macros/0.2.0:acidalia_proc_macros",
        "//third-party/rust/crates/crossbeam-channel/0.5.16:crossbeam_channel",
        "//third-party/rust/crates/dashmap/5.5.3:dashmap",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/shaderc/0.7.4:shaderc",
        "//third-party/rust/crates/wgpu/0.12.0:wgpu",
        "//third-party/rust/crates/winit/0.26.1:winit",
    ],
)
