load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adaclaw_server",
    srcs = glob(["**/*.rs"]),
    crate = "adaclaw_server",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adaclaw-core/0.1.0:adaclaw_core",
        "//third-party/rust/crates/adaclaw-security/0.1.0:adaclaw_security",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
