load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acdp",
    srcs = glob(["**/*.rs"]),
    crate = "acdp",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/p256/0.13.2:p256",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
