load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aabb3",
    srcs = glob(["**/*.rs"]),
    crate = "aabb3",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/number_traits/0.1.6:number_traits",
        "//third-party/rust/crates/vec3/0.1.6:vec3",
    ],
)
