load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abscissa",
    srcs = glob(["**/*.rs"]),
    crate = "abscissa",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/gumdrop/0.7.0:gumdrop",
        "//third-party/rust/crates/handlebars/2.0.4:handlebars",
        "//third-party/rust/crates/ident_case/1.0.1:ident_case",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
