load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_session_mongodb",
    srcs = glob(["**/*.rs"]),
    crate = "actix_session_mongodb",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-session/0.9.0:actix_session",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/bson/2.15.0:bson",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mongodb/2.8.2:mongodb",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
