load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "action_gate_core",
    srcs = glob(["**/*.rs"]),
    crate = "action_gate_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/action-gate-types/0.1.0:action_gate_types",
        "//third-party/rust/crates/canonical-keysort-json/0.1.0:canonical_keysort_json",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
    ],
)
