load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_client",
    srcs = glob(["**/*.rs"]),
    crate = "acme_client",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
)
