load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/a/a-0.1.0.crate",
    ],
    sha256 = "58169884a52f5647006cc1d663adb1432a948a8af1a28379880274d0b7a160e8",
    type = "tar.gz",
    strip_prefix = "a-0.1.0",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "a",
    srcs = [":vendor"],
    crate = "a",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
