load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_core",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
