load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "acode_cli",
    srcs = glob(["**/*.rs"]),
    crate = "acode_cli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/dialoguer/0.11.0:dialoguer",
        "//third-party/rust/crates/openssl/0.10.81:openssl",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/spinners/4.2.0:spinners",
    ],
)
