load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "amgen_rs",
    srcs = glob(["**/*.rs"]),
    crate = "amgen_rs",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
