load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abproof",
    srcs = glob(["**/*.rs"]),
    crate = "abproof",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
