load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_actor_pool",
    srcs = glob(["**/*.rs"]),
    crate = "actix_actor_pool",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.13.5:actix",
    ],
)
