load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad1",
    srcs = glob(["**/*.rs"]),
    crate = "ad1",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
