load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advocat",
    srcs = glob(["**/*.rs"]),
    crate = "advocat",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/configparser/3.2.0:configparser",
        "//third-party/rust/crates/curl/0.4.50:curl",
        "//third-party/rust/crates/diff/0.1.13:diff",
        "//third-party/rust/crates/directories/4.0.1:directories",
        "//third-party/rust/crates/exitcode/1.1.2:exitcode",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/terminal_size/0.1.17:terminal_size",
        "//third-party/rust/crates/termion/1.5.6:termion",
        "//third-party/rust/crates/zip/0.5.13:zip",
    ],
)
