load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accumulator",
    srcs = glob(["**/*.rs"]),
    crate = "accumulator",
    crate_root = "lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ink_env/3.4.0:ink_env",
        "//third-party/rust/crates/ink_lang/3.4.0:ink_lang",
        "//third-party/rust/crates/ink_primitives/3.4.0:ink_primitives",
        "//third-party/rust/crates/ink_storage/3.4.0:ink_storage",
        "//third-party/rust/crates/parity-scale-codec/3.7.5:parity_scale_codec",
    ],
)
