load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi",
    srcs = glob(["**/*.rs"]),
    crate = "adi",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
)
