load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm_backend_barretenberg",
    srcs = glob(["**/*.rs"]),
    crate = "acvm_backend_barretenberg",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acvm/0.15.1:acvm",
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bytesize/1.3.3:bytesize",
        "//third-party/rust/crates/reqwest/0.11.27:reqwest",
        "//third-party/rust/crates/serde-big-array/0.5.1:serde_big_array",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
