load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_ratelimit",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_ratelimit",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
