load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ade_elementary_circuits",
    srcs = glob(["**/*.rs"]),
    crate = "ade_elementary_circuits",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ade-common/0.1.0:ade_common",
        "//third-party/rust/crates/ade-strongly-connected-components/0.1.1:ade_strongly_connected_components",
        "//third-party/rust/crates/ade-traits/0.1.0:ade_traits",
        "//third-party/rust/crates/smallvec/1.15.2:smallvec",
    ],
)
