load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "tree_sitter_toml",
    srcs = glob(["**/*.rs"]),
    crate = "tree_sitter_toml",
    crate_root = "bindings/rust/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tree-sitter-language/0.1.7:tree_sitter_language",
    ],
)
