load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adjacency_matrix",
    srcs = glob(["**/*.rs"]),
    crate = "adjacency_matrix",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/graph-types/0.0.13:graph_types",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
    ],
)
