load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_plus_utils",
    srcs = glob(["**/*.rs"]),
    crate = "actix_plus_utils",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-plus-error/0.1.0:actix_plus_error",
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/unic-ucd-category/0.9.0:unic_ucd_category",
    ],
)
