load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/fern/0.5.9:fern",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
