load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adept2",
    srcs = glob(["**/*.rs"]),
    crate = "adept2",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adept2-sys/0.1.0:adept2_sys",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/failure/0.1.8:failure",
    ],
)
