load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "addy",
    srcs = glob(["**/*.rs"]),
    crate = "addy",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/fnv/1.0.7:fnv",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
