load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abs_buff",
    srcs = glob(["**/*.rs"]),
    crate = "abs_buff",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abs_sync/0.1.0:abs_sync",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
    ],
)
