load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aardvark_dns",
    srcs = glob(["**/*.rs"]),
    crate = "aardvark_dns",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/arc-swap/1.9.2:arc_swap",
        "//third-party/rust/crates/clap/4.4.18:clap",
        "//third-party/rust/crates/flume/0.11.1:flume",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/hickory-client/0.24.4:hickory_client",
        "//third-party/rust/crates/hickory-proto/0.24.4:hickory_proto",
        "//third-party/rust/crates/hickory-server/0.24.4:hickory_server",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/nix/0.29.0:nix",
        "//third-party/rust/crates/resolv-conf/0.7.6:resolv_conf",
        "//third-party/rust/crates/syslog/7.0.0:syslog",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
