load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_service",
    srcs = glob(["**/*.rs"]),
    crate = "actix_service",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project-lite/0.1.12:pin_project_lite",
    ],
)
