load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acton_htmx_cli_lib",
    srcs = glob(["**/*.rs"]),
    crate = "acton_htmx_cli_lib",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/Inflector/0.11.4:Inflector",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/console/0.16.4:console",
        "//third-party/rust/crates/convert_case/0.9.0:convert_case",
        "//third-party/rust/crates/dialoguer/0.12.0:dialoguer",
        "//third-party/rust/crates/handlebars/6.4.4:handlebars",
        "//third-party/rust/crates/indicatif/0.18.6:indicatif",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
