load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "account_address",
    srcs = glob(["**/*.rs"]),
    crate = "account_address",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
