load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admin_bot",
    srcs = glob(["**/*.rs"]),
    crate = "admin_bot",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/dotenv/0.10.1:dotenv",
        "//third-party/rust/crates/env_logger/0.3.5:env_logger",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.3.9:log",
        "//third-party/rust/crates/telebot/0.2.10:telebot",
        "//third-party/rust/crates/tokio-core/0.1.18:tokio_core",
    ],
)
