load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adskalman",
    srcs = glob(["**/*.rs"]),
    crate = "adskalman",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/approx/0.4.0:approx",
        "//third-party/rust/crates/nalgebra/0.24.1:nalgebra",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
