load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_cli",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_cli",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionqueue-core/0.1.2:actionqueue_core",
        "//third-party/rust/crates/actionqueue-daemon/0.1.2:actionqueue_daemon",
        "//third-party/rust/crates/actionqueue-engine/0.1.2:actionqueue_engine",
        "//third-party/rust/crates/actionqueue-storage/0.1.2:actionqueue_storage",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
