load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionqueue_executor_local",
    srcs = glob(["**/*.rs"]),
    crate = "actionqueue_executor_local",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actionqueue-core/0.1.2:actionqueue_core",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
