load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abels_complex",
    srcs = glob(["**/*.rs"]),
    crate = "abels_complex",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
