load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admiral_types",
    srcs = glob(["**/*.rs"]),
    crate = "admiral_types",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rustc-test/0.3.1:rustc_test",
    ],
)
