load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_redisactor",
    srcs = glob(["**/*.rs"]),
    crate = "actix_redisactor",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.8.3:actix",
        "//third-party/rust/crates/backoff/0.1.6:backoff",
        "//third-party/rust/crates/derive_more/0.15.0:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/redis-async/0.5.2:redis_async",
        "//third-party/rust/crates/tokio-codec/0.1.2:tokio_codec",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
    ],
)
