load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbc_clickhouse",
    srcs = glob(["**/*.rs"]),
    crate = "adbc_clickhouse",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adbc_core/0.23.0:adbc_core",
        "//third-party/rust/crates/arrow-array/58.4.0:arrow_array",
        "//third-party/rust/crates/arrow-buffer/58.4.0:arrow_buffer",
        "//third-party/rust/crates/arrow-ipc/58.4.0:arrow_ipc",
        "//third-party/rust/crates/arrow-schema/58.4.0:arrow_schema",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clickhouse-ext-arrow/0.1.0:clickhouse_ext_arrow",
        "//third-party/rust/crates/clickhouse-types/0.1.2:clickhouse_types",
        "//third-party/rust/crates/clickhouse/0.15.1:clickhouse",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_bytes/0.11.19:serde_bytes",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
