load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "form_data",
    srcs = glob(["**/*.rs"]),
    crate = "form_data",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.6.15:actix_web",
        "//third-party/rust/crates/actix/0.5.8:actix",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures-cpupool/0.1.8:futures_cpupool",
        "//third-party/rust/crates/futures-fs/0.0.4:futures_fs",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/http/0.1.21:http",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
    ],
)
