load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adbqr",
    srcs = glob(["**/*.rs"]),
    crate = "adbqr",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/mdns-sd/0.11.5:mdns_sd",
        "//third-party/rust/crates/nanoid/0.4.0:nanoid",
        "//third-party/rust/crates/qrcode/0.14.1:qrcode",
    ],
)
