load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abduco",
    srcs = glob(["**/*.rs"]),
    crate = "abduco",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nix/0.28.0:nix",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
