load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adb_rust",
    srcs = glob(["**/*.rs"]),
    crate = "adb_rust",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
