load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aderynpy",
    srcs = glob(["**/*.rs"]),
    crate = "aderynpy",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aderyn_driver/0.0.13:aderyn_driver",
        "//third-party/rust/crates/pyo3/0.19.2:pyo3",
    ],
)
