load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_tonic",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_tonic",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-http/3.13.3:actix_http",
        "//third-party/rust/crates/actix-service/2.0.3:actix_service",
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/const_format/0.2.36:const_format",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/prost/0.10.4:prost",
        "//third-party/rust/crates/retrieve/1.1.2:retrieve",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/to_unit/1.0.2:to_unit",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic/0.7.2:tonic",
    ],
)
