load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_server",
    srcs = glob(["**/*.rs"]),
    crate = "ace_server",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-core/0.5.5:ace_core",
        "//third-party/rust/crates/ace-proto/0.5.5:ace_proto",
        "//third-party/rust/crates/ace-sim/0.5.5:ace_sim",
        "//third-party/rust/crates/ace-uds/0.5.5:ace_uds",
    ],
)
