load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abv",
    srcs = glob(["**/*.rs"]),
    crate = "abv",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
