load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actinium226_librespot_playback",
    srcs = glob(["**/*.rs"]),
    crate = "actinium226_librespot_playback",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/futures-executor/0.3.34:futures_executor",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/lewton/0.10.2:lewton",
        "//third-party/rust/crates/librespot-audio/0.4.2:librespot_audio",
        "//third-party/rust/crates/librespot-core/0.4.2:librespot_core",
        "//third-party/rust/crates/librespot-metadata/0.4.2:librespot_metadata",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/ogg/0.8.0:ogg",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_distr/0.4.3:rand_distr",
        "//third-party/rust/crates/shell-words/1.1.1:shell_words",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/zerocopy/0.6.6:zerocopy",
    ],
)
