load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a8e_test",
    srcs = glob(["**/*.rs"]),
    crate = "a8e_test",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
