load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advent_of_utils_cli",
    srcs = glob(["**/*.rs"]),
    crate = "advent_of_utils_cli",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advent-of-utils/0.2.3:advent_of_utils",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/directories/5.0.1:directories",
        "//third-party/rust/crates/libloading/0.8.9:libloading",
        "//third-party/rust/crates/r2d2/0.8.10:r2d2",
        "//third-party/rust/crates/r2d2_sqlite/0.25.0:r2d2_sqlite",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
