load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actoriwc",
    srcs = glob(["**/*.rs"]),
    crate = "actoriwc",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actori-codec/0.2.0:actori_codec",
        "//third-party/rust/crates/actori-http/1.0.1:actori_http",
        "//third-party/rust/crates/actori-rt/1.0.0:actori_rt",
        "//third-party/rust/crates/actori-service/1.0.5:actori_service",
        "//third-party/rust/crates/base64/0.11.0:base64",
        "//third-party/rust/crates/bytes/0.5.6:bytes",
        "//third-party/rust/crates/derive_more/0.99.20:derive_more",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/rand/0.7.3:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.6.1:serde_urlencoded",
    ],
)
