load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "actix_httpbin",
    srcs = glob(["**/*.rs"]),
    crate = "actix_httpbin",
    crate_root = "src/main.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web-httpauth/0.0.2:actix_web_httpauth",
        "//third-party/rust/crates/actix-web/0.6.15:actix_web",
        "//third-party/rust/crates/base64/0.9.3:base64",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/env_logger/0.5.13:env_logger",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/http/0.1.21:http",
        "//third-party/rust/crates/linked-hash-map/0.5.6:linked_hash_map",
        "//third-party/rust/crates/mime/0.3.17:mime",
        "//third-party/rust/crates/rand/0.4.6:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.5.5:serde_urlencoded",
        "//third-party/rust/crates/tera/0.11.20:tera",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
        "//third-party/rust/crates/url/1.7.2:url",
        "//third-party/rust/crates/uuid/0.6.5:uuid",
    ],
)
