load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adoptium_api",
    srcs = glob(["**/*.rs"]),
    crate = "adoptium_api",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/strum/0.27.2:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
    ],
)
