load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abrasive_protocol",
    srcs = glob(["**/*.rs"]),
    crate = "abrasive_protocol",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
