load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_ibc_host",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_ibc_host",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cosmwasm-schema/2.3.4:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/2.3.4:cosmwasm_std",
        "//third-party/rust/crates/cw-controllers/2.0.0:cw_controllers",
        "//third-party/rust/crates/cw-orch/0.26.0:cw_orch",
        "//third-party/rust/crates/cw-ownable/2.1.0:cw_ownable",
        "//third-party/rust/crates/cw-paginate/2.0.0:cw_paginate",
        "//third-party/rust/crates/cw-storage-plus/2.0.0:cw_storage_plus",
        "//third-party/rust/crates/cw-utils/2.0.0:cw_utils",
        "//third-party/rust/crates/cw2/2.0.0:cw2",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
