load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a3s_lane",
    srcs = glob(["**/*.rs"]),
    crate = "a3s_lane",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/cron/0.17.0:cron",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
