load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "act_rs",
    srcs = glob(["**/*.rs"]),
    crate = "act_rs",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/delegate/0.13.5:delegate",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
