load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "access_db",
    srcs = glob(["**/*.rs"]),
    crate = "access_db",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/mysql/22.2.0:mysql",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
