load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable_derive_lib",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable_derive_lib",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable_shared/0.5.0:abi_stable_shared",
        "//third-party/rust/crates/arrayvec/0.4.12:arrayvec",
        "//third-party/rust/crates/core_extensions/0.1.20:core_extensions",
        "//third-party/rust/crates/proc-macro2/0.4.30:proc_macro2",
        "//third-party/rust/crates/quote/0.6.13:quote",
        "//third-party/rust/crates/syn/0.15.44:syn",
        "//third-party/rust/crates/typed-arena/1.7.0:typed_arena",
    ],
)
