import { AJTheme } from "../aj-theme.slint";
import { AJAppState, AJUserState } from "../aj-state.slint";
import { AJHomeCallbacks } from "../aj-callbacks.slint";
import { AJPublicUserData } from "../models/users.slint";
import { AJText, AJTextType } from "../components/aj-text.slint";
import { AJInput, AJInputType } from "../components/aj-input.slint";
import { AJAdminBadge } from "../components/aj-admin-badge.slint";
import { AJButton } from "../components/aj-button.slint";
import { AJDateTimeText } from "../components/aj-datetime-text.slint";

export component UserProfilePage {
    property <AJPublicUserData> user: AJAppState.opened-user-profile;

    VerticalLayout {
        alignment: start;
        spacing: AJTheme.spacing;

        AJText {
            text: "Профиль";
            type: AJTextType.Heading;
        }

        AJText {
            text: "id";
            type: AJTextType.Medium;
        }

        AJText {
            text: user.id;
            font-italic: true;
        }

        AJText {
            text: "логин";
            type: AJTextType.Medium;
        }

        AJText {
            text: user.login;
            font-italic: true;
        }

        AJText {
            text: "уровень админа";
            type: AJTextType.Medium;
        }

        AJAdminBadge {
            level: user.admin-level;
        }

        AJButton {
            text: "<< назад";
            clicked => {
                AJAppState.page = 5
            }
        }
    }
}
