load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actify",
    srcs = glob(["**/*.rs"]),
    crate = "actify",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actify-macros/0.1.1:actify_macros",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/env_logger/0.10.2:env_logger",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tonic/0.9.2:tonic",
    ],
)
