load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "admychat",
    srcs = glob(["**/*.rs"]),
    crate = "admychat",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/zed_extension_api/0.2.0:zed_extension_api",
    ],
)
