load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_custom_device_to_pcsclite",
    srcs = glob(["**/*.rs"]),
    crate = "add_custom_device_to_pcsclite",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/plist/1.10.0:plist",
    ],
)
