load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix",
    srcs = glob(["**/*.rs"]),
    crate = "actix",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-rt/0.2.6:actix_rt",
        "//third-party/rust/crates/actix_derive/0.4.0:actix_derive",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/crossbeam-channel/0.3.9:crossbeam_channel",
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/hashbrown/0.2.2:hashbrown",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.7.1:parking_lot",
        "//third-party/rust/crates/smallvec/0.6.14:smallvec",
        "//third-party/rust/crates/tokio-codec/0.1.2:tokio_codec",
        "//third-party/rust/crates/tokio-executor/0.1.10:tokio_executor",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
    ],
)
