load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_platform_traits",
    srcs = glob(["**/*.rs"]),
    crate = "actr_platform_traits",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
