load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerate_general",
    srcs = glob(["**/*.rs"]),
    crate = "accelerate_general",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/num-complex/0.4.6:num_complex",
    ],
)
