load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "active_cd",
    srcs = glob(["**/*.rs"]),
    crate = "active_cd",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/crossterm/0.28.1:crossterm",
        "//third-party/rust/crates/dirs/5.0.1:dirs",
    ],
)
