load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ades",
    srcs = glob(["**/*.rs"]),
    crate = "ades",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cms/0.2.3:cms",
        "//third-party/rust/crates/const-oid/0.9.6:const_oid",
        "//third-party/rust/crates/der/0.7.10:der",
        "//third-party/rust/crates/lopdf/0.32.0:lopdf",
        "//third-party/rust/crates/p256/0.13.2:p256",
        "//third-party/rust/crates/pem-rfc7468/0.7.0:pem_rfc7468",
        "//third-party/rust/crates/rand_core/0.6.4:rand_core",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/signature/2.2.0:signature",
        "//third-party/rust/crates/spki/0.7.3:spki",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/x509-cert/0.2.5:x509_cert",
    ],
)
