load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adminx_core",
    srcs = glob(["**/*.rs"]),
    crate = "adminx_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/bcrypt/0.17.1:bcrypt",
        "//third-party/rust/crates/jsonwebtoken/9.3.1:jsonwebtoken",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/qrcode/0.14.1:qrcode",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_urlencoded/0.7.1:serde_urlencoded",
        "//third-party/rust/crates/tera/1.20.1:tera",
        "//third-party/rust/crates/totp-rs/5.7.2:totp_rs",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
