load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abr",
    srcs = glob(["**/*.rs"]),
    crate = "abr",
    crate_root = "src/main.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/phf/0.8.0:phf",
        "//third-party/rust/crates/structopt/0.3.26:structopt",
    ],
)
