load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_space",
    srcs = glob(["**/*.rs"]),
    crate = "add_space",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aok/0.1.18:aok",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unic-emoji-char/0.9.0:unic_emoji_char",
        "//third-party/rust/crates/unicode-script/0.5.8:unicode_script",
    ],
)
