load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aaa_test_cw_orch",
    srcs = glob(["**/*.rs"]),
    crate = "aaa_test_cw_orch",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cw-orch-contract-derive/0.21.1:cw_orch_contract_derive",
        "//third-party/rust/crates/cw-orch-fns-derive/0.19.1:cw_orch_fns_derive",
    ],
)
