load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actuate_macros",
    srcs = glob(["**/*.rs"]),
    crate = "actuate_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
    ],
)
