load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accessibility",
    srcs = glob(["**/*.rs"]),
    crate = "accessibility",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accessibility-sys/0.2.0:accessibility_sys",
        "//third-party/rust/crates/cocoa/0.26.1:cocoa",
        "//third-party/rust/crates/core-foundation/0.10.1:core_foundation",
        "//third-party/rust/crates/objc/0.2.7:objc",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
