load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "activitylog",
    srcs = glob(["**/*.rs"]),
    crate = "activitylog",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/csv/1.4.0:csv",
        "//third-party/rust/crates/quick-xml/0.37.5:quick_xml",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
