load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_buffering",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_buffering",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/3.3.3:actix_web",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/uuid/0.8.2:uuid",
    ],
)
