load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix",
    srcs = glob(["**/*.rs"]),
    crate = "actix",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix_derive/0.2.0:actix_derive",
        "//third-party/rust/crates/bitflags/1.3.2:bitflags",
        "//third-party/rust/crates/bytes/0.4.12:bytes",
        "//third-party/rust/crates/crossbeam-channel/0.2.6:crossbeam_channel",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/fnv/1.0.7:fnv",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/libc/0.2.189:libc",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.5.5:parking_lot",
        "//third-party/rust/crates/smallvec/0.6.14:smallvec",
        "//third-party/rust/crates/tokio-executor/0.1.10:tokio_executor",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
        "//third-party/rust/crates/tokio-reactor/0.1.12:tokio_reactor",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/tokio-timer/0.2.13:tokio_timer",
        "//third-party/rust/crates/tokio/0.1.22:tokio",
        "//third-party/rust/crates/uuid/0.6.5:uuid",
    ],
)
