load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_macos",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_macos",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.16.3:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.24.3:accesskit_consumer",
        "//third-party/rust/crates/objc2-app-kit/0.2.2:objc2_app_kit",
        "//third-party/rust/crates/objc2-foundation/0.2.2:objc2_foundation",
        "//third-party/rust/crates/objc2/0.5.2:objc2",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
    ],
)
