load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adbook",
    srcs = glob(["**/*.rs"]),
    crate = "adbook",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/fern/0.6.2:fern",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/handlebars/3.5.5:handlebars",
        "//third-party/rust/crates/indicatif/0.15.0:indicatif",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/ron/0.6.6:ron",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
