load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adts",
    srcs = glob(["**/*.rs"]),
    crate = "adts",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/genindex/0.2.2:genindex",
    ],
)
