load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/enumset/1.1.14:enumset",
        "//third-party/rust/crates/kurbo/0.8.3:kurbo",
    ],
)
