load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abpfiff",
    srcs = glob(["**/*.rs"]),
    crate = "abpfiff",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bytemuck/1.25.2:bytemuck",
        "//third-party/rust/crates/libc/0.2.189:libc",
    ],
)
