load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "turn",
    srcs = glob(["**/*.rs"]),
    crate = "turn",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/hmac/0.12.1:hmac",
        "//third-party/rust/crates/lru/0.12.5:lru",
        "//third-party/rust/crates/md5/0.8.1:md5",
        "//third-party/rust/crates/nonce-auth/0.6.3:nonce_auth",
        "//third-party/rust/crates/once_cell/1.21.4:once_cell",
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha1/0.10.7:sha1",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/turn/0.11.0:turn",
        "//third-party/rust/crates/twox-hash/2.1.3:twox_hash",
        "//third-party/rust/crates/webrtc-util/0.12.0:webrtc_util",
        "//third-party/rust/crates/webrtc/0.14.0:webrtc",
    ],
)
