load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adriann",
    srcs = glob(["**/*.rs"]),
    crate = "adriann",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/fxhash/0.2.1:fxhash",
        "//third-party/rust/crates/kiddo/5.3.3:kiddo",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/ndarray-stats/0.6.0:ndarray_stats",
        "//third-party/rust/crates/ndarray/0.16.1:ndarray",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rand_distr/0.5.1:rand_distr",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
    ],
)
