load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abi_stable_derive",
    srcs = glob(["**/*.rs"]),
    crate = "abi_stable_derive",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abi_stable_shared/0.9.0:abi_stable_shared",
        "//third-party/rust/crates/as_derive_utils/0.9.0:as_derive_utils",
        "//third-party/rust/crates/core_extensions/0.1.20:core_extensions",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
        "//third-party/rust/crates/typed-arena/2.0.2:typed_arena",
    ],
)
