load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aas",
    srcs = glob(["**/*.rs"]),
    crate = "aas",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bigdecimal/0.4.10:bigdecimal",
        "//third-party/rust/crates/iref/3.2.2:iref",
        "//third-party/rust/crates/iso8601/0.6.5:iso8601",
        "//third-party/rust/crates/oxilangtag/0.1.6:oxilangtag",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_with/3.22.0:serde_with",
        "//third-party/rust/crates/strum/0.27.2:strum",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
