load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actionable_macros",
    srcs = glob(["**/*.rs"]),
    crate = "actionable_macros",
    crate_root = "src/lib.rs",
    edition = "2018",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/darling/0.12.4:darling",
        "//third-party/rust/crates/ident_case/1.0.1:ident_case",
        "//third-party/rust/crates/proc-macro-error/1.0.4:proc_macro_error",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
