load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accepted",
    srcs = glob(["**/*.rs"]),
    crate = "accepted",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aho-corasick/0.6.10:aho_corasick",
        "//third-party/rust/crates/ansi_colours/1.2.3:ansi_colours",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/dirs/1.0.5:dirs",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/fuzzy-matcher/0.2.2:fuzzy_matcher",
        "//third-party/rust/crates/jsonrpc-core/10.1.0:jsonrpc_core",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/rbtag/0.3.0:rbtag",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/ropey/1.6.1:ropey",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_derive/1.0.229:serde_derive",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/shellexpand/1.1.1:shellexpand",
        "//third-party/rust/crates/syntect/3.3.0:syntect",
        "//third-party/rust/crates/termion/1.5.6:termion",
        "//third-party/rust/crates/toml/0.4.10:toml",
        "//third-party/rust/crates/typemap/0.3.3:typemap",
        "//third-party/rust/crates/unicode-width/0.1.14:unicode_width",
    ],
)
