load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ach",
    srcs = glob(["**/*.rs"]),
    crate = "ach",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ach-array/0.1.9:ach_array",
        "//third-party/rust/crates/ach-cell/0.1.18:ach_cell",
        "//third-party/rust/crates/ach-lazy/0.1.3:ach_lazy",
        "//third-party/rust/crates/ach-mpmc/0.1.4:ach_mpmc",
        "//third-party/rust/crates/ach-once/0.1.7:ach_once",
        "//third-party/rust/crates/ach-pubsub/0.1.9:ach_pubsub",
        "//third-party/rust/crates/ach-ring/0.1.10:ach_ring",
        "//third-party/rust/crates/ach-spsc/0.1.2:ach_spsc",
        "//third-party/rust/crates/ach-util/0.1.17:ach_util",
    ],
)
