load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_redis",
    srcs = glob(["**/*.rs"]),
    crate = "actix_redis",
    crate_root = "src/lib.rs",
    edition = "2015",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.5.8:actix",
        "//third-party/rust/crates/backoff/0.1.6:backoff",
        "//third-party/rust/crates/failure/0.1.8:failure",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-core/0.1.18:tokio_core",
        "//third-party/rust/crates/tokio-io/0.1.13:tokio_io",
    ],
)
