load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr_platform_native",
    srcs = glob(["**/*.rs"]),
    crate = "actr_platform_native",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actr-hyper/0.3.12:actr_hyper",
        "//third-party/rust/crates/actr-platform-traits/0.3.12:actr_platform_traits",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
