load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abu_rag",
    srcs = glob(["**/*.rs"]),
    crate = "abu_rag",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abu-provider/0.1.0:abu_provider",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/rand/0.10.2:rand",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
