load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adtp2",
    srcs = glob(["**/*.rs"]),
    crate = "adtp2",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/aes-gcm/0.10.3:aes_gcm",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rsa/0.9.10:rsa",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
