load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acktor_ipc",
    srcs = glob(["**/*.rs"]),
    crate = "acktor_ipc",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acktor-ipc-proto/1.1.0:acktor_ipc_proto",
        "//third-party/rust/crates/acktor/1.1.2:acktor",
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/dashmap/6.2.1:dashmap",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/zerocopy/0.8.56:zerocopy",
    ],
)
