load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adder_4702",
    srcs = glob(["**/*.rs"]),
    crate = "adder_4702",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add_one_8732/0.1.0:add_one_8732",
        "//third-party/rust/crates/rand/0.8.7:rand",
    ],
)
