load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm",
    srcs = glob(["**/*.rs"]),
    crate = "acvm",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/itertools/0.15.0:itertools",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
