load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adar",
    srcs = glob(["**/*.rs"]),
    crate = "adar",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adar-macros/0.1.0:adar_macros",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
    ],
)
