# .gitlab-ci.yml
stages:
  - build
  - lint
  - test

build:
  stage: build
  image: rust:latest
  script:
    - cargo build
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/

lint:
  stage: lint
  image: rust:latest
  needs:
    - build
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
  cache:
    paths:
      - target/
test:
  stage: test
  image: rust:latest
  needs:
    - build
  script:
    - cargo test
  cache:
    paths:
      - target/
