load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adifsurgeon",
    srcs = glob(["**/*.rs"]),
    crate = "adifsurgeon",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/regex/1.13.1:regex",
    ],
)
