load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerate_sys",
    srcs = glob(["**/*.rs"]),
    crate = "accelerate_sys",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/block/0.1.6:block",
    ],
)
