load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_windows",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_windows",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.16.3:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.24.3:accesskit_consumer",
        "//third-party/rust/crates/paste/1.0.15:paste",
        "//third-party/rust/crates/static_assertions/1.1.0:static_assertions",
        "//third-party/rust/crates/windows-core/0.58.0:windows_core",
        "//third-party/rust/crates/windows/0.58.0:windows",
    ],
)
