load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acacia",
    srcs = glob(["**/*.rs"]),
    crate = "acacia",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/itertools/0.5.10:itertools",
        "//third-party/rust/crates/nalgebra/0.10.1:nalgebra",
        "//third-party/rust/crates/num/0.1.43:num",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
