load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actio",
    srcs = glob(["**/*.rs"]),
    crate = "actio",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
