load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abbreviation_extractor",
    srcs = glob(["**/*.rs"]),
    crate = "abbreviation_extractor",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/lazy_static/1.5.0:lazy_static",
        "//third-party/rust/crates/punkt_n/1.0.5:punkt_n",
        "//third-party/rust/crates/pyo3/0.22.6:pyo3",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
