load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_sdk_core",
    srcs = glob(["**/*.rs"]),
    crate = "ace_sdk_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/dirs/6.0.0:dirs",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
    ],
)
