load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adlt",
    srcs = glob(["**/*.rs"]),
    crate = "adlt",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/2.34.0:clap",
        "//third-party/rust/crates/evmap/10.0.2:evmap",
        "//third-party/rust/crates/nohash-hasher/0.2.0:nohash_hasher",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/slog-async/2.8.0:slog_async",
        "//third-party/rust/crates/slog-term/2.9.2:slog_term",
        "//third-party/rust/crates/slog/2.8.2:slog",
    ],
)
