load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adafruit_io_http",
    srcs = glob(["**/*.rs"]),
    crate = "adafruit_io_http",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/ureq/1.5.5:ureq",
    ],
)
