load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_broker",
    srcs = glob(["**/*.rs"]),
    crate = "actix_broker",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix/0.10.0:actix",
        "//third-party/rust/crates/fnv/1.0.7:fnv",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
