load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actrix_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "actrix_sdk",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actrix-admin/0.5.7:actrix_admin",
    ],
)
