load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "utility_programming",
    srcs = glob(["**/*.rs"]),
    crate = "utility_programming",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.5.6:rand",
    ],
)
