load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "address_book",
    srcs = glob(["**/*.rs"]),
    crate = "address_book",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/pest/2.8.8:pest",
        "//third-party/rust/crates/pest_derive/2.8.8:pest_derive",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
