load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a_flags",
    srcs = glob(["**/*.rs"]),
    crate = "a_flags",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/phf/0.11.3:phf",
    ],
)
