load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adam_core_rs_spice",
    srcs = glob(["**/*.rs"]),
    crate = "adam_core_rs_spice",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/faer/0.22.6:faer",
        "//third-party/rust/crates/rayon/1.12.0:rayon",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/spicekit/0.2.2:spicekit",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
