load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_middleware_ed25519_authentication",
    srcs = glob(["**/*.rs"]),
    crate = "actix_middleware_ed25519_authentication",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/4.14.1:actix_web",
        "//third-party/rust/crates/ed25519-dalek/1.0.1:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
    ],
)
