load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adhoc_audio",
    srcs = glob(["**/*.rs"]),
    crate = "adhoc_audio",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
