load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad7190",
    srcs = glob(["**/*.rs"]),
    crate = "ad7190",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal-async/1.0.0:embedded_hal_async",
    ],
)
