load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_macros",
    srcs = glob(["**/*.rs"]),
    crate = "acme_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/syn/1.0.109:syn",
    ],
)
