load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "translate",
    srcs = glob(["**/*.rs"]),
    crate = "translate",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/piston_meta/2.0.1:piston_meta",
    ],
)
