load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actor_attribute_macro",
    srcs = glob(["**/*.rs"]),
    crate = "actor_attribute_macro",
    crate_root = "src/lib.rs",
    edition = "2024",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
