load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aam_rs",
    srcs = glob(["**/*.rs"]),
    crate = "aam_rs",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bumpalo/3.20.3:bumpalo",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/rustc-hash/2.1.3:rustc_hash",
        "//third-party/rust/crates/smol_str/0.3.6:smol_str",
        "//third-party/rust/crates/tinyvec/1.12.0:tinyvec",
    ],
)
