load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actor_helper",
    srcs = glob(["**/*.rs"]),
    crate = "actor_helper",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
