load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adrscope",
    srcs = glob(["**/*.rs"]),
    crate = "adrscope",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/askama/0.14.0:askama",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/glob/0.3.4:glob",
        "//third-party/rust/crates/pulldown-cmark/0.13.4:pulldown_cmark",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/serde_yaml/0.9.33:serde_yaml",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/time/0.3.55:time",
    ],
)
