load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "addering",
    srcs = glob(["**/*.rs"]),
    crate = "addering",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adder-one/0.1.0:adder_one",
        "//third-party/rust/crates/rand/0.3.23:rand",
    ],
)
