load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ad5700",
    srcs = glob(["**/*.rs"]),
    crate = "ad5700",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/embedded-hal-async/1.0.0:embedded_hal_async",
        "//third-party/rust/crates/embedded-hal/1.0.0:embedded_hal",
        "//third-party/rust/crates/embedded-io-async/0.7.0:embedded_io_async",
        "//third-party/rust/crates/embedded-io/0.7.1:embedded_io",
        "//third-party/rust/crates/hart-protocol/0.1.0:hart_protocol",
    ],
)
