load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acme_compilers",
    srcs = glob(["**/*.rs"]),
    crate = "acme_compilers",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.6.20:axum",
        "//third-party/rust/crates/http-body/0.4.6:http_body",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/scsys/0.1.42:scsys",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/strum/0.24.1:strum",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/wasmer/3.3.0:wasmer",
    ],
)
