load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abtz_add_two",
    srcs = glob(["**/*.rs"]),
    crate = "abtz_add_two",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/rand/0.9.5:rand",
    ],
)
