load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_connect",
    srcs = glob(["**/*.rs"]),
    crate = "actix_connect",
    crate_root = "src/lib.rs",
    edition = "2018",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-codec/0.1.2:actix_codec",
        "//third-party/rust/crates/actix-service/0.4.2:actix_service",
        "//third-party/rust/crates/actix-utils/0.4.7:actix_utils",
        "//third-party/rust/crates/derive_more/0.14.1:derive_more",
        "//third-party/rust/crates/either/1.17.0:either",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/tokio-current-thread/0.1.7:tokio_current_thread",
        "//third-party/rust/crates/tokio-tcp/0.1.4:tokio_tcp",
        "//third-party/rust/crates/trust-dns-resolver/0.11.1:trust_dns_resolver",
    ],
)
