load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acta",
    srcs = glob(["**/*.rs"]),
    crate = "acta",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/derive_more/2.1.1:derive_more",
        "//third-party/rust/crates/owo-colors/4.3.0:owo_colors",
        "//third-party/rust/crates/smart-default/0.7.1:smart_default",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
