load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accache",
    srcs = glob(["**/*.rs"]),
    crate = "accache",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bs58/0.5.1:bs58",
        "//third-party/rust/crates/indexmap/2.14.0:indexmap",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/solana-account/3.4.0:solana_account",
        "//third-party/rust/crates/solana-commitment-config/3.1.1:solana_commitment_config",
        "//third-party/rust/crates/solana-pubkey/4.3.0:solana_pubkey",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/zstd/0.13.3:zstd",
    ],
)
