load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acvm_blackbox_solver",
    srcs = glob(["**/*.rs"]),
    crate = "acvm_blackbox_solver",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/acir/0.43.0:acir",
        "//third-party/rust/crates/blake2/0.10.6:blake2",
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/k256/0.11.6:k256",
        "//third-party/rust/crates/keccak/0.1.6:keccak",
        "//third-party/rust/crates/p256/0.11.1:p256",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/sha3/0.10.9:sha3",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
