load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_prom",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_prom",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project/1.1.13:pin_project",
        "//third-party/rust/crates/prometheus/0.13.4:prometheus",
    ],
)
