load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accelerometer",
    srcs = glob(["**/*.rs"]),
    crate = "accelerometer",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/generic-array/0.12.4:generic_array",
    ],
)
