load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "aci_png",
    srcs = glob(["**/*.rs"]),
    crate = "aci_png",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/afi/0.5.0:afi",
        "//third-party/rust/crates/flate2/0.2.20:flate2",
    ],
)
