image: archlinux
packages:
- rust
sources:
- https://git.sr.ht/~liz/actix-ws-proxy
tasks:
- build: |
    cd actix-ws-proxy
    cargo build
- test: |
    cd actix-ws-proxy
    cargo test
- fmt: |
    cd actix-ws-proxy
    cargo fmt --check
