load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

http_archive(
    name = "vendor",
    urls = [
        "https://static.crates.io/crates/acoustix/acoustix-0.2.1.crate",
    ],
    sha256 = "05faa9788a03358eae572c282c68104c8c0945c1baaded868e4650ff4165f0eb",
    type = "tar.gz",
    strip_prefix = "acoustix-0.2.1",
)

cargo_manifest(
    name = "manifest",
    vendor = ":vendor",
)

rust_library(
    name = "acoustix",
    srcs = [":vendor"],
    crate = "acoustix",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",

    rustc_flags = ["@$(location :manifest[env_flags])"],
    visibility = ["PUBLIC"],
)
