load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adlo",
    srcs = glob(["**/*.rs"]),
    crate = "adlo",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/nalgebra/0.34.2:nalgebra",
    ],
)
