load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adamo_sys",
    srcs = glob(["**/*.rs"]),
    crate = "adamo_sys",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
)
