load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "adulting",
    srcs = glob(["**/*.rs"]),
    crate = "adulting",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
)
