load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adi_gpu",
    srcs = glob(["**/*.rs"]),
    crate = "adi_gpu",
    crate_root = "src/lib.rs",
    edition = "2015",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/afi/0.3.2:afi",
        "//third-party/rust/crates/ami/0.5.0:ami",
        "//third-party/rust/crates/asi_vulkan/0.1.1:asi_vulkan",
        "//third-party/rust/crates/awi/0.1.1:awi",
    ],
)
