load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "active_standby",
    srcs = glob(["**/*.rs"]),
    crate = "active_standby",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/crossbeam/0.8.4:crossbeam",
    ],
)
