load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "advisor_catalog",
    srcs = glob(["**/*.rs"]),
    crate = "advisor_catalog",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/advisor-core/0.1.0:advisor_core",
    ],
)
