load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "ace_gateway",
    srcs = glob(["**/*.rs"]),
    crate = "ace_gateway",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ace-can/0.2.2:ace_can",
        "//third-party/rust/crates/ace-client/0.2.2:ace_client",
        "//third-party/rust/crates/ace-core/0.2.2:ace_core",
        "//third-party/rust/crates/ace-doip/0.2.2:ace_doip",
        "//third-party/rust/crates/ace-macros/0.2.2:ace_macros",
        "//third-party/rust/crates/ace-proto/0.2.2:ace_proto",
        "//third-party/rust/crates/ace-server/0.2.2:ace_server",
        "//third-party/rust/crates/ace-sim/0.2.2:ace_sim",
        "//third-party/rust/crates/heapless/0.9.3:heapless",
    ],
)
