load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actix_web_async_await",
    srcs = glob(["**/*.rs"]),
    crate = "actix_web_async_await",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actix-web/0.7.19:actix_web",
        "//third-party/rust/crates/futures/0.1.31:futures",
        "//third-party/rust/crates/tokio-async-await/0.1.7:tokio_async_await",
    ],
)
