load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acronym_engine",
    srcs = glob(["**/*.rs"]),
    crate = "acronym_engine",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/fs2/0.4.3:fs2",
        "//third-party/rust/crates/hf-hub/0.5.0:hf_hub",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/rusqlite/0.32.1:rusqlite",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokenizers/0.23.1:tokenizers",
    ],
)
