load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adapto_cli",
    srcs = glob(["**/*.rs"]),
    crate = "adapto_cli",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adapto_compiler/0.2.5:adapto_compiler",
        "//third-party/rust/crates/adapto_live/0.2.5:adapto_live",
        "//third-party/rust/crates/adapto_parser/0.2.5:adapto_parser",
        "//third-party/rust/crates/adapto_runtime/0.2.5:adapto_runtime",
        "//third-party/rust/crates/adapto_ssr/0.2.5:adapto_ssr",
        "//third-party/rust/crates/adapto_store/0.2.5:adapto_store",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
