load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "abootcrafter",
    srcs = glob(["**/*.rs"]),
    crate = "abootcrafter",
    crate_root = "src/main.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/memmap2/0.9.11:memmap2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
