load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a9_lint",
    srcs = glob(["**/*.rs"]),
    crate = "a9_lint",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a9-prettyplease/0.1.7:a9_prettyplease",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/toml/0.8.23:toml",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
    ],
)
