load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "absolut_macros",
    srcs = glob(["**/*.rs"]),
    crate = "absolut_macros",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/darling/0.20.11:darling",
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/z3/0.11.2:z3",
    ],
)
