load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "actr",
    srcs = glob(["**/*.rs"]),
    crate = "actr",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/actr-framework/0.4.21:actr_framework",
        "//third-party/rust/crates/actr-protocol/0.4.21:actr_protocol",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
    ],
)
