load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "acidjson",
    srcs = glob(["**/*.rs"]),
    crate = "acidjson",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/atomicwrites/0.3.1:atomicwrites",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
