load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "accesskit_android",
    srcs = glob(["**/*.rs"]),
    crate = "accesskit_android",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/accesskit/0.23.0:accesskit",
        "//third-party/rust/crates/accesskit_consumer/0.33.1:accesskit_consumer",
        "//third-party/rust/crates/jni/0.21.1:jni",
        "//third-party/rust/crates/log/0.4.33:log",
    ],
)
