load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adv_linalg",
    srcs = glob(["**/*.rs"]),
    crate = "adv_linalg",
    crate_root = "src/lib.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/adv_linalg_lib/0.1.1:adv_linalg_lib",
    ],
)
