load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "add_macro",
    srcs = glob(["**/*.rs"]),
    crate = "add_macro",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/add-macro-impl-display/0.1.1:add_macro_impl_display",
        "//third-party/rust/crates/add-macro-impl-error/0.1.0:add_macro_impl_error",
        "//third-party/rust/crates/add-macro-impl-from/0.1.1:add_macro_impl_from",
        "//third-party/rust/crates/add-macro-impl-fromstr/0.1.0:add_macro_impl_fromstr",
        "//third-party/rust/crates/add-macro-impl-into/0.1.1:add_macro_impl_into",
    ],
)
