load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abnf",
    srcs = glob(["**/*.rs"]),
    crate = "abnf",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/abnf-core/0.5.0:abnf_core",
    ],
)
