query GetGrader($id: IdOrKey!, $project: IdOrKey!) {
    grader(id: $id, project: $project) {
        id
        key
        name
        graderType
        graderConfig {
            __typename
            ... on JudgeConfigOutput {
                model { key, harmonyUrl }
                criteria
                userTemplate
                systemTemplate
                examples {
                    input {
                        role
                        content
                    }
                    output
                    pass
                    reasoning
                }
            }
            ... on PrebuiltConfigOutput {
                model { key, harmonyUrl }
                criteria {
                    key
                }
            }
            ... on RemoteConfigOutput {
                url
                version
                description
            }
            ... on CustomConfigOutput {
                description
            }
            ... on FunctionConfigOutput {
                sourceCode
                description
            }
        }
    }
}
