load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "abstract_cw1",
    srcs = glob(["**/*.rs"]),
    crate = "abstract_cw1",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/cosmwasm-schema/1.5.11:cosmwasm_schema",
        "//third-party/rust/crates/cosmwasm-std/1.5.11:cosmwasm_std",
        "//third-party/rust/crates/schemars/0.8.22:schemars",
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
