load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "adder_codec_core",
    srcs = glob(["**/*.rs"]),
    crate = "adder_codec_core",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/bincode/1.3.3:bincode",
        "//third-party/rust/crates/bitstream-io/2.6.0:bitstream_io",
        "//third-party/rust/crates/enum_dispatch/0.3.13:enum_dispatch",
        "//third-party/rust/crates/fenwick/2.0.1:fenwick",
        "//third-party/rust/crates/float-cmp/0.9.0:float_cmp",
        "//third-party/rust/crates/hashbrown/0.13.2:hashbrown",
        "//third-party/rust/crates/itertools/0.10.5:itertools",
        "//third-party/rust/crates/ndarray/0.15.6:ndarray",
        "//third-party/rust/crates/nestify/0.3.3:nestify",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/numquant/0.2.0:numquant",
        "//third-party/rust/crates/priority-queue/1.4.0:priority_queue",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/rustdct/0.7.1:rustdct",
        "//third-party/rust/crates/seq-macro/0.3.6:seq_macro",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_bytes/0.11.19:serde_bytes",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/transpose/0.2.3:transpose",
    ],
)
